### ISSUE TITLE
Allow object iteration

### ISSUE THREAD

**Issue by gliese1337** [ractivejs/ractive#115]
I said (https://github.com/Rich-Harris/Ractive/issues/110#issuecomment-22333513) that I couldn't think of a reason to need to add properties to a Ractive model that aren't referenced in the template, but then just today I ran into one: dealing with a model that contains a key-value map rather than a regular array.

This is kind of a pie-in-the-sky feature request (it's fairly simply worked around, and it would make magic setter methods per #110 harder to implement in the absence of Object.observe or Proxy objects), but it would be kind of neat to have something like

```
{{#object:key}}Value:{{.}}{{/object}}
```

that would automatically iterate over object properties.

**Comment by zaus** [comment]
_(correct me if I should make another issue)_

I see elsewhere (https://github.com/ractivejs/ractive/pull/1474) that "objects are first class citizens" and we can iterate objects in a couple different ways:

    {{#obj:k,i}}<p>{{@key}} = {{k}} and {{@index}} = {{i}}, but value = {{.}}</p>{{/}}

But what if you want two-way binding on the key?  ex) turn a dictionary/map into a table so you can edit both key/value.

**Comment by Rich-Harris** [comment]
@zaus' comment led me back to this (long-since-abandoned!) issue - @svapreddy the `delete` thing came up recently in the form of #1649. It contains a useful code snippet for deleting data from the model. I closed the issue, but invited people to comment in support of adding `ractive.unset(keypath)` to the core API - feel free to weigh in!
