### ISSUE TITLE
Silent reset and silent set 

### ISSUE THREAD

**Issue by batmandarkside** [ractivejs/ractive#1182]
### proposal to make silent reset and set model

``` javascript
this.observe('filtersData', function (value) {
    if (value) {

    }
}, {init: false});

this.set({filtersData : {}}, { silent : true })

// filtersData don't observe
```
### this.data.filtersData = {}; does not work if you later make

``` javascript
 this.set({filtersData : { test : 'test' }  })
```

**Comment by hezki** [comment]
+1 this

**Comment by guilhermeaiolfi** [comment]
Yeah, that would be very useful in something I'm trying to do. So +1.

**Comment by martypdx** [comment]
@hezki , @guilhermeaiolfi - can you give an example or more explanation as to how this would be useful?

**Comment by guilhermeaiolfi** [comment]
Sure, I was creating a decorator for ckeditor and wanted to keep the model in sync with the ckeditor instance value. To achieve that I had to observe the model for changes (model  -> ckeditor) and set the model when ckeditor changed (ckeditor -> model). 

The problem is that when I set the model it would trigger the observer and ckeditor would re-set the value it already had. Losing the cursor position and some other issues. 

I solved that by using a variable to know when I was set in that particular case so the observer - even tho it was called - wouldn't do anything.

I had similar cases using ember.js and I think they are planning a mechanism to pause and resume observers. That would be cool too. But maybe for those simple cases the silent mode is easier to understand and use.

**Comment by hezki** [comment]
like {init:false}, if you want replace all data without raise obserev events

if, example, i observe 'foo.bar' and i want replace foo object without raise 'foo.bar' event similar init= false

nb. sorry for my bad english.

**Comment by maslianok** [comment]
+1

**Comment by maslianok** [comment]
Well, you can use something like this:

```javascript
this.observe('data', function (n, o, k) {
    if (this.silent) return;
    alert(n);
}, {init: false});


this.set('data', 1); //alert(1)

this.silent = true;
this.set('data', 2); //do nothing
this.silent = false;
```

**Comment by Rich-Harris** [comment]
Sorry for the slow response. I think that @maslianok's approach is probably the best one - it's what I do when I need to prevent this kind of 'blowback', and it's how adaptors typically guard against infinite loops.

The problem with `silent`, as I see it, is that it's not clear who a change is silent for. Should setting `foo` silently cause `{{foo}}` to update, but not trigger `foo` observers? Possibly. But we have to answer other questions - should a `change` event happen? What if we have a computed property `bar` that depends on the value of `foo`. Should *that* update? What if we're observing `bar` - does that observer get triggered by a silent change to `foo`? Since observers are often used for things like data validation, or as an alternative to computed properties, it seems tricky to demarcate what should be affected and what shouldn't.

**Comment by Rich-Harris** [comment]
Re-reading this thread, I think @guilhermeaiolfi pointed towards the right idea with observers that can be paused and resumed. That way, we completely sidestep all the complexity that arises when you try to figure out who should be affected by 'silent' set operations and who shouldn't be; the onus is on the consumer of data rather than the provider.

```js
observer1 = ractive.observe( 'foo', fooChangeHandler );
observer2 = ractive.observe( 'foo', fooChangeHandler );

ractive.set( 'foo', 1 ); // fires for observer1 and observer2

observer1.pause();
ractive.set( 'foo', 2 ); // fires for observer2

observer1.resume(); // should fooChangeHandler be called with current value? unsure...
ractive.set( 'foo', 3 ); // fires for observer1 and observer2
```

I'll give this a `future` milestone, I think it would be good to implement post-0.7.0. In the meantime please weigh in if you think this is the right/wrong direction
