### ISSUE TITLE
style attributes with mustache references overwrite transition values

### ISSUE THREAD

**Issue by martypdx** [ractivejs/ractive#1262]
```html
<div intro='fade' style='width: {{width}}px;'></div>
```
```js
var r = new Ractive({
    el: document.body,
    template: '#template'
})
r.set('width', 200)
```

**Comment by Rich-Harris** [comment]
There's probably limits to what we can do here. Maybe one or both of these could help:

## 1. parse style attributes

Rather than `node.setAttribute('style', newStyle)`, we could do this under the hood:

```js
styles = parseStyles('width: 200px;'); // [{ prop: 'width', value: '200px' }]

styles.forEach( style => {
  node.style[ camelCase( style.prop ) ] = style.value;
});

// plus some logic to handle styles that previously existed but don't any more...
```

This would make it possible to manually manipulate styles without Ractive breaking them, which might in any case be good for interop with libraries that do that kind of DOM manipulation. At the moment Ractive is liable to stomp their changes. Not sure what the perf implications would be with this approach.

Also, it's not immediately obvious how straightforward it would be to parse styles. Definitely not quite as straightforward as splitting on `;`...

## 2. warn if style attribute is affected by data changes during transitions

When a transition starts, a flag is set. If data changes, causing the style attribute to be updated, while the flag is still active, we print a warning.

**Comment by martypdx** [comment]
Agree that looking into treating style attribute specially will good for __future__ milestone. 

It may actually have some perf benefit where style is being used to animate if we can directly target the individual style. There may need to be rules like no blocks across multiple styles like `style='{{#foo}}width: 200px; height;100px;{{else}}max-height: 50px;{{/}}'`. 

It could then be a parsetime additional thing that, if conditions are met, gets applied at runtime - otherwise falls back to full attirbute set.

**Comment by martypdx** [comment]
Just ran across this again in a subtle hard to find way :) 

Had a new idea, what if we allowed style properties as attributes of elements:

```html
<div intro='fade' style.width='{{width}}px;' style.height='{{height}}px'></div>
```

**Comment by evs-chris** [comment]
Classes and styles are no longer trampled in edge.
