### ISSUE TITLE
Including template as seperate file.

### ISSUE THREAD

**Issue by DDKnoll** [ractivejs/ractive#131]
I would like to include my template as a seperate file rather than writing it inline.  This way the browser can cache the template.

``` html
<script id='MyTemplate' type='text/ractive' src='MyTemplate.rac'></script>
```

Either I'm doing something wrong, or this isn't supported yet.

**Comment by wtford** [comment]
Can anyone explain a little bit more why it doesn't work to include a template as an external src's script tag?  I see that it doesn't work, but I don't understand why.

Why do you need an XHR helper, when a script tag can make the http request and handles the data transport directly?

What is the difference between a script tag declared in-line and a script tag with a src attribute?  In both cases, the browser halts rendering until the tag is fully loaded, right?  

Ractive *can* find the elements pulled in from a src'd script tag (at least it doesn't error out), but it cannot make them visible.  Why is that?

**Comment by fskreuz** [comment]
@wtford That's because you can't read the contents of an external script. When the browser sees one, it fetches the resource, and executes it as JavaScript, done. Nothing else made available. On the other hand, the browser sees an inline script, it parses that content and executes it as JavaScript. But! The contents are available as `innerHTML`.

**Comment by wtford** [comment]
Ok, thanks!  That reality makes sense.  But darn!  It's so close to being more useful!  Seems rather arbitrary to make one available and not the other.  I guess it's lucky that anything is available.

In my case, I am using Ractive as the front-end for a microcontroller-based http server, which needs as light-weight solution as possible.  During development it's rather a chore to recompile and reprogram the web code over and over to the MCU, so I was hoping to be able to bring the Ractive templates in from a 3rd party server while I'm working on them.  XHR doesn't work to fetch from 3rd party servers -- until I figure out how to get CORS working, I guess.

Thanks for the quick response on a closed ticket!

**Comment by Madgvox** [comment]
@wtford A quick solution could be to use jsonp to retrieve your templates.

**Comment by matthew-dean** [comment]
I'd love if this were re-opened. I don't agree with this statement:

> Ractive doesn't have things like XHR helpers because these problems have already been solved many times over 

This is only true on the JS side, which wasn't the issue raised. It doesn't exist on the template (declarative) side.

**Comment by Rich-Harris** [comment]
@matthew-dean not sure I understand what's being requested. Is it worth opening a separate issue to discuss further, or is this still the appropriate issue?

**Comment by matthew-dean** [comment]
@Rich-Harris It's a drum I've been beating for a while. I would really love to declare said imports on the template side. Yeah, of course you can do it JS, but there are a few reasons to do it in the template side:

1. There are cases where you have a "generic" Ractive handler and don't "pre-load" the same components or, in this case, external partials. Meaning: sometimes I want to reuse the same data / JS for different templates.
2. Makes it easier to write and use external partials, which makes it easier to separate components
3. I find it more "self-documenting" to see, in the template, what the master template might be, or what partials it references, which
4. Makes it feel like one of these nice nerdy concepts like "dependency injection" or "separation of concerns". That is, template A which relies on template B, when used with plain Ractive X, will always import template (or external partial) B.

For me, using components / external templates via JavaScript seems too prone to failure (not by Ractive, by me, or any other developer on my team), whereas I would use them in a heartbeat if those dependencies were always visible in my templates. It just feels more reliable to write:

```html
<!-- mypage.html -->
{{#import 'components.html'}}
{{#import 'partials.html'}}

<Animal type="cat">
  Am I your master?
</Animal>

<!-- components.html -->
{{#component Animal { type } }}
  {{>content}}
  {{#if type=='cat'}} No. {{else}} Yes. {{/if}}
{{/component}}
```
I feel like I could write stuff like that super-fast without thinking, because it's all within the same declarative "model". JavaScript you have to think about "configuration" of the Ractive, and I don't want to specially configure something, so I usually end up avoiding using components, and end up including all parts of my templates in one long page, even if it's (in one actual case) five pages of a wizard with hundreds of individual elements. It's too much of a cognitive burden (for me) to break up some stuff in partials on one side, and separate some components with a JS configuration on the other side, and on top of that, wrap external partials in a third-party XHR request in order to inject them into my template. So I just skip all of it and avoid separating things at all. Which is probably not great, and I think Ractive could possibly make it easier.

Does that make sense?

**Comment by matthew-dean** [comment]
Maybe this would be a separate issue, since this isn't about caching a template, per se, but related in the sense that I want to import external templates declaratively, albeit with more Ractive-like syntax.

**Comment by Rich-Harris** [comment]
You can already do that with components – see https://github.com/Rich-Harris/ractive-load-example (ignore the ractive-load part, it could be any component loader – this was just to show off the 'look Ma, no build step!' feature of ractive-load):

```html
<link rel='ractive' href='./Rating.html'>

<p class='current-rating'>current rating: <strong>{{rating}}</strong></p>

<div class='ratings'>
  <h3>Clickable Rating</h3>
  <Rating max='10' rating='{{rating}}'/>

  <h3>Readonly rating</h3>
  <Rating max='10' rating='{{rating}}' readonly/>
</div>
```

I just put the demo online – http://www.rich-harris.co.uk/ractive-load-example/. Or did you mean something else?

**Comment by matthew-dean** [comment]
@Rich-Harris Ractive-load seems cool. On the component side, it doesn't look similar (looks like the component is still JS-based), but that could be a separate issue.

**Comment by matthew-dean** [comment]
That said: I feel like I should always pair everything I ask for with the caveat that Ractive makes my life easier on a daily basis, lol. ^_^

**Comment by heavyk** [comment]
@Rich-Harris wow dude, thanks for that demo!! now that I know it's so easy, I'm gonna be all over that! totally rad!

**Comment by fskreuz** [comment]
@matthew-dean For entire components (markup, styles and logic), [rvc](https://github.com/ractivejs/rvc) can [also do the same thing](https://github.com/ractivejs/component-spec/blob/master/authors.md#link-tags---imported-components-optional). All one has to do is `<link>` and depending if you provided the name, rvc will use that name or infer from the path, and simply use the component without using any JS at all.

```
<link rel='ractive' href='foo.html' name='bar'>
<bar />
```
