### ISSUE TITLE
Can't reset data (ractive.reset) when data is an unwrapped array

### ISSUE THREAD

**Issue by AmitAber** [ractivejs/ractive#1310]
When trying to reset data, ```Ractive.reset``` fails with the error "Out of stack space" (ON IE)
http://jsfiddle.net/y9tog30o/8/

This is not necessarily a supported feature by design, but if it shouldn't work it should probably be prevented on creation, and not on ```reset```

**Comment by Rich-Harris** [comment]
@AmitAber sorry for the crazy delay - this is similar to #1318, and something we've been looking at recently. Using an array as the root data object will indeed cause problems, and as of 0.7 (out very soon), you'll get a prominent warning in the console:

![screen shot 2015-03-14 at 2 20 16 pm](https://cloud.githubusercontent.com/assets/1162160/6652893/424ec24c-ca55-11e4-9646-8de4638a2bbd.png)

It won't fail immediately, because that would be a breaking change for a lot of apps that work just fine this way, but that might change in a future release. The best thing to do is to move away from arrays-as-root-objects as soon as possible:

```js
// this...
data: {
  list: myArray
}

// ...instead of this:
data: myArray
```
