### ISSUE TITLE
magic mode arrays: no setters?

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#1318]
Hi,

In magic mode, when using:
array.push(...);
it works and the view is updated accordingly.

However, when using:
array[i] = ...
the data is changed but the view remains unaffected.

Here is a fiddle:
http://jsfiddle.net/405pfp6b/

Is this a bug or a known limitation?

Best regards,

**Comment by Rich-Harris** [comment]
As this currently stands, that last fiddle still won't work, but for a different reason - you can't do `ractive.merge('',arr)` because that implies `ractive.set('',arr)` which doesn't work (we don't explicitly look for that error, but it fails because the `''` keypath doesn't have a parent).

Now that we've resolved to discourage non-POJO root data objects, I'm not convinced that this should be considered a bug. Adapting that example to use a `list` property belonging to `data` works fine: http://jsfiddle.net/rich_harris/Lfnxvsgr/

Any objections to this being closed?

**Comment by martypdx** [comment]
:+1: I know I'm the choir here, but the more we reserve root to not be anything other than POJO hash, the more these headaches go away.

**Comment by Rich-Harris** [comment]
Cool, will close this. @dagnelies, the 'best practice' here is not to have an array as your root `data` object - as of 0.7, Ractive will shout at you if you pass in `data: anythingOtherThanPOJO`. Hope that's a good enough answer!
