### ISSUE TITLE
Parse bug in attribute value without quotes

### ISSUE THREAD

**Issue by codler** [ractivejs/ractive#1350]
This bug exist in 0.5.5 and on edge
```JavaScript
// Incorrect, I expect it should output same as the other
> JSON.stringify(Ractive.parse('<item attr={{attr}}/>'))
> "{"v":1,"t":[{"t":7,"e":"item","a":{"attr":[{"t":2,"r":"attr"},"/"]}}]}"

// Correct
> JSON.stringify(Ractive.parse('<item attr={{attr}} />'))
> "{"v":1,"t":[{"t":7,"e":"item","a":{"attr":[{"t":2,"r":"attr"}]}}]}"
> JSON.stringify(Ractive.parse('<item attr="{{attr}}"/>'))
> "{"v":1,"t":[{"t":7,"e":"item","a":{"attr":[{"t":2,"r":"attr"}]}}]}"
```

**Comment by evs-chris** [comment]
I was trying to resolve this, but it isn't obvious to me what the error is. It's pretty easy to go slightly against the spec and make `<item attr={{attr}}/>` and `<item attr={{attr}} />` parse the same way, but there isn't really an opportunity to throw an error since either way is technically valid. HTML is fun.

**Comment by codler** [comment]
alright then Ill close this since it is valid HTML spec.
