### ISSUE TITLE
`change` events fire before model is updated

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#1371]
Not sure if this qualifies as a bug, but since it's an apparent source of confusion it's worth bringing up: http://jsfiddle.net/damngoto/6dbh1mzk/2/

The `change` event handler is fired before the model is updated after the user interacts with the `<select>`. That means that `this.get('v1')` hasn't been updated by the time it's alerted. Perhaps events (or at least those events that can be used in place of two-way binding) should trigger handlers after the update and not before (though there's a non-zero chance that that would break other things).

**Comment by fskreuz** [comment]
+1

I am strongly a supporter of events after changes, as it will make them consistent with DOM elements and will make components act like your regular DOM elements.

At the moment, we don't use two-way binding in some component, and use DOM/proxy events and manually picking up values. But instead of having something like `component.get('value')`, we end up having the parent component digging for the DOM element of the child component (usually via `event.node.value`), which is bad-practice as components should encapsulate implementation. Besides, what if the component changed implementation, and used something other than an input. That makes `event.node.value` break the code.

**Comment by thomsbg** [comment]
+1 I was recently bit by this bug. Moving the handling of `on-change` to after two-way bindings is my expected behavior.
