### ISSUE TITLE
Enhancement suggestion: put all functions in a single place?

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#1525]
Hi,

I find it currently a bit tricky to use functions in ractive because of "where" they have to be declared.

* Inline expressions have to be in: `data.someFunction`
* Event method calls have to be in root scope: `someFunction`
* Proxy events have to be declared using: `ractive.on( 'someFunction', ...)`
* Computed properties go in: `computed.someFunction`

...and I'm sure others have to be declared somewhere else.
I don't know if it makes sense, but from a user perspective, it'd be nice if we could all declare them in one place.

**Comment by 00Davo** [comment]
Well, under Knockout, everything is essentially in the same place, and I find that pretty clear. Functions for inline expressions, proxy events, and event method calls are all subsumed under "call a method on the current context", which is the same object your data lives on. Computed properties are defined using a `ko.computed()` wrapper and then also stored in the data object. Everything being in the same place has a nice symmetry.

Of course, Ractive is less "intrusive" by design, since you aren't expected to wrap your data in distinct observables, so perhaps a greater degree of separation is appropriate. (For what it's worth, I think I'd prefer some sort of `Ractive.computed()` call akin to `ko.computed()` over the current handling of computed properties?)

**Comment by fskreuz** [comment]
Computed properties are more like the computed properties of Ember views. They change the display of the data without altering the internal representation. If my date in my model is represented in a timestamp, and I want it in MM/DD/YYYY in my UI, computed properties are the way to go.

Data functions can be used in the same way as computed properties, but I usually use them out of convenience. I don't want functions in my data and computed properties can't be nested, whereas data functions resolve similarly to plain data (they climb up the data to find).

Proxy events and method calls are similar, but method calls provide you more control over what you pass. Proxy events rely on the event object + context, which may sometimes be different in some cases. Depends on your taste really. Personally, I go for proxy events as it keeps out function calls in my templates. However, if you want to verbose, method calls aren't that bad.
