### ISSUE TITLE
Enhancement suggestion: inherit attributes for components/widgets

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#1535]
Hi,

Components appear to be extremely great stuff. However, as I already mentionned in #1454, they are  IMHO crippled by one detail. One of the main pitfalls for components is that they don't behave like "normal" html dom nodes. You can't set `<widget style="width:200px" />` except if it's specifically defined in the template. This, in turn, leads to component templates like this:

```
<a href='{{href}}' media='{{media}}' target='{{target}}' type='{{type}}' id='{{id}}' class='{{class}}' style='{{style}}' draggable='{{draggable}}' {{#hidden}}hidden{{/hidden}} title='{{title}}' onclick='{{onclick}}' ondblclick='{{ondblclick}}' onmouseover='{{onmouseover}}' onmouseout='{{onmouseout}}' ondrag='{{ondrag}}' ...
```

...even for trivial components you have huge chunks of "attribute forwarding". It is definitely impractical and error-prone.

The enhancement suggestion would be a flag
 `inheritAttributes: true/false`
When set, all top level elements would inherit all default html attributes, except if it's overriden by some other value in the template itself. If it helps in any way, restricting components to a single DOM element would be ok too in my opinion. This would drastically help making simple components/widgets.

Cheers

**Comment by andreujuanc** [comment]
@dagnelies  it'd be nice to have something like this already implemented, but it's not so easy to design, i can image. What if I want to set an attribute jut for the component and not for the first node of the template? or maybe i have 10, and want just half? Someone said about a switch in the options, but I think it can be done as said before using some kind of decorator.

**Implementation:**
`<widget style="width:200px" config1="12345" />`

**Template:**
`<a href='{{href}}' media='{{media}}' target='{{target}}' type='{{type}}' id='{{id}}' class='{{class}}' style='{{style}}' draggable='{{draggable}}' {{#hidden}}hidden{{/hidden}} title='{{title}}' onclick='{{onclick}}' ondblclick='{{ondblclick}}' onmouseover='{{onmouseover}}' onmouseout='{{onmouseout}}' ondrag='{{ondrag}}' ...`

I dont want config1 to be as attribute in my <a>, so I can see two ways to implement this:
1. Have a list of reserved keywords for attributes, exactly those standard for html elements, so they get automagically "copied".
2. Have a prefix for anything else you need copied but it will get things a bit ugly. :(

I like number 1. this way forces developer not to use html keywords as variable names.

Anyting like, data- , id, class, style, and so on, gets transferred to the first element of the template, heck, i can imagine setting the index for that, so I might wrap the template in a <div> for example and set the index=1 on my ractive instance, so it wont copy the attributes to the div, but to the first child node.

And of course, anything else not defined as "standard keyword attribute" wont be copied, but instead go straight "data".

What you think?

**Comment by dagnelies** [comment]
I'd make it even more simply: every binding that's not used in the template is inherited as regular attribute.

Let's take following component template as example:

`...template: '<a class="btn btn-{{type}} {{class}}">{{yield}}</a>`

everything besides `type`, `class` and obviously `yield` would be inherited, so that:

`<btn type="primary" href="http://..." style="padding:100px">My linked button</btn>`

Would be translated into:

`<a class="btn btn-primary " href="http://..." style="padding:100px">My linked button</a>`

...where the undeclared `href` and `style` have simply been inherited.

**Comment by andreujuanc** [comment]
And how would you have an attribute in <btn> skipped from being added to the element?

Like i said before, if I have parameter that are not html related, but something like a config value for my component, why would it be translated to my element? it will just pollute it.

**Comment by ghost** [comment]
I would favor the verboseness of having to manually forward the attributes instead of implicitly inheriting attributes. Implicit inheritance is too magical, might bite back.

There was a discussion somewhere that talks about forwarding an object as a whole as a binding to the component. Not sure if it was implemented, I couldn't find the tests.:

``` html
// Parent binding. Imagine "." had href, text and target
<Component this="{{.}}" />

// Child template.
<a href="{{ href }}" target="{{ target }}">{{ text }}</a>
```

I would imagine, for this case, you'd want the child template to do the same thing:

``` html
// Parent binding. Imagine "." had href, text and target
<Component this="{{.}}" />

// Child template. Unrolls href and target onto <a>
<a this="{{ . }}">{{ text }}</a>
<div>unrelated div gets nothing</div>
```

The above would satisfy "spreading" the data as attributes selectively and automatically with minimal markup. However, note that there's `text` in the data which isn't an attribute of `<a>`. Should Ractive do this spreading behavior, it should know what attributes are valid and what aren't.

My 2c.

**Comment by evs-chris** [comment]
What if you could specify a list of non-element attributes for your component, and ractive automatically collected everything else up and made it available as a partial? That way you could easily control what's relevant for config/data and where whatever is left over is actually rendered.

``` js
Ractive.extend({
  template: `<div class="header-thing"></div>
<div {{>attribute-content}}>...</div>`,
  configAttributes: [ 'foo', 'baz', 'data-my-special-unicorn', 'value' ]
}); // this will be a component named cmp

var otherTemplate = `<cmp value="{{yeah}}" class="big and purple" foo="{{foo}}" />`
```

I haven't looked at it in depth, but I don't know how combing through the template for top-level refs would work out. Explicit feels safer, and it would make having "required" attributes in another property a bit more natural feeling. Required attributes would be any mappings/config attributes that a component needs in order to accomplish something, where a warning would automatically be emitted if absent.

Would all of that be better left to library functions or baked into ractive? This falls into the category of template manipulation, which is handy, but ractive currently provides no tools to do so. It's all manual at this point, but aside from navigating a terse template structure, it's not difficult at all.

**Comment by andreujuanc** [comment]
@evs-chris I like this approach. 👍 specially the warning part.

If you think it will have an impact on performance then would be better off in a library, but otherwise baked for sure.

**Comment by dagnelies** [comment]
> What if you could specify a list of non-element attributes for your component, and ractive automatically collected everything else up and made it available as a partial?

That would be fine with me.

---

Just to be sure I interpreted it correctly, the result of your example would be:

```
<div class="header-thing"></div>
<div class="big and purple">...</div>
```

right?

---

Sounds good to me, but I'd prefer a more lightweight syntax though:

```
Ractive.extend({
  template: `<div class="header-thing"></div><div {{>attributes}}>...</div>`,
  bindings: [ 'foo', 'baz', 'data-my-special-unicorn', 'value' ]
});
```

The `{{>attributes}}` partial would then contain all other attributes not listed in the bindings. Or, if you want to follow your required/optional parameters logic:

```
Ractive.extend({
  template: '<div class="header-thing"></div><div {{>attributes}}>...</div>',
  required: [ 'foo', 'value' ], 
  optional: ['baz', 'data-my-special-unicorn']
});
```

**Comment by evs-chris** [comment]
@dagnelies yes, you correctly interpreted my example :smile:. Sorry, I typed that message on my phone, so it was a bit short.

After a question on the mailing list about nested components, my own experience putting together container-like components, and some other issues that seem to point in the same direction, I think helpers for manipulating template would be useful. Things like grabbing the top-level elements from a content partial and massaging them into their own data structure a la https://jsfiddle.net/L9rvx5Ly/1/ would be much cleaner with a little bit of library support. It should handle this case more generally by allowing access to the component attributes more easily to make a partial. It could also cover #1786 and #2001.

I'll see what I can put together for an RFC.

**Comment by evs-chris** [comment]
Moving extra attributes to an element is now possible in edge.
