### ISSUE TITLE
Regression bug: root context not available anymore in components

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#1548]
Hi,

Here is the fiddle:
http://jsfiddle.net/qy6gcfg3/

Works in latest, broken in edge.

Btw, observe the output of `this.get()`. When inside a component, it returns an internal `_data, _mapping` properties instead of the resulting data.

**Comment by dagnelies** [comment]
Seems to work now on edge... I'll close it if you don't see objections.

**Comment by Rich-Harris** [comment]
@dagnelies I came here because I was looking for the origin of a particular test case... am currently working on #1594 which simplifies a lot of things but reintroduces this issue in a different form.

I'll try and explain as concisely as possible:

* I recently did some work (https://github.com/ractivejs/ractive/pull/1381#issuecomment-60039921) that affects how inter-component data propagation works. This is partly for performance reasons (it's much more efficient!) and partly because the new model is just more sensible - it eliminates a whole load of bugs and complexity around data flow.
* The key difference is that, internally, data has an 'owner'. If you have `<widget foo='{{bar}}'/>` in your template, the value of `foo` inside the widget doesn't get 'copied' from `bar` outside the widget - instead, the widget knows where it needs to look to find the value of `foo`. So there's a 'single source of truth' and a clean separation, but...
* ...there's no longer a `foo` key on the `widget.data` object. So `JSON.stringify(.)` or `widget.get()` doesn't return the same thing as it did before, although `widget.get('foo')` works as expected.
* To minimise breaking changes that result from this, we introduced `ComponentData`, which uses getters (in ES5 situations) or cloning and tracking (in IE8).
* This turns out to involve quite a lot of back-and-forth, and I came to the view that we'd be better off without `ComponentData`, and in fact that we'd be better off without bothering with `ractive.data` at all (which is what #1594 is about)
* As far as I can see, you can still do everything you'd have wanted to use `ractive.data` for. [This test](https://github.com/ractivejs/ractive/blob/4fe19537a27f903795d6a94763cfbeaaf28bd9ad/test/__tests/componentData.js#L1125-L1143) - the one that brought me to this issue - is the only one left that doesn't pass.

So if we go ahead with #1594, we need to decide how `ractive.get()` or `ractive.get('')` should behave - should it simply return `ractive.viewmodel.data` (which is where the data gets stored), or should it return an object that includes the properties of `r.v.data`, plus the properties of `r.v.mappings` (where `foo`, or `b` in your original example, is to be found) and `r.v.computations`?

And when you have `{{JSON.stringify(.)}}` in a template, you're calling `this.viewmodel.get('')` internally - should *that* return the plain or synthetic object?

Of course, this stuff could be behind options, at least as far as the public API is concerned:

```js
data = ractive.get(); // data === ractive.viewmodel.data

// API is maybe a bit weird - you can only have these options
// when getting the root value, as mappings and computations
// are always followed when you get a property or nested keypath
data = ractive.get({
  includeMappings: true,
  includeComputations: true
}); // generated on-demand
```

**Comment by evs-chris** [comment]
FWIW, I can't imagine a scenario in which you'd want to get the data without *all* of the data included.

**Comment by dagnelies** [comment]
Thanks for the detailed answer. Like chris, I'd include everything by default too

**Comment by dagnelies** [comment]
@Rich-Harris 
Hi,
I'm closing this since I consider this particular bug resolved and done. For the other thread #1594, it's quite long, so I'll read it when I've time. Just do me a favor and keep things simple and robust ;)
And like @evs-chris , I'm in favor of including everything in `ractive.get()` by default, including mappings and computations.
Cheers
