### ISSUE TITLE
ractive.findComponent(selector,{where:filterFn})

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#1556]
Idea for selecting particular components - see https://github.com/ractivejs/ractive/issues/343#issuecomment-66131983. Would also apply to `findAllComponents`.

``` html
<my-component ref='foo'/>
```

``` js
var foo = ractive.findComponent( 'my-component', {
  where: function ( component ) {
    return component.get( 'ref' ) === 'foo';
  }
});
```

**Comment by JonDum** [comment]
Hate to pull this up from the grave, but I have a valid use case.

I have several ractive-autocomplete's in a form, registered as `components: { autocomplete : ... }`. It seems really silly that I have to loop through all of them based on some kind of distinguishing `ref` instead of getting one directly via 'id'.

Why not `findComponent('#someId')`? 

```
<autocomplete id='one' .../>
<autocomplete id='two' .../>
<autocomplete id='someId' .../>
<autocomplete id='three' .../>
```

That maintains parity with DOM querying a la  `querySelector('div')` &  `querySelector('#bla')`. The same could be done with components to match this mental model, no? Return the 'tag' (component) if there is no `#` or return the first found component with that `tag` name with that id if there is a `#` (or even a `.` for classes! )

**Comment by guilhermeaiolfi** [comment]
That would be great. I'm using a ```getByRef``` function in my apps. But would be great to use something that exists in core. Extra +1 for CSS selectors (just ```#``` and ```.``` would be more than enough) there.

**Comment by guilhermeaiolfi** [comment]
How you handle events from components if you need to do something like:
```javascript
instance.on("drop-zone.uploaded", function() {});
```

and you have many ```drop-zone``` components in one page? I mean, without putting a ```on-uploaded``` in the component? How would you know which is which?

I thought that maybe the ```id``` idea could go a little further and support:

```javascript
instance.on('#first.uploaded', function() {});
```

**Comment by martypdx** [comment]
You have access to the component that raised the event:

```js
instance.on("drop-zone.uploaded", function() {
    var dropZone = this.event.component;
});
```

**Comment by skeptic35** [comment]
Hmmm.... I might have a valid use case here:
I have a menu component that has item components which can have a menu component which has item components ... you get the drift.
Due to the recursive nature of these components they are all set to isolated. Yet when I call ```findAllComponents("item")``` in my topmost menu component I do not (as I would have expected) get only direct child components of my menu but instead all item components no matter how far down in the hierarchy they are. So in this case I'd actually like to filter the list of components. Admitted, that is exactly what I do now, just not within the ```findAllComponents()``` call.
Come to think of it - I'd rather have another method for this: ```findAllChildComponents()``` ;)
