### ISSUE TITLE
Ractive won't resolve references with manipulation of index, nor with aliasing (2-way binding or pass to component)

### ISSUE THREAD

**Issue by mkrn** [ractivejs/ractive#1570]
Here's a problem I ran into:
Reference like this `<myComponent fieldValue="{{data[multipleIndex+topRecordIndex][ref]}}” />`  or `<input value="{{data[multipleIndex+topRecordIndex][ref]}}" />` will not be updated on change of indexes when passed to component or for field 2-way binding.

http://jsfiddle.net/yesrmLqu/3/ works great until you add 
`<input value="{{ arr[arrIndex+otherIndex].name }}" />`
The result is: http://jsfiddle.net/yesrmLqu/4/ **Warning! WIll hang**

So I tried aliasing as a work-around but this wouldn't work either:

```
{{# {rowIndex: multipleIndex + topRecordIndex } }}
  <myComponent value="{{data[rowIndex][ref]}}" />
{{/}}
```

Also, I don't know if it's by design or not, but aliasing would not 2-way bind:

```
{{# {something: somethingelse} }}
<input value="{{something.field}}" />  Would show value but not update somethingelse
{{/}}
```

I would appreciate any hints!

**Comment by Rich-Harris** [comment]
Sorry for the extreme delay. Figured out what's going on here: if you do `ractive.set('some.unknown.array[4].property')`, Ractive creates the intermediate objects and arrays ('branches', internally). This is a problem for the example at hand - when you create an input that points to a property of an array member that doesn't yet exist, that array member is created. But that (in this case) increases the length of the array, which causes the section to be rendered again, which creates a new two-way binding, which increases the length of the array, which causes the section to be rendered again,  which creates a new two-way binding...

One possible solution is in #1570 - don't create branches for two-way bindings. I'm not sure if I like it. It's only a partial solution in any case - in this example, the extra array member won't be created when the binding is set up, but it *will* be created when you edit the final `<input>`. Which probably isn't what you want.

I'm not sure if there's a good way that Ractive *can* accommodate this particular case (though hanging obviously isn't ideal). Thoughts welcome...

**Comment by evs-chris** [comment]
That's a nasty little problem that's hard to detect. Also, branching is handy for less infinite cases.

My first thought was to add a runloop counter for loop detection so that at some point Ractive can give up and throw an error out saying 'you have created an endless loop in your template' instead of hanging. I seems to me that that along with @martypdx's fix are the best resolution.

**Comment by martypdx** [comment]
I think it's a broader issue with developers having the potential to do recursive things:

```js
this.observe( 'myArray.*.foo', function ( n, o, k, i ) {
    this.set( 'myArray.' + ( i + 1) + '.foo', n + 1 );
});

// how about
this.observe({
    foo: foo => this.set( 'bar', foo + 2 ),
    bar: bar => this.set( 'foo', bar - 2 )
});
```

While loop detection would be nice, it doesn't seem to come up very often in the gh issues - so I also think we could also put it off to future enhancement.

**Comment by evs-chris** [comment]
The self-extending array issue aside, the nominal issue here has been resolved, since you can bind with aliases `{{#with somethingElse as something}}<input value="{{something.field}}" />{{/with}}`. I'm going to close this, as I don't thing we can really fully protect against the footgun of recursive expansion on arrays without hobbling functionality.
