### ISSUE TITLE
source maps

### ISSUE THREAD

**Issue by victorwpbastos** [ractivejs/ractive#1620]
The version in edge don't have the source mappings!

**Comment by Rich-Harris** [comment]
Working on it! Sourcemaps are hosed at the moment - there are three transform steps (transpile ES6 syntax with 6to5, bundle modules with Esperanto, uglify the result) which each output sourcemaps, after which they need to be combined into a single sourcemap. If any of those steps is slightly wrong, it has compounding effects.

One (or more) of those steps is currently slightly (or maybe very!) wrong. I'm not sure which, though I suspect it's my fault. I'll mark this as a bug so that it gets resolved before we ship a new stable version.

**Comment by martypdx** [comment]
@Rich-Harris can we take the `//# sourceMappingURL=02-6to5-[...].js.map` directives out of the build in the mean time?

**Comment by Rich-Harris** [comment]
Closing this issue as sourcemaps are now published, #1774 and #1777 notwithstanding. @martypdx might not be a bad idea to remove intermediate `sourceMappingURL` comments - have opened https://github.com/esperantojs/esperanto/issues/120
