### ISSUE TITLE
Enhancement: {{elseif}}

### ISSUE THREAD

**Issue by Madgvox** [ractivejs/ractive#1629]
I'm in a situation where I basically require a `switch` statement, with access to a 'default' action. It's certainly possible without an elseif, but it's uglier for it.

https://github.com/ractivejs/ractive/pull/662 mentions `{{elseif}}` being put off (understandably) until pain is felt. I'm feeling a bit of the pain. Maybe not enough to justify an implementation, but there's certainly a use case for it.

**Comment by evs-chris** [comment]
This has been on my list for a while, as I have several templates that would benefit from not having to nest `if`s or repeat conditions so much. I looked into it a while back to see what it would take to implement.

Currently, the `else` is picked up as a special reference during post-parse processing and the if block is split into the main conditional and a negated conditional. I think the simplest approach would be to keep the special reference handling, but instead of negating the conditional, link the two (or more for `else if`s) together with a siblings list. Then as a scheduled task after an update, iterate the siblings list and render the first truthy one and unrender all of the others. Any `else` block would always be truthy, and thus, the default case.

As far as template syntax, I don't think anything with `{{# else if }}`-type syntax will end up looking right and could lead to weird scenarios like
```html
{{# if foo }}...{{/if}}
You should not do this...
{{# elseif bar }},,,{{/elseif}}
```

Closee/open sections also don't feel right to me:
```html
{{# if foo }}
  foo is truthy
{{ /# elseif bar }}
  bar is truthy
{{ else }}
  what happens with me, or should I be handlebar-style too?
{{ /elseif }}?
```

I personally lean toward a special, blessed method-call:
```html
{{#if foo }}
  foo is truthy
{{ elseif (bar) }}
  foo is falsey, bar is truthy
  my single argument would be converted into my condition
{{ else }}
  my block is always true, but will only render if my siblings have a falsey value
{{/if}}
```

In that case, `elseif`s basically get the same treatment as `else`s.

**Comment by martypdx** [comment]
> `{{ elseif (bar) }}`

There's nothing special about the parens, could just be: `{{ elseif bar }}` right?

**Comment by evs-chris** [comment]
In this case the parens are required, since the parser would need to pick it up as a method call. `else if` could be added as a special case directly in the mustache parser to avoid having to use parens, but I kind of like them here. Invalid js expressions in non-section mustaches look weird to me.

**Comment by Madgvox** [comment]
My only issue with parens is that it's such a weird requirement. Parens aren't really a requirement anywhere else in a template. Given someone who knows that there is an elseif functionality, but haven't seen the documentation, their first inclination will be to produce something like what @martypdx wrote, `{{ elseif bar }}`. I think that it makes sense for `{{ elseif }}` to be a reserved keyword just like `{{ else }}` is.

**Comment by Rich-Harris** [comment]
This is now implemented! http://jsfiddle.net/rich_harris/bmba0usa/ Thanks everyone for the input and @evs-chris for the tests and initial implementation

**Comment by rstacruz** [comment]
this is fantastic. dealing with conditionals in Ractive have always felt awkward before this :)
