### ISSUE TITLE
[IE8] "Stop running this script?" dialog + template Iteration performance approach question

### ISSUE THREAD

**Issue by akhoury** [ractivejs/ractive#1652]
During some IE8 testing, I noticed that I occasionally get the __"Stop running this script dialog"__. I was able to narrow it down to part of my template where it's iterating of a list of ~1000 items and creating a span of text for each in the DOM (while the parent container has __display:none__) 

Before I go ahead and start implementing pagination, I wanted to see if there is a better approach to create and append a large list of DOM Nodes, like all at once (kind of like using createDocumentFragment), or maybe suggest that Ractive internally could use that fragmentation when possible, because to be honest, 1000 is not a large number in computer-speak.

However, I do admit that my widget is heavier than just simple fiddle, so in order for me to replicate the error in a simple fiddle, I had to use 10000 instead of 1000.

#### HTML
```html
<script id="template" type="text/template">
    Hidden list below
    <div style="display:none;">
        {{#each list:i}}
        <span data-i="{{i}}">list-index-{{i}}</span>
        {{/each}}        
    </div>
</script>

<div id="target"></div>
```
#### JS 
```javascript
var r = new Ractive({
    el: '#target',
    template: '#template',
    data: {
        list: new Array(10000)
    }
})
```

![screen shot 2015-01-22 at 6 40 44 pm](https://cloud.githubusercontent.com/assets/1398375/5867121/3dd06002-a266-11e4-8e5e-3d9904c50f5c.png)

View fiddle: http://jsfiddle.net/bentael/yfzxaLo4/8/
View on ie8: http://jsfiddle.net/bentael/yfzxaLo4/8/embedded/result/

### Interesting finding: 

I also tested with just vanilla JS, trying to get that error again, and I tried like appending 300000 nodes, the scripts would run for 30 or 40 seconds, and __I was not able to get that same dialog, even when I try 1,000,000 nodes, IE8 would stop responding but still, no "Stop running this script dialog" dialog.__ Could you think of anything that Ractive might be doing internally to trigger that dialog? Also, when I actually see the dialog, if I select NO *(do not stop the script),* everything finishes normally, __it's NOT like there is an infinite loop or recursion__ or anything of that kind, which should just hang. 

I do understand that with Ractive's feature set, the performance cannot be benchmarked against a Vanilla JS test case, but still, the browser hanged and I didn't see the dialog :/ 

Without fragmentation, 300k items, avg 37s on ie8 in a VM
http://jsfiddle.net/bentael/g63hf00o/7/embedded/result/

With fragmentation, 300k items, avg 35s, on ie8 in a VM
http://jsfiddle.net/bentael/L786gd4q/8/embedded/result/

**Comment by akhoury** [comment]
looking through your source, it looks like fragments are used everywhere, so I take suggestion back, but I am still not able to figure out the part that's causing ~5,000,000 statements, according to this [SO answer](http://stackoverflow.com/a/21134559/493756)

**Comment by Rich-Harris** [comment]
I get the same result viewing that fiddle in IE8. I believe HTMLBars (replacement for Handlebars in future Ember versions) has a neat trick which may be relevant here - using `fragment.cloneNode(true)` for repeated sections rather than building each one up programmatically, which (apparently) is not as performant. It may be possible to do something similar in some cases - it does introduce some complexity (e.g. you need to reach into the cloned DOM to change stuff after it's been created, which means you need an efficient way of selecting nodes), but it could potentially reduce the number of statements/increase performance.

There may be other ways to reduce the number of statements so that it's harder to breach that threshold - will have to investigate.

**Comment by martypdx** [comment]
One potential area of performance improvement would be to reduce the number of virtual DOM pojo's used in sections. So that `{{#items}}<span>{{.}}</span>{{/items}}` only produces one object/set of objects with an array pointing to the DOM nodes, and the actual node-specific state is stored on the DOM node. Something of a flyweight pattern.

In the mean time, I don't have IE8 but [here's](http://jsfiddle.net/w8k2nha7/2/) a go at metering the data to control rendering. I'm assuming use of `setTimeout` allows the browser to "breath" and reset statement count.

```js
var count = 10000, step = 100, counter = 0, 
    fullList = new Array(count);

for(var j=0; j < count; j++){
    fullList[j] = j;
}

Ractive.components.widget = Ractive.extend({
    template: '<div data-i="{{i}}">list-index-{{i}} item {{num}}</div>'
})

var r = new Ractive({
    el: '#target',
    template: '#template',
    data: {
        list: []
    },
    oninit: function(){
        
        var next = function(){
            var chunk = fullList.splice(0, step);
            var merge = this.get('list').concat(chunk);
            this.merge('list', merge);
        }.bind(this);
        
        this.on('widget.render', function(){
            var current = this.event.component.get('i') + 1;
            if( current < count && current % step === 0){
                setTimeout(next);
            }
        });
        
        next();
    }
});
```

**Comment by akhoury** [comment]
@martypdx Thanks your solution works great in IE8! 

(had to switch to ractive-legacy obviously and you can only run it in embedded mode on jsfiddle in ie8)
http://jsfiddle.net/bentael/ghwyh2he/1/embedded/result/

**Comment by akhoury** [comment]
hey @martypdx, again, thanks, but could you explain `this.event` for me? I couldn't find it in the docs, 
what is that? the latest event? how could this be reliable in an asynchronous model? wouldn't it make more sense if the event was just passed in as a 1st argument ?

**Comment by martypdx** [comment]
Here's the docs for `this.event`: http://docs.ractivejs.org/latest/publish-subscribe#accessing-the-event-object

In the code example I gave, it works because it's used to end each rendering phase which happens synchronously (you can think of it as: change data --> DOM render --> event fires --> check if done). The asynchronicity is only used to schedule the next rendering phase.

If you needed to hold onto the information, alias the value for the closure:

```js
this.on({
    'myEvent': function() {
        console.log('a', this.event.name);
        var eventName = this.event.name;
        setTimeout(function() { 
            console.log('b', eventName);
        }, 250);
    }
});    
```

One thing about this solution that you could argue is sub-par is that is requires the component to know about `{{i}}`, its index position in it's parent. In your case, it looks like it was using that number anyway.

But to explore the topic a bit more, the directive format looks attractive because it's completely controlled by the parent:

```html
<widget on-render='widgetComplete'/>
```

This fires a new event when the widget.render event happens. Unfortunately adding arguments is not supported (`widgetComplete:{{i}}`).  And the context, keypath, and indexRef are not set relative to the parent - so no way to access the index. This is probably the easier enhancement we could make. You could also keep a counter and divorce it from the `{{i}}` altogether.

But, given that the component _does_ know about `{{i}}` it seems simpler to just directly handle the `widget.render` event. BTW - in this example you can also get the index via `this.event.context.i` instead of `this.event.component.get('i')`.

**Comment by akhoury** [comment]
awesome thanks!

**Comment by akhoury** [comment]
I wrote a quick `each` component for anyone facing the same issue on IE8, using @martypdx 's example, but expand it a bit to be to do this

```html
    <ul>
    <Each array={{myList}}>
        <li>id: {{id}}, name: {{name}}</li>
    </Each>                
    </ul>   
```

http://jsfiddle.net/bentael/ghwyh2he/11/

It can definetly be improved per Marty's last comment, but that works for now.

**Comment by akhoury** [comment]
but it gets a little more complicated when you're trying to pass an upper context or partial in, and listen to events 
```
    <ul>
    <Each array={{myList}}>
        <li on-click="onClick">id: {{id}}, name: {{>namePartial}}</li>
    </Each>                
    </ul>   
```
