### ISSUE TITLE
Edge ractive-legacy - errors on Object.defineProperty 

### ISSUE THREAD

**Issue by simond-14** [ractivejs/ractive#1654]
I'm trying to pickup fixes which I think relate to  #1431 but when I load the edge version of ractive from the CDN the site starts erroring in IE8.

It appears related to the use of Object.defineProperty / line 6423 throws an 'Object doesn't support this function'.

This reproduces the problem for me:

```
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=8" />
</head>
<body>

<div id='container'></div>

<script id='template' type='text/ractive'>
    <p>Hello, {{name}}!</p>
</script>

<script src='http://cdn.ractivejs.org/edge/ractive-legacy.js'></script>

<script>
    var ractive = new Ractive({
        el: 'container',
        template: '#template',
        data: { name: 'world' }
    });
</script>
</body>
</html>
```

Is this a known issue?   Any help appreciated.

**Comment by Madgvox** [comment]
Looks like the `parseJSON` module in the [6to5](https://github.com/6to5/6to5) package, which gets included in the build for `ractive-legacy.js`, does not check to see if `Object.defineProperty` is supported before using it. IE8 only allows `Object.defineProperty` to be used on DOM elements, so an error is thrown. Ractive is actually really good about checking for that sort of thing... apparently 6to5 is not.

**Comment by simond-14** [comment]
Thanks for the quick response.   Is there anything that you can think of that I might be able to do to workaround / fix the problem in the short term?  I'm keen to avoid figuring out a workaround for the issue I came across in 0.6.1 latest when it looks resolved in edge.

Thanks again for the help - much appreciated.

**Comment by Madgvox** [comment]
Initial searches on emulating `defineProperty` in IE8 are negative. It seems like Microsoft decided to make it as good as impossible to create getters and setters for objects _in only IE8_. The only thing I could think of was wrapping it in a function with a try-catch statement:

```js
Object._defineProperty = Object.defineProperty;
Object.defineProperty = function( obj, key, descriptor ) {
    try {
        Object._defineProperty( obj, key, descriptor );
    } catch ( err ) {}
}
```

Which is obviously not ideal as you have to go through a try-catch every time and if it's IE8 nothing happens at all. But maybe it'll work for you? ¯\\\_(ツ)_/¯

**Comment by simond-14** [comment]
crumbs..  thanks for that.   Would the workaround affect much of ractive's functionality?   It seems like it could be a fairly fundamental part of the code..

I'm testing a version from December 1st which appears to be pre 6to5 and post the DOM issue that I was facing with 0.6.1 Latest and so progress looks okay for the moment.

Do you think the 6to5 / legacy IE8 issue will get resolved for 0.7.0?   Unfortunately IE8 support is a requirement for our project and ractive is hugely helpful.

**Comment by martypdx** [comment]
[Here's what Ractive does for IE8](https://github.com/ractivejs/ractive/blob/dev/src/utils/object.js#L7-L21). You could turn that into a polyfill.

**Comment by Madgvox** [comment]
Basically `ractive-legacy` needs to not have the `parseJSON` module in it. From what I can tell it's the only thing that's breaking legacy-mode Ractive in IE8. It probably got included by accident at some point, since it kind of defeats the purpose of having a legacy mode and it wasn't there in 0.6.1. I searched the entire codebase for it and the only place it exists is inside the hidden `.gobble-build` folder. It's not even in the `6to5` module in the `gobble-6to5` package. I have no idea why it's there and there only.

In the meantime @martypdx's solution should work fine.

**Comment by simond-14** [comment]
aha fantastic - thanks guys.  Ractive is an incredibly awesome library - thanks for your help and work on it.  I've cloned a copy of the source and so hopefully I'll be more help on the next issue.

**Comment by Rich-Harris** [comment]
Well this is a fun irony... the `_defineProperty` function is added by 6to5 so that we can use computed properties [here](https://github.com/ractivejs/ractive/blob/dev/src/utils/parseJSON.js#L13-L18). We're using computed properties to [trick 6to5 into generated code that's valid ES3](https://github.com/ractivejs/ractive/commit/bde1f3eb40d4ae8fcc29c2ec872b825c659b797e).

So by trying to make things IE8 friendly, we've, err...

It *looks* as though https://github.com/ractivejs/ractive/pull/1656 fixes the problem - @evs-chris would you mind taking a look when you get a chance, since you might have already tried this and found some problem with it? Thanks

**Comment by Rich-Harris** [comment]
Thanks everyone, this should be fixed now - as long as all the build dependencies are up-to-date, the build should be correct, at least as far as this particular issue goes. @simond-14 let us know if you run into any more IE8 issues
