### ISSUE TITLE
Two-way binding on object iteration key

### ISSUE THREAD

**Issue by zaus** [ractivejs/ractive#1673]
Re: https://github.com/ractivejs/ractive/issues/115#issuecomment-72273997 and https://github.com/ractivejs/ractive/pull/1474

We can iterate objects and see the properties in a couple different ways:

    {{#obj:k,i}}<p>{{@key}} = {{k}} and {{@index}} = {{i}}, but value = {{.}}</p>{{/}}

Putting them in inputs lets us change the value, but not the key:

				{{#each item:k,i}}
				<tr>
					<td headers="trans-key">
						
						<input type="text" value='{{@key}}' />
					</td>
					<td headers="trans-value">
						<input type="text" value='{{.}}' />
					</td>
					<td headers="trans-act">
						debug: key={{@key}} k={{k}} i={{i}} this={{.}}
						<br />
						<a on-click="addRow" class="btn add"><i></i></a>
						<a on-click="delRow" class="btn delete"><i></i></a>
					</td>
				</tr>
				{{/each}}

And yes, probably the easier answer would be to refactor the key/value into a list.

**Comment by Rich-Harris** [comment]
Refactoring *would* be the best approach here, yes - if you were able to change the keys, I expect what would happen is the row you were editing would fall to the bottom of the list (because it would be seen as a deletion followed by a new entry). An ordered list is the only way to ensure that doesn't happen.

That being said, I'd class this as a bug - Ractive should warn or throw an error if two-way binding is used with a 'special' keypath like `@key`.

I've created a JSFiddle to build a test case from later: http://jsfiddle.net/rich_harris/Ljhfxpnd/

**Comment by zaus** [comment]
You're totally right about new/changed items jumping around (I was able to use `twoway=false` and a custom update function, per some other issue you helped me with, to get it to change the key).

**Comment by Rich-Harris** [comment]
Ractive will now warn if you try to do `<input value='{{@key}}'>` or something similar.
