### ISSUE TITLE
Dynamic Components

### ISSUE THREAD

**Issue by aphitiel** [ractivejs/ractive#1678]
Hi! Can I make my template choose a component based on data?

For now I'm using something like 

```
{{#if component === 'c1'}}<c1 />{{/if}}
{{#if component === 'c2'}}<c2 />{{/if}}
```

but that means the template has to know which components are available.

So I thought, maybe we could have nice things like `<{{component}} />`, or am I doing it wrong?

(BTW, ractive rocks, thanks for that!)

**Comment by Madgvox** [comment]
Right now you cannot define dynamic components. You can however define dynamic partials, so if you do not require the extra features of components, a dynamic partial might suit you well.
```js
partials: {
  'myPartial': 'Hello World'
},
data: {
  foo: 'myPartial'
}
```
```js
// outputs 'Hello World'
{{>foo}}
```

**Comment by dagnelies** [comment]
Ractive rocks indeed ...but I wouldn't push it too far. Doing something like `<{{component}} />` seems like opening Pandora's box ;)

**Comment by aphitiel** [comment]
Heh, thanks! Just wrapping those components in partials actually seems to work for me - let's see if Elpis still is in that box:)

So there are no plans for dynamic components? I have to admit that I have no idea where/how to implement that myself. But I can live without it - there will be other workarounds if the above hack breaks.

**Comment by martypdx** [comment]
The current state for dynamic components assumes they won't change once rendered (unless the hosting view changes or is `reset`) and is specified using a function for the component:

```
<!-- in template: -->
<selected-component/>

// js, assuming corresponding component names returned by data.component have been registered
components = {
  'selected-component' : function(data){
    return data.component;
  }
```
AFAICT, the work @evs-chris did for partials (to use the result as a reference instead of a token when the token cannot be found) is logically portable for components and IMO would be pretty useful instead of having to code the above, plus you get the targeted rerender if it changes without having to muck about with `reset` on the parent view (you can fake this to some degree by using partials that contain a component). 

I would forgo the `{{ref}}` and do same as partials -just try to process as a mustache ref if is not a registered component:

```js
Ractive.components.c1 = C1;
Ractive.components.c2 = C2;

new Ractive({
  template: '<div><component/></div><c1/><c2/>'
  data: {
    component: 'c1'
  }
});

// would yield same as:
'<div><c1/></div><c1/><c2/>'
```

**Comment by evs-chris** [comment]
I think there's probably too much that would need to happen to support either the mustachioed or 'just look up the name as an expression' methods. Partial expressions as of 0.8 support inline partial content, and that with template strings gets you to `{{> { template: `<${component} />` } }}`, which is certainly not awful. If you want runtime-only support (no parsing), you can achieve the same thing pretty easily by adjusting the `e` value of a pre-parsed template inline.
