### ISSUE TITLE
oncomplete function silently swallows errors in 0.6.1

### ISSUE THREAD

**Issue by mikemaccana** [ractivejs/ractive#1686]
http://jsfiddle.net/973cb430/1/

This should complain that `variableThatDoesntExist` isn't defined, but it doesn't.

    oncomplete: function(){
        console.log(variableThatDoesntExist)
    }

Edit: fix jsfiddle URL

**Comment by martypdx** [comment]
[Already fixed in edge](http://jsfiddle.net/973cb430/2/) via #1426.

**Comment by mikemaccana** [comment]
Cool. Is 0.8 far off? Thanks @martypdx! 👍

**Comment by sabob** [comment]
Is it possible to have Ractive throw an error instead of logging to the console? That way the errors bubbles up and eventually prints a stacktrace to pinpoint where the error originated from. This is helpful in development modes when errors occur in the lifecycle handlers.

**Comment by martypdx** [comment]
@mikemaccana It's `0.7`, but anyway see end of #1679 :)

@sabob AFAIK not in this case because `complete` fires asynchronously via a promise so a thrown error doesn't go anywhere.

We could augment the message [here](https://github.com/ractivejs/ractive/blob/dev/src/Ractive/prototype/render.js#L74) to include the fact that it came from the `complete` event.

**Comment by mikemaccana** [comment]
> 'I'd love for us to get a new release out this month'

oooooh. Rad!
