### ISSUE TITLE
Options of inherited options gets error in `Ractive.extend()` on Edge

### ISSUE THREAD

**Issue by codler** [ractivejs/ractive#1687]
http://jsfiddle.net/b37zk5fg <-- latest 0.6.1 and all earlier versions works
http://jsfiddle.net/b37zk5fg/1/ <-- edge broken, im getting errors

Im not sure how to explain this, but it is a regression bug.
I have an Object that have been inherited and then when I pass in to `Ractive.extend` I get error.

```javascript
/**
 * Convert TypeScript Class to be compatible with Ractive Extend 
 * 
 * @param tsClass
 * @returns
 */
function ractiveExtendTypeScriptClass(tsClass) {
	var instance = new tsClass();
	var extend = {};
	for (var key in instance) {
		extend[key] = instance[key];
	}
	return Ractive.extend(extend);
}

var Zeus;
(function (Zeus) {
    var Block = (function () {
        function Block(options) {
        }
        return Block;
    })();
    Zeus.Block = Block;
})(Zeus || (Zeus = {}));
//# sourceMappingURL=Block.js.map

var __extends = this.__extends || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    __.prototype = b.prototype;
    d.prototype = new __();
};
var Designer;
(function (Designer) {
    var Block;
    (function (Block) {
        var ChooseTemplate = (function (_super) {
            __extends(ChooseTemplate, _super);
            function ChooseTemplate() {
                _super.apply(this, arguments);
            }
            return ChooseTemplate;
        })(Zeus.Block);
        Block.ChooseTemplate = ChooseTemplate;
        Block.RChooseTemplate = ractiveExtendTypeScriptClass(ChooseTemplate);
        Ractive.components.chooseTemplate = Block.RChooseTemplate;
    })(Block = Designer.Block || (Designer.Block = {}));
})(Designer || (Designer = {}));
//# sourceMappingURL=ChooseTemplate.js.map

var tplMenu = new Designer.Block.RChooseTemplate({
        el: 'body',
        template: '<h1>Hello</h1>',
    });
```

I tracked down what commit caused this https://github.com/ractivejs/ractive/commit/75556a58615ad59e601bb8a7f7cf3bb3d137dcea

**Comment by Rich-Harris** [comment]
I've whittled the fiddle down to something I can make sense of - http://jsfiddle.net/rich_harris/wh2gywq9/ - and it looks like the issue is that the options object passed to `Ractive.extend()` has a `constructor` property, which is overriding the correct constructor (which is used internally in several places).

I guess the proper thing to do here is throw an error if an object with a `constructor` property is passed to `Ractive.extend()`. In the meantime, the workaround would be to ensure that you delete that property from the options object (which is what I've done in the fiddle).

**Comment by codler** [comment]
Thanks! your suggested solution `delete options.constructor;` works perfect!
