### ISSUE TITLE
#with in combination with ractive.set broken

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#1692]
Here is the fiddle:
http://jsfiddle.net/7tpzoo08/

Half-broken in latest
Doubly-broken in edge

**Comment by evs-chris** [comment]
Note to self (or anyone else bug hunting): Making the references within the `with` relative makes the example work, so it's hopefully a simple ref resolution bug.

**Comment by evs-chris** [comment]
I went ahead an looked into it, and this is another artifact of twoway binding. The binding on the select forces a value to be resolved so that the view and model match. Since there is no scoping on the references and `with` scoping isn't exclusive, they end up being resolved at the root of the model. Making the refs relative is a workaround (`{{.choice}}` and `{{#if .choice === 'B'}}` instead of `{{choice}}` and `{{#if choice === 'B'}}`).

The only way that I can conjure to solve this would be to add some sort of ambiguity tracking for references that could resolve in more than one context. That might end up being more surprising than the current behavior, though.

**Comment by Rich-Harris** [comment]
We could print a warning in this situation - if we get to [this line](https://github.com/ractivejs/ractive/blob/8cb30c0a0ab9c9459946d27af686ddf04b627870/src/virtualdom/items/Element/Binding/Binding.js#L38), we could say 'Two-way binding warning: `val` reference is ambiguous. Consider initialising your data so that references can be resolved immediately, or using a restricted reference (http://docs.ractivejs.org/latest/references#restricted-references)'. Does that sound like a plan? I get headaches just thinking about how unpredictable things would become if we tried to track the ambiguity, or how we'd deal with view -> model changes on unresolved references...

**Comment by dagnelies** [comment]
@Rich-Harris 
Hi,
From a user view point, there is nothing ambiguous about it. It's variable "x" within scope of "y". ...what should be ambiguous about that? Also, if you use another syntax, it works flawlessly:
http://jsfiddle.net/7tpzoo08/1/
It is broken using `{{#with example}}...` but works fine with `{{#example}}...`
...which leads me to think the issue is related to `{{#with}}`

**Comment by evs-chris** [comment]
It is variable `x` within the scope of `y`, but since there is no `y`, the scope stack pops and becomes root when it is forced by the twoway binding.

The plain mustache syntax does not really have an analogue in handlebars syntax. They have subtly different meanings (unless I have a misunderstanding of how they're supposed to work, which is a distinct possibility).

@Rich-Harris if that line is reached, perhaps along with the warning, the binding could also subscribe to its exact keypath and rebind if it changes? Or is that completely bonkers?

**Comment by dagnelies** [comment]
@evs-chris in the provided example, there *is* a `y.x`

**Comment by dagnelies** [comment]
@evs-chris Oh, you are right, at the time of creation it is indeed ambiguous. Indeed, a warning wouldn't harm.

**Comment by martypdx** [comment]
I remember we discussed before about whether ambiguous references, when forced, should bind to root of instance or to current context. But I don't remember why exactly. Should ambiguous reference be bound to current context instead?

> It is broken using {{#with example}}... but works fine with {{#example}}...

Yeah, that seems totally off. AFAIK they should resolve to the same thing.

**Comment by dagnelies** [comment]
Now that a syntax has been introduced to reference root scope ( `{{~...}}`) in  #889, I definitely vote for local scope preference.

**Comment by martypdx** [comment]
@dagnelies It would seem to make sense that `{{#with foo}}{{bar}}{{/with}}` means `foo.bar`, not `bar`. But maybe there are counter examples.

**Comment by Rich-Harris** [comment]
I've just submitted a PR (#1765) that prints a warning in these situations. Local scope preference might make sense (though on the flip side, you can always do `<input value='{{./foo}}'>` to enforce local scope), but I'm not sure if the case is strong enough to change the current behaviour and potentially breaking existing code. Do you reckon we can get away with just warning/nagging about uninitialised data?

**Comment by martypdx** [comment]
> Do you reckon we can get away with just warning/nagging about uninitialised data?

@Rich-Harris I wouldn't change it with `0.7`, maybe with a more compelling wiz-bang future release. :)

**Comment by Rich-Harris** [comment]
Will close this as I've just merged #1692 - running the fiddle above now causes this to be printed to the console:

![screen shot 2015-03-09 at 6 08 46 pm](https://cloud.githubusercontent.com/assets/1162160/6565570/6661bf9e-c687-11e4-88e6-28d2029d764a.png)

Discussion about whether to default to local context is over on #1776.
