### ISSUE TITLE
method calls within #with require global keypathes nevertheless

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#1694]
Hi,

See fiddle:
http://jsfiddle.net/fj6zk20j/

IMHO it would make more sense if everything within "#with" scope would be relative scopes/keypathes.

Cheers

**Comment by evs-chris** [comment]
I don't think there's really a way to accomplish that directly, since the keypath in the example is just a string. I suppose maybe some sort of relative notation could be supported for calls that have a fragment reference available e.g. `on-click="me.push('./items', 'foo')"`.

Personally, I'd just go with `on-click="me.push(@keypath+'.items', 'foo')"` to avoid having to provide the full keypath everywhere.

**Comment by dagnelies** [comment]
thanks for the tip
