### ISSUE TITLE
newly inserted component into the DOM has no access to parent's components

### ISSUE THREAD

**Issue by constantx** [ractivejs/ractive#1708]
as recreated here http://jsfiddle.net/constantx/mr321bqh/7/

A bug? Or maybe I'm using it wrong :)

cc @thomasdavis @rawrin

**Comment by martypdx** [comment]
The `panel` view doesn't have a registry entry for the `list` component. You could register the component `list` component on the `panel`:

```js
  var list = Ractive.extend({
    template: "& list<br>"
  });

  var panel = Ractive.extend({
    template: "& panel <list />",
    components: {
      list: list,
    }
  });

  var App = Ractive.extend({
    template: 'app <panel />',
    components: {
      panel: panel
    },
    ...
  });
```

Or register globally:

```js
  Ractive.components.list = Ractive.extend({
    template: "& list<br>"
  });

  var panel = Ractive.components.panel = Ractive.extend({
    template: "& panel <list />"
  });
```

Or anyway else you can get a ref.

**Comment by Madgvox** [comment]
Yep, when you create the `panel` ractive using `new panel()`, you're not instantiating it as a component, you're instantiating it as a new independent instance of ractive. Since it's independent, it doesn't have the `App` ractive as its parent. No parent, no access to those components. The `append` option just allows the two ractives to share the same element. It does not establish a hierarchy between the two.

**Comment by constantx** [comment]
> The append option only allows the two ractives to share the same element. It does not establish a hierarchy between the two.

I suspect as much :)

Thanks for clarification @Madgvox @martypdx
