### ISSUE TITLE
JS error when updating data that is passed to components

### ISSUE THREAD

**Issue by fgan** [ractivejs/ractive#1717]
when a ractive uses a component and binds two values to that component, updating both of those values simultaneously causes a JS error. This only happens when the component has two-way set to false.

See http://jsfiddle.net/kpmmva1n/3/ for an example

**Comment by Rich-Harris** [comment]
This has been fixed on the dev branch: http://jsfiddle.net/rich_harris/0cuwnkLx/ (the only thing I changed was to use 'RactiveJS Edge' instead of 'RactiveJS Latest'). Are you able to use that build instead? (you can download it from http://cdn.ractivejs.org/edge/ractive.js or do `npm install ractivejs/ractive#build`)

If not the workaround would be to only set one value at a time.
