### ISSUE TITLE
{{>yield}}

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractive#1748]
Just played with yields (and I'm liking it) and I was fascinated by the difference of `{{>content}}` and `{{yield}}`. However...

**Why is `{{yield}}` not in partial notation while `{{>content}}` is?** They both do the same thing (aside from the data context), render contained content to where either of the two is placed.

Would it make sense to make `{{yield}}` to `{{>yield}}` or `{{>content}}` to `{{content}}`? I prefer the former since people might be using `content` as a legit data name, and since yields are special, they're better off in a special syntax.

Thoughts?

**Comment by dagnelies** [comment]
Agreed ...I wondered about that one too

**Comment by cfenzo** [comment]
I assume it is because `{{yield}}` is like any other variable inside the component. It is "pre parsed content".
While `{{>content}}` is treated like any other partial inside the component.

**Comment by evs-chris** [comment]
@cfenzo has it. The content of a component is packaged up into a partial an made available to the component instance. Named partials within the component body are also added to the component instance.

```html
<component>
I am \{{>content}} or \{{yield}} if you want the context to be the container.
{{#partial foo}}I am \{{>foo}} or \{{yield foo}} if you want the context to be the container.{{/partial}}
</component>
```

`{{yield}}` is a special reference (kinda like `{{else}}`) that is effectively `{{>content}}` with the special container context set up. `{{>yield}}` is already a valid partial reference, so it wouldn't get the container context. `{{content}}` could be a special reference, but there was already a construct to handle it in partials. `yield`s could get a special sigil, like the `>` in partial references, but that would be more confusing to me.

**Comment by Rich-Harris** [comment]
Another way to think of it - `yield` *is* the sigil (the same as `>`, except that it means 'this content belongs to the parent, not to me'). In a way, `{{yield}}` is just short for `{{yield content}}` (you can also be more specific and have named yields like `{{yield header}}` and `{{yield footer}}`, if you have partials by those names - apart from the context, they behave like `{{>header}}` and `{{>footer}}`).

We *could* use a special character instead of typing out `yield`, but there aren't many special characters left!

**Comment by fskreuz** [comment]
@Rich-Harris I see. Now I understand.
