### ISSUE TITLE
Checkbox bound to checked and name

### ISSUE THREAD

**Issue by sabob** [ractivejs/ractive#1749]
Hi all,

From the docs[1] it's not possible to bind checkboxes to both checked and name attributes. I understand that "name" is used to identify a binding for multiple "value" while checked is singular.

However, would it be possible to support both? I have the situation where a checkbox is bound to a singular value, hence I use "checked", but I also need to provide a name to the checkbox as some third-party libraries require a name on form fields to work properly. For example I use the jquery plugin AreYouSure[2] to dirty check my forms and disable/enable the save button, however without a name on the checkbox it doesn't get registered by the plugin.

If both "name" and "checked" are defined on a checkbox "checked" is bound as the value. If "checked is missing it becomes multiple? But I can see that might be confusing though.

Kind regards

Bob

[1]: http://docs.ractivejs.org/latest/two-way-binding
[2]: https://github.com/codedance/jquery.AreYouSure

**Comment by martypdx** [comment]
The name attribute still gets passed through, it's just the actual mustache reference string including `{{` `}}`. If that still doesn't work for you, you can get around this by binding the `on-click` to a `toggle` call - which also enables both to work:

```html+django
{{#items:i}}
    <li>
        <input type='checkbox' 
               name='{{selected}}' 
               value='{{i}}' 
               on-click='toggle(@keypath + ".completed")'>
        {{.name}}
{{/}}
```

But I agree we should get both to work so you can do `checked='{{ .completed }}'` instead of `on-click='toggle(@keypath + ".completed")'`.
