### ISSUE TITLE
sourcemaps show wrong file if identically file names exist

### ISSUE THREAD

**Issue by martypdx** [ractivejs/ractive#1774]
`Section$setvalue` for example, has `Triple$setvalue`. It's occurring up at the `babel` level. So `ractive-legacy has the correct file path:

```js
//# sourceMappingURL=/Users/marty/ractive/.gobble-build/02-babel/1/virtualdom/items/Section/prototype/setValue.js.map
```

But the contents of that file (`setValue.js.map`) are for `Triple`:

```
{"version":3,"sources":["/Users/marty/ractive/src/virtualdom/items/Triple/prototype/setValue.js"]...
```

**Comment by evs-chris** [comment]
It looks like something upstream may have fixed this, as I'm getting the right file contents now and it looks like they're all there. Maybe @Rich-Harris fix for merge in gobble?

**Comment by Rich-Harris** [comment]
I was doing a couple of rather bone-headed things in gobble - giving sourcemap files names that were likely to conflict, and populating the `sourcesContent` field with the generated code rather than source code. They're both fixed now, and everything seems to have been restored to sanity, so I'll be optimistic and close this issue.
