### ISSUE TITLE
Exceptions thrown in computed data are silenced

### ISSUE THREAD

**Issue by Skyrpex** [ractivejs/ractive#1793]
That's it.

Any error or exception thrown inside computed data is silently discarded. This means that the computed data is never updated, and you can't really know why...

http://jsfiddle.net/vvp4ug11/2/

Is there any workaround for this? Thanks.

**Comment by martypdx** [comment]
add `debug: true` to your options, or `Ractive.defaults.debug = true;` And you will see the error on the console.

**Comment by Rich-Harris** [comment]
I think it would make sense for `debug` to be `true` by default, then it's something you have to explicitly turn off in production (if that's what you want). Anyone object?

**Comment by evs-chris** [comment]
I think that would probably be a good thing, but I'd definitely add a big bold statement to the release notes... Also, perhaps making the full exception available on the console would be nice? Maybe the `toString` of the failed function in the case of computations if the stack trace isn't particularly useful. Hmmmm... that actually sounds a little in-depth for a defaulted-to-on setting. Perhaps some sort of extra-detail debug flag would be useful? The defaulted on debug statements could refer to the extra flag to increase visibility?

I know I've had computations failing that I didn't notice until an embarrassing amount of time had elapsed.

**Comment by martypdx** [comment]
> I think it would make sense for debug to be true by default, then it's something you have to explicitly turn off in production (if that's what you want). Anyone object?

That makes me nervous. Could we make `ractive.min.js` was `false` and `ractive.js` `true`, or is that weird?

**Comment by martypdx** [comment]
> I know I've had computations failing that I didn't notice until an embarrassing amount of time had elapsed.

I think you could argue`debug: false` should be console error (which would be noticed by devs who have debug false) and throw the error if `debug: true`

**Comment by Skyrpex** [comment]
@martypdx that sounds pretty good to me

**Comment by evs-chris** [comment]
> Could we make ractive.min.js was false and ractive.js true,

@martypdx that's brilliant! I think using minification as flag is way better than an extra parameter.

How's this for minification detection?:

```js
Ractive.isMinified = (
  (function() {
    // do any minifiers leave single line comments?
  }).toString()
).indexOf('//') === -1;
```

That should work for code that gets minified outside of our build as well. Could we also use that in combination with the debug flag to turn down some chattiness automatically for 'production' mode?

**Comment by aharpervc** [comment]
What is the rationale for swallowing exceptions in production? Exceptions should never be swallowed. If that means turning this option on in production, so be it.

**Comment by evs-chris** [comment]
To be clear, by chattiness, I meant missing partial, deprecation, and other warnings that you would presumably not care about in production.

**Comment by Rich-Harris** [comment]
There are some cases where you might legitimately even want to ignore certain exceptions - if you have a computed value that depends on some asynchronously-loaded data, for example, you might feel it makes sense to let the computation fail silently prior to the data loading, rather than having a bunch of 'are we ready yet?' detection code.

Generally though, the older and grumpier I get, the less I want my tools to 'help' in this way.

I've been wondering if perhaps we should replace `Ractive.prototype.debug` (and the ability to control `debug` on a per-class/instance basis) with a global `Ractive.DEBUG` flag. This would simplify some code, let us do things like print a one-off message when the first instance is created ('You are running Ractive in debug mode. To squelch non-essential error messages, set `Ractive.DEBUG = false`'), and so on.

It might even make sense to skip the try-catch for some operations - in debug mode, you want to know that a computation or an observer failed and get some relevant debugging info, but in production you might get a speed boost by not try-catching.

I think it should be a choice for developers - *generally* unminified means 'development' and minified means 'production' but that's not necessarily the case, it seems a bit magical to enable/disable debugging based on whether or not we're minified. Though that `toString()` trick is fiendishly clever.

**Comment by evs-chris** [comment]
+1 to `Ractive.DEBUG`

Also, from my perspective, bonus points for init based on minification status. I like a little magic sometimes, when used sparingly.

**Comment by aharpervc** [comment]
> Generally though, the older and grumpier I get, the less I want my tools to 'help' in this way.

:+1:

**Comment by constantx** [comment]
:+1:

**Comment by Rich-Harris** [comment]
Will close this issue for now - as of #1813, Ractive will gleefully point out your errors until you silence it with `Ractive.DEBUG = false`. It won't let exceptions from computations stop execution (though we could change that behaviour if we decided that was what we wanted... see my rationale for *not* doing so [here](https://github.com/ractivejs/ractive/issues/1792#issuecomment-79761708)), but nor will you be able to ignore them.
