### ISSUE TITLE
ractive & custom tags

### ISSUE THREAD

**Issue by timoxley** [ractivejs/ractive#1800]
I like to use custom tags in my ractive templates so it's easy to see which elements belong to which ractive component.

Something like:

``` js
import Ractive from 'ractive'

document.registerElement('my-element')

var MyElement = Ractive.extend({
  isolated: true,
  template: `
  <my-element title="{{title}}">
    <h1>{{title}}</h1>
  </my-element>
  `
})

new Ractive({
  el: document.body,
  template: `<my-element title="{{title}}"></my-element>`,
  components: {
    'my-element': MyElement
  },
  data: {
     title: 'hello'
  }
})
```

To produce HTML like:

``` html
<body>
  <my-element title="hello">
    <h1>hello</h1>
  </my-element>
</body>
```

To prevent ractive from creating infinitely recursive components, you need to use `isolated: true` or null out the component reference within itself:

``` js
var MyElement = Ractive.extend({
  components: {
    "my-element": () => false
  },
  template: `
  <my-element title="{{title}}">
    <h1>{{title}}</h1>
  </my-element>
  `
})
```

This nulling out the component idea is a minor pain in debug mode since Ractive whinges and whines about there not being a component reference (gets verbose if you have a lot of elements):

```
Ractive.js: A function was specified for "my-element" component, but no component was returned
```

Perhaps a flag to disable this warning or to simply disable recursive components?

Another issue is that you need to remember to forward class and id type information onto to the custom tag.

It would be good if Ractive had a better story for dealing with custom elements. Obvious solution could be a flag which would just leave the Ractive component in-place as a custom element.

**Comment by martypdx** [comment]
> Perhaps a flag to disable this warning or to simply disable recursive components?

I have apps that use recursive components, so that wouldn't work across the board. What if you could just do:

```js
components: {
    "my-element": null
 },
```

> Another issue is that you need to remember to forward class and id type information onto to the custom tag.

Yeah this comes up from time to time, see #1535 for example. (You could create a decorator or `onrender` handler that did this). The issue is that IMO components as ractive instances shouldn't dictate the structure of the contents (for example even having a single top-level element). OTOH there's this widget/custom element view of the world that behaves as your suggesting. My hunch is that that needs to be its own class of component, either by option or maybe even a separate `Ractive.Element.extend` or something.

**Comment by Rich-Harris** [comment]
The 

```js
components: {
    "my-element": null
 },
```

idea seems like it could work. Alternatively, what if you were to omit the wrapper element from the template, and have it in the component definition - something like this?

```js
var MyElement = Ractive.extend({
  wrapperElement: 'my-element', // or registerAs: 'my-element', or whatever
  template: '<h1>{{title}}</h1>'
});
```

Maybe a little confusing though, as when you included it (`<my-element title='{{title}}'/>`) the resulting DOM element wouldn't have the `title` attribute, and I'm sure there are other ways in which it would confound expectations. And it's still not totally clear whether things like `style` attributes would be applied to the element itself or treated as data.

It does seem natural that we should be able to generate custom elements from Ractive components, and at some point we're going to have to think about what that looks like. It hasn't been a huge issue up till now because the web component specs have been too fluid (and support too sparse) for them to be anything but a curiosity for adventurous developers, but that will change.

Web components have some limitations that Ractive components don't share - two in particular will probably cause us headaches:

* everything exists in a single namespace
* because custom elements inherit everything we love about the DOM, you can't do perfectly reasonable things like `myElement.setAttribute('items', array)` - everything is coerced to a string

Probably a longer answer than was warranted, but I think it's important we approach this issue with a holistic mindset.
