### ISSUE TITLE
Cannot map to a computed property

### ISSUE THREAD

**Issue by ElliotChong** [ractivejs/ractive#1805]
Recently tried my project using `dev` and started receiving the new validation Error for `Cannot map to a computed property`.

I have some use-cases where this is a useful feature (my property is a getter and _setter_, so the data being passed in was previously being modified by the setter on the component's initialization before being stored under a different underscore prefixed key for later retrieval)... Curious what the rationale was behind this validation and whether there's a valid use-case here to support.

For now I can work around it with handlers in `oninit`, but I enjoyed the ease / cleanliness of having a computed setter ingesting data that needed some modification.

**Comment by martypdx** [comment]
We found that the data boundary between components is/was a source of code complexity and a major performance bottleneck. As it existed in 0.6 data was essentially copied bidirectional between components. 

@Rich-Harris  started the process of change in 0.7 by replacing this with mappings that introduced the idea of a single owner for any piece of data - by delegating calls within the child component viewmodel to the parent. 

I actually had a computed property reverse mappings working, but we decided to take it out because once you break out of the strong unidirectional flow from view parent to view child, the complexity level skyrocketed. While computed to upstream mapping can be convenient, perhaps the easiest way to explain why it's awkward to implement is to compare it to this:

```js
var foo = function(a, b){
    a = b + 3;
}
a = 1, b = 2;
foo(a);
a; // like trying to make a === 5
// and all these kinds of questions start popping up:
a = 2; // can you assign a?
delete foo; // does this
a = 3; // make a settable?
a; // or equal to 1 again?
```
And having complex code like that ran against another goal we have of increasing PR's and participation by, over time as we move forward, making the code easier to understand and work with.

The `parent` and `root` properties introduced in 0.7 should make it easier to create observers that can fulfill the same task `this.parent.set('foo', value);`

**Comment by ElliotChong** [comment]
Thanks for the thoughtful response @martypdx!

I'm not sure I fully understand your example in the context of a computed property... I get that you'd like to ensure that there is only one owner of a piece of a data and that a child's mapping is just a reference back to that one source of ownership; however, it seems like the issue in the above example is more of a holistic computed property concern than being specific to passing a mapping into a computed setter during initialization? AKA: Is throwing an error in this instance actually solving that issue?

For example:
```
<Example foo="{{foo}}" />

Example = Ractive.extend
    computed:
        foo:
            get: -> return this.get("_foo")
            set: (value) -> this.set("_foo", value)
        bar:
            get: -> return this.get("_foo")
            set: (value) -> this.set("_foo", "A different value") // You'd possibly use value to control some other logic
        baz:
            get: -> return this.get("boom")
```

A computed property is essentially a proxy- sometimes you'll want to store that mapping reference for later retrieval (which would still uphold the one source of truth principal, `foo` example above), other times you'll use it to kick off other logical flows in a component and not store that mapping (`bar` in the example), or you might just be proxying another mapping / locally stored data (`baz`). So with that said, I'm confused how passing a mapping into this proxy at initialization time changes the complexity over just using these explicitly defined proxies post-initialization?

I created a quick branch to see if anything breaks by allowing a mapping to be passed into a computed setter (it will still error if a setter isn't present) @ https://github.com/ElliotChong/ractive/commits/computedSetter
It seems to be working alright, but once again- I might be missing some key piece of understanding here on the edge cases that now arise by allowing this. I assume that if you're passing / storing the original mapping, the flow should work just fine as unidirectional?

Also, kudos to the team on the refactor! It's been a long time since I've dug into the internals of Ractive and I can tell the structure has been cleaned up quite a bit. :+1: :+1:

**Comment by ElliotChong** [comment]
After thinking about this a bit more- is the issue really that you shouldn't be able to map *from* a computed value since it could then get rather complex, versus passing a mapping *to* a computed property?

**Comment by Rich-Harris** [comment]
I'm trying to get my head back to where it was when we were discussing this before - it requires some gymnastics! So if this is a bit confused/confusing, bear with me...

The fundamental problem is that a component has to own its own computed properties, which means that if you have a mapping between a parent data property and a child computed property, the child will try to 'own' the parent data. The fact that this was (sort of) possible previously was, I've come to believe, a major flaw in the original design:

```html
<!-- suppose we have both of these in the same template -->
<Example foo="{{someValueOnData}}" />
<Example bar="{{someValueOnData}}" />

<p>The value of someValueOnData is {{someValueOnData}}</p> <!-- which??? foo or bar? -->
```

So when you change `someValueOnData`, the `foo` setter and the `bar` setter will both be invoked, followed by the getters (because the computed properties have dependents that must be updated, which means querying the computed properties). It so happens that the value of `someValueOnData` depends on both the `foo` and `bar` getters, so we have a conflict. (The fact that this conflict may not always present itself doesn't change the fact that the system has a flaw.) If we followed this train to its final destination, then the setters would be invoked again if either `foo` or `bar` had a different value to what the other computed property's getter thought it should be, and we end up with a) an infinite loop or b) if we're smart enough to prevent that, a mismatch that violates single-source-of-truth.

With non-computed properties we can solve this problem very easily - we simply ensure that a common parent of the two `<Example/>` components 'owns' `someValueOnData` (which is already the case in this example, but in a more complex situation might entail 'transferring ownership' to the parent).

We could try and identify situations where those conflicts don't arise, and be lenient, but we tried that and it turns out to involve some real hoop-jumping!

So I guess the question is what the use case is, and whether it's something that's common enough that we should develop a pattern for it?

**Comment by ElliotChong** [comment]
Thanks for the explanation @Rich-Harris!

So I understand the point you're making that once we're in computed land it's extremely hard to know if the developer is doing something they shouldn't (i.e.: Creating infinite loops by modifying the parent's scope from within the Component's computed) but I'm not sure how preventing a shortcut assignment to the computed really prevents the root problem... which is essentially scope. Theoretically once a reference is passed in to a computed property you should be good to go since the child typically isn't able to modify the value tied to a pointer on the parent.

In a perfect world, the answer to your question:
```
<!-- suppose we have both of these in the same template -->
<Example foo="{{someValueOnData}}" />
<Example bar="{{someValueOnData}}" />

<p>The value of someValueOnData is {{someValueOnData}}</p> <!-- which??? foo or bar? - Neither, it's still `someValueOnData` since children can't change a parent's reference -->
```

But, due to Ractive's ability for the setter definition of `Example.foo` to do something like:
```
Example:
  computed:
    foo:
      set: (value) ->
        this.set("someValueOnData", "This is a terrible practice");
```

You'll now end up in a recursive loop and bad things happen since scope was breached.

So, the real question I have is that if this type of situation can still be created even without the shortcut of passing a value to assign on instantiation- should this restriction actually be in place (I would argue that it's the developer's job to ensure they're properly scoping their components, not unexpectedly leaking to the parent, and watching out for recursive assignments of properties) and is the real issue at heart the fact that children components can modify their parents?

As a general rule of thumb and to prevent situations like the above I pretty much always prefix all references to the data model with a `.`- it would be quite the breaking change, but arguably a much better design philosophy overall would be to default to not leaking scope when accessing a property through `this.get / this.set` and opt-in to global scope via a `.` prefix.

So, this topic branched a bit there- but I'd sum it up to: 1.) Not allowing a reference to be passed to a computed on instantiation handicaps the ease-of-use of components and forces developers to use workarounds and placeholder values while not actually solving the root issue. 2.) Should component-level scope be the default and global scope opt-in?

**Comment by martypdx** [comment]
Maybe the more fundamental issue is having two things defined with the same name. Something we allow even without component mappings, presumably because it's convenient, but perhaps we shouldn't:

```js
data: {
    foo: 'bar'
},
computed: {
   foo: {
      get: () => { ... },
      set: val => { ... }  // foo gets passed in on initialization!
   }
}
```

Assigning a value to a mapped property isn't an issue, it's what components do. I can see the view the computed property is "wrapping" the map property - but to do that under the same name is what makes it harder to deal with.

**Comment by ElliotChong** [comment]
@martypdx Ah hah! You know, I never even considered that you _could_ do a data property and a computed property with the same name since that would cause all sorts of confusion in your own implementation when you do `this.get` / `this.set`.

I'm assuming that if you have `foo` defined in `data` and a computed property exists with the same name you must be trying to bootstrap the computed with a default value (similar to passing `foo` in on instantiation)? Otherwise, you'd never be able to access the value you assigned to `data.foo` since `this.get / set` gives computed precedence.

**Comment by Skyrpex** [comment]
Isn't there a way to allow read-only data for components? For example, I was just developing a component for input validation, which is used like this:

```handlebars
{{#message}}
<label>Your message</label>
<xinput value={{value}} rules="required|max:160" valid={{valid}} />
<p>Is valid: {{valid? 'yes' : 'no'}}</p>
{{/message}}
```

The xinput component use "rules" to compute "valid" property, which is a boolean. This property is meant to be read-only.

I'm not sure how could I do this now, without manually passing the current keypath to the component...

**Comment by Skyrpex** [comment]
At the moment, my current implementation involves using the xinput component like this:

```mustache
{{#message}}
<label>Your message</label>
<xinput value={{value}} rules="required|max:160" valid={{@keypath + '.valid'}} />
<p>Is valid: {{valid? 'yes' : 'no'}}</p>
{{/message}}
```

Internally, the component observes value, rules and valid properties to set the boolean property to the parent. It works but doesn't feel good...

**Comment by Skyrpex** [comment]
Sorry to write here again. I've been thinking a bit about this. Do you really think that it is a flaw design to let components own the parent's data?

IMO, it's a pretty useful feature. The example @Rich-Harris wrote could just throw a runtime error or something similar.

```handlebars
<!-- suppose we have both of these in the same template -->
<Example foo="{{someValueOnData}}" />
<Example bar="{{someValueOnData}}" />

<p>The value of someValueOnData is {{someValueOnData}}</p> <!-- which??? foo or bar? -->

```

**Comment by evs-chris** [comment]
I think this is nicely handled in 0.8.
