### ISSUE TITLE
Support for alternative templating languages

### ISSUE THREAD

**Issue by transtone** [ractivejs/ractive#1827]
Can I use another template replace the default one?
I like the jinja2 template:  http://mozilla.github.io/nunjucks/  and https://github.com/sstur/jinja-js

**Comment by Madgvox** [comment]
Technically yes, if you can compile the template into a [ractive template](https://github.com/ractivejs/template-spec), you can replace the native template with whatever you want. In fact, I've been working on a method to compile [jade](http://jade-lang.com/) into ractive directly myself. Ractive does not natively support switching out the template spec however due to the template format it uses compared to other templating engines.

**Comment by evs-chris** [comment]
I'm going to say this definitely won't happen in core, but there's no reason an external library couldn't target our compiled template structure. There's more than a little nuance involved in doing so, though.
