### ISSUE TITLE
Aliasing + 2-way-binding = 1-way-binding

### ISSUE THREAD

**Issue by anton-ryzhov** [ractivejs/ractive#1834]
Here is an example http://jsfiddle.net/3g844y6b/

Try to change first, second and first input again.

```html
<script id="main" type="text/ractive">

<p>foo:<br><input type="text" value="{{ foo }}" /></p>
<p>value: {{ foo }}</p>

{{# { alias: foo } }}
    <p>alias:<br><input type="text" value="{{ alias }}" /></p>
    <p>value: {{ alias }}</p>
{{/ {} }}  
        
</script>
```
```js
new Ractive({
    el: 'body',
    template: '#main',
});
```

**Comment by martypdx** [comment]
See #1353. Aliases (which are essentially expressions) are not bi-directional as they are computationally derived, not linked.  (And while the result of an expression is not directly bindable, the properties are bindable, which is why it works and is consistent between the two uses of `alias` in your example.)

On the wishlist, but not currently supported.

**Comment by anton-ryzhov** [comment]
Ok, I got it.
Sorry for inconvenience

**Comment by martypdx** [comment]
This case of aliasing has come up a number of times. I wonder if we should syntax like `{{ foo as alias }}`. That way we can eliminate the opacity of an expression which keeps us from fully linking these props.

**Comment by evs-chris** [comment]
@martypdx I was wondering if your keypath work could handle this. I haven't been able to go through it completely, but to the naive observer, it looks like it should be possible to detect and install the right linkages when a context object pops up with direct references.

@anton-ryzhov would `link`ing (#1722) help out at all?

**Comment by martypdx** [comment]
@evs-chris Creating "links" will be trivial. We can add API for something like `ractive.link(keypath1, keypath2)`.  

But I still think there's an issue with the opacity in expressions that make it hard to "guess" at the correlation between input and output. But maybe there's a way to compare output to input and it gets re-evaluated each computation? 

That's why I thought a directive would be cleaner, and also we wanted to add `{{#each foos as foo}}`, so if we did it for with blocks too: `{{#with foo as alias}}` then it probably hits the 80/20 rule pretty good.

**Comment by anton-ryzhov** [comment]
JS-api won't help in my case, I need to access some keypasses created inside template. I'd try to alias it to access it simpler.

Like that:
```html
{{# fields }}
  {{# { value: object.foo.bar.dataStorage[this].value } }}
    <input value="{{ value }}" />
  {{/ {} }}
{{/ fields }}
```
There is no place to do JS-calls.

BTW components are already working with this:
```html
<Component value="{{ object.foo.bar.dataStorage[this].value }}" />
```
does 2-binding.

I don't know your implementation internals, but it would be great if parser knew itself whether it expression or just alias (expression with one variable, no transformations etc).

**Comment by evs-chris** [comment]
@martypdx's proposed syntax is note implemented in edge.
