### ISSUE TITLE
References cannot easily contain hyphens

### ISSUE THREAD

**Issue by ctolsen** [ractivejs/ractive#1846]
Somewhat related to #1165:

I loaded some JSON data into some Backbone models, attempting to expose it in Ractive with `{{ variable-name }}`. The expression computes to `NaN`.

After tinkering around I figured that I could do `{{ this['variable-name'] }}`, which is far from elegant. Is there any way around this other than changing the attribute name at parse time? I can't be the only one with data sources with hyphenated attributes :smile:

**Comment by evs-chris** [comment]
Unfortunately there's not a good way to distinguish between `foo-bar` the hyphenated attribute and `foo-bar` the subtraction expression. And you're not the only one... I've got a bunch of data with literal `.`s in it...

**Comment by martypdx** [comment]
Mustache references need to be valid javascript. 

Partials are in a quasi middle ground because they a bit like custom elements - so it makes sense to be able to use them as `{{ > header-bar }}`.  

Note however that this only applies to literal named Partials, not dynamic partial references - even in that case references must be valid javascript.

**Comment by martypdx** [comment]
@evs-chris we should at least get {{ this["my.field"] }} to work in `0.8` - http://jsfiddle.net/jkvrrwfz/ :(

**Comment by ctolsen** [comment]
Thanks for quick replies! Guess I can live with limitations :smile:
