### ISSUE TITLE
remove sourcemaps from ractive.min.js?

### ISSUE THREAD

**Issue by martypdx** [ractivejs/ractive#1855]
`ractive.min.js` includes `//# sourceMappingURL=ractive.min.js.map`. This adds about a second to load time. When people are using `http://cdn.ractivejs.org/latest/ractive*`, I think the min should be fast as possible.

**Comment by evs-chris** [comment]
I was under the impression that source maps are only loaded when the console is open.

**Comment by martypdx** [comment]
> I was under the impression that source maps are only loaded when the console is open.

And if you're developing something using ractive, good chance console will be open. :)

**Comment by Madgvox** [comment]
> And if you're developing something using ractive, good chance console will be open. :)

But if you are developing something using ractive it might be helpful to be able to trace through the source.

**Comment by evs-chris** [comment]
Fair enough :)

I figured someone doing active poking about in production would probably be more interested in tracking issues than load times. I guess it kinda makes it hard to do performance testing though. You can always disable sourcemaps in dev tools too (just found it a few days ago - one of those obvious little options that hides in plain sight).

**Comment by martypdx** [comment]
I bet a lot of people just want it to work and aren't expecting any hassles from ractive. Maybe it's just something on this current client project (there are other load time issues I'm tracking down) and not that big a deal. 

I could see `edge` being that way, but minified latest, I dunno...

**Comment by Madgvox** [comment]
Actually that makes sense. If someone is using minified latest it is most likely that they want it to Just Work™. If they want to peruse the code they're probably not going to grab the minified version.

**Comment by codler** [comment]
Here are some discussion about removing source map also http://bugs.jquery.com/ticket/14415

**Comment by Rich-Harris** [comment]
I might be being dense but I'm not sure I understand the rationale for removing sourcemaps - if the console isn't open, you're not affected, and if it is open surely you want the sourcemaps for debugging? A stack trace that points to minified code is never useful. People can always opt out of sourcemaps, but they can't opt in if we remove them.

Also, some websites use things like [sentry](https://www.getsentry.com/welcome/) to monitor errors in the wild, and those tools are vastly more useful if sourcemaps are available.

Some interesting discussion on that jQuery thread. I agree the 404s are a nuisance, if people download `ractive.min.js` to their project and don't bring the `.map` along with it. (We don't have the problem of needing to serve the unminified code alongside, because the sourcemap contains it.)

@martypdx does disabling sourcemaps help with the load time issue? I've never tried to gauge how much of an impact sourcemaps have.
