### ISSUE TITLE
List problems after updating

### ISSUE THREAD

**Issue by blackgate** [ractivejs/ractive#1861]
http://jsfiddle.net/v5nmzLrv/2/

If you open this fiddle and the console, you start seeing lots of  undefined values that get passed to the getRange function.

For some reason it is using the keypaths of the previous list.

**Comment by Rich-Harris** [comment]
In an older version of Ractive, 'expressions' (in templates) and 'computations' (explicitly defined) were different things that happened to share a lot of functionality. The only real difference was that expressions kept track of whether they were currently rendered, which meant they could avoid being called when (for example) the section they were inside got removed.

It turns out that this requires a lot of unwieldy book-keeping, and was a source of bugs. So now things happen slightly differently: rather than having two separate-but-similar things, they're both computations - when constructing the virtual DOM, if Ractive encounters an expression (e.g. `{{a+b}}`), it will 'request' that its *viewmodel* compute that value and notify on any updates.

The viewmodel doesn't know anything about the virtual DOM, it just knows that something is interested in the value of `a+b`. Because computations are the first things to be updated when data changes (because otherwise you might rerender, then recompute, then discover that the DOM is already out of sync), this means that an expression inside a list item will be updated even as that list item is being removed.

This sounds wasteful, but in practice it's a much simpler and more robust approach. As long as any functions called by the expression don't have any side-effects (which they shouldn't! except perhaps the occasional `console.log`) then it shouldn't be possible for any bugs to arise from doing things this way.

**Comment by blackgate** [comment]
Thanks for the explanation.
In my opinion this should be explained in the docs as well, because right now i think it's not obvious.

**Comment by Rich-Harris** [comment]
That's fair. I've opened https://github.com/ractivejs/docs.ractivejs.org/issues/203, will close this in favour of that issue
