### ISSUE TITLE
Need an extra line after the sourceMappingURL in ractive.js 0.7.1 to make it compatible with r.js optimizer

### ISSUE THREAD

**Issue by tangst** [ractivejs/ractive#1874]
At the end of ractive.js 0.7.1, this line exists:
    //# sourceMappingURL=ractive.js.map

I have a personal project that runs r.js and concatenates JS libraries together into a single file.  r.js adds a semicolon at the end of whatever file is it concatenating, so it ends up like this:

    //# sourceMappingURL=ractive.js.map;

When I view the site in Chrome, the console always says:
    
    http://SOMESITE.NET/j/ractive.js.map; not found (404)

When I went into the ractive.js file and hit the return button to create a new line, and then ran the r.js optimizer, the error went away in Chrome.

The concatenated file now looks like this:
    
    //# sourceMappingURL=ractive.js.map
    ;
    /* NEXT concatenated file's code */

So, is it possible to add a new line to the end of ractive.js?

**Comment by Rich-Harris** [comment]
Thanks - I've reported the bug in r.js (https://github.com/jrburke/r.js/issues/799) and will add a workaround to the tool that combines sourcemaps (https://github.com/Rich-Harris/sorcery/issues/4) - it'll be fixed in the next release

**Comment by tangst** [comment]
Rich, thanks for providing a workaround in the next version and alerting the r.js developer.  You guys are staying on top of things!

I'll stay on 0.6.1 until the next release.

**Comment by Rich-Harris** [comment]
This has been fixed upstream, so current edge (and future stable) builds will have the trailing newline. If you get a chance to test it out with http://cdn.ractivejs.org/edge/ractive.js to make sure that it works with r.js, I'd be grateful!

**Comment by tangst** [comment]
Rich, I downloaded the revised file, and r.js puts the semicolon on the new line you created.  The browser no longer shows the "sourcemapping not found" error.   I think you're good to keep using this, until rburke fixes r.js.

I'm currently using Bower to manage my front-end dependencies, so I'll have to wait until you make a new release before actually using this change.

**Comment by Rich-Harris** [comment]
Thanks a lot for confirming that it works.

> I'm currently using Bower to manage my front-end dependencies 

I'm so sorry :) Just so you know, it *is* possible to use the edge version with bower, if that's what you'd prefer:

```bash
# to get the latest successful build:
bower install ractive#edge

# to lock to a specific build (from https://github.com/ractivejs/ractive/commits/build)
bower install ractive#4243006e1a96c76ef5ed455f527cb2f7cdf47d73
```

**Comment by tangst** [comment]
Although this is a tangent to the original issue, is there something wrong with Bower?  I just find it a little  easier and more lightweight to use bower than npm (although I do use npm for the Grunt dependencies - I'm not on Gulp either).  

I just didn't know there was a way to get the edge version in Bower, so thank you for letting me know how to target edge and specific builds.  (Bower documentation didn't mention this, so I didn't know this was possible.)

**Comment by Rich-Harris** [comment]
It's a personal opinion, and I probably shouldn't use this as a soapbox, but after using it for a long time I realised it simply doesn't do the things that a package manager needs to do. With an npm package, you can guarantee that a) if you download package `x` and require it, the resolver will be able to find `x` because if it's not in the default location there'll be a `main` field in the `package.json` that points to where it is, and b) you're almost certainly getting a CommonJS module (deviations from that are rare). 

Bower gives you no such guarantees - a lot of bower packages have incomplete/incorrect `bower.json` files, and the library could be in any format (CJS, AMD, globals...), and because there's no bower equivalent of node's resolver, you have to wire up all the locations yourself (`<script src='bower_components/...'>` or a convoluted require.js config, or whatever) which totally defeats the object of using a package manager in the first place!

I have other issues with it, but that's the main one. Eventually I switched to npm+browserify, and I've never looked back.

**Comment by tangst** [comment]
Rich, thanks for sharing your opinion on this.  You're way more experienced than me, so it's good to hear what some of the problems.  Since my personal project (and even some corporate work I've done!) isn't overly complicated, I've never really saw the shortfalls.  I just used Bower, because it interfaced with Github repos, as sometimes I couldn't find an equivalent npm module (but I'm sure that's changing).

That's the end of this tangent.  Back to Ractive.js!
