### ISSUE TITLE
Indeterminate checkbox?

### ISSUE THREAD

**Issue by Crisfole** [ractivejs/ractive#1896]
Is there a built-in way to create a checkbox that can be indeterminate? I'm currently assuming that I'd have to make a component for this.

**Comment by Crisfole** [comment]
As a side note, does Ractive expose a 'keypathIsTruthy' function...something that works exactly the same as the templating engine? Right now the component file for doing this is pretty darn simple, but I want to make sure the behavior is as close to standard as possible.

**Comment by martypdx** [comment]
I think it depends on context. A block `{{#if foo}}` has rules like `[]` is false. [Here's](https://github.com/ractivejs/ractive/blob/dev/src/virtualdom/items/Element/Attribute/prototype/update/updateCheckboxName.js) the checkbox logic.

**Comment by Crisfole** [comment]
For now I've just got this component:
```html
<input type="checkbox" on-change="update()" />
<script>
    var el;
    component.exports = {
        onrender: function() {
            el = this.find('input');

            this.observe('value', function (newVal) {
                if (newVal == null) {
                    el.indeterminate = true;
                }
                else {
                    el.checked = newVal;
                }
            });
        },
        update: function () {
            this.set('value', el.checked);
        }
    };
</script>
```
It seems to be working.

**Comment by Rich-Harris** [comment]
One way would be to not use two-way binding, since that's what's initialising the value: http://jsfiddle.net/rich_harris/pnnwfqn2/

A couple of things to be aware of with your code example above - by declaring `el` outside the component methods, you'd run into problems if you had any additional instances because they'd all share the reference. I often have things like `this.input = this.find('input')` inside my `onrender` function, so that I can have per-instance references.

Also, there's already a `Ractive.prototype.update` method - methods are overridable by design, just be aware that it might confuse anyone else who uses the component!

Apologies if both those are obvious and that was just a simplified example :)

**Comment by Crisfole** [comment]
No the shared `el` was just the result of writing it too quickly. I only needed one, so I wouldn't have caught it either. Thanks.

The `update` error was just a "still new to Ractive" bug.  Thanks for the instruction and the demo of turning two-way off. Never even occurred to me.
