### ISSUE TITLE
performance troubleshooting

### ISSUE THREAD

**Issue by constantx** [ractivejs/ractive#1905]
Been having this for a while, but not sure where to troubleshoot.

I have about ~250 list item being set and the set is taking a long time to be done. It looks to be proportionaly with the complexity of the template that's being used.

My template (simpler version) is something like this:

```mustache
<h4 class="section-heading">
  <ALink href="{{activeResource}}/{{_id}}">
    {{#alias}}{{ alias }}{{else}}{{_id}}{{/}}
  </ALink>
</h4>

{{> PCurrentState }}

created: <strong>{{ _timestamp(created) }}</strong><br>

{{! customer info }}
<AMarker type="customer-with-booking" />
<ALink href="customers/{{ account }}" title="{{ account }}">
  Customer:
  <strong>{{#_account}}{{ .first_name }} {{ .last_name }}{{/}}
    {{^_account}}{{account}}{{/}}</strong>
</ALink>

<br>

{{! drop-off related info }}
{{#dest_dropoff}}
<div class="section-dropoff">
  <AMarker type="booking-agent-dropoff-confirmed" />
  Drop-off: <strong>{{ .address }}, {{ .city }}</strong>
</div>
{{/dest_dropoff}}

{{#dest_pickup}}
<div class="section-pickup">
  {{! pickup related info }}
  <AMarker type="booking-agent-is-enroute-to-garage" />
  Pick-up: <strong>{{ .address }}, {{ .city }}</strong>
  <br>
</div>
{{/dest_pickup}}
```

The `.set` and render (after the set) takes about 10s. (50s with more complex template for the same amount of item)
![developer_tools_-_http___localhost_5000_staging_bookings-archived_and_new_issue_ _ractivejs_ractive](https://cloud.githubusercontent.com/assets/113969/7034688/fadd9cae-dd36-11e4-9faa-06d6e51dc4ac.png)

Tip to speed this up?

**Comment by Rich-Harris** [comment]
Crikey, that sounds bad. Would love to get my hands on a working example, it sounds like we could get some useful data out of it - if it's too complex to produce a stand-in that you can share online but you'd be okay sharing it privately then let me know! Email on my profile.

Without knowing more about what's in e.g. `<AMarker>` it's tricky. Do they contain components of their own?

One thing you could try is `ractive.merge()` - similar to `ractive.set()` except that it attempts to use existing rendered list items rather than changing the data of an already-rendered component. If the list `b` that replaces list `a` is composed of different objects (e.g. it's from an API response) then you can supply a comparator function. [Details on the docs](http://docs.ractivejs.org/latest/ractive-merge).

**Comment by martypdx** [comment]
Another possible issue would be unresolved references, that is `{{ references }}` that don't immediately refer to any actual data.

**Comment by constantx** [comment]
@Rich-Harris @martypdx don’t mind schedule a hangout and do a screenshare with you guys :)

**Comment by constantx** [comment]
So I digged in a bit more into the Chrome Timeline in an attempt to see what's causing the long set.

![developer_tools_-_http___localhost_5000_production_bookings](https://cloud.githubusercontent.com/assets/113969/7738820/99eb1748-ff0d-11e4-9256-934953311538.png)


![developer_tools_-_http___localhost_5000_production_bookings](https://cloud.githubusercontent.com/assets/113969/7738861/0e7a813e-ff0e-11e4-88ba-316244cb8d55.png)

This is becoming more and more of a problem as the data list is growing larger daily :(

**Comment by fskreuz** [comment]
Been through a similar situation yesterday. In my case, the causes were:

- **Deeply nested components.** We have various components that range from the smallest custom autocomplete input, to multi-face apps. An initial data load causes our app to freeze 3 seconds because of initialization of a lot of components. 

- **When your component uses third-party code.** One heavy case was jPlayer for our custom mp3 player. Having 4 during initial render is just terrible.

- **Setting data from the very top component.** We did it ala Flux, that is set the data from the very top component, and let the framework trickle down the changes. When your app has a lot of variable blocs (if-else, sections, expressions), it will cause initializations/teardowns on a massive scale.

- **When the data is totally different.** Ractive is fast when you just mutate the data within the component tree. But when you provide it a huge chunk of totally unidentical data (like a clone of your data), it will cause stuff to churn. One of them are observers of objects (because no 2 objects are the same, unless you just mutated it).

**Comment by constantx** [comment]
> set the data from the very top component, and let the framework trickle down the changes

This seems to be the cause. After I set some of the keypath explicitly to a specific scope, got a 700% boost!

> When the data is totally different

Gonna have to investigate this next.

**Comment by fskreuz** [comment]
You could also design the app to be "wide" instead of "deep". I wrote an article on that once, but it was more for event handling rather than rendering but the idea of "wide" is there: http://scratchpaper.tk/articles/component%20development/

**Comment by constantx** [comment]
thanks @fskreuz, will check it out :)

**Comment by blackgate** [comment]
I have an example that could be related to this issue:
http://jsfiddle.net/9q9uevdc/

You could open the console to see the time it takes. On my machine it takes 1700ms to render 1000 items on the tree.

**Comment by cjrh** [comment]
@blackgate I played around with your example, just to see how the timing changes for updates (i.e., setting new node data into the existing ractive after the first initialisation).  After the first time, the cost drops by a factor 10:

![image](https://cloud.githubusercontent.com/assets/480395/8842511/61d15418-313e-11e5-93bb-b88fc0c422ff.png)

**Comment by Madgvox** [comment]
With the tips given here and the speed boosts provided by #1740 and the 0.8 refactor, Ractive should be a lot more robust with large data sets.
