### ISSUE TITLE
Wrapping the template in <template> and third-party template support

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractive#1916]
### Rationale

I was wondering  if it would be possible to have the template also be wrapped in something like `<template>`. Scripts and styles already have their tags on the top level, why not use the same semantics for the template.

```
<template>
  // Template goes in here
</template>

<script>
  // Scripts go here
</script>

<style>
  // Styles go here
</style>
```

- For Ractive, `<template>` will merely be a wrapper for the template definition and nothing more. It doesn't impart a host/wrapper element (unlike Polymer/Ember/Angular).

- It could be of help for the parser so that it won't have to search through the entire code for what comprises the template. It could just look for `<template>` tags and grab its contents.

- It might even fix whitespace problems since currently, the parser seems to filter `<script>` and `<style>` and consider everything else template.

- Then similar to `<script>` and `<style>`, if the loader finds more than one, they get concatenated then parsed.

### But wait! There's more!

I was going through [ractiveify](https://github.com/norcalli/ractiveify) and can't help but notice how it allows for third-party parsers for scripts and styles. The only thing needed was a `type` attribute

```
<style type="insert type here">
// blank: vanilla CSS
// text/scss: SCSS

<script type="insert type here">
// blank: vanilla JS
// "text/livescript": livescript,
// "text/ls": livescript,
// "text/coffeescript": coffeescript,
// "text/coffee": coffeescript,
// "text/coffee-script": coffeescript
```

Now, if we have the `<template>` in our definition, we could do something like:

```
<template type="insert type here">
  // Template here
</template>

// blank/no template tag (backwards compat): Ractive parser
// "text/mustache": Mustache to Ractive AST parser
// "text/handlebars": Handlebars to Ractive AST parser
// "text/underscore": Underscore to Ractive AST parser
```

It opens up the possibility for loaders to finally use third-party templating languages on Ractive. *As long as the third-party loader spits out an AST that Ractive understands*, then we're in business. No additional work Ractive, all heavy lifting is done by the third-party code.

The only issue I see here is that either the third-party template parser and/or Ractive can only use a subset of the other. Like if the templating language has helpers that has no direct map to Ractive (like if we add in custom helpers in Handlebars), or if the template language has no construct for Ractive helpers (like if the templating language doesn't support partials).

**Comment by Rich-Harris** [comment]
I like the idea of preprocessing stuff. Not that I've used it so far personally (I find that if my style blocks get big enough that I start to need SCSS features, it's usually a sign that I'm trying to cram too much into a component, and I never got into livescript or coffeescript), but I see the value.

From the component loader's point of view, it doesn't really save any work to wrap the markup in a `<template>` (there's just a [few lines of code](https://github.com/ractivejs/rcu/blob/master/src/parse.js#L31-L63) to extract top-level script and style tags), so preprocessing is the main issue here.

Right now, though, it's really only a theoretical benefit. We've discussed using non-standard parsers on a few occasions, and the conclusion is always 'it's possible, in theory' - to my knowledge no-one has created a parser that creates a Ractive-compatible AST from something other than our variant of Mustache/Handlebars.

It would definitely be interesting to explore. Underscore templates would be a real challenge. There's no way to express something like [this](http://jsfiddle.net/rich_harris/4uafm3xd/) in a language Ractive understands.

```html
<!-- collection.repeat is basically just array.forEach,
     but Ractive can't know that -->
<% collection.repeat( function ( val, i ) { %>
  <li><%= i + 1 %>: <%= val %></li>
<% }); %>
```

When you're just concatenating strings (using `with` and `Function` to generate the template function - [source](http://underscorejs.org/docs/underscore.html#section-168)), that's fairly straightforward. It would be nightmarishly difficult to turn that into a tree structure (which is what Ractive needs in order to do DOM updates efficiently) - even knowing that the `<% }); %>` tag closed the section would be profoundly awkward, never mind representing its contents in such a way that you could update things non-destructively without implementing a convoluted diffing algorithm.

So *at the moment* I don't think there's much benefit to wrapping markup in a `<template>` tag, but I reserve the right to change my opinion if people start using alternative parsers :)

**Comment by martypdx** [comment]
From some brief testing, it looks like the `<template>` tag modifies the content like escaping HTML and lower-casing unknown attributes on components. Which makes it difficult to support generally in ractive.

It could be supported by preprocessing as @Rich-Harris pointed out, specific to rcu and the component file. But it could be localized with the build tool of your choice. And IMO it's easier to justify adding it to rcu if people are actually using it with benefit in the wild.

**Comment by dagnelies** [comment]
Just to state the obvious in case @fskreuz missed it.

*script* tags are used because when the page is loaded, it's content is not parsed but considered as raw text which can then be properly parsed by ractive.

If you place the template code in some other elements, it'll be altered in subbte ways when the page loads which may break your template.

As an additional note, I'd like to point that *template* tags are not yet implemented by IE:
http://caniuse.com/#feat=template

**Comment by fskreuz** [comment]
I was thinking more of changing the way the component spec is defining the component. The inspiration of this was Polymer, which defines blocks of stuff inside explicit tags. I have always wondered why templates inside a component file aren't wrapped in some element.

As for the comments:

> script tags are used because when the page is loaded, it's content is not parsed but considered as raw text which can then be properly parsed by ractive.

All these suggestions will only be for component files. I never mentioned using it for templates in HTML. Nothing will change for templates on HTML. Templates in HTML will remain using `<script type="text/not-javascript">`.

And yes, i know why `<script>`  is used for this purpose.

> `<template>` tag modifies the content like escaping HTML and lower-casing unknown attributes on components. Which makes it difficult to support generally in ractive.

> As an additional note, I'd like to point that template tags are not yet implemented by IE:

`<template>` would merely be for indicating that "inside this block is the template for this thing". Loaders will just pluck out the contents of `<template>` and pop it in as `template` for the component definition. `<template>` *will never meet the browser* and we'll never see problems like escaped HTML or lack of support.

> Well, I'd find it confusing if I've to put things in script for in-page templates and in template if used through the component loader. ...it'd also perhaps mislead people in that they think they can use template blocks in the main page.

Documentation can cover that.

**Comment by martypdx** [comment]
@fskreuz That could be done in `rcu` [right before here](https://github.com/ractivejs/rcu/blob/master/src/parse.js#L82) as an optional thing where it checked `parsed` and if top-level single element was `<template>` it could up-level the contents of that element as the main template.

Downside would be that if anyone actually wanted to top-level `<template>` in their output it wouldn't work.

**Comment by dagnelies** [comment]
@fskreuz you can just ignore my comment then. ;) I just wanted to make sure this applied only to the loader.

As for using template tag, I'm personally neither for nor against.

The small upside is a clear splitting template/scripts/style, but that's about it as far as i can tell. On the downside you'll have to code it, to document it and all existing single page components in the wild will break. IMHO the benefit / cost ratio is rather low ...as I said, I'm not against either, but I'd give it a rather low priority.
