### ISSUE TITLE
Partial tutorial is broken.

### ISSUE THREAD

**Issue by donnyv** [ractivejs/ractive#1920]
It looks like the ability to edit is broken.
I click on the item and nothing happens.
http://learn.ractivejs.org/partials/1

**Comment by Madgvox** [comment]
I've crossposted this to the [learn repo](https://github.com/ractivejs/learn.ractivejs.org/issues/22), so I'm going to close the issue here.

---

The tutorials have been on the list for some time to be worked on. They're pretty woefully out of date and don't cover any of ractive's more recent features. Thanks for reminding us about it!
