### ISSUE TITLE
ractive.observe '*' in 0.7 only fires once… when child component is rendered inside Shadow DOM.

### ISSUE THREAD

**Issue by timoxley** [ractivejs/ractive#1926]
`ractive.observe('*', fn)` doesn't seem to fire more than once on 0.7, but fires on each change in 0.6 (IMO expected behaviour).

```js
  this.observe('*', function() {
    console.log('changed', arguments)
  })
```

* Ractive 0.7: http://jsfiddle.net/0xwsco5o/2/
* Ractive 0.6: http://jsfiddle.net/uyju2h0b/3/

Discovered when trying to work around #1925

**Comment by Madgvox** [comment]
I'm fairly sure there's something else at play here, since it works as expected when tested by itself: http://jsfiddle.net/c101mc9d/1/

I haven't looked through your code in detail but at least in Firefox it's throwing an error. Can you double check to make sure something else isn't causing the broken observer behavior?

**Comment by timoxley** [comment]
> I'm fairly sure there's something else at play here, since it works as expected when tested by itself:
> Can you double check to make sure something else isn't causing the broken observer behavior?

@Madgvox Yes, it appears to be something to do with the interplay between ractive and the shadow dom.

> at least in Firefox it's throwing an error. 

Likely the use of custom elements/shadow dom, you can probably enable these features in firefox somehow.

**Comment by MartinKolarik** [comment]
Closing - fixed in edge.
