### ISSUE TITLE
TypeError: Cannot call method 'add' of null (global_css)

### ISSUE THREAD

**Issue by fabien** [ractivejs/ractive#1927]
I just updated from 0.61 and there appears to be a change when trying to build a component in Node. It seems to be related to https://github.com/ractivejs/ractive/blob/7741ceb6e42f2033b98e9ba678d0efa44c6da208/src/global/css.js#L13 and the fact that global_css will not be initialized correctly in this situation.

Removing any `<style>` tags sidesteps the issue, but I would still like to be able to share the exact same component code on both server and clientside.

**Comment by Rich-Harris** [comment]
Thanks - the fix is in, it'll be released in 0.7.3. When I say 'fixed', I mean that it will no longer throw an error - there's a big ol' TODO around how encapsulated CSS is actually handled with server-rendered HTML, which will probably be one of the major areas of focus for 0.9. For now, 'adding' and 'applying' encapsulated CSS is a noop in node.
