### ISSUE TITLE
"Failed to compute" error because of unexpected operation inside #if

### ISSUE THREAD

**Issue by Inversion-des** [ractivejs/ractive#1951]
Here is the problem (Ractive.js  v0.7.3): http://jsfiddle.net/Inversion/hLym2xcy/
See the comments under the code.

Is there a way to overcome these unexpected problems?

Thanks!

**Comment by Madgvox** [comment]
I'm fairly sure this is another example of https://github.com/ractivejs/ractive/issues/1924. The program isn't actually breaking, the 'failed to compute' error is simply a warning that ractive sends in debug mode. Like @martypdx said in the other thread, the message is harmless other than an annoying console log, and it will get cleaned up in 0.8 due to his work in #1740. For example, I set a new value to `pros` after four seconds, and there is no after-effects of the warning: http://jsfiddle.net/hLym2xcy/11/ 

I'm going to close this thread, but if you run into any other problems please don't hesitate to open an issue.

**Comment by Inversion-des** [comment]
Actually I'm not talking about warnings in console, but that some code is being executed when logically it should not be (`if` and `each` iterations).
If it is the same problem then it's ok to close the issue.

**Comment by Madgvox** [comment]
Yep, that's what I was referring to. The console warnings are a symptom of the illogical code execution. 0.8 will be smarter about when to execute code and when not to.
