### ISSUE TITLE
Separate helper functions from data

### ISSUE THREAD

**Issue by JonDum** [ractivejs/ractive#1956]
I've run into this time after time. If you have a helper function named `foo()` either globally or on a parent context and a sub Component with a non-function data item named `foo`, Ractive will try to call the non-function as a function and cause an error. Whackiness. It makes sense that it prefers the nearest item with that name, but it should really be smart enough to know that it's not a function, so don't try to call it.

Is it possible to either add additional logic to avoid the attempted function call, or would it be a better idea to change the api and add a 'helpers: { }' section to instances. Or is the solution just to avoid naming conflicts throughout an entire application?

**Comment by Madgvox** [comment]
Adding a helpers section wouldn't really do anything to solve naming collisions. It would just cause 'data' to collide with 'helpers', rather than 'data' colliding with 'data'. Plus, even if you could implement helpers in a way that solved the 'function' to 'data' collisions, you'd still have 'data' to 'data' collisions to deal with (i.e. a top level `foo` colliding with a local level `foo`)  which are honestly a lot more likely to occur than 'function-data' collisions.

You can specify the current context specifically by prefixing the reference with a dot (`.foo`). This will prevent ractive from trawling up the hierarchy to find `foo`. You can also traverse the hierarchy using `../`, so if you need to specify the `foo` one level up, you can call `../foo`. If you want to go all the way to root, you can prefix the reference with `~/`.

Additionally, if you don't want an attribute in a component to collide with a parent's attribute, you can set `isolated: true` in the configuration of the component, which prevents it from syncing its values with that of its parent. This means that you'd have to manually pass in the values you want to share into the component using attributes, but it means that there's no unwanted sharing of variables. I've run into that a lot, so for my app I've decided to set all components to `isolated: true` by default. It's made my life way more predictable.

**Comment by martypdx** [comment]
Having Ractive skip data based on type seems fraught with peril. See #1753, I think it's what you really want.

**Comment by JonDum** [comment]
@Madgvox The prefixes to a reference are very nice, but not really the issue. I may not have explained myself well, so here's a minimal example of what I'm talking about: 

http://plnkr.co/edit/vo5IpbpE4BfiXcrXC7T3?p=preview

Running it throws a hard error because ractive tries to call a string as a function.

Ractive walks up the parent chain to find a reference, right? If Ractive *knows* that the reference is a function to be called (because of the parentheses in the mustaches), why does it stop on the component's `data` just because it has an object with the same name that isn't a function? It's like it is satisfied with a truthiness check, when it should be searching for a function with that name.

If it's out of the scope of ractive to *not* throw a hard error in this situation and walk up the chain looking for a reference that is a function then feel free to close this. Since that chain walking logic is already there though I feel like in almost no scenario would a user want to execute a non-function as a function, even if the names collide.

**Comment by Madgvox** [comment]
> Running it throws a hard error because ractive tries to call a string as a function.

It's actually not throwing a hard error. The scary `failed to compute` warning just means that ractive caught an error when trying to resolve a reference, and bailed out of the computation. That means that `yell( "hello there" )` just resolves as `falsey`, because `yell` is not a function. If you disable debug mode by setting `Ractive.DEBUG = false` at the top of your app, the `failed to compute` warning will not appear and your app will continue to work as normal.

**Comment by JonDum** [comment]
@Madgvox I see. I guess it's up the to developer to avoid naming conflicts then between helper functions/filters/whatevers and data objects.

**Comment by Madgvox** [comment]
Yep, that's the way that leaves the most flexibility available to the developer. If you use the methods I mentioned above however, you can avoid most (if not all) naming conflicts no problem, even with duplicate reference names.
