### ISSUE TITLE
input type number when empty, value is undefined?

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractive#1966]
Not sure but is `undefined` the expected value of an empty number input? Kinda weird, especially if text input is string all the way, one could argue that number should be number all the way, perhaps a zero or something. http://jsfiddle.net/baynovwx/

```html
<script src="text/template" id="foo">
    <input type="text" value="{{foo}}" /> {{typeof foo}}
    <input type="number" value="{{bar}}" /> {{typeof bar}}
</script>
```

```js
var foo = new Ractive({
    el: 'body',
    template: '#foo',
});
```

**Comment by Madgvox** [comment]
I have to disagree, since an 0 !== undefined. You can have an empty string, but you can't really have an empty number.

Additionally, if you examine the behavior of the number field, it will return `undefined` for anything that is not strictly a number. For example, `-40` gives you `-40`. `-` gives you `undefined`. `20` gives you `20`, `20foobar` gives you `undefined`. With that behavior, it makes sense that an empty number input would give you undefined, since nothing is not a number.

**Comment by fskreuz** [comment]
Oki doki. :+1:
