### ISSUE TITLE
Yield and nested components: events not received

### ISSUE THREAD

**Issue by Skyrpex** [ractivejs/ractive#1970]
Hi!

I'm not sure if this is a bug or a feature... I've created a [fiddle](
http://jsfiddle.net/skyrpex/1otcofgr/).

#### Short explanation:
I've nested components like this:
```handlebars
<Wrapper>
    <Button>Go</Button>
</Wrapper>
```

`<Button>` component emits a click event. This event never goes through `<Wrapper>` because it uses `{{yield}}` to render its contents... Can I use yield AND receive the events of the yielded content?

Thanks.

**Comment by fskreuz** [comment]
I think this is the correct behavior because of `{{yield}}`. The contents between the wrapping component "belong" to the component using the two. Thus, the button events go straight out to the parent instead of Wrapper.

You might want to consider `{{>content}}` instead of `{{yield}}`, since in `{{>content}}` the owner of the enclosed markup is the enclosing component, not their parent.

**Comment by Skyrpex** [comment]
That's what I did at first. Then I wanted to make the `<Wrapper>` more bullet-proof by isolating and yielding it.

I guess I won't go that way :stuck_out_tongue:

**Comment by martypdx** [comment]
You can use the api get the find the containered component or the get the parent container. See http://jsfiddle.net/a0rgpw66/.

So `Wrapper` could do:

```js
this.findAllComponents()[0].on( 'clicked', function(){...} )
```

**Comment by fskreuz** [comment]
Never knew a wrapper could access the yield content. Hacky, but :+1:

**Comment by Skyrpex** [comment]
Neither did I. Excellent!
