### ISSUE TITLE
list in wrong order after jquery sort and then update

### ISSUE THREAD

**Issue by gushogg-blake** [ractivejs/ractive#1973]
Hi, 

I have a list of items displayed with ractive that can be reordered using jquery sort. If I populate the list then drag some items around and then repopulate the list using `ractive.set("list", array);` then the list is in the wrong order.

I realise it is probably not advisable to modify the dom with jquery when it's inside a ractive template and I have found a workaround by first setting the list to an empty array, but I was wondering if this is known behaviour and if it is safe to work around it in this way?

Cheers, 

Gus

**Comment by fskreuz** [comment]
That's because Ractive isn't aware of your DOM changes (it's not part of 2 way binding). So when you call `set` again, it re-renders the data according to what it knows. 

What you could do is keep track of the draggable items (assign them an index or something). When you finish dragging, you could scan the DOM and check the order of the list items. Then mutate `list` to update their order on the component data. Ractive will re-render, but won't be noticeable because of the already moved items.

By the way, Ractive has a sortable plugin https://github.com/Nijikokun/ractive.sortable.js

**Comment by Madgvox** [comment]
Hey @gushogg-blake, it's been awhile since you've responded to the thread, so I'm going to assume your issue has been resolved. If I'm totally wrong, do not hesitate to reopen the thread at any time. :)
