### ISSUE TITLE
Unshift is broken on data rendered with components

### ISSUE THREAD

**Issue by pangolingo** [ractivejs/ractive#1981]
Wen using a component, using `unshift` (and `splice`) on the data array behaves incorrectly. It removes the element from the end of the array and adds two new elements to the beginning of the array. `push` still works as expected

This occurs on both edge and latest.

Here's a demo: http://jsfiddle.net/zeuk7j17/

**Comment by Madgvox** [comment]
Looks like there's a bug with implicit bindings across component boundaries. As a workaround, if you bind the value explicitly, the bug does not occur: http://jsfiddle.net/zeuk7j17/1/

**Comment by pangolingo** [comment]
Thanks for figuring out a workaround. If I were to try to figure out a bugfix, do you have any suggestions for where to start looking?

**Comment by lazylester** [comment]
seems to be related... not sure... even the suggested workaround (thanks for that @Madgvox ) doesn't work when using computed attributes in the component. Since I'm very new to ractive, it's possible I'm doing something stupid too. See it here (adapted from the workaround by @Madgvox ) http://jsfiddle.net/ac00dnmb/ . 
I didn't even get to the point of having the computed attributes depend on attributes from the parent. In my example I'm just returning a fixed value.

**Comment by Madgvox** [comment]
You put the computed property on the component, then attempted to pass it _into_ the component from the parent. Moving the computed value definition from the component to the main ractive fixes your issue: http://jsfiddle.net/ac00dnmb/1/

**Comment by lazylester** [comment]
Yes, your fix works @Madgvox, thank you. Putting the computed method in the component is suggested in the documentation http://docs.ractivejs.org/latest/computed-properties, last example on the page. Also, the component seems to be the appropriate location (similar to Backbone collections and models), since it applies to the member and not the list.
Nevertheless, it works, can't beat that! Thanks again @Madgvox. Confess I don't understand your workaround.

**Comment by Madgvox** [comment]
It appears I mislead you with my example; it seems I solved a different problem than the one you were trying to fix. Can you give me a summary of what you're attempting to do, so I can point you in the correct direction?

**Comment by lazylester** [comment]
The last example on the docs page for computed properties (http://docs.ractivejs.org/latest/computed-properties) is what I'm trying to do. I'm not seeing how to apply your workaround to that example.
Here's a jsfiddle for clarification: http://jsfiddle.net/Nightingill/brpbu630/2/  it exhibits the bug which is the subject of this thread. How would one apply the workaround?
Many many thanks for your help @Madgvox

**Comment by Madgvox** [comment]
Here I'm passing the width and height explicitly into the component, and that lets it work correctly: http://jsfiddle.net/brpbu630/3/

Is this what you were referring to?

**Comment by lazylester** [comment]
Perfect! thank you @Madgvox

**Comment by evs-chris** [comment]
This now fixed in edge.
