### ISSUE TITLE
unshift fails following first list item teardown

### ISSUE THREAD

**Issue by lazylester** [ractivejs/ractive#1992]
ref: http://fiddle.jshell.net/fLaemk65/

If the first item on the list is removed. Subsequent unshift of items onto the list fail (click 'add' to unshift). 

It's because the removed item is not in the real DOM, but it is still in the parallel DOM (for presumably good reasons, which I don't know * ). So the ractive.js:line 8792 target.insertBefore fails b/c the second argument (anchor) is not in the DOM.

If items other than the first item are removed. Subsequent unshift of items onto the list works.

*see myRactive.fragment.items[0].renderedFragments in the jsFiddle

**Comment by Madgvox** [comment]
Hmm... this is an interesting problem, because the method you're using to remove the list items doesn't actually remove the entry from the array. There is always a danger when modifying ractive-controlled DOM, since it gets the virtualdom out of sync with the actual DOM. It's just that in this case, it's `ractive.teardown()` itself causing the problem, since teardown doesn't notify ractive to update. Technically, if `teardown` did actually notify ractive, the remove button in your example shouldn't appear to do anything. It would replace the torn down component with a new component, since the entry is still in the array.

That said, the proper way to remove items in this case would be to fire an event on the parent and splice out the entry. Here's an example: http://fiddle.jshell.net/fLaemk65/2/

**Comment by lazylester** [comment]
OK... I had looked through the docs to find how to remove items from the models and views, and teardown is what I took to be the way. Probably teardown is for some other purpose (what could it be?), simply manipulating the models is much cleaner. Not just cleaner either... it works!

Many thanks, @Madgvox.

**Comment by Madgvox** [comment]
No problem! `ractive.teardown()` simply destroys a ractive instance and cleans up all its listeners and DOM. It's basically the same thing you see in many jQuery plugins: `$item.tooltip( 'destroy' )` for instance.

I'm going to assume this issue has been resolved, and close it. If you have any other questions please do not hesitate to open an issue.
