### ISSUE TITLE
Renaming/aliasing `el` to something more meaningful

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractive#1994]
If you look at the [options table](http://docs.ractivejs.org/latest/options), everything makes sense judging by name, except `el`. One could assume "sure, it's an element" but for what?

Would it make sense renaming/aliasing it as something else like `mountPoint` or `root` or `container` or [insert better word for holder of component]?

**Comment by Rich-Harris** [comment]
Yeah. `el` was inspired by Backbone but I agree that it's not exactly self-explanatory. There's a related issue [here](https://github.com/ractivejs/ractive/issues/1848) that suggests renaming it to `element` (or allowing either to be used), which I quite like.

Unfortunately `root` and `container` are already names of properties. I prefer to avoid camelCase property names where possible, because it means you don't need to exercise your shift pinky - so how does `element` sound?

**Comment by fskreuz** [comment]
`element` sounds fine, and closing due to existing issue. :D
