### ISSUE TITLE
Ractive.stringify(parsedTemplate)

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractive#2001]
As discussed in https://github.com/ractivejs/ractive/issues/1998, proposing `Ractive.stringify()`, a counterpart of `Ractive.parse()`. Takes in a parsed template and returns the template in string form.

**Comment by ISNIT0** [comment]
Writing a very limited one is fairly easy...
http://jsbin.com/julitaqave/edit?js,console

(Originally came from this:http://jsbin.com/vewefamaje/edit?html,js,console,output)

I may sit down and start one properly at some point using all of these:
https://github.com/ractivejs/ractive/blob/db7a5d61730ad72857ae355597838b3d77f5bc28/src/config/types.js

**Comment by rstacruz** [comment]
why not release this as a separate library like `ractive-stringify`?

**Comment by ISNIT0** [comment]
Well it could always just be added onto the Ractive prototype manually:
Ractive.prototype.strinigyf = function(){...}
I think once the functionality is there, various different things can be done.

Joe

**Comment by evs-chris** [comment]
This turns out to be pretty complicated, and it doesn't fit in core very well. There's a _mostly_ working implementation over at #2766, which I don't think is going to be merged. I'll leave the branch though, in case there's any interest in doing this.

For the original use-case, internationalization of templates, I think it'd actually be a good deal easier to clone the template and then walk it swapping out text nodes. The only thing you'd care about swapping languages on would be text nodes inside elements (maybe a few attributes, but elements would definitely be the major chunk), and walking the element hierarchy is really easy. The root fragment is an array, text nodes are strings in the fragment array, elements are objects with `node.t === 7`, and the  element fragment array is at `node.f`.

I'm going to close this, as I don't think it will happen in core, and if it _does_ happen as an external library, there's a pretty good start in #2766.
