### ISSUE TITLE
Environment "components"

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractive#2003]
Taking off from @martypdx 's [comment](https://github.com/ractivejs/ractive/issues/2002#issuecomment-113788500) which sparked a eureka moment, I see that it would be handy to have "environment components", component-looking markup that represent essential objects whose properties are often sought after. It's because sometimes, especially when building "isolated" components, accessing `window`, `document` and other globals are really awkward.

## Syntax

@martypdx 's version:

```html
<@window ... />
```

#### What's needed
- Window dimensions and position (left, top, width, height)
- Viewport dimensions (innerWidth, innerHeight)
- Screen dimensions (screenWidth, screenHeight)
- events, particularly `onhashchange`.

#### Where useful
- Sizing and positioning components and elements (old-school layouting)
- hash-based routing

#### Example
```html
<@window left="{{left}}" top="{{top}}" ... on-hashChange="handler" />
```

#### What's needed
- Bubbled event capture.

#### Where useful
- Useful for mouse events and key events.
- Modal components which close when clicked outside the modal.
- Dropdowns that close when clicked anywhere else.

#### Example
```html
<@document on-click="set('visible', false)" />

{{#if visible }}<div class="modal">...</div>{{/if}}
```

#### What's needed
- Bindings to `pathname`, `search`, `hash` and a few other parts of the current url

#### Where useful
- Routing

#### Example
```html
<!-- pathname matching -->
<@location pathname="{{path}}" />

{{router(path, '/home')}}<home />{{/}}
{{router(path, '/about')}}<about />{{/}}

<script>
function router(route){
  return function(){ return router.matchRoute(this.get('path'), route) };
}

component.exports = {
  data: {
    router: function(path, route){ /* return true if match */ }
  }
};
</script>
```

#### What's needed
- `pushState` and `popState`

#### Where useful
- Path-based routing, paired with `<@location />`

#### Example
```html
<@history on-popState="statePopped" />

<script>
component.exports = {
  oninit: function(){
    this.on('statePopped', function(state){
      this.set('state', state);
    }
  }
}
</script>

```

#### What's needed
- Browser and device data

#### Where useful:
- Browser and device-specific data. See [Navigator](https://developer.mozilla.org/en-US/docs/Web/API/Navigator) for some useful ones. I know Mozilla has made this object their playground

#### Example
```html
<@navigator useragent="{{ua}}" />

<div>{{getBrowserName(ua)}}</div>
```
---

Open to interrogation, suggestions and criticism. :D

PS: Programming this way reminds me of Java Server Faces :P

**Comment by Rich-Harris** [comment]
Love it. I've lost count of the number of times I've done this sort of thing...

```js
component.exports = {
  onrender () {
    const resizeHandler = () => this.resize();
    window.addEventListener( 'resize', resizeHandler, false );
    this.on( 'unrender', () => window.removeEventListener( 'resize', resizeHandler, false ) );
    this.resize();
  },
  resize () {
    this.set({
      width: window.innerWidth,
      height: window.innerHeight
    });
  },
  // ...
};
```

...on multiple components within an app. I occasionally wondered if that indicated a need for mixins (though I don't think we ever discussed them properly) but I think this is probably a nicer solution to that problem.

While *support* for these would obviously need to be in the core library, it would be better if they lived as plugins, since you can imagine some pretty niche ones (`<@detect-esoteric-webgl-feature ...>`, accelerometer, battery state, whatever - hell, maybe even `<@flux-dispatcher ...>`). I think 'environment plugin' is probably as good a piece of terminology as anything.

**Comment by MartinKolarik** [comment]
:+1: for having these as plugins. However, I'm not sure if we really need a completely new API to support this.

Everything @fskreuz suggested can be implemented as a component. If you wanted to distinguish these components, you can use `<env:window>` or similar namespace instead of `@`.

The only problem I can see in this approach is that components currently don't support method calls, but that might be something worth supporting anyway.

Also, as a component author, you'd have to take care of adding and removing event listeners, but that can be easily solved by having a helper method for this.

**Comment by Madgvox** [comment]
Just my 2¢, but I think since these components are basically just hooks, and don't render anything, they don't really fall under the 'component' umbrella.

**Comment by dagnelies** [comment]
Dunno... honestly I feel like it's opening one more big digging hole. It may be "nice to have", but I'd still like to emphasize that there are IMHO more important matters. 

In particular, I urge the developpers to keep it simple and more stable. Currently, bugs are popping up rather frequently. Luckily the devs are rather responsive, nevertheless it's still risky and time intensive to use ractive for production code because you encounter too many bugs and unexpected behaviors on the way. Please please please guys, keep it simple!

**Comment by fskreuz** [comment]
Closing because the more I think about it over the week, it's dead weight. Welp, at least I got everyone's opinions about it. :D
