### ISSUE TITLE
Weird array bug in magic mode

### ISSUE THREAD

**Issue by atomiomi** [ractivejs/ractive#2005]
Hi! While implementing nested list I found out some weird bug. Here is [test](http://jsfiddle.net/pvtabau9/1/). In this case I want to remove some item from array and put it to another item (`children` field). If one item is added to another everything is ok but after adding another one, children list of parent item is cloned to next item. Just click two times on `Move` button in test and you will see that `third` and `fourth` have same children array. Without magic mode everything works fine.

**Comment by MartinKolarik** [comment]
The original bug seems to be fixed, but the fiddle demonstrates two new bugs in edge. With `magic: true`, items are not removed from `parents` array, and there's an error in the console saying `Uncaught Error: TODO magic adaptor reset`, with `magic: false`, second `move()` fails with `Uncaught TypeError: Cannot set property 'index' of undefined` inside `RepeatedFragment#updatePostShuffle()`

**Comment by evs-chris** [comment]
I think I may be missing a step on adaptors and shuffling. In edge right now, I don't see where adaptors get notified if their keypath changes from a shuffle. That's mostly fine for the edge array wrapper that gets a reference to a model and just uses that, but it's not good anything else that has to interact with the instance using its initial keypath. It doesn't look like there's really a good way around this other than to add some sort of `shuffled(newKeypath)` support to the adapator API so that it can moved without having to be torn down and re-assembed.

For reference, I bumped into this whilst trying to rewrite the array adaptor such that it doesn't rely on private internals and could thus be extracted at some point in the future.

**Comment by sabob** [comment]
@evs-chris I came to the same conclusion here: https://github.com/ractivejs/ractive/pull/2380#issuecomment-191365419

I briefly checked how 0.7.3 does it and there seems to be a step for updating keypaths after a shuffle which is missing in edge.

**Comment by evs-chris** [comment]
@sabob oops, I missed (or more likely misread) that comment amidst other discussion.

After having slept on it, and looking more into what is expected of adaptors from existing docs, I came to the conclusion that they should probably be reset with the value _and_ keypath if they support reset. Otherwise, they should be torn down and set back up as usual. For the top-level adaptor, it doesn't really matter, but if an adaptor happens to be downstream from another adaptor, it is left as-is.

There is another deeper question here too: should adaptors be reset on every change that updates their value? I feel like they should, but right now, `mark`ing a model may change its value without `reset`ing the adaptor.

At any rate, I now have a branch that fixes this problem, largely by removing the adaptors' assumption that they can still veto teardown and adding a `shuffled` phase to models so that they re-`adapt` their children after shuffling. I should probably add reset support back to the bundled adaptors and make sure reset is used everywhere it should by, but I'd like to resolve the rest of the questions surrounding adaptors in 0.8 before I PR it. Also, I'd like to let the PR stack shrink a bit before I throw more potential merge conflicts at it :smile:

**Comment by sabob** [comment]
@evs-chris do you think delegation is still the way to go for wrappers in the future?

**Comment by evs-chris** [comment]
I do - because I don't think adaptors should be fiddling about with internal API. I think the adaptor API just needs to be adjusted slightly to cover more corner cases.

**Comment by evs-chris** [comment]
While I'm pretty sure the adaptor API could use some adjustment, this is now working without any breaking changes in edge.
