### ISSUE TITLE
Support for Chrome Apps

### ISSUE THREAD

**Issue by cstefan** [ractivejs/ractive#2012]
I am developing a Chrome App and It looks like ractive is using string-to-JavaScript methods like eval() and new Function().

This is restricted on ChromeApps.

Is there a clean workaround? or planned support in the future?

**Comment by Madgvox** [comment]
Take a look at this thread: https://github.com/ractivejs/ractive/issues/1897. Among other things, it discusses the pros/cons of using an AST to evaluate expressions rather than `new Function()`. The discussion was for security compliance, but this is the first real use-case in favor of the change, and it warrants another look at the issue.

In the meantime, would something like [sandboxing](https://developer.chrome.com/extensions/sandboxingEval) help? The example is using handlebars, so I'm sure it'd be a breeze to substitute it out for ractive.

**Comment by cstefan** [comment]
For an existing & large project maybe it makes sense to use sandboxing to adapt it as a Chrome App.
But for a new project, that will use the chrome apis.....this is not a good start.

**Comment by Madgvox** [comment]
Yep, I totally agree. Unfortunately we don't have any plans to tackle an AST evaluator in the short term. We're mainly focused on improving the stability and [speed](https://github.com/ractivejs/ractive/pull/1740#issuecomment-94313301) for 0.8.

**Comment by jaminellis** [comment]
It is a shame. How much of the functionality depends on  new Function()? I'm wondering about a build that has those functions removed, for folk who are running in stricter Javascript environments.

**Comment by martypdx** [comment]
> Unfortunately we don't have any plans to tackle an AST evaluator in the short term.

Just chiming in with my .02 that I don't think build a DSL for javascript is the way to go. I think we should just moving expression function creation into parsing and output a duel template/functions object (details TBD). Less work and cleaner anyway.
