### ISSUE TITLE
State Management through `change` event

### ISSUE THREAD

**Issue by Aintaer** [ractivejs/ractive#2014]
It would be great if the `change` event fired with both the new and old values of the path that was changed. Specifically so that a state manager could track what has been changed and be able to apply the inverse operation.

**Comment by fskreuz** [comment]
I think [`observe`](http://docs.ractivejs.org/latest/ractive-observe) does the same thing. http://jsfiddle.net/qfzq8hrs/.

This works for simple values, especially primitives. But Ractive mutates objects, so be warned. You can either clone them every time, or consider persistent data structures.

**Comment by Rich-Harris** [comment]
I was discussing this in person with @Aintaer yesterday so we talked about whether `observe` would do the trick - tl;dr it doesn't, sadly! The problems start when *anything* might change, and you need to know specifically which keypath changed, and what it changed from and to:

```js
ractive = new Ractive({
  data: {
    foo: {
      bar: 'a'
    },
    baz: 'x'
  }
});

ractive.set( 'baz', 'y' ); // this needs to trigger a change handler...
ractive.set( 'foo.bar', 'b' ); // ...so does this...
ractive.set( 'foo', { b: 'c' }); // ...and so does this
```

Simply observing the root obviously won't work. The `change` event helps, because you get the keypath of the originating change, but it only reports the new value, not the old value. I *think* it would be straightforward to capture both old and new values, though we'd need to figure out what the event would be called and what its data should look like (since updating the `change` event itself would be breaking - though maybe that's okay since we'd be replacing it with something that can take care of existing use cases anyway.)

**Comment by fskreuz** [comment]
@Rich-Harris since `change` just provides the new value as first argument, how about making it like `observe`, in that it has `oldValue` as second argument, and `keypath` as third? This wouldn't break anything since probably everyone expected only the first argument to exist. 

That's unless someone wrote a function that accepts and uses a second and third argument and is hooked to `change`. Reminds me of this funny question from an FP fan on our team before. Explaining made him cringe.

```js
// Why does this map out to [1, NaN, NaN, NaN] and not [1,2,3,4]?
['1','2','3','4'].map(parseInt)
```

**Comment by aharpervc** [comment]
@fskreuz your FP fan should excited for an opportunity to use partial right application ;)

**Comment by Rich-Harris** [comment]
I'd be lying if I said that parseInt thing hadn't caught me out before! You're totally right, using the second argument is logical and is consistent with `observe`. Let's do that.

**Comment by evs-chris** [comment]
There are now recursive observers available on edge that will give you old and new values for previously observed changes, however it's up to the user to get an initial copy of what has changed and do stuff like handle `r.set('foo', { bar: 42 })` where `foo` is being set along with `foo.bar`.
