### ISSUE TITLE
Karma testing and Initialisation without "new"

### ISSUE THREAD

**Issue by nicolas-t** [ractivejs/ractive#2021]
Hi,

I have `payment.coffee` file like this : 
```coffeescript
App.ViewRactive.Payment = App.ViewRactive.extend
    template: '#payment-tpl'
...
```

I want to test this view, so I load it in my karma.config  
so I add this view in my karma.config.coffee like this :  

```coffeescript
module.exports = (config) ->
  config.set
...
    files: [
        'payment.coffee'
...
```

Then karma returns this error :  
```
Error: Could not find template element with id #payment-tpl
  at (...)/js/vendor/ractive.js:6657
```

The idea is to store the view in a variable `App.ViewRactive.Payment`  
but only to instanciate it by calling (in my test file) :  
```coffeescript
view = new App.ViewRactive.Payment(
    el: $('#main-panel')
    data: ...
    ...
)
```  

   
It seems to be related to the `Initialisation without new` ?
http://docs.ractivejs.org/edge/new-ractive

But i'm not sure, any help ?

**Comment by martypdx** [comment]
The problem is using a element id for your template: `template: '#payment-tpl'` as I'm assuming it doesn't exist.  You can either not include `template` in your extend, or use the parsed template instead - in which case you might look into using component files (https://github.com/ractivejs/component-spec/) as that is the formal mechanism for treating html, js and optionally css as a per view unit.

See https://github.com/ractivejs/component-spec/#available-loaders for a variety of packaging modules.

**Comment by nicolas-t** [comment]
thank you :)
