### ISSUE TITLE
Ractive iterates over empty array

### ISSUE THREAD

**Issue by skeptic35** [ractivejs/ractive#2023]
Finally getting round to upgrade from Ractive 0.6.1 to 0.7.3. And as 0.7.3 comes with debug mode turned on, I noticed a "Failed to compute" message that pointed me toward some rather strange behaviour.
See here: http://jsfiddle.net/rm9ah4ra/
As you can see in the console output, the ```testValue()``` method gets called even when the ```test``` array is empty. Imho this shouldn't be the case. I'd say if there is nothing to iterate over, then don't. 
After all if I do 
```
[].forEach(function(){console.log("huh?")});
```
then I get no console output, as should be expected.

**Comment by Madgvox** [comment]
Ractive 0.8 has a revamped [keypath system](https://github.com/ractivejs/ractive/pull/1740) that's smarter about when to notify dependents of changes.

**Comment by skeptic35** [comment]
So does that mean that 0.8 will not iterate over an empty array? Just being smarter doesn't necessarily mean getting it right, you know ;)

**Comment by Madgvox** [comment]
Ractive isn't actually iterating over an empty array, it's simply notifying a dependant of a change when it doesn't have to. When a value changes in an array, everything that touches the value gets notified of the change and re-evaluated. This goes for removing values too. If you have an array `myArray = [1, 2, 3]`, and you set it to `[]`, something that binds to `myArray[2]` will be notified that it has changed from `3` to `undefined`. To the dependencies, `myArray` might as well equal `[undefined, undefined, undefined]`.

In your example's case, when you clear the array, ractive sees that the array has changed and re-evaluates the function call in order to keep the block up-to-date. What ractive 0.7.3 doesn't keep track of is that this process is unnecessary in this case, as the whole block is not going to be rendered due to the surrounding logic. Ractive 0.8 takes a lazier approach to notifying dependants, so in this case it wouldn't bother re-evaluating the function since it knows that the block it's contained in is not going to render.

**Comment by skeptic35** [comment]
Thanks for the clarification. I'll close this one then.

**Comment by gaetano-guerriero** [comment]
So is this considered a bug, and will be fixed in Ractive 0.8 ?
With Ractive 0.7.3, I use `.set({'array.length': 0})` as workaround to avoid `"Failed to compute"` warning

See: http://jsfiddle.net/ac1kqcah/6/

**Comment by Madgvox** [comment]
The unnecessary computation is an inefficiency in the keypath system, and it will be revamped in 0.8 along with a good deal of other optimizations. However, the `failed to compute` warning in 0.7.3 is not a breaking warning. Ractive will continue to function correctly even after one of these warnings are issued. There is no need to avoid them unless you find it annoying that they're clogging up the console (I know I did!).
