### ISSUE TITLE
this.get() does not return a full data copy

### ISSUE THREAD

**Issue by raray** [ractivejs/ractive#2032]
From the docs for `ractive.get()`:
> Returns a shallow copy of all data (the equivalent of ractive.get('')). This does not include Computed Properties, but it does include any mappings if ractive happens to be a component instance with mappings.

However, in practice `this.get()` seems only to return cached data which omits properties that have yet to be used. This is problematic when trying to pass along previously undisplayed data to other components. (In my particular case it is a pop-up editing form). Here is a super-simple fiddle illustrating the issue (check the console log): http://jsfiddle.net/me489awe/2/

**Comment by Madgvox** [comment]
Huh! That seems like such an obvious issue I'm surprised we never caught it!

**Comment by kouts** [comment]
I also had noticed this but i thought that this is how it should work and if I waned a full data copy I must get it from the parent instance!

**Comment by Madgvox** [comment]
Oh, you're totally right @kouts, I did not look nearly close enough at the jsfiddle and did not notice that it was passing through to a child component.

@raray when data is passed implictly through to components, it does not copy the entire data object to the child. So the behavior displayed in your fiddle is totally expected. Like @kouts said, in order to access the entire data object, you should retrieve the parent's data object, which you can easily do by calling `this.parent.get()`. Apologies for the previous misdiagnosis!

**Comment by raray** [comment]
@Madgvox I appreciate the clarification, but the proposed solution doesn't make much sense to me. In the example case, setting the child's `data` to `this.parent.get()` would add all `items` to the child which isn't useful.

**Comment by martypdx** [comment]
You need to explicitly include the context in the component parameters:

`<child item='{{this}}'/>`

**Comment by raray** [comment]
@martypdx Thanks for that. It provides a working solution though I'm left wondering why that context doesn't get copied down by default.

**Comment by martypdx** [comment]
@raray components have their own root data context. Outside data is mapped and keyed off the root if either: 1) it is explicitly passed as a parameter, or 2) the template or an api get references a property that is not found in the context stack within the component (including its own root context) and if component is not isolated (the default) it will look up the context stack within the parent template starting where the component tag exists.

So components don't inherit the current context of their parent as their root data, they merely exist at that place in the context stack for the purpose of resolving references.

There are times when it would be handy to something like `<child this='{{this}}'/>` and avoid having to do `{{#with item}}` in the component template. However, what would that mean for data defined with the component `data`? Adding it to `item` would be unexpected. 

I've wanted to add `{{@state}}` type references to Ractive and post `0.8` should be ready to do that. State would essentially be parallel to `data` and rooted at the component (rather than within the context stack, and `{{@@state}}` could be rooted at `root` ractive instance aka global state).  

The point here being that doing something like directly setting the root data context of a component would be more feasible.

**Comment by raray** [comment]
Thanks, @martypdx. That's a great help!
