### ISSUE TITLE
Value bound through aliasing is not updated

### ISSUE THREAD

**Issue by emirotin** [ractivejs/ractive#2036]
I have a bug when values bound with aliasing are not updated when underlying data model is edited.

Please check this plunker: http://plnkr.co/edit/Q8Z7gEwxoWFjFIUOMVpj?p=preview

Try editing the number in any of inputs. The square is not updated in the title.

Now if I remove the aliasing it works as expected: http://plnkr.co/edit/sEWwffm5HeSZGUhJYIqf?p=preview

Would be very thankful for help, currently encountered this problem with the real-world customer project. The project is not so trivial, so a combination of aliasing and partials helps me keep sanity without remembering every time what is `this`.

**Comment by evs-chris** [comment]
This is an issue that's been around a while (#1353). It's also pretty tough to solve. I believe the upcoming 0.8 will make it easier to solve at some point in the future, but for now `#with` and two-way binding don't really get along.

One potential workaround is to use change events on the input elements instead of binding. You can pass and assemble keypaths as strings in the change events. It's not particularly pretty, though.

**Comment by emirotin** [comment]
Thanks for pointing out. I'm afraid handling change events manually won't help my sanity =) Will have to think of an alternative way, maybe components (though they require some extra work).

**Comment by emirotin** [comment]
Components seem to work OK (though inability to subscribe to events with arguments is a bit annoying, still no idea how to work around it).

**Comment by Madgvox** [comment]
Closing this and pointing discussion of the topic towards https://github.com/ractivejs/ractive/issues/1834 and https://github.com/ractivejs/ractive/pull/2209.
