### ISSUE TITLE
using 'set' inside component does not work

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2048]
on-click='set...' inside a component does not work for me. I'm obviously doing something wrong but i cannot figure what.
Check this jsfiddle: http://jsfiddle.net/kouts/chujkrpu/1/

**Comment by MartinKolarik** [comment]
For `set()` to work in this case, you'll need to explicitly pass `header` to the component:

```html
<objects header="{{header}}" />
```

See http://jsfiddle.net/chujkrpu/2/

**Comment by kouts** [comment]
That solved it thanks @MartinKolarik!
I wonder though if this behavior is expected, since all components that have isolated: false are supposed to have access to the parent's data  - as stated by the docs (http://docs.ractivejs.org/latest/components#isolated-boolean-).
Interesting thing is that if I wrap the non working button with a {{#if header}} then it works - http://jsfiddle.net/kouts/chujkrpu/3/

**Comment by MartinKolarik** [comment]
Yes, it's expected, but this issue comes up pretty often so maybe we should mention it in the docs, or add it to #1915.

Calling `set()` will set the data on child component, unless there's a mapping to the parent. The mapping can be created by:

 - explicitly passing the value (`header="{{header}}"`)
 - calling `get()` from the child component
 - using a reference in child component's template (which invokes `get()` internally) - that's why it works with `{{#if header}}`.

**Comment by martypdx** [comment]
> or add it to #1915.

I don't know that we could infer whether the `set` call was intended as a mapping or the root of the component.

**Comment by MartinKolarik** [comment]
>I don't know that we could infer whether the set call was intended as a mapping or the root of the component.

We could get a list of keypaths on parent component and check if the keypath currently being set is in that list, couldn't we? Although this could obviously lead to some false positives.

**Comment by martypdx** [comment]
> We could get a list of keypaths on parent component and check if the keypath currently being set is in that list, couldn't we?

Seems performance intensive to do that on every set just because data isn't on the component. 

However, TBH we've starting adding default data to the component `data` node whenever we have data intended to be set on the component root, for both sets and gets, specifically to ensure correct resolution. IMO these are all fields I was designate as "state" when/if that exists.

Maybe the restriction on `set` should go away. At the time, it just seemed to be unleashing Zadalgo to have `set` options cascade up the component stack.

**Comment by MartinKolarik** [comment]
> Seems performance intensive to do that on every set just because data isn't on the component.

It's just a property check or `indexOf`, but maybe you are right...

>we've starting adding default data to the component data node whenever we have data intended to be set on the component root

Yes, I tend to do this too.
