### ISSUE TITLE
Inherited properties from removed component

### ISSUE THREAD

**Issue by linde12** [ractivejs/ractive#2061]
Hello!

There is a problem with ractive not rerendering correctly when redefining an array in the components data.

I have a List component and for each item in the people array a subcomponent(ListItem) will be rendered with that item as an argument. Something like this:
```
{{#each people}}
  <ListItem person={{this}} />
{{/each}}
```

In my List i do something like this:
```
this.people = [
  {name: "Oscar", age:21},
  {name: "Stefan", age: 19}
];

this.set({people: people});
```

In the ListItem for `Oscar` i set `eyecolor: 'blue'` on a button press, and thus the array looks like this:

```
[
  {name: "Oscar", age:21, eyecolor: 'blue'},
  {name: "Stefan", age: 19}
]
```

Then i have some function to update my list in List. It redefines the people array to a completely new array containing only `{name: "Stefan", age: 19}`

However now Stefan will also have the `eyecolor: blue` attribute. This is not expected, or at least wasn't expected by me. I think its bad behavior and took long time to debug.

I'm sorry this is really confusing. It's really difficult to explain but i set up a demo for you:
http://jsfiddle.net/mnzbjLq5/3/

If you press "Set color attribute" on the first item in the list and then press "Refetch items" you'll see the new item inherits that color attribute from the removed item.

**Comment by linde12** [comment]
Running `this.reset();` before "refetching" the item in the fiddle resets the color attribute and everything works as expected. But that is not something you want to do every time.

**Comment by martypdx** [comment]
Ractive has two strategies for updating list blocks:

1. For array modifications like splice, pop, push - it reorders/modifies the blocks of template content ( components, dom nodes, etc) to match the array modification
2. For setting a new value for the array, it reuses the existing template blocks as is and adds or removes to match the length.

As you noted, you can reset or first set the array value to `[]` or `null` to force clearing of the components.

Another option is to use `ractive.merge` instead of `ractive.set` which will retain nodes with identical* data and create new nodes (* default is strict equality though you can provide a compare function). Keep in mind there is a cost to doing the comparison, but if your lists are relatively small it's a good option.

Best option may be to design your components to be reactive to data and respond accordingly. You could store `user.color` instead of `color` to avoid assigning to the component root. Or you could use an observer to (re)initialize specific state:

```js
this.observe( 'user', () => this.set( 'color' ) );
```

or reset the component state entirely when the user is changed: 

```js
this.observe( 'user', user => {
    this.reset( { user }  ); // clears all data but user
}, { init: false } ); // no need to reset the first time
```  
It really depends on the characteristics of your app and sizes of your data how best to manage the underlying DOM manipulations.

**Comment by linde12** [comment]
@martypdx Thanks for the quick reply! I see you provided some great solutions but i'm a bit confused by the last one.

In my case i have a user model in an expandable list item. I dont want to set `user.isExpanded` on my `user` object because that will be sent to the server later.

This is what i did before but i don't want to send isExpanded to the server every time. The data i'm interested in storing to the ListItem has nothing to do with the user per se, it's just meta information needed by that component and when it's removed i don't want it to affect any other component.

I'll fiddle around some more but it would be nice if you could tell me your thoughts on this now when you have some more information. Hope it makes sense.

Thanks again for the quick reply!

**Comment by linde12** [comment]
Another way of putting it is that i want my data bound to that specific `ListItem` component, not to its DOM. Because i also want the metadata from other `ListItem`s to be kept

**Comment by martypdx** [comment]
> but i'm a bit confused by the last one.

It resets the data within the component if the user data changes. look at this example and the console: http://jsfiddle.net/mnzbjLq5/7/:

```
init Object {user: Object}
after set blue Object {user: Object, color: "blue"}
before reset Object {user: Object, color: "blue"}
after reset Object {user: Object}
```

> Because i also want the metadata from other ListItems to be kept

Not sure what you mean by that. do you mean for ListItems that are the same (correspond to the same logical data) across the reload?

Or are you wanting to clear everything on reload and rerender from scratch?

**Comment by linde12** [comment]
Ah i see your example but i dont think it would work in my case.

I have a list of users. Each user is "expandable". When you click a user li
they "open up" and you can see detailed information. When i use merge and
"expand" a couple of users and then remove one then the expanded users will
reset to their initial state(not expanded).

So i want to keep the state of each component but when the data of the list
is updated i want to not only "move" the new data in place but also bring
that components state(e.g. isExpanded).

I will try to make a better example of what i'm trying to do once im home
again.

Thanks a bunch for helping me out.

**Comment by martypdx** [comment]
> i want my data bound to that specific ListItem component, not to its DOM

I'm usually the same with complex components - I sometimes just don't want them to be reused. Just setting to an empty array first works and is most efficient way:

```js
this.parent.set({items: [] });
this.parent.set({items: items});
```

You can encapsulate this in the parent component with an observer and then it will happen automatically whenever list is set:

```js
this.observe( 'items', items => {
    this.set( 'items', [] );
    this.set( 'items', items );
}, { init: false } );
```

see http://jsfiddle.net/mnzbjLq5/8/

**Comment by linde12** [comment]
Here! I've go a new fiddle: http://jsfiddle.net/mnzbjLq5/11/

If you expand `Oscar Linde nr. 5` and `Oscar Linde nr. 0` and then click remove on `Oscar Linde nr. 0` you'll see the behavior i'm talking about.

Expected behavior that i want is when `0` is removed then `5` will still be expanded, not `6`. Now `5` doesn't keep it's "expanded" state, seems like its bound to the DOM.

And of course in this case i dont want to use user.expanded because:
A) it wouldn't be set by the server
B) i don't want to store/filter out that information in my model

**Comment by linde12** [comment]
When an item is removed to the list, i don't want to keep that items state(`expanded`) either. But i still don't want other items' state to be changed either. Thus a complete re-render wouldn't work because i still want to keep the other items' state.

**Comment by Madgvox** [comment]
Keep in mind this is a very, _very_ rough example, since I'm running on no sleep at the moment, but here is a working example of what you're trying to do: http://jsfiddle.net/mnzbjLq5/12/

Basically I'm keeping track of the expanded users, and then re-expanding them when the list is updated.

**Comment by linde12** [comment]
Hey & thanks for your response!

I see what you're doing and i thought of the same thing actually. It's just that it seems kind of dirty. I've been using Ractive for a couple of weeks now and i've gotten used to all the awesomeness this just seems like there has to be a better way. Like some way to move the "expanded state" as the list changes.

Everything has been smooth sailing but this just seems like so much to do and is kind of dealbreaking within an application that uses multiple lists like this.

I appreciate the help, and i hate to nag about it, but if you figure out a better way please tell. I will continue messing around with it to see if i can figure out how to move the state as the list updates, because keeping it bound to that element is pointless(at least for me). But feel free to come up with alternative solutions! I just want to keep it as simple as possible.

Thanks again & it's great you guys answer so quickly! Really awesome!

**Comment by martypdx** [comment]
@linde12 I gotcha now. I use Firebase and do the same thing where I call the server and it triggers an event in the client that I respond to in order to modify the array. Except that it gives me enough info on the event to modify the array explicitly versus having to refresh all of the items.

So, first off, `ractive.merge` is exactly what you want if you need to go the route of reapplying the whole items array. See [this example](http://jsfiddle.net/mnzbjLq5/13/). Because we can't use object reference equality, I'm passing in the `name` as the key to compare. You can use whatever key or supply a custom function, or pass `true` to do a full `JSON.stringify` compare (see [docs](http://docs.ractivejs.org/latest/ractive-merge) ). 

But if you don't need to refresh the whole array, you can just use `ractive.splice` to remove that one item and then it just remove that one node. See [this example](http://jsfiddle.net/mnzbjLq5/14/) for effect of splice.

**Comment by linde12** [comment]
@martypdx Oh, cool! You're the best! It works perfectly. I had missed the whole compare thing of `ractive.merge`!

I think i'll still have to update the whole list though since i'm using Ractive with the flux pattern.

Once the server responds and i update my models i just emit a `change` event and then each view has to fetch the data they want. So e.g. when my list has been set on the server the `change` fires and my `ListComponent` does something like `UserStore.getUsers();`. I guess i could do something like `UserStore.getNewUsers();` or something, but it seems like a hassle. I want to keep it as simple as possible so everyone can understand and so that the code is easily maintainable. Right now it's so small amounts of data so i don't think it'll be any problem.

Thanks so much again, it all makes sense now!

@Madgvox Thank you too! You've both been of great help.

**Comment by martypdx** [comment]
> I think i'll still have to update the whole list though since i'm using Ractive with the flux pattern.

Well at least it just means comparing the data and not re-rendering every component and then comparing the output. Or forcing you to use an immutable data structure just to work around that issue :wink: 

> Thanks so much again, it all makes sense now!

:+1:
