### ISSUE TITLE
Re-add Ractive.noConflict

### ISSUE THREAD

**Issue by Madgvox** [ractivejs/ractive#2066]
As per https://github.com/ractivejs/ractive/issues/1547#issuecomment-130145501, the Ractive.noConflict function has ~mysteriously disappeared~

**Comment by JonDum** [comment]
Is noConflict even needed? @Ghazgkull Would you mind chiming in why you need it?

Here's the current module definition in edge:

```
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
  typeof define === 'function' && define.amd ? define(factory) :
  global.Ractive = factory()
}(this, function () { 
```
Only gets added to global if there's *no* detected module system at all.

Do developers that don't use a module system but care about global pollution exist?

**Comment by Ghazgkull** [comment]
I use a module system (Browserify), I care about global pollution, and I need Rangy.noConflict because when you load Rangy asynchronously it stomps on the window.rangy property.

In my case, I have a bit of Javascript (transpiled with Browserify) that gets loaded onto a 3rd party website. The first thing I do is turn around and load my dependencies (jQuery, Ractive, Rangy) by inserting new script tags into the DOM. And when Rangy loads, it sets the global window.rangy property. jQuery does the same thing, but using noConflict it's easy to reset the global var as soon as the script loads.

For now I'm taking a poor-man's approach where I squirrel away the value of window.rangy before I insert the script tag to load my own version and then restore it manually. But it would be nicer to just use noConflict.

**Comment by JonDum** [comment]
That doesn't convince me of the need for noConflict.

You could easily include your dependancies into your browserify bundle instead of hackily injecting script tags and you'd have the benefit of removing additional HTTP requests which will more than likely be an improvement to cold load times anyways.

**Comment by Ghazgkull** [comment]
Whether to bundle required libraries into an application or to reference them externally (e.g. from a CDN) is a decision that has to be made for each application. Sometimes it makes sense to bundle things together and sometimes it absolutely doesn't.

In my case, warm load times are much more important than cold load times. And my application Javascript changes much (much!) more frequently than my required libraries. So I get much faster load times by keeping my libraries out of my app bundle and instead letting the browser hit a CDN for a 304 that returns a few bytes of data.

There's nothing hacky about injecting script tags into the DOM. It's the normal way to load additional Javascript and CSS files.

**Comment by martypdx** [comment]
@Ghazgkull What about using browserify to create (a) separate module(s) bundle that contains your third-party modules like Ractive?

**Comment by Ghazgkull** [comment]
@martypdx I'm doing that for another library I require (Rangy), that's bundled as a core library plus a few optional modules. I use Browserify to bundle them into one bundle that can be pulled down in one shot. The only challenge there is how to host the resulting library. I'd much rather pull down dependent libraries from CDNs wherever possible.

I feel a little bit awkward monopolizing this conversation with the details of how my particular app is architected. I suggest that it's a good idea accommodate more people using Ractive by allowing different scripts built on different versions of Ractive to co-exist. The noConflict() solution works well for other libraries and it'd be nice to have with Ractive as well.

**Comment by JonDum** [comment]
@Ghazgkull If server bandwidth is your limiting factor, Cloudflare is completely free, so you can keep both your initial payload and bundle under a CDN while having complete control over how they are packaged **and** avoiding 3 304's by bundling. I would eat my shoe if one 304 under a CDN results in slower load than *three* 304's under a CDN. 

> I feel a little bit awkward monopolizing this conversation with the details of how my particular app is architected.

I totally agree, but so far the only argument to including noConflict is that it helps your workflow even though your workflow has other solutions that would be improvements! 

My other reason for rebuke was so that marty et. al wouldn't have to spend any time/thought on this so they could focus on more important stuff like 0.8 :) :) but that ship has sailed hehe.

**Comment by Rich-Harris** [comment]
Having found myself in all sorts of hard-to-describe hair-pulling situations involving module loaders, and injecting multiple mini-apps into pages that I don't control (which is basically my day job), I'm sympathetic to @Ghazgkull. IIRC `Ractive.noConflict()` previously existed because we needed there to *always* be a global (even if a module loader was detected, because sometimes globals really are the only way to share a library between different apps on the same page), but wanted there to be a way to clean up the mess for people concerned about such things.

I wouldn't say it's a *massive* priority (down to a dozen failing tests on my local 0.8 branch btw!) given that there are workarounds (however ugly), but I'm generally :+1: on reinstating this.

> And when Ractive loads, it sets the global window.rangy property

wait... what? :grimacing:

**Comment by Ghazgkull** [comment]
> ... even though your workflow has other solutions that would be improvements!

@JonDum I'm always eager to make improvements to my application, but in the end none of the ideas suggested here quite work out to be improvements. I'm trying to be polite by not dumping out all the details of the application I'm implementing and why my current architecture is the best fit.

> And when Ractive loads, it sets the global window.rangy property
>> wait... what?

Ha! Sorry, typo. I got my R-names mixed up. :)

I agree this isn't a massive priority. Anyone can implement their own solution for this (I already have my own in place), but it **would** be "nice to have" a built-in solution following the noConflict() pattern.

**Comment by JonDum** [comment]
@ghazgkull we'll have to take your word for it :)


> down to a dozen failing tests on my local 0.8 branch btw!
@rich-harris hell yea! Can't wait to start refamiliarizing myself with the new code so I can help out.

**Comment by evs-chris** [comment]
`noConflict` is back in edge.
