### ISSUE TITLE
Binding fails inside aliasing

### ISSUE THREAD

**Issue by alexmakeev** [ractivejs/ractive#2079]
Binding to outside variables fails inside aliasing
```
    {{header.product}}
    {{# {hd: header}}}
            <button on-click="set('hd.product', 'Value')">Doesn't work</button>
    {{/}}
```
Also, it partly works when used inside component & aliasing, see fiddle:
http://jsfiddle.net/alexmak/w8qsfbmz/12/

**Comment by martypdx** [comment]
> Binding to outside variables fails inside aliasing

It's really an expression (`{ hd: header }` ) used as the context for a with block, not true aliasing. Using `set` is the same as calling `ractive.set`, so it operates per the rules of the component api - which doesn't currently include expressions (AFAIK) so you can't do something clever like `set(@keypath + '.product', 'Value')`.

The real answer is to do true aliasing with something like `{{#with header as hd }}`

**Comment by alexmakeev** [comment]
Thank you for reply @martypdx ,
Is there a way to do multiple true aliasing?

**Comment by martypdx** [comment]
> Is there a way to do multiple true aliasing?

Not sure what you mean. 

For two-way binding where you need to change the name, component parameters work effectively as do computed properties. 

Creating a object literal expression has limitations, as you discovered.

**Comment by alexmakeev** [comment]
I mean
```{{#with {hd: header, ft: footer} }} ... {{/}}```
instead of
```{{#with header as hd }}{{#with footer as ft }} ... {{/}}{{/}}```

**Comment by martypdx** [comment]
Oh, it's a hypothetical, though oft requested, feature. So it can be anything at this point. :)

It might be possible to do some parse time analysis on expressions so that we do automatically aliasing on object literal assignments that only contain references. So something like: 

`{{#with {hd: header, ft: footer, size: ( header.size + footer.size + 10 ) } }} ... {{/}}` 

would create a link between `hd` and `header` and `ft` and `footer`, but not `size` because it's a true expression.

btw - as an available hack, you can do something like:

       this.observe('hd', function(n, o, k) {
           this.set('header', n);
       }, { init: false });

to back link the alias. Though that usually defeats the simplicity of just doing something in the template.

**Comment by alexmakeev** [comment]
Sure, the simplicity is first. Will use nested {{#with ...}} for now.

**Comment by Rich-Harris** [comment]
For the record I'm wary of trying to statically analyse expressions like `{{#with {something: else} }}` to facilitate two-way binding, because we quickly find ourselves in territory where it's not obvious to a casual observer when the magic applies and when it doesn't (Also, I hate the way the closing curlies butt up against each other!). I realise we're already there to some extent with 'reference expressions' like `value='{{foo[bar]}}', which were added to meet a similar need.

So I'd be in favour of something like `{{#with something as else}}`, and similarly for list sections i.e. `{{#each people as person}}` – less confusion for both humans and machines. Would be nicer for doing tabular stuff:

```html
{{#each rows as row}}
  <tr>
    {{#each columns as column}}
      <td>{{row[column]}}</td>
    {{/each}}
  </tr>
{{/each}}

<!-- instead of the slightly more cryptic thing we do now -->
{{#each rows :r}}
  <tr>
    {{#each columns}}
      <td>{{rows[r][this]}}</td>
    {{/each}}
  </tr>
{{/each}}
```

No reason this couldn't work with expressions as well, i.e.

```html
{{#with ( header.size + footer.size + 10 ) as size }}...{{/with}}
```

**Comment by evs-chris** [comment]
Edge now has support for `{{#with foo.bar as baz, bippy.bop as boop}}...`, where two way binding is supported for references and calculations are shared (only execute once).
