### ISSUE TITLE
Dynamic property binding

### ISSUE THREAD

**Issue by robinklaassen** [ractivejs/ractive#2083]
I recently started using Ractive to rebuild an app I originally made in Angular. I'm very satisfied thus far with the simplicity of use - I remember that back then I finally managed to build the app, but still did not by far understand the workings of Angular. But now I'm wondering if something specific is possible: dynamic property binding. I did not manage to find any info on this in the docs or on the internet (yet).

A small example:
```javascript
{{#each members}}
<input type="text" value="{{something[id]}}">
{{/each}}
```

In the above, each object in 'members' has an 'id' property. Let's say this id is "94". I would then like my input value to bind to "something[94]" instead of "something[id]".

I would like to know if this type of binding is supported by Ractive, and if not, if there are any good workarounds, as I do require this functionality for my app. I hope the example and question are clear. Thanks in advance for any help!

**Comment by Madgvox** [comment]
I'm afraid I don't understand what your expected behavior is, and how it differs from how ractive acts by default. The input will be bound to the value of `something[id]`. If `id == 94`, then the input is bound to the value of `something[94]`. Here's a [jsfiddle demo](http://jsfiddle.net/ehtegxw9/). If I'm totally misinterpreting what you're trying to do, feel free to change it to display the behavior you're referring to.

**Comment by robinklaassen** [comment]
Thanks for your quick reply. I played around a bit with the fiddle you provided and I see that Ractive does act as I wish. The fact that it's not working right in my app must then have a different cause - most likely that I'm dynamically loading data that affects the entire Ractive. I already have a few ideas to continue, so I'll close this issue. Cheers!
