### ISSUE TITLE
[BUG] Nested inline partial inside a defined partial does not work in edge (0.8)

### ISSUE THREAD

**Issue by NikhilVerma** [ractivejs/ractive#2084]
Example: Add the following snipped inside samples/render.js and run the build. It will fail with the following error:

![image](https://cloud.githubusercontent.com/assets/87832/9554513/09b6a4fa-4de4-11e5-94b2-bfaa4badb9a6.png)

```javascript
{
    name: 'Nested inline partial inside a defined partial',
    template: '{{#items}}{{>foo}}{{/items}}',
    data: { items: [{value: 1}, {value: 2}, {value: 3}] },
    result: '<div>1</div><div>2</div><div>3</div>',
    partials: { foo: '{{#partial bar}}{{value}}{{/partial}} {{#if value}}<div>{{>bar}}</div>{{/if}}' },
}
```

**Comment by NikhilVerma** [comment]
Seems like it's a known limitation, not really a big deal now :)

**Comment by evs-chris** [comment]
I meant to comment on this earlier, but I lost track of it...

Directly nested partials have never been supported. Somewhere around 0.7, we got support for searching up the template hierarchy for partials anchored at elements, so you can effectively nest partials if the nested partial is at least one element deep in the parent e.g. `{{#partial foo}}<p>{{#partial bar}}...?{{/partial}}{{>bar}}</p>{{/partial}}`. That particular example is useless, but there are situations where it's handy to break common chunks of template into local partials.

Since we now have that ability, I wonder if it would make sense to remove the directly nested partial restriction? My gut says no because they would effectively sit next to their parent partial when they anchor, and that would be weird.
