### ISSUE TITLE
Custom elements aren't initialised correctly

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#2088]
Playing around with #2043 a bit more, and found what seems to be yet another oddity with the design of custom elements: http://jsfiddle.net/rich_harris/7kxdm71d/

The tl;dr is that the `createdCallback` is called as soon as a custom element is programmatically created, before you get a chance to set attributes. So if the `createdCallback` refers to the element's attributes (as in @paulie4's fiddle – http://jsfiddle.net/3c2pfhgL/1/), it will fail.

I'm not sure there's a good solution to this...

**Comment by Jeff17Robbins** [comment]
The workaroundl is to use your favorite `async` method (`setTimout, requestAnimationFrame, MutationObserver, or setImmediate`) and defer `createdCallback` until just a bit later, which is long enough to wait for Ractive because Ractive adds all its attributes in the same call frame as it creates the element.  

You really only need a "microtask" work item (at the end of the current frame, like `MutationObserver`) rather than a "macrotask" as shown here http://jsfiddle.net/v99d8sb9/7/

But this fiddle fixes @paulie4 's to show the "Ractivated caption" using Ractive 0.8.0-edge.

**Comment by Rich-Harris** [comment]
@Jeff17Robbins The trouble is that the custom element author needs to understand and use that workaround, which might be okay in a situation like this but is liable to fail with third party custom elements.

I wondered if the solution involves generating some HTML, calling `someDiv.innerHTML = theHtml` so that `createdCallback` has access to attributes, then detaching/reinserting the resulting node(s), but then you'd very likely run into problems with parent/child relationships.

**Comment by martypdx** [comment]
Why not use the `insertedCallback`?

**Comment by Rich-Harris** [comment]
@martypdx it's the same problem, refracted slightly differently – a custom element author has to know to use a different lifecycle hook or they could innocently create something that appears to work perfectly well in a normal HTML context, but fails with Ractive (or any view library for that matter).

In the `<img is='img-ext'...` case, the `attachedCallback` is probably the correct hook to use since it needs to modify the DOM. But for some elements (particularly non-UI elements, such as the hypothetical `<x-socket...` component in the fiddle above), `createdCallback` is the correct hook since the state of the websocket connection should have nothing to do with if/when/where it's been inserted into the document.

**Comment by Jeff17Robbins** [comment]
We've been doing some work with [webcomponents](https://github.com/WebComponents/webcomponentsjs) and Ractive, and ended up emulating Polymer's [ready](https://www.polymer-project.org/1.0/docs/devguide/registering-elements.html#ready-method) lifecycle callback.  

It would be great if there was a standardized "ready" callback.

It is frustrating that the emerging [specification](http://w3c.github.io/webcomponents/spec/custom/#dfn-created-callback), edited by a Google employee, leaves the standard with the "slightly too early" createdCallback, and no standard "ready" callback.

Were it not for Google's commitment to "do no evil", I might even be a tad suspicious that they were laying the groundwork for the value-add of Polymer.  Embrace and extend, the old Microsoft strategy with standard API's.  Were I in England, and not in these here United States, I might say "plus ça change, plus c'est la même chose" in honor of my EU neighbors across the channel.

**Comment by paulie4** [comment]
The [spec](http://w3c.github.io/webcomponents/spec/custom/#dfn-created-callback) says, "For the duration of [the createdCallback] invocation, the **element is being created** flag must be set to true." It seems like for our use case, the "element is being created flag" would make more sense to be a way to hold off on the createdCallback (and all subsequent lifecycle) events to be triggered. Although, it might be simpler if the new createElement and createElementNS methods also allowed for an optional parameter that takes an object with key/value pairs holding the initial attributes the custom element should have before the createdCallback is called.

We should submit an issue here, since I don't see an existing one:
https://github.com/w3c/webcomponents/issues?q=is%3Aopen+label%3Acustom-elements+createdCallback

**Comment by evs-chris** [comment]
The spec still seems a bit of a mess as far as practicality outside of pre-rendered HTML in text form, but I _think_ the `adoptedCallback` might maybe perhaps be the solution, especially if it gets called from _all_ of the ways to create a custom element (text, createElement, constructor, any other?). It doesn't appear to be implemented really, so I'm going to close this to revisit when the spec settles - hopefully into something a bit more usable?
