### ISSUE TITLE
Setting children of computed values

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#2123]
Related to #2122: if `obj` is a computed value with a `foo` property, setting `obj.foo` should cause an error if `obj` does not have a setter function.

If `obj` _does_ have a setter, there are two possibilities:
1. an error – you should set `obj` directly
2. the setter should be called with the current value, except with the `foo` property overwritten

Of those I think I favour 1 – there's no way of knowing whether it's safe to mutate the value of `obj` from outside the computation.

**Comment by Rich-Harris** [comment]
Implemented option 1 as 732a07c1e7b926d272e31379ba01238459a6b187 on #2122

**Comment by martypdx** [comment]
Seems artificially restrictive to me, what problem is this trying to solve?

If I understand correctly, it means if I have a filtered list, I can no longer edit the items of that list:

```html
{{#each filtered(items)}}
    <li><input value='{{this.name}}'>
{{/each}}
```

**Comment by Rich-Harris** [comment]
That already fails – it just does so without warning! http://jsfiddle.net/rich_harris/by1kmhxt/. To do that you'd need to iterate over `items` then wrap the input in an `{{#if filter(this)}}` block.

**Comment by Rich-Harris** [comment]
Here's the warning you'd get with #2122:

<img width="775" alt="screen shot 2015-09-05 at 10 52 58 am" src="https://cloud.githubusercontent.com/assets/1162160/9699776/577f7878-53bc-11e5-9f0a-5caa0801aeb0.png">

**Comment by martypdx** [comment]
I understand we have the limit of not being able to map items of `items` to corresponding `filtered(items)` (someday :) ), but there are times when that limitation is fine and you just want to operate on the data tree under the computation.

I think a warning would be ok, but not an error (looks like this is the case from screenshot).  But I think the guidance is wrong, it should just warn that the computation will not notify equivalent properties of it's dependencies.

**Comment by Rich-Harris** [comment]
It *does* error if you attempt `ractive.set('computed.child', 'foo')`, the warning is only for attempted two-way binding. But it turns out the error causes a problem with a particular component edge case, so I've disabled that in #2124 anyway, at least temporarily :)

> there are times when that limitation is fine and you just want to operate on the data tree under the computation

interesting – can you elaborate? I didn't imagine there'd be a case for doing that (surely it's dangerous since you might well be mutating objects and causing the view to desync without realising it – try editing the filtered list then clicking the 'force update' button on [this updated fiddle](http://jsfiddle.net/rich_harris/rfgywg10/)), but happy to be proven wrong.

**Comment by martypdx** [comment]
@Rich-Harris Thought about it some more and given the limitations (inability) to map _through_ expressions this seems like the right way to go.

Though I think a bigger piece of the puzzle (beyond twoway binding) is educating people to use view filters instead of data filters. The later causes replacement of data through a large number of nodes whereas the former adds or removes or needed nodes. 

Along those lines, another thing I've learned is that for for frequently mutating lists `style='{{#if filter(this)}}display:none;{{/if}}'` makes a lot more sense than conditionally rendering/unrendering entire fragment.

**Comment by heavyk** [comment]
@martypdx - yes, I have begun to do the same thing. the cost for the creation and removal of elements has become very costly (a few hundred ms of freeze for long lists)... I did it differently though. I had a `let els = findAll('...', {live: true})` where I go through and update it manually. only when I need to get rid of the element, do I splice it out of the list - which is why the splice problem is such a big one for me...

I just had an epiphany!! I will just save a deleted list and keep those as display none too, that is, until I'm ready to delete the whole list!! that way my splice problem goes away.

on a related subject, do you guys know of a way to transfer an element from one list of data to another?

```js
let l1 = [{a: 1}, {a: 2}, {a: 3}]
let l2 = []
this.set('l1', l1)
this.set('l2', l2)
l2.push(l1.splice(1, 1)[0])
```

something like that, but without needing to rerender the elements for the data: `{a: 2}`

so, say something the template was something like this:
```html
<div class="unused-items">
{{#each l1}}
  <item d="{{.}}" />
{{/each l1}}
</div>

<div class="used-items">
{{#each l2}}
  <item d="{{.}}" />
{{/each l2}}
</div>
```

what I would want to do, is move the fragment from one list to the other without having to recreate the elements. does that make sense?

**Comment by martypdx** [comment]
> is move the fragment from one list to the other without having to recreate the elements. does that make sense

yep, makes sense but doesn't currently exist. :) 

Would be useful for dragging items between lists. Though I don't really have pref problem with current times for that operation. But it has caused issues with decorators getting torn down, recreated, etc.

Might be difficult to infer from api because even if you can up with something better than say: 

`ractive.move( 'list1', 3, 2 ).to( 'list2', 4);`

How do you decide what _DOM nodes_ get moved from what _section_ to what other _section_? Maybe it's not an api at all but a template semantics that gets applied during the run loop.

**Comment by heavyk** [comment]
yeah, actually I was thinking about that too, hehe... I know what I want to do, but I don't have it clear how I would write such a thing... I'm leaning against syntax altogether. we know that objects can be identified from other objects, so splicing an object out of an array can be identified if inserted back into another.

so, I like your syntax with the move, however there is an inherent problem if list2 has a different way of rendering the same data. so, my original idea actually solves the problem in a different way. there is a fragment cache linked to data objects in lists (literals don't count)... it's based on a [WeakMap](https://www.npmjs.com/package/weakmap) so there's no memory leakage either. when fragments are removed from the list, they are not discarded immediately. and, whenever data is added to a list and is also an object, we'd do the lookup on the fragment cache for the template to see if that fragment is still is located somewhere in memory. if it is, then the fragment is used instead of recreated.

for example, in the drag scenario, it's common to splice the element out of one list and put it into the other, so this would just work without any extra syntax at all. the other use case I have is a long list of elements, and I want to expand one of the elements to full screen, so right now I hack it and I set all the other elements to display none and simulate a page change - because if I delete them, then hit the back button, the browser will freeze for 100ms while rerendering the list. the template fragment cache solves both of these use cases elegantly.

the one thing I would want to have though, is some way of getting access to this cache, because for example, I'm developing a mobile app and I'd like to maintain the fragments of the home page in memory so when the user navigates away from the home screen a moment to open some other unimportant panel I don't need to rerender all that data again.

how about that?

**Comment by evs-chris** [comment]
FWIW I have used this a fair amount in my pre-0.8 projects: `{{#each some.filterAndSort.expression()}}... <input value="{{.someval}}" /> ... {{/each}}`. I was a bit surprised when I swapped out 0.7.3 for edge. I don't see any harm in allowing it with the proper warning and guidance, since it is terribly convenient for mockups. I can also appreciate that it can be a bit of a sharp edge if you're not careful.

**Comment by JonDum** [comment]
I too just ran into this trying to migrate to 0.8.x (#2330, thanks @evs-chris). We use computed props to act as aliases of sorts for when a lot of logic or other conditions determine which what item should be returned by the computed. Not being able to set anything on the returned item is a huge limiting factor.

> 2 the setter should be called with the current value, except with the foo property overwritten

 > Of those I think I favour 1 – there's no way of knowing whether it's safe to mutate the value of obj from outside the computation.

I wish I saw this back in September. I would have been a loud advocate for option 2. :)

**Comment by martypdx** [comment]
We could add an option like `computedBinding: true` that you have to _opt-in_ to use. IMO that would allow people who "know what they're doing" to have a bit more rope with which to hang themselves :grin: .

**Comment by evs-chris** [comment]
I was just looking into doing a PR for that, but I hadn't come up with a good name yet.

**Comment by JonDum** [comment]
@martypdx @evs-chris That'd work for me! I wish I could help out with these PRs without breaking everything and anything :(
