### ISSUE TITLE
Observers don't respect initially ambiguous implicit mappings

### ISSUE THREAD

**Issue by KP** [ractivejs/ractive#2142]
Observers in a child component don't work if mappings don't exist on initialization. Probably easier to show with the fiddle than explain:

http://jsfiddle.net/wpsha9ae/

**Comment by evs-chris** [comment]
Good news! Looks like it works as expected in edge.

**Comment by Rich-Harris** [comment]
Alas, not if there's any contextual ambiguity :cry: http://jsfiddle.net/rich_harris/fxoq3oxj/

**Comment by heavyk** [comment]
I think this is a dup of https://github.com/ractivejs/ractive/issues/1978

**Comment by evs-chris** [comment]
Hmmm. This is one of the areas I've always found a bit fuzzy. Are ambiguous references meant to rebind if a less ambiguous binding springs into existence after they've resolved initially? I'm particularly curious about mappings, which, if not explicit, are often the source of some strange mental gymnastics for me. I suppose my model of components probably tends more toward tighter coupling than it should.

My thought here was that perhaps ambiguities would benefit from their own model impl that could manage any retargeting for their deps. Something that could watch any relevant paths and make sure the most appropriate is used.

**Comment by Rich-Harris** [comment]
It *is* a bit fuzzy. We could make life a lot easier for ourselves by disallowing implicit mappings altogether! In my experience though that slows development down a fair bit, especially when you're in the initial phase and aren't yet sure how an app's components should be organised, since explicit mappings require you to constantly re-plumb things as you move components around.

(In the long run explicit mappings are better – data flow is easier to understand, and Ractive has slightly less work to do. And it solves situations like this one. In fact, perhaps Ractive should print a warning in debug mode suggesting explicit mappings as an optimisation whenever an implicit mapping is created. But I digress.)

Anyway:

> Are ambiguous references meant to rebind if a less ambiguous binding springs into existence after they've resolved initially?

No, mappings are immutable. As soon as it's possible to resolve an ambiguous `{{foo}}`, the mapping (between the child's root `foo` and whatever `foo` was added to some parent context) is created. It's basically the same as in a component-less template, where `{{foo}}` in `{{#with obj}}{{foo}}{{/with}}` binds to the root `foo` if available, and ignores a subsequently-added `obj.foo` property: http://jsfiddle.net/rich_harris/8p2b6u3t/

There is some relevant precedent: with an expression `{{foo()}}`, if `foo` calls `this.get('bar')` and `bar` is initially unresolved, the expression is updated when it *does* resolve. Though I've just checked and this doesn't work with components: http://jsfiddle.net/rich_harris/vhjdkg7v/
