### ISSUE TITLE
Inline partials doesn't work 

### ISSUE THREAD

**Issue by PaulMaly** [ractivejs/ractive#2150]
Hello, I try to use this code snippet:

```
<div class='gallery'>
  {{#items}}
    {{>thumbnail}}
  {{/items}}
</div>

{{#partial thumbnail}}
  <figure class='thumbnail'>
    <img src='assets/thumbnails/{{id}}.jpg'>
    <figcaption>{{description}}</figcaption>
  </figure>
{{/partial}}
```

But in console I see: Ractive.js: Could not find template for partial "thumbnail"
Latest version of RactiveJS.

Can you give some advice? Thanks!

**Comment by Madgvox** [comment]
I created a jsfiddle out of your snippet and I'm not getting an error: http://jsfiddle.net/4txrm7a7/
Can you reproduce it in jsfiddle?

**Comment by martypdx** [comment]
Partials within the template are scoped to the element in which they are defined. So if you have this it won't work:

```
<div>{{>thumbnail}}</div>
<div>{{#partial thumbnail}}partial content{{/partial}}</div>
```

**Comment by JonDum** [comment]
@martypdx Woah seriously? that's crazy! I tried exactly what @PaulMaly did, but my templats are precompiled with `ractive-loader` so I thought it was not working because of `polymer-loader`. 

Had no idea about that limitation.

**Comment by martypdx** [comment]
> Had no idea about that limitation.

It was intended as a feature :grin:. So you could scope partials and do nutty stuff like: 

```html
     <div>
      {{#partial keyword}}{{foo}}{{/partial}}
      {{#items}}
        {{>thumbnail}}
      {{/items}}
    </div>
    
    <div>
      {{#partial keyword}}{{bizz}}{{/partial}}
      {{#items}}
        {{>thumbnail}}
      {{/items}}
    </div>

    {{#partial thumbnail}}
        {{description}}-{{>keyword}}
    {{/partial}}
```

see http://jsfiddle.net/4txrm7a7/1/

**Comment by PaulMaly** [comment]
Strange feature....is this feature described in docs?

**Comment by evs-chris** [comment]
It is indeed, in the inline partials section of the [docs](http://docs.ractivejs.org/latest/partials). It's both an artifact of allowing partials to be inlined anywhere in the template and a feature that's handy for doing layouts with partials, as briefly described on that doc page.

**Comment by jmiguel-localvox** [comment]
I might have found a bug with something related to this, relevant [jsfiddle](https://jsfiddle.net/r3o7dxdh/)

The example is a bit contrived, but I don't know for sure why placing the commented on #partial inside of the div would break the application in this case.

I understand from a partial fetching viewpoint that if it can't find the partial it would break the application, but I don't know for sure why it can't find the partial if it's inside of the div. 

My suspicion is that, by placing the partial definition inside of the div, it's not registered on the component, where the Tag component would have otherwise looked to find the relevant partial.

**Comment by evs-chris** [comment]
The reason putting partial defs inside the div makes them inaccessible to the component is that partials don't currently cross component _template_ boundaries. The components find the partial def that's on the instance template because the partial is registered on the instance and components do inherit parent instance partials.
