### ISSUE TITLE
Using quotes in conditional attribute's dynamic value throws exception

### ISSUE THREAD

**Issue by andrewrota** [ractivejs/ractive#2162]
Noticed this edge case issue the other day; not sure whether it's possible to fix.  Rendering an element with a conditional attribute that has a dynamic value with quotation marks triggers an exception instead of escaping the quotation marks (as it does if it were not in a conditional section).  The exception is `Error: Failed to execute 'setAttribute' on 'Element': 'world""' is not a valid attribute name.`.

``` javascript
var ractive = new Ractive({
  el: fixture,
  template: '<span {{#if name}}class="{{name}}"{{/if}}>hello!</span>',
  data: { name: '"world"' }
});
```

Example test case here: http://jsfiddle.net/sx1mdyae/

**Comment by MartinKolarik** [comment]
I agree that this behavior is a little unfortunate and maybe unexpected, but I don't see a good way to fix it without completely changing the implementation and restricting other use cases.

Currently, the whole `{{#if}}` section is rendered as it normally would inside the element, and then parsed into individual attributes. This allows you to do stuff like this:

```html
<div {{attributeList}}>...</div>
<div {{>somePartial}}></div>
<div {{#each attrs}}{{name}}="{{value}}"{{/each}}></div>
```

... but it also means we can't escape anything, because we don't know what part of the string is the value.

I think the best thing we can do is making this clear in the documentation, and maybe add a method for escaping to the public API.

**Comment by Madgvox** [comment]
I'll label this as `better error` for now, then.

**Comment by evs-chris** [comment]
Attributes are now their own entities in conditional sections, so this is no longer an issue unless you use a partial with attributes in it.
