### ISSUE TITLE
Two way binding for custom <select> replacement (for ractive-select component)

### ISSUE THREAD

**Issue by JonDum** [ractivejs/ractive#2195]
As we're all probably aware, there's no easy way to style `<select>` element's dropdowns. I decided to do the work once and then release it as a component for everyone if they need it.

So I've got [ractive-select](https://github.com/JonDum/ractive-select) going on now and it's neat that it works as a drop-in replacement for any existing `<select>`'s if you do

``` js
components: {
   select: require('ractive-select')
}
```

then in your template:

``` html
<select class='foo' value='{{thing}}'>
   <option>1</option>
   <option>2</option>
   <option>3</option>
</select>
```

results in a dom like this:

``` html
<div class='ractive-select foo'>
    Select ...
    <div class='icon'></div>
    <div class='dropdown'>
       <option>1</option>
       <option>2</option>
       <option>3</option>
    </div>
</div>
```

Which allows much greater freedom to style.

My goal is to make it work exactly the same as a select. I noticed there's a bunch of stuff in [SingleSelectBinding.js](https://github.com/ractivejs/ractive/blob/dev/src/view/items/element/binding/SingleSelectBinding.js), to handle updates to the options. Is there anyway I can get a reference to that binding without a select element to use those methods to update the `<option>` tags in the dropdown? 

Trying to avoid duplicating the bulk of that logic to keep the `<options>` in sync. That'd be a waste of kb! :)

**Comment by fskreuz** [comment]
Aren't components recommended to have a dash in their name (which means the name is at least 2 words) so that they won't conflict with any native elements? Not sure about the effects of using `<option>` outside `<select>` tho, or how the browser might treat it.

**Comment by JonDum** [comment]
> Aren't components recommended to have a dash in their name (which means the name is at least 2 words) so that they won't conflict with any native elements

You're thinking of Web Components / Polymer shit. Since it's just a ractive template, ractive replaces the `<select>` with whatever you want, so it's like an alias/partial/drop-in. 

 > Not sure about the effects of using <option> outside <select> tho, or how the browser might treat it.

There's no side effect really. They just render as display block elements.

**Comment by heavyk** [comment]
you're both right. custom components (that is, anything registered with `document.registerElement`) must use a dash to (because, all non-dashed names are reserved for non-custom components, I guess).

however, since day one, you can call `document.createElement('caca')` and have an element of caca in your website. it will be a basic block element and you can indeed style it up just as if it were a div. I think there were incompatibilities with old IE and so that's why it's shunned, but you always could ... though what makes it not-special, is your caca element won't have the custom components lifecycle events until you define them with `document.registerElement` and then they finally become a "web component"

**Comment by bryansray** [comment]
I'd love to see a component like this. One thing to be aware of would be support for HTML5 validation? 

Based on your components current dom markup, I'm not sure how you would support the "required" attribute. As far as I know, that attribute only works on actual form controls. This may require you to put some sort of text input in to your markup so that the browsers all work out of the box with a component like this.

**Comment by JonDum** [comment]
@bryansray I would have to manually add support for that along with other attributes like I did in (ractive-autosize-input](https://github.com/JonDum/ractive-autosize-input/blob/master/src/template.html). Sadly, until you can fully style form elements, you are forced to recreate them with javascript and that means you can't use the fancy `:valid` and `:invalid` selectors. So I still use normal classes `.valid`, `.invalid`, etc.

**Comment by evs-chris** [comment]
After a year, I'm gonna say it's safe to close this. If not, please feel free to reopen. Also not that there's an open issue for a collection of ui components at #2763 :smile:
