### ISSUE TITLE
Unexpected function call (in partial context)

### ISSUE THREAD

**Issue by woodlandhunter** [ractivejs/ractive#2224]
See the attached fiddle. `someFunc` is called (with undefined as the argument) when `foo` is set to `null`

http://jsfiddle.net/j3mjdf0m/

**Comment by Rich-Harris** [comment]
Some breadcrumbs: it turns out the function is being called indirectly as a result of a `clearUnresolveds` call, via [here](https://github.com/ractivejs/ractive/blob/gh-2224/src/model/Model.js#L176). The thing that's unresolved is the name of the partial. It looks like the resolver gets created to try and find a value for `test-partial` even though it's a) a named partial, and b) the name wouldn't be a valid reference.

Have opened a branch with a failing test: https://github.com/ractivejs/ractive/tree/gh-2224

**Comment by evs-chris** [comment]
Looks like the partial with context bit can be more-or-less fixed, but since it's just a `{{#with}}` wrapped around the partial, any other unresolved inside a side-effecting `{{#with}}` is going to have the same issue.

It looks like if we made the expression proxy aware of its rendered state somehow, we could avoid the recomputation since it should go out of scope with the wrapping conditional. I didn't see a quick and easy way to do so though, since those are a sort of hybrid model fragment beastie. My inner-functional-snob say just don't side-effect like that :smile:

At any rate...

```diff
diff --git a/src/view/items/Partial.js b/src/view/items/Partial.js
index b4b4eaf..7c6371e 100644
--- a/src/view/items/Partial.js
+++ b/src/view/items/Partial.js
@@ -5,8 +5,6 @@ import getPartialTemplate from './partial/getPartialTemplate';

 export default class Partial extends Mustache {
        bind () {
-               super.bind();
-
                // keep track of the reference name for future resets
                this.refName = this.template.r;

@@ -16,10 +14,13 @@ export default class Partial extends Mustache {
                if ( template ) {
                        this.named = true;
                        this.setTemplate( this.template.r, template );
-               } else if ( ( !this.model || typeof this.model.get() !== 'string' ) && this.refName ) {
-                       this.setTemplate( this.refName, template );
                } else {
-                       this.setTemplate( this.model.get() );
+                       super.bind();
+                       if ( ( !this.model || typeof this.model.get() !== 'string' ) && this.refName ) {
+                               this.setTemplate( this.refName, template );
+                       } else {
+                               this.setTemplate( this.model.get() );
+                       }
                }

                this.fragment = new Fragment({
```

**Comment by evs-chris** [comment]
Fixed :smile:
