### ISSUE TITLE
 Additional option on observer?

### ISSUE THREAD

**Issue by vujovicigor** [ractivejs/ractive#2241]
Hi.
Is is possible to have additional option on observer
witch will force observer to notify updates when same value is assigned.

I use data mapping to exchange data between components, and it works great,
but sometimes I need to force refresh.

example:
      this.set('someprop', 5);
      this.set('someprop', 5); <-- I need observer to trigger again

Thanks for great work.

**Comment by fskreuz** [comment]
Why would you want this? Could you provide a bit more context to your situation, like what the observer actually does or what you're trying to achieve? I believe you're trying to solve the wrong problem, and a bit of context might help us provide an alternate solution.

**Comment by Rich-Harris** [comment]
Just to add to what @fskreuz said, this is actually trickier to implement than you might imagine – it's not the the observer *ignores* updates that result in the same value, it's that the observer is never triggered, because Ractive immediately recognises that there's no change to propagate. (This saves a lot work, e.g. in the form of unnecessary DOM manipulation.)

**Comment by vujovicigor** [comment]
Thank you, that is fine, just asking :)
I solved my problems with additional data member: add('refresh'), 
so now my observer is 
this.observe('propertyToObserve refresh')...

Thanks.
