### ISSUE TITLE
Another "Failed to compute"/TypeError: _0 is undefined

### ISSUE THREAD

**Issue by woodlandhunter** [ractivejs/ractive#2259]
Similar to #2092, which was previously fixed

Press one of the delete links in the fiddle to see the error:

http://jsfiddle.net/9120ev47/

**Comment by JonDum** [comment]
This looks like a regression.... Again. Ractive is re-computing indexes that don't exist anymore.

For a workaround to avoid the error do a check:

 `<td>{{id && .id.toFixed(2)}}</td>`

But this totally shouldn't be happening in the first place. :|

**Comment by Madgvox** [comment]
I'm fairly certain this is the same issue as #1879.

**Comment by heavyk** [comment]
I don't believe it is, because this one works in 0.7.3 and #1879 does not. (#1879 doesn't work in either)

additionally #1879 gives a different error in edge: `Failed to compute @@undefined[0]\.b: Cannot read property '0' of undefined`

**Comment by Madgvox** [comment]
I found something that may be of note; when the last index is deleted, no error occurs: http://jsfiddle.net/9120ev47/1/

**Comment by Rich-Harris** [comment]
The offending line is [here](https://github.com/ractivejs/ractive/blob/08c05d2d23fa48dbe9a8856a1c785d7288883a44/src/view/items/shared/Mustache.js#L53) – the `{{.id.toFixed(2)}}` mustache is trying to save itself the trouble of unnecessarily updating following the rebind. Commenting it out and replacing [this line](https://github.com/ractivejs/ractive/blob/08c05d2d23fa48dbe9a8856a1c785d7288883a44/src/view/items/shared/Mustache.js#L60) with `this.handleChange()` fixes the issue (and doesn't break any tests), because the computation is allowed to update lazily as per the design. 

The trade-off is that we'll mark sections of the virtual DOM tree as dirty unnecessarily, and touch the real DOM without actually changing anything. Perhaps the mustache itself can keep track of its current value to avoid the need for that premature computation.

**Comment by Rich-Harris** [comment]
On reflection, the savings from preventing unnecessary updates probably aren't worth the additional book-keeping (since it's only the 'dirty' parts of the list section that get triggered at that point), so I'm going to go ahead and propose that as the solution. PR inbound
