### ISSUE TITLE
unable to proxy composition events

### ISSUE THREAD

**Issue by jcppman** [ractivejs/ractive#2263]
[Composition events](https://developer.mozilla.org/en-US/docs/Web/API/CompositionEvent) are not proxied.

- Ractive version: 0.7.3
- Browser: Chrome 46
- Template: 

```
<textarea on-click="clk" on-compositionstart="cps"></textarea>
```

- JS:

```
ractive.on('clk', function(){
  console.log("I am clicked");
});
ractive.on('cps', function(){
  console.log("composition started");
});
```

When click the element, "clk" is triggered as expected, when switch to accent-based input method (like Chinese or Japanese) and start composition, "cps" is not triggered.

**Comment by Madgvox** [comment]
I don't have the ability to easily test this myself, so could you check whether this occurs on 0.8-edge? The easiest way to do that would be to create a [jsfiddle](http://jsfiddle.net). You can load 0.8-edge from the dropdown on the left. My initial guess would that it will reproduce, but I want to be sure.

**Comment by Rich-Harris** [comment]
It works for me in Chrome and Firefox using @Madgvox's fiddle – it shows the missing plugin warning (because the `<textarea>` doesn't have an `oncomposition` property, which is [how Ractive detects support for that event](https://github.com/ractivejs/ractive/blob/46848c9f845ea7591a406f8e5b39b4af4652f5e1/src/view/items/element/ElementEvents.js#L20-L22) – we could potentially add some special case logic), but once I switch input method to e.g. Hiragana and start typing, it logs 'composition started' as expected. Can you reproduce the issue in a fiddle?

**Comment by jcppman** [comment]
Hi, thanks for the quick response. 

For some reason http://cdn.ractivejs.org/ is unreachable so I can't check it using the fiddle above.

I tried Hiragana on my local env with RactiveJs 0.7.3 and still can not get 'composition started' on Safari, Firefox & Chrome. 

I'll try the fiddle once cdn is back :)

**Comment by jcppman** [comment]
yeah with 0.8.0-edge I can not reproduce this issue, compositionstart is well triggered!

**Comment by Madgvox** [comment]
Great! :+1:
