### ISSUE TITLE
Can I create a singleton partial? 

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#2268]
Can I create a partial that will include its content into the document if it is used one or more times, and does nothing if it is not used? 

My usecase: 

```
{{#partial the-modal}}
    <div id="the-modal">.....</div>
{{/partial}}

{{#partial my-dialog}}
    {{>button-that-creates-a-content-into-the-modal }}
    {{>the-modal}}
{{/partial}}

{{>my-dialog}}
...

{{>my-dialog}}
...

{{>my-dialog}}
...
```
...which should create 3 buttons but only one `<div id="the-modal">.....</div>` node in the document.

**Comment by Madgvox** [comment]
The immediate problem I see with that is where should the partial go? Does it get attached to the first one? The last one? It'd be way too easy to get unexpected behavior. Plus, what happens if you want more than one modal to be displayed at a time? You'd have to create an entirely new partial for each modal. It gets ugly very fast.

There are much more flexible methods to create a modal behavior with ractive. My personal favorite is probably creating a modal component. Then I can reuse it anywhere, and since the modal behavior is encapsulated within a component, it's much easier to create more instances of the modal if I need them.

```js
var Modal = Ractive.extend({
  //...
  show: function ( text ) {
    // show the modal
  },
  hide: function () {
    // hide the modal
  }
});

// then in my app...
var app = new Ractive({
  // ...
  components: {
    'modal': Modal
  }
});

// I can then use findComponent to get the instance of the modal in the app...
var pageModal = app.findCompoent( 'modal' );
// ... and access its methods
pageModal.show( 'foo bar baz' );
```

**Comment by ceremcem** [comment]
Although the modal would be hidden, it's not important where it appears first in the document but yes, this use case seems very uncommon. I have implemented your suggestion [in another way](https://github.com/ceremcem/aktos-website/blob/fix-nav-bar/app/partials/scada-edit/widget.jade). Thank you.
