### ISSUE TITLE
Error: call to Function() blocked by CSP

### ISSUE THREAD

**Issue by 3demax** [ractivejs/ractive#2286]
Hi everyone! I'm trying to use Ractive in my applicaton for FirefoxOS.
The problem is that FxOS have strict CSP for privileged apps:
```
Firefox OS and the Web runtimes for Android and desktops enforces the following CSP for privileged apps:

"default-src *; script-src 'self'; object-src 'none'; style-src 'self' 'unsafe-inline'"
```
That's why I get "Error: call to Function() blocked by CSP" while trying to create Ractive object.
Therefore, question emerges:
*Are there any possibilities to avoid using calls to Function in Ractive?*

**Comment by JonDum** [comment]
> Error: call to Function() blocked by CSP

Oh god seriously? That's like the core of Ractive's expressions.

**Comment by fskreuz** [comment]
Yup. Been there before. Also, FirefoxOS CSP cannot be "relaxed" so you can't really allow privileged apps to use `Function` or `eval`. There's no way getting around it aside from Ractive using something other than `Function`.

**Comment by heavyk** [comment]
you can use unsafe-eval for chome apps. it worked for me

**Comment by fskreuz** [comment]
Mozilla has a really spread out documentation regarding CSP. Finally found one that summarizes the ones regarding the apps: https://developer.mozilla.org/en-US/Apps/Build/Building_apps_for_Firefox_OS/CSP#Applicable_CSP_Restrictions

> **eval is disallowed**
You may not use the eval() function or the eval operator. Both will throw security errors.

> **The function constructor is banned**
You may not use the Function() constructor. Using it will throw a security error.

> **Dynamic code execution with setTimeout and setInterval is banned**
You MUST pass callable objects (i.e.: functions) to the setTimeout and setInterval functions. Passing strings will not create the timer and the function will return 0.

Further down:

> **My templates aren't being rendered in my privileged packaged app.**
If you're using a client-side templating library (such as Mustache or Nunjucks), you must ensure that you're precompiling your templates. This means that you must run a script to compile your templates from HTML to JavaScript before packaging your app. Privileged apps cannot use remote loaders that download and compile templates on the fly because the compiler uses eval() or new Function().

> **I set the CSP in my manifest to allow the use of [feature], but it still doesn't work.**
*You cannot loosen the default restrictions on privileged or certified packaged apps*. The CSP field in the app manifest can only be used to tighten the CSP, not loosen it.

**Comment by JonDum** [comment]
> My templates aren't being rendered in my privileged packaged app.
If you're using a client-side templating library (such as Mustache or Nunjucks), you must ensure that you're precompiling your templates. This means that you must run a script to compile your templates from HTML to JavaScript before packaging your app. Privileged apps cannot use remote loaders that download and compile templates on the fly because the compiler uses eval() or new Function().

I may be mistaken, but ractive doesn't create the functions for expressions until the template is about to be rendered, right? I've never seen any functions in pre-parsed templates.

**Comment by fskreuz** [comment]
iirc, pre-parsed templates carry the trimmed down expressions (the ones that look like `_0 +_1`). They are inert in that form. Not sure exactly when, but Ractive "revives" them by enclosing it in `Function`, and caches the function created.

```
JSON.stringify(Ractive.parse('{{ foo + bar }}'))
// {"v":3,"t":[{"t":2,"x":{"r":["foo","bar"],"s":"_0+_1"}}]}
```

**Comment by JonDum** [comment]
So *theoretically*, we could replace the `"s"` representation of the expression with an id, and store a cache of already parsed functions on the template?

Something like this? 

```
{
    v: 4,
    fn: [
        function(_0,_1) { return _0 + _1 },
        function(_0,_1) { return _0 * _1 }
    ]
    t: [
        {
            t: 2,
            x: {
                r: ['foo', 'bar'], // {{ foo + bar }} 
                s: '0'
            }
        }
        {
            t: 2,
            x: {
                r: ['foo', 2], // {{ foo + 2 }}
                s: '0'
            }
        },
        {
            t: 2,
            x: {
                r: ['foo', 2], {{ foo * 2 }}
                s: '1'
            }
        }
     ]
}
```

**Comment by MartinKolarik** [comment]
@JonDum not only theoretically; it's already been discussed a few times before, but we never got to implementing it.

PR's on its way.

**Comment by MartinKolarik** [comment]
Closing as this feature is now available in edge - if you pre-compile your templates, `new Function()` won't be used at runtime.
