### ISSUE TITLE
Observers, computed, decorators and `node.style` do not get along

### ISSUE THREAD

**Issue by JonDum** [ractivejs/ractive#2312]
Was doing some investigating about all the weirdness that happens using the `model` suggestion from #2166 (I think these two bugs are related so I'm putting them in one).

---

http://plnkr.co/edit/DsE1vzrjTUL078IzQ97s?p=preview
- Hit the "move" button then hit the  "delete" button. Notice that the "three" box is now slowly animating when it should never have gotten an "x" value. This doesn't happen for the "direct" approach. I think Ractive is recycling the DOM node? If you run `app.findAllComponents()[1].get()` the `model` object still has a name of "two" (it didn't get deleted?), but if you run `app.findAllComponents()[1].get('model.name')`it returns "three". :confused: 

---

http://plnkr.co/edit/N4GEj1KpvKFv3NDcPlyb?p=preview

Same plunk, but the only difference is that I've removed the entire `style="left:{{x}}px"` attribute on the component div and added an observer to change the color green when `x` changes.

In this case all of the computed nodes turn green when only the second item should be changing. It works correctly for the direct nodes.

**Comment by martypdx** [comment]
> This doesn't happen for the "direct" approach. I think Ractive is recycling the DOM node?

Correct. When a new array is "set" Ractive reuses the dom nodes. When the array is "sliced` (or any equivalent) the corresponding DOM nodes are removed.

So the "direct" case gets sliced and those (more minimal) changes are propagted selectively (remove node TWO). But the computed property is more coarse as Ractive treats the entire array as having changed.

Rative could call `merge` on computed properties of type array that change, but there's no way to specify merge comparator options.

Generally, I think best bet is to move filtering logic into the template, rather than returning a whole separate array via computed properties

Alternatively You can use an observer instead and then use `merge`: http://plnkr.co/edit/DAE68GKRZc7OhGR64dLZ?p=preview

I'm removing the bug label in favor of better docs, because I don't see anything not working in a way that we would change it, though arguably it's not as expected.

**Comment by JonDum** [comment]
> Generally, I think best bet is to move filtering logic into the template, rather than returning a whole separate array via computed properties

That's the whole point of computed properties for me though: to move that logic outside the template because it's too complicated. I usually end up with things like filtering, sorting returning default values and a slew of other things in a computed prop's function and a simple `{{# items}}` in the template. But ractive does not play nice with computed arrays in these cases.

---

```
              this.observe('comps', function(comps) {
                  this.merge('items', comps.slice());
              });
```

Totally would never have thought to do it that way, but it seems to work much better than computed. Now I'm going to have a bunch of observers instead of nice clean computed props :confounded:

**Comment by martypdx** [comment]
> Now I'm going to have a bunch of observers instead of nice clean computed props

I've been thinking about the array case as well, that's why I mentioned:

> Rative could call merge on computed properties of type array that change, but there's no way to specify merge comparator options.

Could be added to the property same way we do `get` and `set`:

```js
    computed: {
            items: {
                base: 'comps',
                filter: function(comps){
                    return comps.filter(...);
                }
            }
     },
```

Just a strawman API, but could also potentially allow binding to individual items of array.

**Comment by JonDum** [comment]
Would there be no way to correctly diff the computed array from its previous value?

My perception has been that any time an array changes, ractive would be able to figure out the differences and smartly update the dom as needed. That's probably why I've literally never used `merge` before, since I just assumed that ractive did some black magic to figure out the differences after a `set`.

**Comment by evs-chris** [comment]
0.9 seems to be behaving much better. The only weird part is the green decorator sticking around on the second element, but that tracks with what is supported right now. I'm going to punt the discussion of better sorting to #2599 and #2947
