### ISSUE TITLE
Publish edge to NPM

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractive#2326]
```
npm ERR! notarget No compatible version found: ractive@'>=0.8.0 <0.9.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.2.0","0.2.1","0.2.2","0.3.0","0.3.1","0.3.2","0.3.3","0.3.4","0.3.5","0.3.7","0.3.8","0.3.9","0.4.0-pre1","0.4.0-pre2","0.4.0","0.5.0","0.5.1","0.5.2","0.5.3","0.5.4","0.5.5","0.5.6","0.5.7","0.5.8","0.6.0","0.6.1","0.7.0-edge","0.7.0","0.7.1","0.7.2","0.7.3"]
```

Just moved to npm from Bower for my dependencies (because Gobble and Rollup rocks!), but Ractive doesn't have edge (0.8) on npm. :'(

**Comment by fskreuz** [comment]
Worked around using a git url `git://github.com/ractivejs/ractive.git#edge`. Still would be nice to have it published like in Bower.

**Comment by Rich-Harris** [comment]
> Just moved to npm from Bower for my dependencies

Welcome to the light! 

> Worked around using a git url git://github.com/ractivejs/ractive.git#edge

Yeah, that's what I do as well (or I pick a specific commit hash from https://github.com/ractivejs/ractive/commits/build). The trouble is that even though npm allows you to tag releases as something other than `latest` (so `npm i ractive` doesn't install the edge version), it doesn't let you publish over an existing version, so it wouldn't be possible to install `ractive@0.8.0-edge`.

Maybe we could always update the version to be `0.8.0-[commithash]` and then do `npm publish --tag edge`, so that you could do `npm install ractive@edge`? Does anyone knowledgable about npm know if that would work as expected, or do version numbers need to increase even you tag them?

**Comment by JonDum** [comment]
You are totally on the fringe of knowledge on npm. ;)

I think the git url as a dep works fairly well and is consistent with
something that changes frequently. Getting npm i ractive@edge working may
be more trouble than the sugar is worth?

**Comment by fskreuz** [comment]
I'll close this. The thought was nice back then. Now it doesn't seem to make sense. :smile: .
