### ISSUE TITLE
'this' references window with Ractive.set's promise

### ISSUE THREAD

**Issue by sabob** [ractivejs/ractive#2338]
Hi all,

Wish everybody a great new year.

When using ractive.set().then(function() { 
this == window 
}

Would it not be better (if possible) for 'this' to still reference the ractive instance?

Here is a fiddle, check the console output:
https://jsfiddle.net/sabob/utLpgtut/

Kind regards

Bob

**Comment by fskreuz** [comment]
Native promises have their context set to `window` (I just tried the following with Chrome). Not sure if we want this behavior to change, as the promises may be hooked to generic resolve/reject handlers that expect `this` as `window`.

```js
Promise.resolve('test').then(v => console.log(this)) // Window
```

**Comment by martypdx** [comment]
As @fskreuz mentions, Promise callbacks come from global land, so not sure we can do much about that.

Presumably, if you're using Promises, which are an ES6 feature, then you have access to fat arrow functions which don't have a context and thus use the calling context:

```js
this.set("name", "James").then( () => {
    console.log("this", this); // now `this` is ractive instance!
});
```

Otherwise you're back to manual binding via `function(){}.bind(this)` or aliasing `var self = this;`.

**Comment by sabob** [comment]
Thanks for the response, very helpful.

As I'm not using es6, I'll just use the 'var that = this' workaround.

Kind regards

Bob
