### ISSUE TITLE
Problem with comma decimal numbers and input type number

### ISSUE THREAD

**Issue by espkal** [ractivejs/ractive#2360]
It looks like there is a bug when binding a decimal number to a input type number in IE10+ and Edge. 
Example: http://codepen.io/anon/pen/JGLgPL

When typing a decimal number with comma as decimal separator in IE the number will be floored. Meanwhile in Edge the number will be set to nothing.

**Comment by petterek** [comment]
In chrome the norwegain , does not work in either of the inputs

**Comment by sabob** [comment]
Don't think this is a Ractive bug. 

When using input type=number, the browser won't return a value if the input is invalid. Depending on your locale number might accept periods or commas. If you want to enter _invalid_ numbers and have Ractive bind it, you can use input=text and process and validate it yourself.

Kind regards

Bob

**Comment by MartinKolarik** [comment]
It seems both latest IE and Edge only allow period as a separator, regardless of the locate.

**Comment by Madgvox** [comment]
This has to do with the input box itself, not ractive's implementation of it. The implementation seems to vary between browsers, with firefox being the most flexible. I'm not sure if the period and comma working / not working would flip if your region is different (this is with a US region). If @petterek is anything to go by, it doesn't appear to.

| Input | Firefox | Chrome | IE | Edge | Safari
| ------- | --------- | ----------- | --- | ------- | -------
| 123 | ✔ | ✔ | ✔ | ✔ | ✔
| 123.45 | ✔ | ✔ | ✔ | ✔ | ✔
| 123,45 | ✔ | | | ? | 
| 123,456.78 | ✔ | | | ? |
| 123.456,78 | ✔ | | | ? |
| 10e-1 | ✔ | ✔ | ✔ | ✔ | ✔

Edge has a few question marks because I wasn't able to test it myself.

I would take @sabob's suggestion and use a `type=text` instead.

**Comment by MartinKolarik** [comment]
>I'm not sure if the period and comma working / not working would flip if your region is different (this is with a US region). If @petterek is anything to go by, it doesn't appear to.

It does, at least in Chrome. Also, if I type `123.45`  in FF it's automatically changed to `123,45`. Bottom line, it's browser dependent. If you need to be in control, use a `type=text`.

**Comment by MartinKolarik** [comment]
@Madgvox yes, for Edge it's the same as IE.

**Comment by martypdx** [comment]
Related: when I set my regional settings, the number inputs work correctly, but the templated `{{value}}` is showing with the `.`. Are we using `.toString()` when we should be using `.toLocaleString()` or some equivalent?  Messing with js in console, it doesn't appear to use the setting by default.
