### ISSUE TITLE
Official Meteor support

### ISSUE THREAD

**Issue by eliezedeck** [ractivejs/ractive#2370]
I have always found that Ractive is better in all the use cases that I have ever encountered. And performance-wise, it's just amazing. There are many plus to using Ractive, in my opinion against using React or Blaze.

Meteor seems to be a very nice platform that could benefit from Ractive. I have seen some integration, but most of them are not a full integration with Meteor and running as package. There is even a repo in the Meteor project that seems to indicate that Ractive had something to do with Meteor in the past, but I'm not sure as to where things went afterwards.

How about adding **official support for Meteor**? Taking advantage of all the _data reactivity_ that this platform offers?

Is there any project aiming towards this?

**Comment by JonDum** [comment]
I don't think that's on the agenda of any of the core team. I would imagine that's more of a thing to implement on the Meteor side, but that's what their Blaze is for.

**Comment by eliezedeck** [comment]
I agree.

The reason I have posted it here, is that, like I said before, Ractive seems to have already been in their repo in the past. Meaning that they probably have already considered Ractive but for some reason it has been abandoned.

Even though Blaze is similar in Ractive, I do not think it's anywhere near the capabilities of Ractive. Well that's debatable, that is my opinion.

Ractive is a freaking great library, and everytime I use Blaze, I just wished it was Ractive instead.

**Comment by fskreuz** [comment]
FWIW, it was because of (running away from) Meteor that I bumped into Ractive. Ractive was the closest thing to Meteor sans the server. Easier to integrate with existing servers and stuff.

Not entirely sure what changed since then (was 0.6 that time, sooo beta), but if I remember correctly, Meteor uses some kind of JSON-based protocol over websockets. In Ractive, one can simply write an [adaptor](http://docs.ractivejs.org/latest/adaptors) that talks to that server. Adaptors are essentially data translation plugins which can be written separately from core Ractive, can be written by anyone and can be made to talk to any data layer whose data can be translated into a POJO.

**Comment by eliezedeck** [comment]
As of now, Meteor is at 1.2.1 and things have changed a lot. I actually really like the Meteor server part, it's now the templating engine which I find kinda limited.

@fskreuz Thanks for mentioning the adaptor thing. I'll see what can be done.
