### ISSUE TITLE
Request: expression functions outside of data!

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#2392]
Hi,

I know this has been brought forward several times already, but this is one more humble request to move expression functions outside of data. For example in ractive root scope, like for method calls. Thanks for consideration.

**Comment by evs-chris** [comment]
I don't think it's feasible to move all expressions out of data, because then you don't have access to stuff like `{{ .name.toUpperCase() }}`. But starting with 0.8, you will be able to use `@ractive` to get at your Ractive instance from the template. So you could hang whatever you'd like off of your instance, or even the root instance from inside a component (`@ractive.root`), and access it from the template without mucking about in your data.

**Comment by martypdx** [comment]
What @evs-chris said. The creation of "state" parallel to "data" was designed to handle this type of use case:

```js
// "global" functions:
Ractive.prototype.formatFoo = function( foo ) { return foo + '!' };

// "instance" functions (components too on extend)
new Ractive({
    // ...
    template: `
        {{#each item in items}}
            <li>{{ @ractive.upperCase( item.name ) }}</li>
        {{/each}}`,
    data: {
        items: [ ... ]
    },
    upperCase( str ) {
         return str.toUpperCase();
    }
})
```

fyi - Some discussion happening on #2386 as to alternate tokens for `@ractive`
