### ISSUE TITLE
Why does Ractive ship its own polyfills?

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractive#2393]
I know it's for older IE but...

- Why does Ractive implement its own polyfills? Why not bundle in [es5-shim](https://github.com/es-shims/es5-shim), [es6-promise](https://github.com/stefanpenner/es6-promise) and others?

- Can the polyfills/shims be moved out into a separate, optional file? That way, the core of Ractive is kept "modern" while those who want to support older browsers can just add this optional file.

- Some shims/polyfills are in `legacy.js` while others are under `utils` (Promise, rAF etc.). Makes me wonder why.

Just wondering if it's possible to offload the work to other libs and/or shed a few lines of code and/or do some code reorganization.

**Comment by evs-chris** [comment]
@Rich-Harris actually started working on dropping the legacy stuff and setting it up to bring your own polyfill in #2131. I think they were originally included because the polyfill scene was not awesome, and good IE8 support was _really_ important.

I'd say the polyfill scene is much better now, and I can't speak for everyone, but since the beginning of the year, we (people I write stuff for) no longer support IE < 10. I think those two add up to not needing a special pre-polyfilled legacy build.
