### ISSUE TITLE
Progressive enhancement with triple mustaches doesn't work

### ISSUE THREAD

**Issue by monoblaine** [ractivejs/ractive#2403]
I think the progressive enhancement feature has some problems regarding triple mustaches.

The following example (http://jsfiddle.net/monoblaine/h516ecvz/1/) runs fine:

``` js
setTimeout(() => new Ractive({
    el: 'ractivable-el',
    template: '{{txt}}',
    enhance: true,
    data: { txt: 'Hello!' }
}), 6000);
```

This one (http://jsfiddle.net/monoblaine/tqhs0bmb/1/), however, unnecessarily recreates the text node: (not the best example for triple mustaches, I know)

``` js
setTimeout(() => new Ractive({
    el: 'ractivable-el',
    template: '{{{txt}}}',
    enhance: true,
    data: { txt: 'Hello!' }
}), 6000);
```

**Comment by evs-chris** [comment]
Triple mustaches and progressive enhancement together are problematic conceptually too. We can probably fix the text node issue with triple mustaches, but I don't think their actual use-case will work with with progressive enhancement - at least not as it exists now. Since there are likely tags inside the triple, it would have to render itself to a document fragment, then match the actual DOM with the fragment DOM and try to correct as it went. Is that better than throwing in the rendered fragment and stripping out the leftover tags on the way to the next element?

**Comment by martypdx** [comment]
What about an `.innerHtml` type compare for triples? Broad try to see if html is same.

**Comment by evs-chris** [comment]
Ah, but `.innerHTML` on what? Triples may be other-thing™ adjacent.

**Comment by monoblaine** [comment]
> Is that better than throwing in the rendered fragment and stripping out the leftover tags on the way to the next element?

I can't say anything about this, but if implementing it isn't worth the trouble (or the performance benefit, if any) using triple mustaches may be discouraged for those who are obsessed with progressive enhancement.
