### ISSUE TITLE
Bug: @index incorrectly 

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#2422]
Hi,

in the process of chasing a bug (not yet able to isolate), I nevertheless managed to isolate another one:

http://jsfiddle.net/txptg3bz/4/

The line: `<span style="margin-left:{{50*(@index)}}px;">{{.}}</span>` "breaks" and appear to render based on a wrong index after a splice. This works with latest, but breaks on edge.

**Comment by evs-chris** [comment]
I feel like this is probably my fault and the result of changes made to speed up splicing for big iterative sections. I'm a bit swamped right now, but I'll get round to it shortly. Sorry.

**Comment by dagnelies** [comment]
No biggy, take your time. We all have just two hands and one head.

**Comment by evs-chris** [comment]
I've tracked this back to an issue with rebinding attributes that depend on an expression with an index ref, so it wasn't me after all :smile:. What's happening is the attribute isn't a mustache, so it doesn't rebind directly. Instead it delegates to its fragment. Since it doesn't have a model to check for a change, it doesn't know that it changed. It seems like the best way forward is to check the attribute value on rebind to see if an update is in order, but I'm not sure. An alternate would be to have a proper rebind for attributes, which would get them to update with their fragment if something actually changes, though I suppose that's not really too different than just doing a value check.

**Comment by dagnelies** [comment]
Well, you're the expert here. ;) I sometimes try to look into the sources but I'm quickly lost there. I'd just pick the safest, simplest, straightforward solution.

**Comment by dagnelies** [comment]
thanks! :+1:
