### ISSUE TITLE
Bug: input field and data gets updated despite it shouldn't

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#2427]
Hi,

As usual, here is the fiddle:

http://jsfiddle.net/xc2o8y08/31/

The other input field (and data) sometimes get updated despite it shouldn't. Note that the behavior is rather odd. If the text of the input fields is the same, they'll get updated (and the data too), but only some of them, and only those "after" it.

This concerns both latest and edge.

**Comment by dagnelies** [comment]
There is some kind of loopback effect here. Because the data changed, the sorting is triggered again, then it seems the data is set again, despite it shouldn't.

**Comment by evs-chris** [comment]
I've tracked this back to a locking issue that will hopefully get resolved along with all of the observer issues. What's happening is the element is being updated and locked while the computation is also taking place, so the correct value gets shuffled down to its new location while its replacement can't update the locked element.

**Comment by evs-chris** [comment]
I was trying to come up with an alternate fix for this, and I think I found a reasonable one that fails part of a test for #771. The fix is to change locking from a boolean to an equality check against the value set in the binding - so in binding `this.attribute.lock = value` and in update delegate `if (this.lock !== value)`.

The [failing test](https://github.com/ractivejs/ractive/blob/dev/test/browser-tests/twoway.js#L422) is expecting the value not to update when the observer sets it because it is locked. Only the first assertion fails because the value gets set to `BAR` when the lock is expecting it to be `bar` and thus allows it to change. The rest of the test seems to be fine.

*I* think that this test case is a bit bizarre because it expects the model and view to be out of sync on purpose. It seems like modifying an input with an observer should be handled by a lazy binding, which is now possible at the element level. Locking is still required because without it, the value gets reset with every char on non-lazy bindings, which makes the cursor jump to the  beginning.

So, I would propose that we drop support for observers getting the model and view out of sync in favor of lazy bindings and locking with the value instead of a non-specific true/false. Thoughts?

**Comment by martypdx** [comment]
> modifying an input with an observer should be handled by a lazy binding

What does that mean? Can you explain "handling by a lazy binding"?

**Comment by evs-chris** [comment]
I'll see if I can ramble through it :smile:

The current behavior, which the test relies on, is:

1. a non-lazy two-way binding causes an update to the model (say, the user typed 'f')
2. the observer for that value then fires and also updates the model (toUpperCase - so 'F' is now in the model)
3. the time to update the attribute rolls around, and it is locked, so the attribute keeps its original value ('f')

I think that behavior was added because laziness wasn't readily available for a single input and without it, every character typed would update the input value, making the cursor jump back to the beginning of the input.

With a lazy binding, the model isn't updated until the input loses focus (or a timeout), so the model and input don't have an opportunity to get out of sync:

1. the lazy binding effectively buffers the user input (say 'foo')
2. the binding gets round to firing, which triggers the observer that updates the model (toUpperCase, so now the model is 'FOO')
3. there's no danger of messing up the input by making the cursor jump, so the value can be safely updated to match the model ('FOO')

My question is should we modify the behavior of bindings to keep the jumpiness of the cursor at bay only if the value stays the same from the binding getting a change to the update being called on the bound attribute. That would eliminate the class of binding bug found in this issue, but it also breaks observers that expect to be able to update the model without having the binding that fired them (and that shares the same mode) update as well.

**Comment by dagnelies** [comment]
thanks, as usual, good job!
