### ISSUE TITLE
on-click="resetPartial(...)" not working

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#2431]
both latest/edge:

http://jsfiddle.net/xc2o8y08/42/

calling `resetPartial` in the code instead of the button works. Likewise, removing databound items from the partials also make it work in the button.

I guess I see a lot of things because I used ractive rather heavily in a production application.

**Comment by martypdx** [comment]
Did a bit of research, it's the mustache `{{` in the on-click method expression that's failing at _parse_time.

**Comment by evs-chris** [comment]
I think I can solve this and issues with nested quotes in directives if/once #2386 lands. Instead of grabbing everything in the attribute and parsing it again based on the attribute type and what the content looks like, it can do proper parsing of the attribute/directive values. It could technically be done now, but I don't think it would be pretty because of the legacy syntax for proxy events, decorators, and transitions.

**Comment by evs-chris** [comment]
This is now fixed in edge and available in `0.9.0-build-1`.
