### ISSUE TITLE
Add `{{#alias}}` block that works like `{{#with}}` but doesn't change context.

### ISSUE THREAD

**Issue by martypdx** [ractivejs/ractive#2433]
Using the new `{{#with foo as bar}}` aliasing is awesome. 

Sometimes you don't want to create a new context, you just want to introduce the aliases:

```handlebars
{{#each items as item}}
    <-- a helpful alias -->
    {{#with item.foo + 12 as addFoo}}
        <!-- but now context is addFoo :( -->

    {{/with}}
{{/each}}

```
 
So I'm proposing `{{#alias foo as bar}}` that introduces the alias, but doesn't change the context:

```handlebars
{{#each items as item}}
    <-- a helpful alias -->
    {{#alias item.foo + 12 as addFoo}}
        <!-- now context is still item :) -->

    {{/with}}
{{/each}}

```

**Comment by evs-chris** [comment]
Unless I'm misunderstanding, `{{#with foo as bar}}` doesn't introduce new context. It kinda just overloads `with` and if there are aliases no additional context is introduced. It just adds a block in the template to find aliases whilst walking up during resolution.

```
new Ractive({
  el: 'main',
  template: '{{#with foo.bar as bat}}{{.foo.bar}} {{bat}}{{/with}}',
  data: { foo: { bar: 'yep' } }
});
```

That results in `yep yep`. I decided _not_ to try to add context because that gets really weird with multiple aliases in a list e.g. `{{#with foo.bar as bat, bip.bop * 12 + 2 as wat, some[great].fun() as ynot}}`.

**Comment by martypdx** [comment]
> Unless I'm misunderstanding, {{#with foo as bar}} doesn't introduce new context

Okay, my bad then. Still is this desirable?

```handlebars
    <div>outside: {{JSON.stringify(this)}}</div>
    {{#with foo as bar}}
    	<div>inside as: {{JSON.stringify(this)}}</div>
    {{/with}}
	
    {{#with foo}}
    	<div>inside: {{JSON.stringify(this)}}</div>
    {{/with}}
```

```sh
outside: {"foo":{"name":"fooage"}}
inside as: {"foo":{"name":"fooage"}}
inside: {"name":"fooage"}
```

> decided not to try to add context because that gets really weird with multiple aliases in a list e.g. {{#with foo.bar as bat, bip.bop * 12 + 2 as wat, some[great].fun() as ynot}}.

Yea, I see where your headed. Unless that context was a pseudo object with the rollup of those aliases.

Meh, okay - closing for now.
