### ISSUE TITLE
TypeError: node is undefined

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#2452]
Hi,

...one more bug I'm not able to isolate as simple example. It's again a very strange one. In the meantime, here is the stack trace:

```
15:26:12.415 TypeError: node is undefined
makeFunction/<() ractive.js:1449
find() ractive.js:10712
find() ractive.js:13456
find() ractive.js:6740
find() ractive.js:13456
find() ractive.js:7330
find() ractive.js:13456
Ractive$find() ractive.js:14758
printWarning() ractive.js:185
warnOnce() ractive.js:244
warnOnceIfDebug() ractive.js:255
warnAboutAmbiguity() ractive.js:9645
Binding() ractive.js:9668
GenericBinding() ractive.js:10056
createTwowayBinding() ractive.js:10701
bind() ractive.js:10684
_bind() ractive.js:1158
forEach() self-hosted:216
bind() ractive.js:13405
resetTemplate() ractive.js:13630
forceResetTemplate() ractive.js:6777
forceResetTemplate() ractive.js:13783
forEach() self-hosted:216
resetPartial() ractive.js:13793
```

**Comment by fskreuz** [comment]
`makeFunction` sounds to me like something's trying to evaluate an expression between `{{ }}`. Probably adding relevant templates would be good start.

**Comment by dagnelies** [comment]
Here is something that *might* be related:

http://jsfiddle.net/xc2o8y08/55/

**Comment by martypdx** [comment]
The issue is an error happening during the `console.warn` [here](https://github.com/ractivejs/ractive/blob/dev/src/utils/log.js#L63). 

`ractive.fragment.rendered` is returning true, but then in the execution of `ractive.find('*')`, which is meant to provide additional log context, fails because the virtual dom `input` _doesn't_ have a node yet. 

Don't know if it's a result of it being in a partial, in a section, in a component, or all/none of the above.

fyi, original warning is:

```
<content> The 'bar' reference being used for two-way binding is ambiguous, and may cause unexpected results. Consider initialising your data to eliminate the ambiguity
```
