### ISSUE TITLE
2 way binding with Select cast int to string

### ISSUE THREAD

**Issue by grunk** [ractivejs/ractive#2468]
Hi,
i have the following exemple : 
http://jsfiddle.net/kov4f4r0/

If i do the following : 

1. Select "Test" => in the console : connected = 0
2. Change status to "connected"
3. Select "1"
4. Go back to "Test" => in the console : connected = "1"

You can see that the value of "connected" became a string instead of an int. This is very problematic.

This problem seems to appear only with <select> and not <input>.

Is there a way to force a parseInt somehow ?

**Comment by ADantes** [comment]
Putting your values inside of `{{}}` seems to do the trick.  See http://jsfiddle.net/Ly3uh97u/

**Comment by evs-chris** [comment]
@ADantes is correct. Attribute values default to strings in most cases because that's what HTML expects, except in obvious instances like `<input type="number" />` where it's supported. So you have to be specific if you want not stringy values, which usually just means wrapping the value in a mustache e.g. `{{42}}`, `{{null}}`, or `{{false}}`.

**Comment by grunk** [comment]
Thanks guys :)
