### ISSUE TITLE
Bug: Can't unset keys in objects passed from parent

### ISSUE THREAD

**Issue by ADantes** [ractivejs/ractive#2469]
I need to unset a key from an object.  Unfortunately for me, Ractive's update only notices the change *if* it's at the root level.

This works just fine: http://jsfiddle.net/q493yc7b/2/
Moving all the relevant logic into a component breaks it: http://jsfiddle.net/q493yc7b/1/

**Comment by evs-chris** [comment]
This is sort-of known issue, though I can't seem to find the relevant number at the moment. On edge, you can work around it by updating without the key e.g. `update('color')` instead of including the full path. I'm looking into fixing it fully on edge, but unfortunately I don't think there's going to be a 0.7.4 to fix latest. If it's something you don't mind hacking around until 0.8 emerges, you can do roughly the same thing as edge by using `this.parent.update(this.viewmodel.mappings['color'].keypath.str)` to force the parent to update as well.
