### ISSUE TITLE
Allow css option to look for an element like template

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractive#2511]
**Problem:**
I'm building a widget where a build step isn't an option (it's a drop-in script) and everything is written in the least amount of files possible (potentially just a framed HTML file). This throws ES6, template strings, and inlined templates/css out the window.

Managing templates is easy since `template` allows a selector reference and one can build the template outside the JS. The same can't be said for the `css` option. Docs state that `css` only accepts a string. Also, while one _could_ write CSS in the global space, I prefer having it scoped.

**Proposed solution**:
Allow `css` to do the same thing `template` does.

**Pros:**
- Allow `css` to accept off-script sources (elements, script strings).
- Still have the perks of component-scoped CSS.

**Cons:**
Haven't thought of any yet.

**Comment by martypdx** [comment]
I think you mean make it more like `template`, because the final value is a `string` and we'd need to discriminate that `#some-element` is a string that means a query selector to get css, whereas `p { color: blue }` is a string that means the css.

Though `css` is different than other options in that applies per component, not per instance.

But in any case, it may be easy to repurpose the template option logic. If not, would allowing functions by adequate? 

Just be clear, this is a convenience enhancement because you could obviously do something like:

```js
var View = Ractive.extend({
	template: '<p>hello</p>',
	css: document.getElementById('css-id')
});
```

**Comment by fskreuz** [comment]
Yep, just for convenience really. I was thinking something like the following:

```js
var View = Ractive.extend({
    template: '#hello-template'
    css: '#hello-css'
});
```
