### ISSUE TITLE
Indexing ractive+routie SPA by search engines bots

### ISSUE THREAD

**Issue by NesterenkoD** [ractivejs/ractive#2517]
Hello!

I develop SPA with Ractive and Routie library for routing. My SPA has a few pages and all it's content contains in index.html. But I have a problem with search engines bots, they are see page like HTML with mustaches, for example:
<div class="menu">
	{{#each cities}}
		<div class="item" data-text="{{this}}">{{this}}</div>
	{{/each}}
</div>

And in this case Google search bots can't find other pages of my SPA, because routieJS and RactiveJS not started when bot comes. He see the one big index.html with content of other routieJS pages, but can not find this pages with own content, all URLs like "#rules" link to index.html.

My site avtoritet.club.

Please help!

**Comment by evs-chris** [comment]
I've not used routie, but I have had google successfully index single-page sites that are built on page.js and Ractive. Sometimes the google-bot picks up the raw template on the first run through, but it usually gets everything sorted fairly quickly.

Do you have a hard requirement to not use the history api? My best guess that the google-bot is seeing hash links and thinking that it's all meant to be a giant page with anchor navigation.

I will say that last time I checked bind didn't do so well with SPA-style sites, but I've not had any severe problems with google.

**Comment by fskreuz** [comment]
> they are see page like HTML with mustaches

Of course. Think of bots as browsers that don't have JS. Without JS, Ractive won't run. If Ractive won't run, then all your page is is just a bunch of templates. And that's what the bot actually sees.

On the other hand, you can do server-side rendering with Ractive. You can run the app in Node and have the top-most component render itself using [`toHtml`](http://docs.ractivejs.org/latest/ractive-tohtml) and `toCss` (undocumented, but works the same).

There was a [discussion recently](https://github.com/ractivejs/ractive/issues/395) about "isomorphic" Ractive, where instances on the client, when bound to the markup of its server-rendered version, would auto-bind itself without throwing away the existing markup. Not sure where the discussion ended up or if it was ever implemented.

Anyways, if you aren't using Node, or if "isomorphic" isn't your thing, you can always put static content on the page for bot consumption which will be thrown away when Ractive runs on the page.

```html
<div id="app">
  <!-- for bot consumption -->
  <p>default content</p>
</div>

<script>
  // Creating a new instance will blow away anything defined in `el`
  new Component({ el: '#app" });
</script>
```

Additionally, so that bots won't parse the template, write your components in either external JS files or as [component files](https://github.com/ractivejs/component-spec) and leaving nothing on the page. Also consider having a build phase to compile your app.

**Comment by evs-chris** [comment]
Just wanted to note that google is throwing a good bit of weight behind angular and are therefore much more webapp friendly.

Additionally, edge has an option to use progressive enhancement that doesn't blow away the dom that the browser has already rendered (entirely, anyways) when the Ractive instance kicks off. See the `enhance` option in the edge docs.

**Comment by MartinKolarik** [comment]
I usually use UA sniffing to send server-rendered pages for all common bots, and render client-side for everything else.

Given the support for progressive enhancement in 0.8, it might make sense to simply always send server-rendered pages, but in my experience, due to how it works, Ractive is quite slow for server-side usage.

**Comment by martypdx** [comment]
[Here's](https://webmasters.googleblog.com/2015/10/deprecating-our-ajax-crawling-scheme.html) an interesting blog post from google.

@MartinKolarik:

> I usually use UA sniffing to send server-rendered pages for all common bots, and render client-side for everything else.

from above post:

> Serving Googlebot different content than a normal user would see is considered cloaking, and would be against our Webmaster Guidelines.

**Comment by MartinKolarik** [comment]
@martypdx it's no different than using phantomjs which is a common practice. Also:

>If you pre-render pages, make sure that the content served to Googlebot **matches the user's experience, both how it looks and how it interacts.**

Pages for bots look exactly same as in any JS enabled browser.

**Comment by NesterenkoD** [comment]
Thanks to all.

But I have a question: if I use server-side rendering, the page still haven't content, it will be looks like:
`<div id="app"></div>`
and Google can not see content.

Only after JS files will be load, query will be send to server and answer with html will be recieve, the page will be render.

And I can set default content correctly, because this default content be the same for main page, /#profile, /#login and any other pages, using JS-routing.

In that case I can understand how server-side render can help me.

**Comment by MartinKolarik** [comment]
>Only after JS files will be load, query will be send to server and answer with html will be recieve, the page will be render.

Server-side rendering means you render and send full HTML in the first response, not that you load it later using AJAX.

**Comment by NesterenkoD** [comment]
Do you know what is better?
https://github.com/MartinKolarik/ractive-render
https://github.com/zenflow/ractive-express

Or exist better solution?

**Comment by MartinKolarik** [comment]
I wrote the first one, so that's the one I'm going to recommend :smile:

**Comment by NesterenkoD** [comment]
Thanks)

**Comment by paulocoghi** [comment]
I am using Ractive + Page.js and I will update details here about google indexing. Until now, everything seems ok.

**Comment by paulocoghi** [comment]
As promised, here are the details until now:

Google is rendering and indexing all the pages properly. It's important to use a routing library as **page.js** with history API support, that "intercept" clicks and allow the use of regular "a" links.

This way:

 - you don't need to use `on-tap` or `on-click` to simulate links
 - normal "a" links are crawled
 - your SPA can be requested in any URL and link previously provided
 - links can be shared externally

I am now validating complete SVG-pages and seeing how they will be crawled. For this test, I fixed page.js to work including with SVG links. ([here is the PR](https://github.com/visionmedia/page.js/pull/394) and [here is the fork](https://github.com/Altiva/page.js))
