### ISSUE TITLE
Ractive.js v0.8.0-edge problem with new style attribute support

### ISSUE THREAD

**Issue by Jeff17Robbins** [ractivejs/ractive#2522]
`updateStyleAttribute()` assumes that `this.getValue()` returns a string.  But `this.getValue()` can return a bool if the style attribute has no value (admittedly a corner case).  

```javascript
  function updateStyleAttribute () {
  	var props = readStyle( this.getValue() || '' );
```

If `this.getValue()` returns a bool (see example below), readStyle assumes that it is being passed a string, and tries to call `.replace()` on that bool, which throws

```javascript
  function readStyle ( css ) {
      var values = [];

      return css.replace( escape, function ( match ) { return ("\u0000" + (values.push( match ) - 1)); })
```

```
ractive.js:9863 Uncaught TypeError: css.replace is not a function
```

	Ractive.js v0.8.0-edge
	Wed Apr 20 2016 23:39:55 GMT+0000 (UTC) - commit abdad6a6cdfe8c66d4900c603b0417389999862f

http://jsfiddle.net/q8bhrzsn/ (Ractive.js v0.8.0-edge) doesn't work

http://jsfiddle.net/aqahqs0x/ (Ractive.js v0.7.3) does work

HTML
```html
<div id="output"></div>
  <script id="template" type="text/ractive">
    <div style="{{#if somebool}}{{else}}display:none{{/if}}">
      unhide this
    </div>
  </script>
```

JavaScript
```javascript
var r = new Ractive({
  el: '#output',
  template: '#template',
  data: {
    somebool: false
  }
});

r.set('somebool', true);
```

**Comment by martypdx** [comment]
@Jeff17Robbins thanks again!

You know your analysis is so complete, you should do a PR 😁

**Comment by evs-chris** [comment]
> You know your analysis is so complete, you should do a PR 😁

True! In fact, it was so thorough, I already had a PR ready to submit by the time @martypdx posted that because I was pointed directly to the fix. I'll hold off if you'd like to get credit since you did most of the work :smile:

**Comment by Jeff17Robbins** [comment]
While I am flattered, you're talking about a guy who uses Notepad to edit code.  I'm pretty sure you don't want me messing with the codebase directly.  :cold_sweat: I'm happy to keep producing test cases and share what I can see in the code.  Hope that's ok with you guys?

**Comment by paulie4** [comment]
BTW, updateStyleAttribute() also hides problems from the user if a style property's value is invalid. For example, `style.display = ''` is valid, but if `''` is placed in a template, then it turns into the following in the updateStyleAttribute() function, which is invalid but throws no error nor logs any warnings:
```style['display'] = "''"```

Since Ractive 0.7.3 was just setting the style attribute's string value, having `display=''` used to work. Maybe the right way to warn users about mistakes is if Ractive.debug && style[ keys[i] ] != props[ keys[i] ], then log a warning message.

**Comment by evs-chris** [comment]
@Jeff17Robbins there's nothing wrong with notepad. 😁 We can't all write code accurately at 200wpm with a magnetized needle, as I assume @Rich-Harris does. But by all means, keep filing excellent bug reports! Hopefully you'll run out of bugs to report soon.

@paulie4, I quite like the idea of checking the style property value right after setting if `Ractive.debug` and warning if it doesn't match. Does anyone know if that will fall over in certain scenarios involving shorthand?

**Comment by paulie4** [comment]
@evs-chris I just tried `$0.style.border = 'medium dashed green'` in Chrome and in IE11. Chrome will return the same value if you read `$0.style.border`, but IE11 will return `'dashed green'`, so IE11 doesn't print back the default "medium" width. It seems valid to warn the user that the returned value doesn't match, since they are different strings.
