### ISSUE TITLE
#with and 2-way binding (main bug and related bug)

### ISSUE THREAD

**Issue by arkenidar** [ractivejs/ractive#2542]
**Description of the bug:**
When using 2-way data binding, the with statement is ignored.

**Versions affected:**
0.7.3

**Platforms affected:**
Bug discovered in Firefox and Windows 7.
All platforms may be affected.

**Reproduction:**
[fiddle showing the bug](http://jsfiddle.net/devdev/geo63339/1/)

**Code:**
```
<script type="text/template" id="template">
    WORKING [2-way data binding, full path, no #with]:
    <input placeholder='Type your name' value='{{user.name}}'> <br>   
    {{#with user}}
    WORKING [#with mustache when not bound with 2-way data binding]: age is displayed here: {{age}}<br>
    BUG #1: email is NOT displayed here [2-way data binding using a #with mustache]: <input placeholder='Type your email' type=email value='{{email}}'> <br>
    BUG #2: email is NOT displayed here (too) [usual #with mustache]: {{email}} <br>
    {{/with}}
    <br>
    (BUG #1) #with mustache does not work with 2-way data-binding.
    <br>
    (BUG #2) BUG #1 prevents usual #with mustaches from working
</script>

<script type="text/javascript">
var ractive = new Ractive({
	el: 'body',
	template: '#template'
});

ractive.set('user.name', 'user.name is set');
ractive.set('user.age', 30);
ractive.set('user.email', 'user@gmail.com');
</script>
```

**Comment by martypdx** [comment]
In latest Ractive `0.7.3` unresolved references (at initial render, there is no data this `email` is not resolved to anything) resolve to the root of the ractive instance. The following warning messgae is logged:

```sh
Ractive.js: The 'email' reference being used for two-way binding is ambiguous, 
and may cause unexpected results. Consider initialising your data to eliminate 
the ambiguity
```

So either make sure the data is available in the model, _or_ use a restricted references `{{.email}}` to indicated the property is only to be found on the immediate context.

In the next version of Ractive, the default binding for unresolved references is changing to the immediate context, because for the most part it's what people expect. See http://jsfiddle.net/martypdx/geo63339/2/
