### ISSUE TITLE
Trouble with subclassing of a component with complex data

### ISSUE THREAD

**Issue by seijikun** [ractivejs/ractive#2546]
**Description of the bug:**
When subclassing a component (=> `Ractive.extend(...).extend(...)`) which has complex `data` fails to create a new instance at the second extend. All so created "instances" somehow seem to be actually only one instance (= sharing their data etc.).

**Versions affected:**
I could reproduce with `0.7.3` and `0.8-edge`

**Platforms affected:**
`Opera-37.0.2178.32`, `Firefox-46.0`, latest `Chromium`, `QupZilla-2.0.0`

**Reproduction:**
This [fiddle](https://jsfiddle.net/jy85t4d9/3/) shows the problem: 
(fails with 0.8-edge, with 0.7.3 the second `Child` suddenly has two array-elements)
- Create a component (with `Ractive.extend()`), which is given a complex `data`-option.
- Create a subclass of this component while giving a `data`-option to overwrite a property of the parent component.

-> All instances created of the subclass seem to be actually only one instance (sharing data etc.)
Same problem, when using `Ractive.extend({...}, {...})` instead of `Ractive.extend(...).extend(...)` ([fiddle](https://jsfiddle.net/0ckgn7yd/2/)).

One of the following fixes the problem:
- Passing a non-complex `data`-option to the parent-component ([fiddle](https://jsfiddle.net/hzgnfbua/2))
- Overwriting all properties of the `data`-option passed to the parent-component ([fiddle](https://jsfiddle.net/nf3e6gLj/))
- Not providing any `data`-option to the child but instead manipulating the data after initialisation ([fiddle](https://jsfiddle.net/0o4p2xne/))

(Of course, only the last option would be actually helpful for a workaround)

Is this possible, or do I have a massive misunderstanding somewhere?

**Comment by MartinKolarik** [comment]
You need to [use a data function](https://jsfiddle.net/jy85t4d9/4/) for the `Child` component. I *think* this is expected behavior.

**Comment by martypdx** [comment]
Once upon a time I think mixing primitives and functions worked correctly, though we may have simplified things along the way and required the use of functions in mixed extend stacks (it doesn't come up very often - I suppose composition over inheritance? 😄  ). 

So, I marked bug and/or better error - at a minimum because in the `0.8` case it shouldn't fail.

**Comment by seijikun** [comment]
Argh. I tested nearly every variation, except of this one. Thanks, that solved the error!

**Comment by evs-chris** [comment]
The issue is the `Child` component having only a single instance of data, which is shared. Having a function in parent doesn't work around the shared reference issue with stacked data. Pushing to the array updates the array for _all_ instances, which completely blows up expectations for shuffling in the second instance. I don't think there's really a way around this other than flat out refusing to use a non-function for data in extend, which may not be a bad idea at some point, but for now, the warning will have to suffice.
