### ISSUE TITLE
Unqualified method events are deprecated. Prefix methods with '@this.' to call methods on the current Ractive instance.

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#2553]
Hi,

it's nice to provide a warning, but it would be even nicer to write "where" this happens. After all, this is a change impacting lots of users/code/plugins.

**Comment by kouts** [comment]
What does this warning means exactly?
Does it mean that we must prefix '@this.' to all methods inside templates?

So instead:
``` <button on-click="myMethod()">Call my method</button> ```
We should now write:
``` <button on-click="@this.myMethod()">Call my method</button> ```

Is this the case?

**Comment by evs-chris** [comment]
That's correct, because you can now use any valid expression that includes a call in an event handler, not just a simple `methodname(...args)`. For instance, you can call data methods and multiple functions as a comma separated list e.g. `<button on-click=".bar.foo(10, ../something), @this.parent.fire('someEvent')">Click Me</button>`, which would call `foo` on the `bar` object in the current context and then fire a 'someEvent' on the parent instance when the button is clicked.

**Comment by kouts** [comment]
Ok I understand, It would be great if the '@this' part was optional though, at least for single method calls. To me it seems that -at least in my templates- it will just add additional clutter.
But that's just me...

**Comment by fskreuz** [comment]
`@this` was implemented to tell what's from the data and what's from the instance. Without `@this`, how would you know which `foo` is used where?

```
<button on-click="foo('bar')">{{ foo }}</button>`.
```

In the older versions this was easy. `foo` in the event would be a method while `foo` in the mustache would be something in the data. In the upcoming version, where it appears that both can be used, there must be a way to tell which is which.

**Comment by JonDum** [comment]
>there must be a way to tell which is which.

Isn't that already accomplished with the `.` prefix? Now that I think about, the `@this` is redundant if you have that, no?

```html
<button on-click=".bar.foo(10, ../something)">Click Me</button> // access method on data model

<button on-click="@this.parent.fire('someEvent')">Click Me</button> // use @this to access parent 

<button on-click="fire('someEvent')">Click Me</button> // no dot, assume it's @this
```

**Comment by fskreuz** [comment]
`.` and `this` (no `@`) refers to the current data context. `@this` (has `@`) refers to the Ractive instance.

```
const Component({
  ...
  data: {
    foo: function(){/* Data function. */}
  },
  foo: function(){/* instance method */}
});
```


Now if I remember correctly, Ractive can "climb" up the data to look for that property if it doesn't exist in the current context. This can lead to ambiguity, especially when no reference was found. To mitigate this, it was recommended to use [restricted references](http://docs.ractivejs.org/latest/references#restricted-references) (adding `.`) to prevent this climbing behavior.

Now with both instance and data expressions present, you cannot simply assume `foo` as `@this.foo` when it could be `foo` higher up in the data. You can't also put a `.` before `foo` since you might also want that climbing behavior.

**Comment by dagnelies** [comment]
see, that's what I told, the `this` versus `@this` will be a source of confusion! :wink:
