### ISSUE TITLE
BUG: Observers with wildcards in components generated from array

### ISSUE THREAD

**Issue by michaljerabek** [ractivejs/ractive#2601]
**Description of the bug:**
If components generated from an array have an observer with a wildcard and the array is rearranged, an error is thrown.

**Versions affected:**
0.8-edge

**Platforms affected:**
Any browser

**Reproduction:**
http://jsfiddle.net/Lq19arzw/4/

**Comment by evs-chris** [comment]
This one is tricky because the observer is depending on the mapping, but the mapping doesn't get updated until after the observer fires. Making the observer deferred is a likely workaround, but I don't think it should be a requirement.

**Comment by michaljerabek** [comment]
Deferred observer doesn't work either.

**Comment by evs-chris** [comment]
This no longer throws an error, but a proper fix will take a bit more effort. As it sits, the observer will fire with the wrong keypath during the shuffle.

**Comment by evs-chris** [comment]
Guys, I need a sanity check on this because 0.7.3 throws an error in this scenario so I can't verify based on its behavior. I think I wrote a wrong test when I stopped the error:

```html
{{#each list}}<cmp foo="{{.}}" />{{/each}}<br/>
<button on-click="swap">swap</button>
```

```js
var r = new Ractive({
  template: '#upthere',
  components: {
    cmp: Ractive.extend({
      template: '{{foo.bar}}',
      onconfig() {
        this.observe('foo.*', v => console.log(v), { init: false });
      }
    })
  },
  data: { list: [ { bar: 'a' }, { bar: 'b' }, { bar: 'c' } ] }
});

r.on('swap', function() {
  r.pop('list').then(item => this.unshift('list', item));
});
```

When you click the button, it pops the last item (`{ bar: 'c' }`) and then unshifts it on `list`. The test as it stands expects the pattern observers to fire in each instance, but they _shouldn't_, because `foo.*` in each component hasn't _actually_ changed, right? I ask because I just spent an embarrassing amount of time trying to make that test turn green with an experimental branch, and I just realized that the behavior I've been trying to "correct" is actually the correct behavior to begin with. Right?

**Comment by martypdx** [comment]
Yes, should not fire. The list is mutating, not the items in the list

**Comment by fskreuz** [comment]
Related issue https://github.com/ractivejs/ractive/issues/580#issuecomment-42156301

**Comment by michaljerabek** [comment]
Initially, I also thought, that it should not fire, but the observer may somehow depend on the index...

**Comment by martypdx** [comment]
> but the observer may somehow depend on the index

Well the observer could "depend" on any number of additional factors, but it's not a computed property where each additional piece of information is tracked. Doesn't it make sense that an observer fires based on what it is observing?

**Comment by michaljerabek** [comment]
You're right. It would not make much sense.

**Comment by evs-chris** [comment]
This is now fixed.
