### ISSUE TITLE
BUG: Arrays + components + observers create duplicates

### ISSUE THREAD

**Issue by michaljerabek** [ractivejs/ractive#2604]
**Description of the bug:**
Rearranging "an array of components" creates duplicates if an observer changes data in the component.

**Versions affected:**
0.8-edge

**Platforms affected:**
Any browser

**Reproduction:**
http://jsfiddle.net/saut2tx2/3/

EDIT: The description is not entirely accurate. It simply creates a new object.

**Comment by evs-chris** [comment]
This is now as fixed as it can be for 0.8. You will need to use deferred observers for scenarios like this where you want the observer to stop firing when the component is removed e.g. `this.observe('...', () => {}, { defer: true });`.

**Comment by evs-chris** [comment]
This is back in a weird way. Basically, since modifyArrays is off by default now, the first splice (removing the element) doesn't notify ractive of the change, so the second splice creates a duplicate when it _does_ notify ractive. I'm looking into the best way to handle this, but I think it's probably to allow array self merges as proposed in #2648.
