### ISSUE TITLE
Feature Request: Pass parameters to section / partial

### ISSUE THREAD

**Issue by ElliotChong** [ractivejs/ractive#261]
It would be great to be able to add parameters to a section or partial similar to [Dust.js's implementation](https://github.com/linkedin/dustjs/wiki/Dust-Tutorial#sections-with-parameters).

Data:

```
{
   "name": "root",
   "anotherName": "root2",
   "A":{
      "name":"Albert",
      "B":{
         "name":"Bob"
      }
   }
}
```

---

**Setting Strings**
Template:

```
  {{#A.B foo="Hi" bar="good to see you"}}
      {{foo}} {{name}} {{bar}}
  {{/A.B}}
```

Output:

```
Hi Bob good to see you
```

---

**Other Previously Defined Values**
Template:

```
  {{#A.B foo=A.name bar=anotherName}}
      {{foo} {{name}} {{bar}}
  {/A.B}
```

Output:

```
Albert Bob root2
```

Combined with setting partials dynamically this would allow for a lot of really great componentized implementations.

**Comment by ghost** [comment]
Hey guys, I finding this feature to be really slow on data updates. Or, maybe I've gone a little crazy with it.

I have a div-based table setup.

{{#each groups}}
{{>group { like 10 keys passed } }}
{{/each}}

inside group

{{#each .groupItems}}
{{>item { like another 10 keys passed } }}
{{/each}}

in item:

{{#each item.field}}
 {{> field { pass another 10 or more keys } }}
{{/each}}

Updates can take like 5 seconds or more. Trying to combine the variable updates.

Is this due to the template scoping? I notice the scope paths get giant (like enough to fill up my entire console log when there's an error). Should I go back to simply using the inherited scope like before?

**Comment by ghost** [comment]
@clintonskakun suggesting opening a different issue for this so we can mark it under performance and so that it doesn't hijack a dead thread.

**Comment by evs-chris** [comment]
What @fskreuz said, but as a brief response here, the problem is that you're creating lots of computations (object literal expressions) that are getting set as context in each partial. Direct access would be much more efficient, and using aliases would probably be pretty close in performance to direct access e.g. `{{#each groups as group}}{{>group some.value as key, other.thing as otherKey}}{{/each}}` where `group`, `key`, and `otherKey` are relatively quick to fetch and keep in sync with the model in the `group` partial.

**Comment by ghost** [comment]
@evs-chris Thanks for the tip. Yeah the literal computations were creating some serious overhead. Swapping it out for the aliases made a giant improvement. Where it'd take 3-5 seconds to complete now does it in like <500ms. Thanks again.
