### ISSUE TITLE
Bug: Observer is fired in a wrong component

### ISSUE THREAD

**Issue by michaljerabek** [ractivejs/ractive#2622]
**Description of the bug:**
If the order of "an array of components" is changed, observers fire in wrong components.

**Versions affected:**
edge

**Platforms affected:**
Any browser

**Reproduction:**
http://jsfiddle.net/Lq19arzw/10/

**Comment by fskreuz** [comment]
I initially thought this was a feature (Ractive retaining bindings in order without moving the DOM of similar entities) but it appears that [it's not how 0.7 behaved](http://jsfiddle.net/Lq19arzw/11/).

**Comment by evs-chris** [comment]
This is an issue with how models handling bindings and observers. Basically, observers aren't part of a view, so they don't get rebind notification when a component binding changes. There's also not an immediately obvious way to cause the rebind from the bound model, because it doesn't know that some of its deps are bound in another namespace that has actually changed. I have a chunk of code that addresses this issue, but it's a fairly major change and it isn't quite passing all tests just yet.

**Comment by evs-chris** [comment]
This now behaves the same way in edge and 0.7.3.
