### ISSUE TITLE
Bug: SVGs and progressive enhancement

### ISSUE THREAD

**Issue by michaljerabek** [ractivejs/ractive#2623]
**Description of the bug:**
Ractive throws an error, if an SVG with `<use>` is used.

**Versions affected:**
edge

**Platforms affected:**
Any browser

**Reproduction:**
http://jsfiddle.net/dLtr1wxc/2/

**Comment by evs-chris** [comment]
This was caused by the enhance process not finding a namespace declaration, which should be fine because xlink is one of the implicit ones from what I can tell. It was looking all the way up to document, which has no `hasAttribute`, so there is now a check for that before the call and a test to verify progressive enhancement on svgs works. Thanks!
