### ISSUE TITLE
Rerendering components and its children

### ISSUE THREAD

**Issue by ekhaled** [ractivejs/ractive#2628]
**Description of the bug:** Not a bug

**Versions affected:** All

**Platforms affected:**

**Reproduction:**

Is there any way to re-render a component, and then maybe use `findAllComponents()` to walk down the hierarchy and re-render the children.

Basically, I really would like to implement Hot Module Reloading properly, ( the one on [bestguy/ractive-webpack-boilerplate](https://github.com/bestguy/ractive-webpack-boilerplate) reloads the whole app, which is not really HMR, more of a LiveReload )

To do that, I would have to inject some code that would eventually re-render the module into the webpack loader.

The VueJS loader uses this method, see [https://github.com/vuejs/vue-loader/blob/master/lib/loader.js#L219-L232](https://github.com/vuejs/vue-loader/blob/master/lib/loader.js#L219-L232) and [https://github.com/vuejs/vue-hot-reload-api/blob/master/index.js#L102](https://github.com/vuejs/vue-hot-reload-api/blob/master/index.js#L102)

Wondering if there was a method to do that in ractive

**Comment by evs-chris** [comment]
It sounds like you're looking for something like `resetTemplate` and `resetPartial`, but for components. There's nothing quite like that available that I'm aware of.

If you know what you're going to need to reload to some extent ahead of time and your data is all mapped (to avoid losing it when the components are torn down and recreated), you could set them up in a conditional e.g. `{{^reloadThisComponent}}<someComponent><hierarchyHere /></someComponent>{{/}}`. Then when you need to reload, just swap out the component on the relevant instance (`parentInstance.components.someComponent = newlyLoadedComponent; parentInstance.components.hierarchyHere = otherNewlyLoadedComponent`) and trigger and unrender/re-render (`parentInstance.toggle('reloadThisComponent'); parentInstance.toggle('reloadThisComponent');`). That's more or less the procedure used to reload partials before `resetPartial` came along.

I don't know how generally useful `resetComponent` would be, but with edge, there's the possibility to keep the viewmodel intact by transferring it to the new instance when doing the reset. Any components that do special init would need to make sure they don't overwrite anything, or there would need to be a new lifecycle for components that started with a `reset` rather than the usual `init` and friends.

**Comment by ekhaled** [comment]
if we had the ability to maybe swap the `template` and `css` options and then trigger a re-render, so that new DOM and CSS are applied...... that would be just awesome.

Typically, HMR is used during development. It will be hard to strip out what you are suggesting during a production build. It will be also hard to inject that in from a loader.

**Comment by evs-chris** [comment]
I think the best approach to this for now is still going to be to unrender the root app, swap out the component, and then re-render it. You can try getting more precise by using `findAllComponents` and `resetTemplate` on each one.
