### ISSUE TITLE
Recomputing a computed values causes observers to re-fire, even if the value hasn't changed

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#2629]
**Description of the bug:**

Recomputing a computed values causes observers to re-fire, even if the value hasn't changed

**Versions affected:**

Edge

**Reproduction:**

http://jsfiddle.net/ub7540xq/

**Code:**

```js
var ractive = new Ractive({
  computed: {
  	int () {
    	return Math.round( this.get( 'number' ) );
    }
  },
  data: {
    number: 1,
    observerCalledTimes: 0
  }
});

ractive.observe( 'int', function ( int ) {
  console.log( int );
  this.add( 'observerCalledTimes', 1 );
});

ractive.set( 'number', 1.1 );
ractive.set( 'number', 1.2 );
ractive.set( 'number', 1.3 );
ractive.set( 'number', 1.4 );

console.log( ractive.get( 'observerCalledTimes' ) );
// expected 1, got 5
```

**Comment by evs-chris** [comment]
I thought the fix for this would be pretty simple: just check `!isEqual( newValue, oldValue )` before scheduling the observer, but it turns out that that runs afoul of the #771 test that seems to hate me so. Out of curiosity does anyone actually use observers for validation i.e. mutating a value from an observer that is watching it as the user types? I would think per-element laziness would preclude the need for that particular facility, but I've been wrong so very many times.

**Comment by giovannipiller** [comment]
> mutating a value from an observer that is watching it as the user types?
@evs-chris: like observing `a` and modifying it while user types on a `<input ... value="{{a}}">`?

If that's so, I'd say per-element laziness is an ok approach.

**Comment by michaljerabek** [comment]
> Out of curiosity does anyone actually use observers for validation i.e. mutating a value from an observer that is watching it as the user types?

Yes, I use observers for this. (And it causes many issues, because of those bugs, I've reported.)
