### ISSUE TITLE
Tracking array changes in edge is impossible

### ISSUE THREAD

**Issue by mefjuu** [ractivejs/ractive#2639]
**Description of the bug:** There is a problem with tracking array mutations in observers. `newValue` and `oldValue` are the same. As far as I remember it was possible in 0.7.3. Now, I can't recognize which array items were added, removed, or altered.

**Versions affected:**
0.8 edge

**Reproduction:**
http://jsfiddle.net/zLgw84nt/2/ - 'Pushin' clicking and console.log watching

**Comment by fskreuz** [comment]
Not sure about your claim in `0.7`. [It appears to behave the same way](http://jsfiddle.net/zLgw84nt/6/). 

I think the problem is with the old value when used on a mutated entity. It works when using set([0.7](http://jsfiddle.net/zLgw84nt/8/), [0.8](http://jsfiddle.net/zLgw84nt/10/)), replacing the value and correctly providing the old and new values, since the new value is an entirely different array. The behavior you're seeing is because the array is still the same array, therefore newValue _is_ oldValue.

Not sure how to resolve this. If `oldValue` was a clone `arr`'s former self, it would probably cause identity checks to fail.

**Comment by mefjuu** [comment]
(as for 0.7 I'm not convinced and must check in my older app sources)

What can I say more is that I need some Ractive-way to track changes in quite big array, to keep it sync with offline store (using some wrapper for indexedDB).

**Comment by evs-chris** [comment]
I think you may be looking for a pattern observer: `this.observe('arr.*', function(n, o, k, idx) { ... }`. Like @fskreuz said, with objects and arrays there's no way to give you an old and new version when a child of the array triggers the change because Ractive doesn't do defensive cloning. We have discussed adding the hooks into the observer process to allow users to do their own cloning for better comparisons.
