### ISSUE TITLE
A problem when I use computed to change the observed items

### ISSUE THREAD

**Issue by Wunan777** [ractivejs/ractive#2643]
**Description of the bug:**
There is going wrong when I use computed to change the observed items;
There is an example;
http://jsfiddle.net/kg6na484/27/
You can test by clicking the checkbox order by 1 -> 2 -> 3 -> check all -> 1 -> 2 -> 3
then you can find the "check all"  checkbox is unchecked
![image](https://cloud.githubusercontent.com/assets/12150093/18043714/47f0e8dc-6dfc-11e6-9f98-4f9703c44af5.png)

**Versions affected:**
Edge
**Platforms affected:**

**Reproduction:**

**Code:**

**Comment by evs-chris** [comment]
The way dependency tracking in computations works, you need to access each value that you want to cause a recomputation directly from the computation getter e.g. `this.get('list.0.checked')`, etc. If you don't then it won't recompute unless the list itself actually changes. Here's an updated fiddle that subscribes the computation to each checked property nested in the list: http://jsfiddle.net/kg6na484/28/

**Comment by evs-chris** [comment]
Note that this still has a few issues because you're changing deps from inside the computation, so it will get confused if you make some random selections and intermix check all states with more random selections. I usually use the click event to manage checking/unchecking selections in situations like this because bindings are sensitive to things that can cause themselves to change, like this and observers that mutate their observed value.

**Comment by musicode** [comment]
It is quite natural to do it by two way binding. so I don't think use the click event is the best way, it likes a hack.

**Comment by fskreuz** [comment]
I just noticed something. Do the following:

1. Check 1
2. Check 2
3. Check 3 (Check All gets checked)
4. Uncheck Check All (everything gets unchecked)
5. Check 1
6. Check 2
7. Check 3 (nothing happens, as reported). But...
8. Uncheck and recheck 1
9. Uncheck and recheck 2
10. Uncheck and recheck 3 (Check All gets checked)
11. Uncheck Check All (all isn't unchecked)
12. Check and Uncheck Check All (everything gets unchecked)

Same thing happens when I tried making a workaround using observers http://jsfiddle.net/kg6na484/29/. It seems like the computation isn't being run certain phases causing this skip.

**Comment by fskreuz** [comment]
However, this does work properly in 0.7 http://jsfiddle.net/kg6na484/30/ (Was pretty sure this worked before. I made something similar before using 0.6.)

**Comment by evs-chris** [comment]
@fskreuz it is indeed a bug, so thanks for the walk-through!

Just to note, the observer solution has a catch: if all are selected and you deselect one, the allChecked observer will fire with the new value indicating that all are no longer checked and it will uncheck the rest too. You'd have to add a lock or a check that all are already checked to avoid that.
