### ISSUE TITLE
Question: plugin for input formatting

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2650]
I'm sorry if this should go elsewhere. I'm looking for a way to format input fields like e.g https://github.com/BobKnothe/autoNumeric
How to achieve this the Ractive way? Is there a plugin available?

I tried creating a decorator with [autoNumeric](https://github.com/BobKnothe/autoNumeric) and although it works on user input when data gets reset by ractive then the input doesn't get formatted.

**Comment by dagnelies** [comment]
What you need is a computed variable:
http://docs.ractivejs.org/latest/computed-properties

```js
ractive = new Ractive({
  data: { num: 1234 },
  computed: {
    formatted_num: {
      get: function() { /* some function to format the number */ },
      set: function ( str ) {
        var num = ...
        this.set('num', num);
      }
    }
  }
});
```

**Comment by kouts** [comment]
@dagnelies I'm trying to apply a mask on the input field as the user types.
Does the above example accomplishes it?
I can't understand exactly how.

**Comment by dagnelies** [comment]
oh, that would be tricky indeed. Probably better to not databind it at all in this case and insert/extract the value on load/submit. Personally, I dislike these "changing fields".

**Comment by fskreuz** [comment]
The problem is that Ractive only knows about the DOM. Ractive does not know about your integrations in the same way your integrations does not know about Ractive. The developer must introduce both to each other.

This is an ideal job for a decorator, or a custom component and a third-party library. You will have to let Ractive know the plugin changed the value, and you need to let the plugin know Ractive changed the value.

I've done similar things, especially with jQuery UI plugins, particularly autocomplete. You can do yours in a similar fashion. Refer to your plugin's API for details on events and setters tho.

```
const MaskedInput = Ractive.extend({
  template: `
    <input type="text">
  `,
  data: {
    value: ''
  },
  onrender(){
    // Initialize your plugin on the DOM element
    const input =  jQuery(this.find('input').plugin();
  
    // Observe changes from the input via the plugin's API and inform Ractive about it
    input.plugin('change', event =>  this.set('numberInData', event.target.value));

    // Observe changes from Ractive and set it to your input via the plugin's API
    this.observe('value', newValue => input.plugin('setvalue', newValue));
  }
});

// Usage in template
<MaskedInput value="" />

```

**Comment by kouts** [comment]
Thanks @fskreuz , managed to do the same thing with a decorator.
