### ISSUE TITLE
How to get current component instance's DOM?

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#2654]
Sometimes we need to manipulate a DOM with jQuery, which requires the DOM selector (or DOM itself). We can use `id=` property by issuing `$("#THE_ID_OF_THIS_INSTANCE")`, which is not useful every time. 

In a component's `oninit` handler, we can use CSS selectors along with `ractive.find`, but that gives all matching DOM's. 

How can I get a component's only that instance's DOM, preferably in that component's `oninit` function?

**Comment by fskreuz** [comment]
Hmm... `onrender` and `$(this.find('SELECTOR_HERE'))` always worked for me. I wouldn't do it on `oninit`, the component isn't on the DOM yet.

**Comment by martypdx** [comment]
As @fskreuz mentions, you need to use `onrender` because there is no DOM yet.

If you're using `id`, you can access it via `this.nodes.idOfTheNode` and Ractive will "scope" that id to the component (yes id's aren't suppose to be repeated in DOM, but that's up to you).

Otherwise, use query selector like `this.find('input')` instead.

**Comment by ceremcem** [comment]
`this.find('my_html_element')` in `onrender` worked great, thank you!
