### ISSUE TITLE
Dynamic tag not supported?

### ISSUE THREAD

**Issue by van-nguyen** [ractivejs/ractive#2691]
**Description of the bug:**
When I try to generate a list of headers, it throws an error ```Error: Illegal tag name at line x character xx:```

**Versions affected:**
0.8.0

**Platforms affected:**
All

**Code:**
```mustache
{{#tags}}
  {{#if @index}}
    <h{{@index}}>{{content}}</h{{@index}}>
  {{/if}}
{{/tags}}
```

**Comment by evs-chris** [comment]
No, dynamic tags and components are not directly supported at this time. You can _fake_ it with `{{#each tags as tag}}{{#if @index}}{{> { template: "<" + tag + @index + ">{{content}}</" + tag + @index + ">" } }}{{/if}}{{/each}}` or something similar. https://jsfiddle.net/rc60of3x/

**Comment by van-nguyen** [comment]
Thanks for the recommendation, got me thinking and inspired to write a function to render the html instead, which should be more maintainable in my case as complexity increases. Any reason I shouldn't do this?

**Comment by evs-chris** [comment]
Do whatever works for your usecase :smile:. The downside would be if you want to deploy without parse support (runtime-only). It is also re-parsed any time a variable changes. You could also get crazy with triples if your content is simple. You can use any expression to get the partial, so you clean it up considerably with a function to generate the partial.

**Comment by paulocoghi** [comment]
@evs-chris Marty already solved this with his [dynamic component](http://stackoverflow.com/questions/31075341/how-to-create-ractives-subcomponents-dynamically-and-change-them-programmatical) (there is a nice snippet in the answer).

**Definition**
```javascript
Ractive.components.dynamic = Ractive.extend({
    template: '<component/>',
    components: {
        component: function() {
            return this.get( 'name' );
        }
    },
    oninit: function(){
        this.observe( 'name', function(){
            this.reset();
        }, { init: false });
    }
});
```

**And usage:**
```javascript
<dynamic name='{{name}}'/>
```

With it, I extrapolated this idea and create a completely opinionated front-end framework based on Ractive, with transparent route and dynamic components rendering according to route, along with ajax, local storage, jwt auth, middleware, automatic support for browser and devices (encapsulated with cordova, for example).

Of course it is completely open-source, but I was afraid to publish it here right now because there are still some work to do outside of the framework, including website, documentation, etc.

(also, I am an intermediate programmer, not an expert)

If everything goes well, in a week or two the site will be online with complete documentation and the first production release.

**Comment by evs-chris** [comment]
@paulocoghi I look forward to checking that out!
