### ISSUE TITLE
0.8.0: DEBUG mode console output & Ractive.parse

### ISSUE THREAD

**Issue by timoxley** [ractivejs/ractive#2701]
Since `0.8.0`, `Ractive.parse` generates a lot of noisy console output by default.

This is problematic when `Ractive.parse` is being used in node within a build tool e.g.

https://github.com/rstacruz/ractive-loader/pull/5

Yes, it's a simple fix to turn DEBUG mode off, but I'd suggest that Ractive was a better behaved API in `0.7.3`. In the browser, I can agree that `DEBUG=true` by default is fine, however when Ractive APIs are used in any other environment I'd suggest that having verbose logging on by default is generally considered poor behaviour.

**Comment by timoxley** [comment]
Note the 0.7.3 behaviour may have been less of a browser vs node thing and more a `Ractive()` vs `Ractive.parse()` thing. While turning debug logging off for `Ractive.parse` would resolve my immediate grievance, I believe it makes sense that Ractive should be quiet by default everywhere but the browser and even there, I'd be ok if debug mode were opt-in like most other tools.

**Comment by fskreuz** [comment]
Hmm... This sounds more like a tooling issue rather than Ractive itself. Ractive is not aware how it is being used by its dependents. So it might make sense for the dependent (in this case, the tool) to set the conditions instead of Ractive.

Instead of making Ractive do the decision, either:

- Have the tool turn if off,
- or have the tool suppress logging without completely turning off the option globally,
- or have the tool support turning off the errors via an option.
 
Prior to `0.7`, `debug` was by default `false`. There's a longer discussion about why `debug` was set to `true` in https://github.com/ractivejs/ractive/issues/1793

**Comment by evs-chris** [comment]
I could see where that would be quite painful parsing a large number of templates. How about a global option - something like `Ractive.WelcomeMessage` - that defaults to on that can be turned off by tools. That way you can still get deprecation and other warnings from your tooling? I'll have a PR shortly that includes some other useful debug stuff for parsing.
