### ISSUE TITLE
Ractive 0.8 doesn't fire `change` events for computeds

### ISSUE THREAD

**Issue by Jeff17Robbins** [ractivejs/ractive#2704]
## Description:
Ractive 0.8 doesn't fire `change` events for computeds.  
Ractive 0.7.3 does.
## Versions affected:
	Ractive.js v0.8.1-build-5
	Tue Oct 18 2016 15:28:26 GMT-0400 (EDT) - commit adbd4c06d169f8fcfbad1d5d7e42e3120f4e6934

## Platforms affected:
Windows 10 Chrome Version 54.0.2840.59 m
## Reproduction:
[Ractive 0.8 jsfiddle](https://jsfiddle.net/t3c2ayca/)
outputs
```
observe("derivedNum") callback: new value = 34 old value = 2 keypath = derivedNum

onChange handler: {"someNum":17}
```

[Ractive 0.7.3 jsfiddle](https://jsfiddle.net/5082do4q/)
outputs
```
observe("derivedNum") callback: new value = 34 old value = 2 keypath = derivedNum

onChange handler: {"someNum":17,"derivedNum":34}
```
NOTE that `derivedNum`, a computed, is delivered in the 0.7.3 onChange handler, but not delivered in the 0.8 onChange handler.  However, `observe('derivedNum', ...)` works in both versions of Ractive.
## **Code:**
HTML
```
<script src="https://unpkg.com/ractive@edge"></script>
<textarea style="width: 500px; height: 100px;"></textarea>
```
JavaScript
```
var storeA = new Ractive({
  modifyArrays: true,
  data: {
    someNum: 1
  },
  computed: {
    derivedNum: function() {
      return this.get('someNum') * 2;
    }
  }
});

var output = document.querySelector('textarea');
storeA.on('change', function(updates) {
  output.value = output.value + '\n' + 'onChange handler: ' + JSON.stringify(updates);
});

storeA.observe('derivedNum', function(n, o, k) {
  console.log('in observe of derivedNum with', 'new value =', n, 'old value =', o, 'keypath =', k);
  output.value = output.value + '\n' + 'observe("derivedNum") callback: new value = ' + n + ' old value = ' + o + ' keypath = ' + k + '\n';
}, {
  init: false
});

console.log("calling storeA.set('someNum', 17);");
storeA.set('someNum', 17);

```

**Comment by Jeff17Robbins** [comment]
Adding `this.registerChange(...)` to `Computation.prototype.handleChange(...)` might fix this.

```
  	Computation.prototype.handleChange = function handleChange$1 () {
  		this.dirty = true; 
  		this.registerChange( this.getKeypath(), value );
```

**Comment by evs-chris** [comment]
This one is tricky. Computations are now completely lazy, so the only place to check to see if the value has changed is when it is recomputed, which will never happen if the computation isn't used somewhere. If the only place it is used is in the template, then it will generate a second change event after its dependencies have fire their change, because template updates happen after the change event. If the computation is checked when it is marked as dirty, it will break the lazy functionality expected elsewhere. I have a patch that registers the change on recompute, and I'll go ahead and push it to dev. I don't think it's a decent long term solution though. 

An observer can successfully observe a computation because it can fetch the value to check it at the appropriate point in the cycle, whereas the change event is just a registry that holds values that it is given. I think this is ultimately why the change event code has comments saying that it needs to be deprecated.

I'm starting to think that dropping the change event and replacing it with something like `this.observe('**', () => ..., { links/mappings: true|false })` would be better. The '**' would register interest in _any_ keypath from this root, with optional inclusion of links and mappings. That way there is no hacky trying to force changes into the change event if they aren't needed (no subs), and if they are, it's explicit and can happen from one place instead of everywhere in the model code.

In your particular case, though, I believe cross-instance links are the answer. I have added a test to #2674 that verifies that it is possible to link another instance's root to a path in the local instance.

**Comment by Jeff17Robbins** [comment]
@evs-chris, I think I'm following you.  

What it sounds like is that, just because `Computation.prototype.handleChange(...)`  is called, doesn't mean that the computation has changed?  Instead, all it means is that a dependency of the computation has changed?

What continues to confuse me is that `Computation.prototype.handleChange(...)` starts with
```
  this.dirty = true;
```
which is why I thought it made sense to call `this.registerChange(...)`.  

What **does** `this.dirty = true;` mean?

**Comment by evs-chris** [comment]
Sounds like you've pretty much got it. `handleChange` means a dependency has changed, which _may_ mean that the computation's value will also change.

`this.dirty = true` just means that the next time the computation is fetched it needs to be recomputed i.e. it can't used the cached value like it usually does when something asks for the value. When `handleChange` is called, the computation notifies all of its dependencies, so as long as it has at least one dependency, be it an observer, some vdom, or another computation that has its own dependencies to trigger it to recompute, the computation will recompute and, with the lastest edge build, check to see if the value has changed to queue up a change for a change event.

Calling `registerChange` in `handleChange` will cause a bunch of false positive change events, especially if the computation has multiple dependencies that are closely related, such that it may be notified of multiple changes per cycle. Also, at the point of `handleChange`, the computation's value hasn't actually changed yet. My first attempt to address this was to force a recomputation at `handleChange`, but it broke a bunch of tests that ensure that computation stays lazy.
