### ISSUE TITLE
Input is not updating while focused

### ISSUE THREAD

**Issue by paulocoghi** [ractivejs/ractive#2712]
**Description:**
Inside an **observer**, using `ractive.set( 'number', this.phone_mask( newValue ) )` to apply a mask with an input using it:

```html
<input type="text" value="{{number}}">
```

The value showed is not updated in input while its focused. Instead, the correct value is shown only when input "focus out".

**Versions affected:**
0.8.1 (latest)
0.8.2-edge

In 0.7.3 it's working: http://jsfiddle.net/zbve5t49/13/

**Platforms affected:**
Chrome 55 and Firefox 49 (using Ubuntu 16.04)

**Reproduction:**
http://jsfiddle.net/zbve5t49/16/
_(in console it's possible to see that the data is updated inside Ractive)_

**Code:**

HTML
```html
<div id='container'></div>

<script id='template' type='text/ractive'>
    <input type="text" value="{{number}}">
</script>
```

Javascript
```javascript
var ractive = new Ractive({

    el: '#container',
    template: '#template',
    data: {
        number: '',
    },

    phone_mask: function ( v ) {

        v = v.replace( /\D/g,"" )
        v = v.replace( /^(\d{2})(\d)/g,"($1) $2" )
        v = v.replace( /(\d)(\d{4})$/,"$1-$2" )

        return v;
    },

    oncomplete: function () {
        var observer = this.observe( 'number', function( newValue, oldValue, keypath ) {
            if ( !this.get( 'masking' ) )
            {
                this.set( 'masking', true )
                this.set( 'number', this.phone_mask( newValue ) )
                this.set( 'masking', false )

                console.log( this.get( 'number' ) )
            }
        }.bind(this));
    }

});
```

**Comment by fskreuz** [comment]
🤔 not sure if the demo is working...

**Comment by paulocoghi** [comment]
@fskreuz Updated. In Firefox, the Ractive JS file was not loading due to invalid SSL certificate. I replaced `https` to `http` and everything is working now in Firefox too.

**Comment by paulocoghi** [comment]
In new tests, I realized that in 0.7.3 everything works fine.
http://jsfiddle.net/zbve5t49/12/

**Comment by paulocoghi** [comment]
**New information:**

In **0.7.3**, it only works with `defer: true`.

In **0.8.1** (latest) or in **0.8.2-edge** it doesn't work in all cases, with or without `defer: true`

**Comment by evs-chris** [comment]
This is one of those things that _mostly_ works in 0.7.3, but there are some really funky issues with letting an observer update the value that it is observing, especially when that value is participating in a two-way binding. Notably, it works mostly fine on 0.7.3, but _only_ if you're typing at the end of the input. Notice that if you move the cursor back a few characters and start typing, only the first keystroke will land in the right place and the rest move to the end.

I think that a decorator is more suited to handling live formatting of a two-way bound input. Of course, someone smarter than me (and there is a vast multitude that fits that description :smile:) could figure out how to handle wacky locking issues involved. The test suite is actually pretty good in this area, since it popped up a lot on the path to 0.8.

**Comment by paulocoghi** [comment]
Thanks again, @evs-chris !

Since this particular use case is not recommended and there is a better way to do this, I will close this issue.

**Comment by fskreuz** [comment]
I've been around discussions where input masks were recommended be done in either a custom component or a decorator that wraps a third-party masking library. It's simpler since all Ractive does is pass in and accept the underlying data (the raw phone number) while the masking lib does the input magic that it does well.

**Comment by paulocoghi** [comment]
@fskreuz Thanks for the info! Using or building decorators is the way to go :)
