### ISSUE TITLE
observors do not fire if registered during onconfig

### ISSUE THREAD

**Issue by ADantes** [ractivejs/ractive#2725]
## Description:

`observeOnce` appears to do nothing if called during `onconfig`.  `observe` triggers immediately, but does not listen for subsequent updates.
## Versions affected:

0.8.2
## **Code:**

I would expect to the console output to be "OBSERVE", "OBSERVE", "OBSERVE ONCE".  Instead, it just outputs "OBSERVE" once.

```
new Ractive({
  onconfig: function() {
    this.observe("test", function() {
      console.log("OBSERVE");
    });
    this.observeOnce("test", function() {
      console.log("OBSERVE ONCE");
    });

    this.set("test", "foobar");
  }
});
```

0.8.2: https://jsfiddle.net/u5d0b5yt/
0.7.3: https://jsfiddle.net/smfwt4h8/

**Comment by mefjuu** [comment]
It's always better to initialize data.

https://jsfiddle.net/u5d0b5yt/1/

After doing it, observeOnce works.

**Comment by evs-chris** [comment]
_Technically_ `onconfig` should not allow observers or events to be registered at all, based on the original lifecycle events PR #1256, because the viewmodel isn't fully initialized at that point. The place for those would be `oninit`. I think the docs could probably be a bit better, and this should probably throw an error or log a warning.

`onconstruct` would be used to mangle the options object that is passed to `new Ractive`.
`onconfig` would be used to do any setup that needs to happen before the view is created but after any inherited config is processed, like looking for missing partials, or injecting template.
`oninit` the instance is fully set up, but nothing is rendered, so you can subscribe to events and observers and generally interact with the instance as if it were created without a target.

**Comment by evs-chris** [comment]
After the bit of refactoring on edge observers, this now works :smile:
