### ISSUE TITLE
Question: Links for stable and edge

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2737]
For some time now I was using http://cdn.ractivejs.org/edge/ractive.min.js to download and test the new versions. From what I can tell by reading some of the issues here, is that version has progressed to 0.8.3 or maybe 0.8.4?

http://cdn.ractivejs.org/latest/ractive.min.js has the 0.8.1 version which is outdated.

So where to get latest stable and edge versions?
Also there seems to be an 0.9 version?

Thanks.

**Comment by ghost** [comment]
Hmm... Looks like the docs need updating.

@evs-chris moved to using unpkg which is more updated. It's found in the [Published Versions](https://github.com/ractivejs/ractive#published-versions) section of the readme. 😄

**Comment by kouts** [comment]
Ahhh ok, thanks @fskreuz, so where is the edge build now?
When I click on https://unpkg.com/ractive@edge the version I get is v0.8.2-edge.
Shouldn't it be 0.8.4 or something?

**Comment by evs-chris** [comment]
Yep, we're just publishing to npm now, which has to be done for tooling anyways, and whatever cdns pick us up from there or our build tags on this repo are what we're recommending. We've moved in that direction because cd.ractivejs.org has no cert to handle TLS, which has become problematic in the https-everywhere age.

There is a 0.9 build and there will be another out soon. You can get the full list from npm with `npm show ractive versions`. Unreleased builds have a `-build-1` (where the 1 becomes the actual build number) appended so they don't move latest ahead before the release. That gives a bit more stability than just targeting an edge build, since `0.9.0-build-1` will exist as it is now until the end of npm. You can be sure that no extra bugs will pop up suddenly.

I'm not really sure how best to announce changes like this, which is why it only showed up in the readme, in a few issues, and in the github templates for issues and PRs. What do most people look at for news? I suppose we could do a `NEWS.md` to follow non-code changes. We could also just drop them in the changelog. If someone would like to do blog entries from time to time, that would probably work too.

**Comment by evs-chris** [comment]
I'm still trying to figure out how best to move the numbers along. There isn't an edge build right now, because I've been publishing patches on the 0.8 line relatively quickly. Publishing to npm isn't automated yet, but I'm hoping to get travis to publish `edge` and `next` builds for us. For now, I'm using `edge` to mean "the latest un-published build in the stable line" and `next` to mean "the latest un-published build in the dev line". There are some pretty breaking changes between 0.8 and 0.9 already. Would welcome any input on how to better handle publishing version numbers :smile:

**Comment by ghost** [comment]
> What do most people look at for news?

Twitter and NPM (via `ncu`) 😄 

> If someone would like to do blog entries from time to time, that would probably work too.

I can probably do that. 😄

**Comment by kouts** [comment]
@evs-chris one more time thanks for your great work, It would be great if there were direct links for edge, next and 0.9 builds for easy testing among projects.

**Comment by evs-chris** [comment]
I've adjusted tagging for releases and updated the readme. Here's the scheme:
- The latest dev build for a series (say 0.8) is tagged as `v0.8-dev`. So if there is a `0.8.5-build-1`, it will also be tagged as `v0.8-dev`.
- The latest `dev` branch build is tagged as `edge`, so as of right now, `0.9.0-build-2` is tagged as both `edge` and `v0.9-dev`.
- A released build also updates the dev tag, so as of right now, `0.8.4` is also tagged `v0.8-dev`, as it's the latest available build in the 0.8 series.

latest (stable): https://unpkg.com/ractive
latest (potentially unstable) for 0.8: https://unpkg.com/ractive@v0.8-dev
edge (potentially unstable) for 0.9: https://unpkg.com/ractive@v0.9-dev
bleeding edge: https://unpkg.com/ractive@edge
