### ISSUE TITLE
Binding for input type='file' does not work on ractive 0.8

### ISSUE THREAD

**Issue by harry-bix** [ractivejs/ractive#2739]
## Description:
Read Binding for
  <input type='file' value='{{fileList}}'>
returns empty string with 0.8 and FileList on 0.7

## Versions affected:
0.8

**Comment by ghost** [comment]
Sounds like a possible bug, but can we confirm it through a demo? A JSFiddle perhaps?

**Comment by mpowell-atomic** [comment]
0.83: https://jsfiddle.net/fLzodg8m/
0.73: https://jsfiddle.net/8dghs1r6/

**Comment by evs-chris** [comment]
I think the pre-0.8 behavior was actually undefined, so I'm not entirely sure what to do with this. File inputs are read-only, so a binding, which is either twoway (ractive <-> input) or one way (ractive -> input), doesn't really make sense. I suppose we could special case the file input value binding so that it does a backwards one way binding (input -> ractive).

An on-change event seems more appropriate, but I don't suppose it would hurt to do the backwards binding as long as it's documented. Any thoughts or opinions?

**Comment by evs-chris** [comment]
It seems that neither of those fiddles works in chrome (no open dialog), but the 0.7 fiddle does seem to work in firefox.

**Comment by ghost** [comment]
I'm on Opera on Windows (essentially a red Chrome 😄 ). The 0.7 fiddle does return a FileList. The 0.8 doesn't fire the observer at all.

**Comment by ghost** [comment]
If I remember correctly, I dealt with file uploads before. But I'm not sure if I used binding or if I just wrapped the input in a component and used events to know when to extract the data manually.

In the mean time, events+manual extraction (hook an on-change on the input, extract the FileList from the input manually when it fires, no binding) would be the best workaround until this gets fixed.

**Comment by evs-chris** [comment]
Here's what I'd recommend as the workaround until the issue is resolved: `<input type="file" on-change="event.set('.fileList', event.node.files)" />`. https://jsfiddle.net/fLzodg8m/1/

**Comment by evs-chris** [comment]
I've added a special binding class for file inputs that sets the model to the files property of the input to mirror the behavior in 0.7. This will go out with 0.8.4. There's not really a way to test this beyond trying it out in a sample, unfortunately, so I couldn't add a regression test.
