### ISSUE TITLE
view not updating when elements changed in loop

### ISSUE THREAD

**Issue by hradhak** [ractivejs/ractive#2740]
## Description:
I upgraded to 0.8.3 from 0.7.3 and I've noticed some unexpected behavior.  If I set an array on ractive and then later add items to that array asynchronously (say after an ajax call), Ractive used to update the view layer as I pushed those objects.  Now I have to explicitly set the variable on ractive (or call ractive.update) to update the view.  

I was unsure if this is expected behavior or if I needed to set a configuration to use the same behavior that was in 0.7.3.   I'm also not sure if this is a bug, but I've encountered this in other areas, and have either had to rewrite code, or force the view layer to update with ractive.update()

## Versions affected:
Ractive 0.8.3
Ractive 0.8.1
## **Code:**
```    
      find: function() {
            var _this = this;
            var search = this.get('search');

            var _id = uuid();
            var out = [];

            $.ajax({
                url: "/ajaxurl/",
                data: {
                    q: search
                }
            }).done(function (data) {
                data.results.forEach(function (result) {
                    out.push(result);
                });

                // _this.set('searchResults', out); , <- this will update the view layer with 0.8.3 and 0.7.3
            });

            this.set('searchResults', out); <- this will only update the view layer with 0.7.3;  0.8.1 and 0.8.3 will not update
        }
```

**Comment by evs-chris** [comment]
This is intentional and listed as a breaking change in the changelog, I think. You can get the old behavior back by passing `modifyArrays: true` as an init option. The reason `modifyArrays` is now defaulted to false is that it's a bit heavier than you would expect, and it is set to be pulled out of the main code base into a plugin in a future release. `magic` will also be pulled into a plugin.

The idiomatic way to handle this would be to use `this.push('searchResults', result)` for each data result. Or even better, skip the forEach and use

``` js
// put the keypath to push to as the first arg
data.results.unshift('searchResults');
// apply the push with all results pushed at once, so only one update :)
this.push.apply(this, data.results);
```

**Comment by hradhak** [comment]
Thanks for the super fast reply.  I read through [here](http://docs.ractivejs.org/edge/migrating) but it didn't register when I read through it.     This is pretty clear in the docs related to [options](http://docs.ractivejs.org/edge/options#modifyArrays), so I will close my issue.
