### ISSUE TITLE
Ractive.reset() doesn't reset as hard as it used to between 0.7 and 0.8

### ISSUE THREAD

**Issue by TehShrike** [ractivejs/ractive#2742]
I have functions on my data object that return values based on external state (the current url).

I occasionally call `ractive.reset` based on lifecycle events when the route changes.

## Some dummy example code

```js
var ParentRactive = Ractive.extend({
  data: {
    someFunction: function() {
      return // the current url or whatever
    }
  }
})

var ractive = new ParentRactive({
	template: 'Totally legit value: {{someFunction()}}',
})

setInterval(function() {
	ractive.reset()
}, 1000)
```

In Ractive 0.7.x, calling `reset` would cause `someFunction()` to be re-evaluated, at least the first time reset was called.

In Ractive 0.8.3, `someFunction` is only called once.

## Reproduction

- [0.7.3 jsfiddle](https://jsfiddle.net/juuh15Lu/3/): the counter is incremented in the view the first time `reset` is called
- [0.8.3 jsfiddle](https://jsfiddle.net/9u7axqej/3/): the counter is not incremented when `reset` is called

## Question

What is the correct way to cause function calls to be re-evaluated?

Or, since I'm starting to doubt that having my components extend a parent object with functions to represent external state was the correct idea:

What is the best way to reference external state in a template expression?

**Comment by evs-chris** [comment]
I'll look into the reset, because it looks like that should work. Reset probably isn't the best approach to that though, as it destroys the world and recreates it. Sharing data across instances is one of the things 0.9 is trying to improve.

There are two approaches available in 0.8, both of which are based on the same method of updating, namely, capture. You could move the counter to a global variable, which would track if you're bringing in `window.location` or something like that. Then you can just `ractive.update('@global.whatever')`, and since the global model is shared among all ractive instances (assuming you don't have multiple versions of ractive loaded), everything in every instance that references `@global.whatever` will update.

The less anti-pattern way to handle it would be to use capture with a base instance. Basically, you create a non-rendered instance and set a reset flag in its data. You can then reference that flag from your function, which will cause the reset flag to be captured, and any update to the flag will cause the function to re-evaluate where it's referenced. I'm lousy at explaining, so I tweaked your fiddle: https://jsfiddle.net/9u7axqej/4/

In 0.9, depending on exactly what you're trying to do, this may become much, much simpler, though you still have a base instance from which to share data. The cross-instance capture approach will also continue to work going forward.

**Comment by TehShrike** [comment]
`reset` is actually appropriate for different reasons - in this case, the route change has resulted in me displaying the same component, but with an entirely different/new state.  Whatever I end up using to get the function to evaluate, I'll need to keep calling `reset`.

I should have given you more details on the function instead of XYing you - the function in this case takes inputs from the template in beyond just looking at global state - it's actually a function that generates links for `a href`s based on the states that have been set up.  It ends up being more like

``` js
generateUrlForAHref('name-of-destination-state', 
  { someParam: 'someValue', otherParam: 'wat' }, 
  { inheritParametersFromCurrentUrl: true })
// => '/route-for-that-state/someValue?otherParam=wat
```

where all of the information about routes and destination states is stored in another library, away from the view.  [Example here](https://github.com/TehShrike/state-router-example/blob/1862d0346e288de8c96743602a74bc962e9214e7/implementations/ractive/app/app.html#L6)

That example of yours is blowing my mind, I had no idea that Ractive would track dependencies across components like that!  I should be able to get that to work pretty easily for my case.  Thanks!

I'll be interested to hear what changed with `reset`.

**Comment by evs-chris** [comment]
I've poked through it, and the thing that changed is that resetting data is no longer a "wipe the cache and start over thing". 0.8 keeps track of its data via a tree of model objects, each of which is responsible for a specific keypath. 0.7 keeps track of its data in a giant hashmap, where each key is the keypath. `reset` on 0.8 basically says "I've got new data, propagate the changes", as opposed to "I've got new data, throw the cache away and recompute everything".

The reason the function isn't run again is that it is strict equal to the original function, which ractive sees as a sign that nothing needs to happen, as nothing has actually changed. If you use a data function, the reset works as expected because the new function !== the old function: https://jsfiddle.net/9u7axqej/5/

Things like this have come up a lot in the transition from 0.7 to 0.8. I'm not sure if the new behavior is incorrect, or if the old behavior was just poorly defined in some areas due to side-effects from the implementation. :confused:

**Comment by TehShrike** [comment]
This definitely feels like a weird side effect that just happened to work for me.  I was surprised when I made the jsfiddles that the counter only incremented once in 0.7, I had been assuming that it would keep incrementing indefinitely.  I get the impression that I was lucky that it did what I wanted whenever I was noticing.

If there was a new "definitely recalculate every single thing" method, using it would be an antipattern in the general case, even if the framework I'm using does have a good excuse to call it here.

I think making my function have a dependency on a non-rendered instance is the best solution for my current case, I'll give that a try tonight.

Thanks so much for the help!
