### ISSUE TITLE
How can I push 2 way mustache templates into components? 

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#2759]
How can I achieve this behaviour: http://jsfiddle.net/vgtf1rbo/1/

**Comment by ghost** [comment]
I have no answer from the top of my head. Dynamic partials/components come into mind but not sure. 🤔 

http://docs.ractivejs.org/latest/advanced-configuration

**Comment by evs-chris** [comment]
Do you trust your data? I'm guessing you do if you want to run it as template, so you can do just that with a literal partial: http://jsfiddle.net/vgtf1rbo/2/

That could be done a bit more efficiently by detecting mustaches in the strings to render a partial. It also will never be CSP no eval if there are expressions in the template, because there's no way to pre-parse dynamic data.

Beyond that, you could have a cell component with a dynamic template based on whatever data it is passed. That's a bit heavier than a partial literal, but some may consider it a cleaner approach.

**Comment by ceremcem** [comment]
Hmm... I didn't think about SQL injection like vulnerability... But answer satisfies very well for my specific purpose. 

Thank you.
