### ISSUE TITLE
0.8.4 - Decorator priority on input field

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2762]
Check this fiddle: [http://jsfiddle.net/jfwsaemk/](http://jsfiddle.net/jfwsaemk/)
When you enter a value in the first input field all is well.
When you enter a value in the second input field (which uses the same keypath as the first input),
it seems that first input takes precedence over the second one so the value never changes.

**Comment by evs-chris** [comment]
I think this may be a locking issue with the decorator. Since both fields are updating and bring updated by the same source, they are fighting through the effectively shared two way binding.

**Comment by kouts** [comment]
So, is there a way to have a formatting decorator in two or more input fields that share the same data binding?

**Comment by evs-chris** [comment]
My jquery is super rusty, but I _think_ this does what you're after: http://jsfiddle.net/jfwsaemk/1/

Basically, for this kind of thing, it's easier to let the decorator handle the binding instead of fighting with the built-in binding, which doesn't play very well with having multiple things update its underlying model at the same time. One of those observers modifying the observed value things.

The main failing in the node info api is that there isn't an `info.observe('.relative.path', ...)`, which should probably be addressed. So you you can't use this decorator in a expression context, even though that's possible again in 0.9. I also forgot to `info.resolve(keypath)` for the observer, just in case it's a relative keypath.

**Comment by kouts** [comment]
Thanks @evs-chris , this does not solve it, but I'm going to close this since it seems that it is impossible to achieve this kind of behavior.

**Comment by evs-chris** [comment]
@kouts I played around a little more with it... is this closer? http://jsfiddle.net/jfwsaemk/4/

**Comment by kouts** [comment]
@evs-chris close enough but this doesn't update if value is updated programmatically e.g:
[http://jsfiddle.net/85scbbaL/1/](http://jsfiddle.net/85scbbaL/1/) :wink:

**Comment by evs-chris** [comment]
`autoNumeric` doesn't like to fire change events :smile:

Try this out: http://jsfiddle.net/85scbbaL/2/

It can get a bit weird around the decimal point because it's updating itself, but you _could_ work around that by making it lazy (don't subscribe the input event).

**Comment by kouts** [comment]
Thanks @evs-chris your help is more than appreciated.
