### ISSUE TITLE
Event Bubbling from {{>content}} to `ractive` instance

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#2793]
## Description:

Let's explain with actual problem: 

I needed to define a page component that will show and hide its content: 

```
<page name="one" curr="{{selected}}"> <p on-click="hello"> Page 1: I'm {{ visible? 'visible' : 'hidden' }} </p></page>
<page name="two" curr="{{selected}}"> <p on-click="hello2"> Page 2: I'm {{ visible? 'visible' : 'hidden' }} </p></page>
```

`hello` and `hello2` handlers are defined in `ractive = new Ractive(...)` instance, so I should define `<page>` component with `{{yield}}`: 

```
<div style="{{#if isHidden(curr)}}border: 1px solid red{{/if}}"> {{yield}} </div>
```

```
isHidden: function(curr) {
    name = this.get('name');
    visible = curr === name;
    this.set('visible', visible);
    return visible
}

```

This way, if `name is curr` then content is shown, else hidden (hidden = red border). If you click any of `<p>` element, appropriate event is fired. 

Problem is, they both displays "I'm visible" string. 

If I change `{{yield}}` with `{{>content}}`, last problem disappears and they show "I'm visible" or "I'm hidden" strings correctly, but when clicked, no events fired. 

I found [this](http://stackoverflow.com/a/25575481/1952991) answer of @MartinKolarik but it complicates things. 

Is there any plans to provide something like: 

```
<div ...>
    {{yield {visible: visible, otherVar: somethingOther} }}
</div>
```

**Edit**

Original `<page>` component is [here](https://github.com/aktos-io/aktos-scada2/tree/master/src/client/components/page). 

**Edit-2**

Or maybe we could define events as objects: 

```
ractive.on({
  a: {
    b: function(){ console.log("I'm b!"),
    c: function(){ console.log("I'm b!")
  }
});
```
and use it like: 

```
<page on-a="a"> 
    <p on-click="a.b"> this is a.b! </p> 
    <p on-click="a.c"> this is a.c! </p> 
</page>
```

## Versions affected:
0.8.5

**Comment by ghost** [comment]
Top of my head (I'll try it out in a fiddle in a bit), if you go the `{{> content }}` route, you can probably take advantage of bubbling. You can listen to the `hello` and `hello2` on the enclosing instance by namespacing the events `page.hello` and `page.hello2`, or `*.hello` and `*.hello2`.

Delegated listeners require a namespace. Otherwise, without it, the handler is treated as listening to something on the current instance rather than from a descendant.

```js
this.on('something', function(){ /* listens from the current instance */ });

this.on('page.something', function(){ /* listens for something from a page component descendant */ });

this.on('*.something', function(){ /* listens for something from any descendant */ });
```

**Comment by ghost** [comment]
With `{{> content }}`, logic goes in `<page>`, and you use bubbling to capture the event. https://jsfiddle.net/o23g0eay/3/

```js
Ractive.components.page = Ractive.extend({
  template: `
    <div style="{{#if !isVisible }}opacity: 0.5{{/if}}">
      {{> content}}
    </div>
  `,
  computed: {
    isVisible() {
      return this.get('curr') === this.get('name');
    }
  },
  data: {
    curr: '',
    name: ''
  }
});

new Ractive({
  el: 'body',
  template: `
    <button type="button" on-click="@this.set('selected', 'one')">Select one</button>
    <button type="button" on-click="@this.set('selected', 'two')">Select two</button>
    
    <page name="one" curr="{{selected}}">
    	<p on-click="hello"> Page 1 (hello): I'm {{ isVisible ? 'visible' : 'hidden' }}</p>
    </page>
    <page name="two" curr="{{selected}}">
    	<p on-click="hello2"> Page 2 (hello2): I'm {{ isVisible ? 'visible' : 'hidden' }}</p>
    </page>
  `,
  data: {
    selected: 'one'
  },
  oninit() {
    this.on('page.hello', () => {
      console.log('hello');
    });
    this.on('page.hello2', () => {
      console.log('hello2');
    });
  }
});
```

With `{{yield}}`, you just move out the logic, no bubbling required. https://jsfiddle.net/o23g0eay/4/

```js
Ractive.components.page = Ractive.extend({
  template: `
    <div style="{{#if !isVisible }}opacity: 0.5{{/if}}">
      {{ yield }}
    </div>
  `,
  data: {
    isVisible: false
  }
});

new Ractive({
  el: 'body',
  template: `
    <button type="button" on-click="@this.set('selected', 'one')">Select one</button>
    <button type="button" on-click="@this.set('selected', 'two')">Select two</button>
    
    <page isVisible="{{ selected === 'one' }}">
    	<p on-click="hello"> Page 1 (hello): I'm {{ selected === 'one' ? 'visible' : 'hidden' }}</p>
    </page>
    <page isVisible="{{ selected === 'two' }}">
    	<p on-click="hello2"> Page 2 (hello2): I'm {{ selected === 'two' ? 'visible' : 'hidden' }}</p>
    </page>
  `,
  data: {
    selected: 'one'
  },
  oninit() {
    this.on('hello', () => {
      console.log('hello');
    });
    this.on('hello2', () => {
      console.log('hello2');
    });
  }
});
```

**Comment by ghost** [comment]
Just to point out one more thing:

```
isHidden: function(curr) {
    name = this.get('name');
    visible = curr === name;
    this.set('visible', visible);
    return visible
}
```

It looks like visibility is a function of the name and the current selection. To avoid cases where selection, name and visibility go out of sync, visibility should be a computed property or an expression (as seen in the examples above). 😄

**Comment by ceremcem** [comment]
@fskreuz [This](https://jsfiddle.net/o23g0eay/3/) is exactly what I needed. In order to write clean codes in `<page>` component, I should stick with `{{>content}}` way.  Thank you :+1: 

When I understand how the computed properties work and when I should choose them, I believe I will refactor whole application :))

**Comment by evs-chris** [comment]
I have but two things to add:

1. You _can_ fire and subscribe to namespaced events, so from the `{{yield}}` `<page ...><p on-click="a.hello">...</p></page>` can be subscribed with `this.on( 'a.hello', ... )` or `this.on( '*.hello', ... )`, and the `*` form will also pick up bubbled events as would be fired by the `{{>content}}` version.

2. edge (0.9) has (experimental, meaning feedback welcome) yielded aliases, so that the component can inject variables into the yielded content, so the page component can do `{{yield with visable as visable, somethingOther as othervVar}}` and the yielded content can access them `<page>here is {{visible}} and {{otherVar}}</page>`. They're also available in named yields `{{yield foo with something as name}}` -> `<cmp>{{#partial foo}}here's {{name}}{{/partial}}</cmp>`. This is particularly handy for yielding inside an iteration, where the context belongs to the owner, but the component needs to contribute something as well.
