### ISSUE TITLE
Removing a few magical features

### ISSUE THREAD

**Issue by ghost** [ractivejs/ractive#2798]
## Description:

- **Magic mode** - Ractive detecting direct object mutation.
    - Ractive must know about the properties in advance.
    - Can't set new properties directly.
    - Individual setting of properties causes separate renders.
    - Nothing a `ractive.set()` can't do.

- **Array Modification** - Ractive detecting direct array mutation.
    - `__proto__`-modification code. On IE, it's array-modification code.
    - Doesn't really support all array methods, ie `array.fill()`, `array.concat()`
    - There are equivalent instance methods. Much more explicit in saying what is supported.

- **Deprecation warning system** - Ractive throwing friendly warnings on deprecations.
    - If a developer is keen on upgrading, they read change logs, not update and pray.

Ideas are welcome. 😄

**Comment by evs-chris** [comment]
Two more for consideration, though I'm not sure how magical they are:

* __Ambiguous resolution__, which causes all manner of confusion among users, adds quite a bit of complexity to the (Ractive) code, and is the source of some fairly large performance penalties in some situations.
* __Implicit mappings__, which also cause confusion for component users, add a bunch of extra complexity to the (Ractive) code, and add significant performance overhead, especially when combined with ambiguous references.

For the magic and array adaptors, I'd like to distill an API good enough to handle them, a good firebase adaptor, and a proxy-based magic mode for 0.10.

**Comment by ghost** [comment]
Does this mean components become isolated (which also gets rid of `isolated`) by default and that step 7-9 in [reference resolution](http://docs.ractivejs.org/latest/references) won't happen anymore? If so, I'm in 👍 .

**Comment by evs-chris** [comment]
Well, it doesn't quite get rid of `isolated`, which also controls whether or not components inherit _other_ stuff, like adaptors.

It looks like you added `ractive.data` in an edit, but I think it's already removed in edge? I thought that was one of the deprecations I cleaned out.

I was curious, so I created a branch that strips out the array and magic adaptors, removes support for resolving ambiguous references, removes support for implicit mappings, and removes support for keypath expressions (bet you don't even know what those are :smile:) over here: https://github.com/ractivejs/ractive/tree/less-magic. There were a few tests that had to be updated (~50) because they were relying on ambiguous resolution. The rest were specifically testing one of the removed features.

Having fiddled through updating the test suite, I can say that there are a few places where ambiguous references are pretty convenient, particularly around iterative structures. I think adding a `helpers` holding area would go a ways toward handling that and would be very light on code. I don't know how well the community would react to _another_ place to put stuff, though `helpers` has been specifically requested before.

Adding a shorthand for component bindings would go a long way too. Perhaps just having `<cmp foo />` be equivalent to `<cmp foo="{{foo}}" />` would work. I don't think I've ever seen a boolean attribute on a component in the wild, and the syntax has some sort of precedent with ES6 `{ foo }`.

For the curious, the new branch builds to 197K minified or 57K gzipped, versus 208K and 61K for edge. There's also a bit of a perf increase from not having to do all the extra work involved with accounting for unresolved things that may resolve later, especially around mappings.

**Comment by ghost** [comment]
> Well, it doesn't quite get rid of isolated, which also controls whether or not components inherit other stuff, like adaptors.

Oh yeah. 😱 

> It looks like you added ractive.data in an edit, but I think it's already removed in edge? I thought that was one of the deprecations I cleaned out.

I was looking at https://github.com/ractivejs/ractive/issues/2799 . Forgot it was 0.8.x. 😁 

> bet you don't even know what those are 

Only a few days ago did I learn that magic and array modifiers were just adaptors under the hood. 😄 

"keypath expressions"... wassat? 😄 Lemme give a good guess... array notation? 😁 

These things are probably beyond me at the moment. Still studying the source and [sifting through docs](https://ractive-docs.readthedocs.io/en/rtd/). I _might_ be using them but don't really know what they're called. 😄 

> I think adding a helpers holding area would go a ways toward handling that and would be very light on code.

Helpers like handlebars helpers? Don't we already have methods that does an all-around job of methods, formatter, custom logic, event handler etc.? Reminds me of this Svelte thread: https://github.com/sveltejs/svelte/issues/166

> Adding a shorthand for component bindings would go a long way too.

Too boolean-looking for me though.

> the new branch builds to 197K minified

🎉

**Comment by tomekmarchi** [comment]
Let the witch hunt begin!

**Comment by sarendipitee** [comment]
>removes support for resolving ambiguous references

How do you specify something should use a computed over a keypath with the same name at the root?

How do you specify that a keypath should take one reference over another if exists? E.g., `{{ .foo || ~/foo}}` : use `foo` on this object if exists, else use the root `foo`. I'm pretty sure something like that has not worked correctly for me in many cases and I ended up having to use an ambig ref `{{foo}}` to get around it.

**Comment by evs-chris** [comment]
> How do you specify something should use a computed over a keypath with the same name at the root?

Computeds always take precedent. That's more a function of the model than the resolution though, as the resolution process just asks the model if it has a matching key. It doesn't care what kind beyond that.

> I'm pretty sure something like that has not worked correctly for me in many cases and I ended up having to use an ambig ref

Yeah, there's a bit of fuzzyness to a few things, which is why I didn't open a PR. I just wanted to see what it would look like :smile:. I think the best approach is a sort of hybrid, where ambiguous refs can resolve from context, but they don't sit around unresolved waiting for a keypath to grow somewhere. Putting back immediate ambiguity would be a comparatively tiny change, and if nothing resolves, I think it'd be safe to use the immediate context.

Dropping all the fluff around component boundaries and implicit mappings also resulted in a huge clarity increase in quite a few places.

**Comment by sarendipitee** [comment]
👍 

It's definitely cleaner. Maybe let's do the magic/array adaptors sweep, then do another round for ambig refs and implicit mappings? I think magic/array can be done very cleanly without a lot of disruption, but there will be some weirdness with changing ambig refs for now (and possibly breaking?)

**Comment by dagnelies** [comment]
> Magic mode / Array Modification

I don't personally use it. ...but the reason is solely because it was fairly buggy when I started with ractive. I think it's a fairly attractive feature, but if it's a source of complexity / unexpected behaviors / bugs, then I'd vote to remove it too.

> Getting rid of deprecation warning system

Oh no! :scream: For those maintaining big apps based on ractive, updates are a pain. In the past, there were all sorts of changes from version to version, mostly undocumented. Having deprecation warnings is a life saver! I'd vote in favor of the deprecation system.

> Ambiguous resolution

How does that happen actually? I thought it's clearly defined:

- look at the local scope
- move up until you find it
- if it doesn't exist and bound to a value, create it in local scope

...is it not? Can you show us a few examples of what's ambiguous?

...if it breaks normal mustache templates, which it probably does, I'd vote against. Instead, I'd look into whether the resolution process can be made simpler and more obvious.

> Implicit mappings

I don't know what that is. Can you show an example?

> getting rid of `isolated`

I think that's a wise choice actually. Components are cleaner that way and the benefits probably outweights the disadvantages by far. It would surely simplify the resolution process as well. Deprecate it in 0.9 and get rid of it in 0.10. ;)

**Comment by ghost** [comment]
> I think it's a fairly attractive feature, but if it's a source of complexity / unexpected behaviors / bugs

Yep, my thoughts exactly. It's great when it works, it's terrible when it doesn't. Also, there's too much explanation of the edge cases and warnings in the docs enough to scare away potential users.

> Having deprecation warnings is a life saver!

Instead of removal, wondering if it can be pushed over to https://github.com/ractivejs/ractive/issues/2733 , as part of an optional debugging extension. There, deprecation warnings, friendly error logging, etc. can live separately from core, removable during production.

> How does that happen actually?

I think it's step 9 in the [References](http://docs.ractivejs.org/latest/references) page. 

>> If the reference is still unresolved, add it to the 'pending resolution' pile. Each time potentially matching keypaths are updated, resolution will be attempted for the unresolved reference.

Pretty much how @evs-chris describes it, "sits around unresolved waiting for a keypath to grow somewhere".

I think an example (and correct me if I'm wrong) would be a mustache that's already rendered on page, but has a reference to a keypath that doesn't exist at that moment. That reference sits around and resolution is retried in an attempt to render something in case they keypath now has something. When exactly that resolution happens (which operation causes it), I know not when... yet. 😄

**Comment by paulocoghi** [comment]
> Instead of removal, wondering if it can be pushed over to #2733 , as part of an optional debugging extension. There, deprecation warnings, friendly error logging, etc. can live separately from core, removable during production.

An optional debug extension is the best of both worlds, and I totally agree.

**Comment by evs-chris** [comment]
Another candidate for removal: live queries. A live query is a `findAll` or `findAllComponents` query that when passed `{ live: true }`, will keep the returned array up to date as new elements/components are added and removed. Note that there is no notification that goes along with that, it just keeps the array updated, and doing so adds a fair bit of housekeeping every time an element/component is added or removed. That housekeeping happens whether you're using live queries or not.

So, is anyone using live queries or would object to them being removed? I can't imagine needing a number of arbitrary queries kept up to date, so a decorator that tracks elements would probably be better for the `findAll` case. For components, listening for the appropriate `render` events at the root would work. Both of those replacements have the benefit of actually allowing for a callback to be fired when something actually changes.

I would also like to note that there's some really funky code that supports live queries to keep the array elements in the right order. See [Query.js](https://github.com/ractivejs/ractive/blob/dev/src/Ractive/prototype/shared/Query.js)

**Comment by paulocoghi** [comment]
@evs-chris  I've never used live queries.

**Comment by ghost** [comment]
I've never found a use case, even with the native equivalents, for live lists. It's quite strange to have an API that at one point only returned a set number of elements and then a few unrelated operations later, magically grew a dozen more. Live lists are also a mysterious cause of infinite loops, one I find commonly asked over at Stack Overflow.

Also, a big 👍  if this equates to performance.

**Comment by dagnelies** [comment]
Never heard of that `{live:true}` parameter before. Why was it implemented in the first place?

**Comment by evs-chris** [comment]
@dagnelies ¯\_(ツ)_/¯ it's been around forever, or at least as long as I've worked with Ractive. I would guess it was useful for a Guardian project way back when.

**Comment by dagnelies** [comment]
Indeed, it seems to come from #91:
Commit: https://github.com/ractivejs/ractive/commit/a080aed26baf7fc421b77b1547b6d636aadaf12a
...seems obsolete to me too ...but it's always difficult to guess with such things. I would already mark it as deprecated, perhaps someone will pop up here if it's really used.
