### ISSUE TITLE
How to detect if component has custom event in template?

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#2799]
## Description:
How can I detect in component if the component (instance) itself has `on-myevent="someEvent"` defined in the template? 

### Rationale

I want to define a component (a checkbox component, for instance) that it will toggle "checked" attribute on every press **if it doesn't have any external handler**, else, it will not touch `checked` variable and will only fire `on-statechange=` event and let this external event handle/change its `checked` state. 

## Versions affected:
0.8.7

## Reproduction:
https://jsfiddle.net/6hyad9fu/

**Comment by evs-chris** [comment]
There's not really a supported way to do this. You can muck about in the internals of the component a bit and find out if there's a matching subscriber, but it's actually less simple than even that, since there may be a starred (`*.myevent`) listener subscribed. If you're just looking to see if there's specifically an `on-myevent` in the component tag, that would fall in with #1535, but allowing access to event listeners as well as attributes.

**Comment by ceremcem** [comment]
Well, knowing if an `on-myevent` is specifically declared or not for the instance suffices my needs. But I didn't get how I can capture if `on-myevent` is declared or not in the component definition by looking at #1535

**Comment by evs-chris** [comment]
Well, one of the proposed solutions to #1535 would have provided more accessible access to template contents, but it was too complex to add to core. It will be made into a separate library at some point, but for now to check for an event listener, in a `construct` or `init` event you can use:

```js
if (this.component && this.component.template.m.find(a => a.t === 70 && ~a.n.indexOf('my-event'))) {
  // there is an on-my\-event in the component template e.g. <cmp on-my\-event="something" />
}
```
