### ISSUE TITLE
making components isolated by default

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#2803]
Hi,

With the current trend of simplifications attempts, here is another one. :wink: It might help to:

1. make cleaner components
2. simplify ractive's code

Currently, Ractive components are "non-isolated" *by default*. In other words, the component's template can access data defined somewhere else outside of it. I think it's a bad default, and would even go further, to make all components isolated. Always.

It's also trivial to transform a non-isolated component into an isolated one: simply provide the data as argument. There is no excuse for not doing so IMHO. This would make cleaner reusable components and simplify both the resolution process and the code. ...and it's probably one of the easier features to get rid off.

**Comment by ghost** [comment]
> simplify ractive's code

I'm currently doing some experiments to simplify it 😉. Polyfill removals, moving common code together, simplifying directory structure and stuff. But I get distracted when I see interesting code. 😁 

Actually, there's more at stake than just data when it comes to isolation. Adaptor resolution, for instance, climbs up to ancestors in search for adaptors but is controlled by isolation. Not sure what else is.

But, I'm for permanently isolated components. Much more explicit, less magic. 👍

**Comment by kouts** [comment]
It depends in what context one designs and uses the components.
I find  it very useful in some senarios for all components to interact with the global scope freely.
I have components that use all sorts of different keypaths that transforming them into isolated ones would be a huge pain.
I also of course have reusable components that are isolated and all data is passed explicitly.
I think important is to retain the existing behavior when setting isolated false, even if the default is changed to true. Maybe add a global default option?

**Comment by dagnelies** [comment]
@kouts can you show us such an example where isolated false is preferred?

**Comment by kouts** [comment]
Well I unfortunately I cannot share code, but  imagine components as sections of different screen layouts that have common data coming from the backend.

**Comment by dagnelies** [comment]
Well, simply adding an attribute `<component mydata="{{...}}">` would solve it. In doubt, you could even pass the root to forward all data.

**Comment by tomekmarchi** [comment]
I strongly disagree with this suggestion. I rather have it none isolated by default and using this./. is perfectly fine for accessing that contexts data without going up the tree. Readability is the added benefit. I do not have a single component where I specifically ask for isolation.

**Comment by sarendipitee** [comment]
To play devil's advocate, every one of my components is isolated because it forces me to be explicit with where data is coming from — there are less "gotchas" when a non-specific keypath has a naming conflict with a parent keypath you forgot about. 

Although, my opinion is that we should only consider this change if @evs-chris thinks there is a sizable benefit and reduction in complexity/code.

**Comment by evs-chris** [comment]
Implicit mappings require a _bit_ of extra code. The real nastiness is unresolved references with implicit mappings. If the keypath doesn't exist in the component _or_ the parent and the mapping (or just data if on the component) is expected to pop into existence when the keypath appears on either, then you have a big confusing ball of wtf. I _think_ unresolved implicit mappings have died as of 0.7, though. I would dearly love to remove the unresolved resolution process entirely, meaning that if there is no matching keypath when trying to resolve, even an ambiguous one, then you give up and use the current context rather than creating a bunch of watchers that sit around waiting for a keypath to appear at some point in the future on any model between root and the current context hierarchy.

So, I can see where implicit mappings can be handy, and I have no problem with their existence. I think they should probably be opt-in rather than opt-out though, as even if you know what you're doing they can bite pretty hard if something seemingly minor changes in your data or you don't have lifecycle events setting up your data precisely at the right point.

**Comment by evs-chris** [comment]
Also note that regardless of the outcome here, you can already and will still be able to set an isolation level for any inheritance hierarchy starting with the Ractive prototype e.g. `Ractive.defaults.isolated = true`, `const Base = Ractive.extend({ isolated: false });`, and `const SomeView = Base.extend({ isolated: true });`. There anything extending Ractive is isolated by default, anything extending Base is non-isolated by default, and anything extending SomeView is isolated by default.

**Comment by dagnelies** [comment]
@evs-chris Thanks for the tip.

Despite the comments, I keep to my opinion that isolated components should be the default. Why? Because it's safer (and cleaner IMHO).

Non-isolated components can just get screwed up if you have something in your instance data and in the component template sharing the same name. They are by essence non-reusable components, since they are tailored to the instance's data, not through data provided as arguments.

I understand that people still find use in non-isolated components, to represent specific areas of their custom UI or so. However, I still think the safe, reusable, dumb-proof components where you explicitly provide the data should be the *default*. Releasing that safety to "look outside the component's scope" should be explicitly set IMHO, not the other way round.

**Comment by dagnelies** [comment]
Great, thanks, I think it's a wise decision in the long term. I hope though it won't stir much trouble because of the sudden change.
