### ISSUE TITLE
What is the "fakebuild" for?

### ISSUE THREAD

**Issue by ghost** [ractivejs/ractive#2809]
## Description:

Just wondering what it is for. It appears to allow a broken build to exit cleanly, but not sure how it is used. If it's for development purposes (like watching), I could just put the flow in the gobblefile.

**Comment by evs-chris** [comment]
An elegant build target for a more civilized age. 

It's not strictly necessary, but it can come in handy for perf testing, which uses the artifacts in the build folder rather than the unpredictable gobble output. Should be fine to move it to the gobble file. Or maybe even just keep the build folder artifacts up to date during normal dev mode.
