### ISSUE TITLE
Make 'event' the original DOM event, deprecate `event.original`

### ISSUE THREAD

**Issue by sarendipitee** [ractivejs/ractive#2810]
This is something that's annoyed me for a long time because it *always* trips up new members of my team.

If you do something like this `<button on-click=' doSomething(event.clientX, event.clientY)'>` I think it's fairly natural to assume that the `event` there is a DOM event. But it's not. And that's seriously confusing.

I feel slightly embarrassed telling a new team member that you have to use `event.original` to access the "actual" event.

Historically it was fine because it was easy access to the [helper](http://docs.ractivejs.org/edge/method-calls) methods, but now that we have `@` references in event method calls, I think it's time to deprecate the special "event object" that ractive creates.

There's no need for `event.pop()`, `event.get()`, `event.animate()` etc when you can use `@this.get()`, `@this.animate()`.

Then this would allow us to make `event` the *real* event object and remove `event.original`.

Proxy events would still behave the same way (for now).

Thoughts?

**Comment by evs-chris** [comment]
Apologies in advance for the rambling, but I've thought a bit about cleaning up events before.

We still need some way to access context methods, because they are already scoped to the current context. For instance, if we're at keypath `foo.bars.7.bazzes.12.bat`, using `event.set('wat', 10)` will set `foo.bars.7.bazzes.12.bat.wat` to 10, whereas `@set('wat', 10)` will set the root keypath `wat` to 10. The context specific methods are _required_ for calling methods on keypaths in a computed context (template expressions).

I _think_ the reason that the DOM event is pushed off into the `original` property is to have a common interface between DOM events and plugged-in events. There were also some additional properties hanging off of the event, like context and index that have been done away with since.

I've thought that perhaps it would be a good idea to split the source event and the event context apart for a while now. I just haven't come up with a good way to do it. There's also a bit of conflation between DOM-triggered proxy events and manually fired events that confuses things. There's some weirdness around `fire` that needs to be addressed, especially when used from an event directive. It's a little better without proxy event args, but I still think it could be made better. Not automatically making the event the first argument would improve the interface, I think. Perhaps moving the args into the event object would be better. I'm not sure, but that doesn't really directly relate to this issue.

I would propose that `event` be deprecated and split into two special refs: `@event`, which would be the actual DOM (or custom) event object, and `@context` (or something else appropriate), which would have the context methods and, in the case of an event firing, an `original` property === `@event`. That would also appease my sometimes excessive desire to have normalized refs everywhere with the special `event` moving to an `@` prefixed ref :wink:. I don't know whether or not it would make sense to have `@context` be available outside of an event handler, but it would effectively be the same as `@this.getNodeInfo(__nearest_node_ref_somehow__)`. 

I think it would also be nice to have an easy reference to the actual DOM node available to the event handler e.g. `on-blur="@global.alert(@node.value)"` or whatever. Exposing the `event.target` context as `@target` would also be a nice addition for event delegation. I couldn't come up with a nice clean way to have builtin event delegation, especially since making manual delegation easier results in less code (user and framework) than what I could come up with for automatic delegation.

**Comment by ghost** [comment]
How about this:

- `event` in `ractive.on` becomes the original node event object.
```js
this.on('event', function(event){ /* event === node event */ });
```
- Bubbling from a DOM event works in the same manner. If not intercepted, the delegated handler still gets the original sequence of event then args.
- `event` is only present on DOM events. `null` on custom events.
```
this.on('someEventHookedToClick', function(event){ /* event === node event */ });
this.on('someEventFromRactiveFire', function(event) { /* event === null */ });
```

As to why `null`, custom events might not originate from DOM events at all, thus no event object.

- Bubbling from a custom event, or an intercepted and re-fired event follows the custom events semantics of `null` then arguments.

- Arguments (from `ractive.fire`) start from second arg onwards.
```js
this.on('event', function(event, arg1, arg2){ /* event === node event */ });
```
- Methods stay explicit. If you want stuff, you pass in stuff in the same fashion as inline JavaScript (like passing `this` to send in the node reference). In this case, pass in `@event` if you really need it.
```
<button on-click="@this.myMethod(@event, 'foo', 'bar')">Click Me!!!</button>

myMethod(event, fooString, barString){ ... }
```
- For node information, I think `Ractive.getNodeInfo(event.target)` from inside the handler is sufficient. It's less magic work that you might not need, and much more explicit code for the consumer.
```js
this.on('event', function(event, arg1, arg2){
  var nodeInfo = Ractive.getNodeInfo(event.target);
  nodeInfo.set('foo', 'bar');
});

// assume being called as @this.myMethod(@event, 'foo', 'bar')
myMethod(event, fooString, barString){
  var nodeInfo = Ractive.getNodeInfo(event.target);
  nodeInfo.set('foo', 'bar');
}
```
- Get rid of `this.event`. Feels like a hack. It's also a trap when multiple events that run async operations try to access it after async event completion.

Watcha think? Also, you're not alone with being awkward explaining the existence of `event.original`. 😄

**Comment by sarendipitee** [comment]
I think you guys are spot on. 

I've never used `event.set("thing")` actually. It's too confusing. Instead I usually opt for `set(@keypath + ".thing")` instead which should be the same effect, right?

@fskreuz 

Totally agree that passing in the event should always be more explicit.

I don't think it has to be null for all proxy events though. We could just redo the docs to rename the args to `context` or something

```
this.on('customevent', function(context){ });
```

So people don't get confused that it's a DOM event. There is actually quite a lot of benefit to me to being able to easily access `context.node` (the node/comp the `on-customevent=` was added to) in addition to the event.target/currentTarget).

**Comment by ghost** [comment]
A `ractive.on` that listens for an event from an HTML element and receiving the original event object is sort of how the native `addEventListener` works.

The `null` suggestion was to just avoid breaking expectations. I'm looking at it more from a static types point of view where and arg's type is predetermined. That way, you can safely assume the argument is of a certain type, or `null` if not present. Less headache down the road I guess. 😄

**Comment by martypdx** [comment]
With es6 destructuring, it might make sense to change `event` to `context` (per @JonDum), and change `.original` to `.event`. Then you can do:

```
this.on('some-event', (context) => {});
this.on('some-event', ({ event }) => { });
this.on('some-event', ({ node }) => { });
this.on('some-event', ({ event, node }) => { });
```
