### ISSUE TITLE
Class-Instances in Ractive data get converted to plain Object

### ISSUE THREAD

**Issue by LeJared** [ractivejs/ractive#2816]
Example
https://jsfiddle.net/lejared/otn7rdxq/7/

It took me hours just to make simple fiddle which can show this bug reproducible.

The instance of `myClass` gets converted into a plain object when passed to a component, and thus loses it's prototype functions.

During my research on this issue,  sometimes also the data of the parent ractive-instance seems to be affected, by simply outputting data.myObj in the template, but I could not manage to build an example where this happens every time.

**Update**
This one is even more confusing
https://jsfiddle.net/lejared/otn7rdxq/9/
I just inlined the `.get()` into the `console.log()` calls.
While this one `this.get('val').getText()` seems to work, this one `this.get().val.getText` can't access the prototype method. Maybe it's an issue with Ractive.get()?

**Comment by evs-chris** [comment]
This will likely be an issue with a plain `get()`, which will build a composite object with all of the computations and mappings. There is an option to skip the composite build (`get({ virtual: false })`), but it looks like that is insufficient here because the data isn't copied into the root object during construction. There are some complex machinations around configuration, but I think this could be solved by making sure that keys that grow on the root model get added to the actual object as well.

**Comment by LeJared** [comment]
Thanks!
Now, that I know it's an issue with plain `.get()` i'll just stick to `.get('keypath')` as a workaround.

**Comment by evs-chris** [comment]
I completely missed the component layer there on my first run through it. The default `get()` gives you the full object tree, including any links and computations, as is necessary to get the data here. The virtual tree needs to be reconstructed with plain objects though, so that links make it in safely without modifying the source tree and wreaking all sorts of strange havoc. Since I don't really see a way around that for the `get()` case, and there's the `get(keypath)` version that will work, I'm going to go ahead and close this.

**Comment by LeJared** [comment]
OK, that's fine. But I think, this should be mentioned in the documentation, because until now I did not expect any differences between `get()` and `get('keypath')` except for explicitly defined computed properties.

**Comment by evs-chris** [comment]
I've updated the `get` docs for 0.8 and edge. It seems that those were missed in the shuffle from 0.7 to 0.8.
