### ISSUE TITLE
Conditional transition have a different behaviour between 0.7.x and 0.8.x

### ISSUE THREAD

**Issue by marcalexiei** [ractivejs/ractive#2822]
## Description:
- In 0.7.x if I made a condition to avoid transition inside the `intro-outro` attributes when the condition is not valid and the element with transition is removed from the DOM the transition is not executed.
- In 0.8.x the animation is performed also when the component is remove from the DOM.
 
I've used this syntax to avoid transition on component teardown / unrender. The wanted behaviour is   very similar to `noOutro` component attribute (https://github.com/ractivejs/ractive/issues/2770).

## Versions affected:
- 0.8.x
- edge

## Reproduction:
1. enable the animation
2. display the element
3. use "Disable transition and hide" to check different behaviour. 

**0.8.x** https://jsfiddle.net/swkz9n7n/33/

**0.7.x** https://jsfiddle.net/swkz9n7n/32/

## Code:

**0.8.x** 
```html
<h1>Hello!</h1>
 
  <button on-click="@this.toggle('performTransition')">
  	Enable/Disable transition
  </button>
 
  <br>
  
  <button on-click="@this.fire('disableTransitionAndHide')">
  	Disable transition and hide
  </button>	
  
  <br><br>
  
  <button on-click="@this.toggle('showElement')">
  	Toggle element
  </button>
  
  <p>Animation enabled: {{performTransition}}</p>
 
 {{#if showElement}}
  	<p {{#if performTransition}}fade-in-out{{/if}}>
    	  	We are ready for some bugs!
  	</p>
  {{/if}}
```

```javascript
function fade(t, params) {
  var DEFAULTS = {
    delay: 0,
    duration: 300,
    easing: 'linear'
  };

  var targetOpacity;

  params = t.processParams(params, DEFAULTS);

  if (t.isIntro) {
    targetOpacity = t.getStyle('opacity');
    t.setStyle('opacity', 0);
  } else {
    targetOpacity = 0;
  }

  t.animateStyle('opacity', targetOpacity, params).then(t.complete);
}

const r = window.r = new Ractive({
  el: '#main',
  template: '#template',

  transitions: {
    fade,
  },

  data: {
    performTransition: true,
    showElement: true,
  },

  onrender() {
    this.on('disableTransitionAndHide', () => {
      this.set({
        performTransition: false,
        showElement: false,
      });
      return false;
    });
  },
});
```

**0.7.x** 

```html
 <h1>Hello!</h1>
 
 <button on-click="togglePerformTransition">
  	Enable/Disable transition
  </button>
 
  <br>
  
  <button on-click="disableTransitionAndHide">
  	Disable transition and hide
  </button>	
  
  <br><br>
  
  <button on-click="toggleShowElement">
  	Toggle element
  </button>
  
  <p>Animation enabled: {{performTransition}}</p>
 
  {{#if showElement}}
  	<p intro-outro="{{performTransition ? 'fade' : ''}}">
    	We are ready for some bugs!
  	</p>
  {{/if}}
```

```javascript
function fade(t, params) {
  var DEFAULTS = {
    delay: 0,
    duration: 300,
    easing: 'linear'
  };

  var targetOpacity;

  params = t.processParams(params, DEFAULTS);

  if (t.isIntro) {
    targetOpacity = t.getStyle('opacity');
    t.setStyle('opacity', 0);
  } else {
    targetOpacity = 0;
  }

  t.animateStyle('opacity', targetOpacity, params).then(t.complete);
}


const r = window.r = new Ractive({
  el: '#main',
  template: '#template',

  transitions: {
    fade,
  },

  data: {
    performTransition: true,
    showElement: true,
  },

  onrender() {
    this.on('disableTransitionAndHide', () => {
      this.set({
        performTransition: false,
        showElement: false,
      });
      return false;
    });

    this.on('toggleShowElement', () => {
      this.toggle('showElement');
    });

    this.on('togglePerformTransition', () => {
      this.toggle('performTransition');
    });
  },
});
```

**Comment by evs-chris** [comment]
This is an unfortunate side-effect of the way that Ractive batches changes to the DOM. Each method that returns a Promise (generally) uses Ractive's internal runloop that waits to propagate changes to the VDOM, and subsequently the DOM, until all of the data changes have propagated. Since the element is responsible propagating changes to its attributes, one of which is the transition section, the transition doesn't have a chance to unregister before the element begins its removal process. The way around that is to make sure that the transition is removed in its own turn of the runloop e.g. `this.set('performTransition', false); this.set('showElement', false);`. All changes in Ractive are synchronous _except_ element removal when a transition is involved, so you can safely ignore the runloop Promise anywhere there are no transitions or you don't care that removed elements may be in the DOM while the transitions complete.

**Comment by marcalexiei** [comment]
So the transition behaviour between 0.7 and 0.8 has been changed and the one present in the last Ractive version is the expected one?

Just to confirm.

**Comment by evs-chris** [comment]
Not exactly. The behavior with 0.7 would not _remove_ the transition, it will just change the plugin name so that when the transition starts to try to run, there is nothing to actually run. With 0.8, the transition is actually removed from the element.

I think the best solution to some of these transition issues may be to come up with a composite transition that could also run other transitions in sequence and/or parallel. Something like `<div compose-in-out="[{ name: performTransition ? 'grow' : '' }, { name: performTransition ? 'fly' : '' }], { name: performTransition ? 'fade' : '' }">...</div>`, which would perform the fly and grow transitions at the same time and then the fade when they are done. The conditional would effectively make the transition resolve immediately when `performTransition` is falsey.

**Comment by marcalexiei** [comment]
So in my understanding I need to write a transition which invokes other `n` transitions in sequence or in parallel. In order to do this I have to use ractive.transition() (http://docs.ractivejs.org/latest/ractive-transition)

Right now I have problem using this function inside a transition: it seems that t.complete is never invoked. I have made a simple example: https://jsfiddle.net/wpy70jm7/

In addition I haven't find a way to specificy .isIntro,  so the transition performed is always the `out` one: https://jsfiddle.net/wpovmp6y/2/. However the node is never removed from the DOM.

**Comment by evs-chris** [comment]
You don't necessarily _need_ to; I was mostly just thinking out loud. In this case using two separate `set`s is the best workaround.

I wouldn't use `transition` to build a composite transition. I would store and replace the `complete` method on the passed transition object, replace it with a local one used to move the sequence along, and call the stored method when everything's done.

`transition` was added more to have a way to trigger transitions without having to add and remove bits of DOM. So you can do things like `<button on-click="@.transition('ripple'), @.doSomething()">`.

**Comment by marcalexiei** [comment]
Ok, thank you for the clarification.
