### ISSUE TITLE
Question: Get multiple ractive variables and assign them to specific key inside the JSON with ractivejs

### ISSUE THREAD

**Issue by clestcruz** [ractivejs/ractive#2828]
I'm currently trying to learn `ractive js` at the moment. Right now I'm figuring how I can store a dynamic value and pass it on a `JSON object` and set it to the API.

I have managed to get the value using `app.get` but how I do store it or pass it to a specific key-pair or object. Right now I'm getting an unexpected identifier as an error. 

WIP: http://fiddle.jshell.net/clestcruz/6L1vwcqw/

    <div class="form-element-container">
        <label>Company Name <span class="required">*</span></label>
        <input type="text" class="form-text full-width" placeholder="Enter the company name" id="accountName" value="{{leadData.accountName}}"/>
    </div>

    <div class="col col2">
        <label>Street Name.</label>
        <input type="text" class="form-text" placeholder="-" id="streetName" value="{{leadData.streetName}}"/>
    </div>

    <div class="form-element-container default-cta-container">
        <a class="button cta" on-click="addLead">Create Account</a>
    </div>

```
        app.on('addLead', function(event) {
          var leadData     = {}, 
          var addData         = ractive.get('leadData');

           app.set(function(addData, data) {
                var leadData     = {
                    "accountName": data.accountName,
                    "streetName" : data.streetName,
                }
            });

        });
```

**Comment by ghost** [comment]
I believe you are the same one who posted [this SO question](http://stackoverflow.com/q/41646039/575527)

> Right now I'm getting an unexpected identifier as an error.

That's because the code after `app.set` is appears to be invalid. Fix that first. 

> Right now I'm figuring how I can store a dynamic value and pass it on a JSON object and set it to the API.

I'm not sure which part is "storing" and where this API is. 

`data` should already be an object containing `accountName` and `streetName` properties (based on your template) containing whatever value you put in the inputs (assuming your code runs properly). You can verify that using `console.log(data)`. Any more than that, we cannot determine unless you provide [a simple reproduction](https://jsfiddle.net/).

**Comment by clestcruz** [comment]
https://jsfiddle.net/clestcruz/aonjwaqp/

Hello @fskreuz, thanks for the comments. I have updated the issues and attach a [link](http://fiddle.jshell.net/clestcruz/6L1vwcqw/) to the production. I still can't figure out how I can fix the issue.
