### ISSUE TITLE
Question: Ractive lazy loading precompiled components

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2830]
Is there something like ractive-load but with precompiled components?
This will help in the context of a large scale app where there may be a need that not all components are bundled inside one big js file.

**Comment by paulocoghi** [comment]
My current approach is to cache in memory each component when they load for the first time.

**Comment by ghost** [comment]
Not that I am aware of.

However, first thing that comes into mind is webpack code splitting. Ractive just recently grew a binary (credits to @evs-chris ) that compiles component files into ES modules. You can probably write a custom loader using that.

my 2c.

**Comment by evs-chris** [comment]
This is actually one of the things I'm working on in a day-job-related capacity. If all goes well, it will be a simple loader that ties in with a Ractive routing/app framework that does _not_ depend on the template version. The plan now is to use script injection to load a pre-compiled component, and I'm also thinking that lazy-loaded pre-compiled partials might be useful. The loader expects roughly the same format as compiled components provided by the Ractive binary, so if you're interested, some feedback on that would be great. I say roughly because there's a wrapper IIFE involved with some global swizzling, but that should be handled by the loader compiler, which will use your Ractive compiler under the covers as a peer dep.

**Comment by kouts** [comment]
@evs-chris that seems a great idea, a routing/app framework that also handles lazy loading is what I'm looking for at the moment! I didn't knew about ractive binary, are there any instructions on how to find/use it?

**Comment by evs-chris** [comment]
The docs for the ractive binary are displayed if you run it with no args or `help` as the command. To see what's there, you can `npm install ractive@edge && ./node_modules/.bin/ractive` from a proper shell. I think I will extend the cli wrapper to work with plugins so that people can add commands for scaffolding and whatnot later on.

**Comment by sarendipitee** [comment]
An an aside, it would go a long way by making components work more easily/dynamically when they are loaded asynchronously.

For example, this doesn't work at all:

```
const main = new Ractive({
    el: 'app',
    template: `
      Foo: <foo/> <br/>
      View: {{> view}}
      `,
    components: {
        // nothing yet
    },
    partials: {
        view: `<foo></foo>`
    },
    oninit() {

        // async call
        setTimeout(_ => {
            this.components.foo = Ractive.extend({
                template: 'I am foo'
            });

            // doesn't work this way either
            this.resetPartial('view');
        }, 2000)

    }
});
```
https://jsfiddle.net/6umLgxcx/

I think I remember getting it to work once, but I had to manually put ever single component under a toggle.

**Comment by evs-chris** [comment]
@JonDum that's basically the main use case for anchors and [attached instances](https://jsfiddle.net/6umLgxcx/1/). I'm not really sure if it would help, but there's not an exposed API to get a list of anchors by name. There _is_ an API for getting attached children by name, but that's sort of the other way around. I haven't fully explored it yet, but it seems that most of the time views attached in this way are more likely to be single-use components that serve as their own view rather than widget-y components that get used all over the place.

**Comment by sarendipitee** [comment]
@evs-chris Wow! That is nifty!! That's exactly the functionality I've been looking for. I'll try that out in an upcoming project and let you know how it works (or assume it's working great if you don't hear form me 😂 )

**Comment by evs-chris** [comment]
Playing about with webpack and the ractive-bin parser turns out that this case is handled pretty well there with chunking/splitting. My lazy loading via script tag works but requires a pretty specific setup in the components themselves. I think webpack is probably the answer to this question for now.
