### ISSUE TITLE
Question: Ractive ecosystem

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2831]
I really like the idea of "Official" utilities like "routing" or "state management" that will propose a way and help build web apps.
Coming from the "server side rendering" world I myself struggle to make 3rd party client side libraries play hand-in-hand with Ractive for creating a large SPA.
Are there any future plans for such an "ecosystem", what are your thoughts?

**Comment by ghost** [comment]
> Are there any future plans for such an "ecosystem", what are your thoughts?

There was a meta discussion about [a monorepo](https://github.com/ractivejs/ractive/issues/2271) so that everything gets built and tested as Ractive's version progresses. Not everyone was on the same boat and that kinda got lost in time. You could try reviving that thread to get everyone's opinion after being dormant for a year and being exposed to other tools that are doing the same. 😄 

I tried building the monorepo during vacation. It's collecting dust at the moment while I learn more about best practices. It's not as easy as it sounds. 😱

**Comment by dagnelies** [comment]
Well, sounds stupid, but "we" as a community are responsible for making the "ecosystem" progress or gather dust. Not anyone else. So @kouts I'd say a good way to start is to write good tutorials on how you solved the difficulty you faced, or publish the helper libraries you made... There was also a talk that instead of a monorepo, we should just present the plugins page better, with nice examples and such.

**Comment by kouts** [comment]
Thanks @dangelies I will when I'm there.
