### ISSUE TITLE
Consider <template> instead of mustache

### ISSUE THREAD

**Issue by nwmcsween** [ractivejs/ractive#285]
Polymer provides a pollyfill for the <template> tag with extensions that allow mustache style interpolation 
http://www.polymer-project.org/platform/template.html
http://www.html5rocks.com/en/tutorials/webcomponents/template

**Comment by zlamma** [comment]
Hi,
One advantage of allowing to consume mustaches from `<template>` would be that they could finally have `<script type='text/javascript'>` nested in them. This is not possible in `<script type='text/ractive'>` due to how browsers interpret the first `</script>` tag as the end of the main script.
I [found](https://github.com/angular/angular.js/issues/2820#issuecomment-31815165) that Angular also noticed the problem and they seem to be looking at the template tag.
I am currently using your single-file-components, which I'm in love with because of how they give me choice of maintaining super high code cohesion where I need it. However, this little nuisance hinders it a bit.

A nice step would be to make Ractive support taking its templates from both of these element types.

**Comment by Madgvox** [comment]
Perhaps I'm just thinking too narrowly, but what applications would embedding script tags inside templates have? I can't think of anything you can do that you couldn't do with the existing code space.

**Comment by zlamma** [comment]
In the spirit of keeping related things together, like in the [single-file-components](https://github.com/ractivejs/component-spec#single-file-components):
When developing templates with rich HTML controls that achieve their logic solely by decorating HTML (think jQuery plugins like datepickers, dropdowns, autocompletes) it is useful to keep the implementation details in the template only (especially which of the hip .js libraries were chosen to fill in the gaps in the ever-changing HTML featureset), so that the Ractive component contains just the lean data model, completely unaware of its HTML structure.
Putting the HTML initialization in the `<script>` inside the template allows you to achieve just that.

Note that this is not a limitation of whole Ractive. Ractive allows you to have these tags until you chose to inline your templates into your HTML page. There are good reasons for the inlining (performance, making page self contained - another one in the spirit of 'keeping related things together'!) so, whenever you feel it would be useful to you, this limitation comes as an annoying surprise.
