### ISSUE TITLE
Single File Components & Partials

### ISSUE THREAD

**Issue by tmilker** [ractivejs/ractive#2856]
Is there any way to define partials in a single file component(loading with rvc/requre) such that they're available to any other components that component uses?  If so, how do I look these partials up?

I've made svapreddy/ractive-widgets-virtual-scroll compatible with ractive 0.8.1(commit fd141daa) and it takes a formatter partial to lay out each block of scroll.  I'd like to define the formatter partial within the component that uses the ractive-widgets-vscroll component but the vscroll component can't find it.  The way it currently looks up partials is with:

```
partials: {
  formatter: function(parser) {
   return parser.fromId(this.get('formatter'));
  }
}
```

but it never finds any partial.  I'm currently working around this with a really ugly hack where I just reference my app's ractive instance as a global and pulling it straight out of ractive.partials within the vscroll component but I'd like to fix this if possible because even with this method, I can't define partials within components that other components used in that component can see, I have to define them in my app's main template.

p.s. I'm sorry for posting a question in Issues but it seems acceptable here and the Google group doesn't appear to get any traction anymore.

**Comment by evs-chris** [comment]
I think the easiest thing to do would be to use a content partial on the component. If you need more dynamism, you can also use a partial expression with a template object.

A content partial would be used as:
```html
<vScroll list="{{items}}" blockCount="100">
  <div class="card">... current item will be {{.}} ...</div>
</vScroll>

<!-- vScroll template would use -->
{{>content list[i]}}
```

Any content in the component's body is bundled up into a partial named `content`. You can specify additional templates with `{{#partial someName}}...{{/partial}}` in the component's body too.

 With edge, you can event `{{yield content with . as item}}` and use `{{item}}` in the content partial rather that `.` so that events and other refs resolve in the parent instance context.

With a partial expression with template object, you could use:
```html
<vScroll list="{{items}}" ... formatter="'<div class="card"> ... {{.}} ...</div>'" />

<!-- and in the vScroll template -->
{{>{ template: formatter } list[i]}}
```
