### ISSUE TITLE
recursive observe doesn't fire on linked data changes

### ISSUE THREAD

**Issue by Jeff17Robbins** [ractivejs/ractive#2862]
## Description:
New recursive observe (`.observe('**', ...)`) has option `links: true` but doesn't seem to fire when linked data changes
## Versions affected:
[https://cdnjs.cloudflare.com/ajax/libs/ractive/0.9.0-build-72/ractive.js](https://cdnjs.cloudflare.com/ajax/libs/ractive/0.9.0-build-72/ractive.js)

## Platforms affected:
WIndows 10 Chrome 56.0.2924.87
## Reproduction:
[https://jsfiddle.net/vz5d3r4f/](https://jsfiddle.net/vz5d3r4f/)
## Code:
```
var linker = new Ractive({
});
var linkee = new Ractive({
  data: {k1:1,k2:2},
});
linker.observe('**', function(n, o, k) {
  console.log('observe**', o, n, k, { init: false, links: true });
});

linker.set('linkee', {});
linker.link('k1', 'linkee.k1', {ractive: linkee});
linker.link('k2', 'linkee.k2', {ractive: linkee});

linkee.set('k2', {k3:17});
console.log(linker.get());
```
As the final `console.log(...)` shows, the `linker` Ractive instance contains a `linkee` key which has the desired keys `k1` and `k2` (along with their values.)  But the `.observe('**',...)` callback only fires once, on the `linker.set('linkee', {});` line.

I was hoping to see the `.observe(...)` callback fire on each `.link(..)` call, and on the `linkee.set(...)` call, because I was testing recursive observe as the replacement for the removed Ractive `change` event, along with linking as the replacement for the Ractive-Ractive adaptor.  

The Ractive instance `linker` wants to see all the data changes in "itself", including the data that actually comes from Ractive instances it links to.

**Comment by evs-chris** [comment]
This was caused by an oversight in linking, but it's now fixed in build 73. Thanks for the report!

**Comment by Jeff17Robbins** [comment]
It doesn't seem to work:  https://jsfiddle.net/kxurofwj/

My upstream `.observe('**', ...)` still is not firing.

**Comment by evs-chris** [comment]
Ah! There's a little bug in the fiddle. The params weren't being passed to the observe call. https://jsfiddle.net/kxurofwj/1/

**Comment by Jeff17Robbins** [comment]
Oops...how embarrassing!  Thanks for finding my bug.

I kinda sorta get what the recursive observe is all about.  Is a regular observe supposed to work?  If I change '**' to '* in my `.observe()` call, I get the same number of callbacks, but the "newvalue" parameter to the callback is simple an empty Object {} each time.

**Comment by evs-chris** [comment]
Yes, a regular or single wildcard observer should also fire the same amount. The difference is that you won't know which path _actually_ changed unless you use a recursive observer. So instead of getting the same parent value on every chance, you get the changed value from whatever arbitrarily deep keypath changed.

**Comment by evs-chris** [comment]
Sorry, I had a reading comprehension fail on that last comment.

When you install a regular observer on the parent of a link, getting the value of the parent won't get the link value in the resulting object because it's not actually part of the parent data. It's kinda like a filesystem with symlinks - the data actually exists elsewhere, you can get to it through the symlink, but unless whatever's looking in the folder containing the symlink has special handling for it, it won't see the data. `get` traverses links automatically to get to children, but it doesn't collect links (or computations) when getting the parent value _unless_ you pass `{ virtual: true }` to build an aggregate object including any links and computations that don't exist directly in the data. I suppose we could add `virtual` as a flag to `observe` to get the full reachable data tree?

**Comment by Jeff17Robbins** [comment]
Thanks for that further explanation.  I'm pretty much getting it (ask anyone, I can be dense at times.)

That `virtual` flag sounds nice, but not necessary, since I can always call `.get()` inside the callback.  Is that equivalent (just checking that I'm following along)?

**Comment by evs-chris** [comment]
You can indeed get the full model with a `this.get(k, { virtual: true })` inside the observer callback. It's a bit expensive to compute with a deep/large dataset though.

https://jsfiddle.net/kxurofwj/6/

**Comment by Jeff17Robbins** [comment]
Would the hypothetical `virtual` flag passed to `.observe()`  be markedly less expensive?

**Comment by evs-chris** [comment]
No, it would be the same. Basically just an automatic shortcut for a virtual get.
