### ISSUE TITLE
Remove src dependency of tests

### ISSUE THREAD

**Issue by ghost** [ractivejs/ractive#2904]
## Description:

Haven't looked into this deeply, but tests depend on some `src` modules to work. Few things of concern:

- Tests should be independent from the source, in theory.
- Some are internal APIs. If they break, the tests break.
- It causes tests to be recompiled when those things from `src` change.

![untitled](https://cloud.githubusercontent.com/assets/1582932/23593930/4f2dbbae-01e3-11e7-9b91-c563ae969239.png)

**Comment by evs-chris** [comment]
Yeah, I've wanted to break the src dependency for a while, but not enough to throw in the effort. It certainly doesn't help test speed any, especially since those few deps end up pulling in 95% of the ractive source for the test output. It gets quite confusing when you search for say 'RepeatedFragment.prototype' in all.js by accident and don't notice that your breakpoints won't ever trip because you're in the wrong file.
