### ISSUE TITLE
0.8.12 - Decorator adds row and breaks binding on splice

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2913]
Removing (any but the first) line from an array using splice, results in
a new line being added at the end of the array when a format value decorator is used.
Here is the fiddle: http://jsfiddle.net/ucLj8mtr/9/

When pressing "Delete row" on any row but the first, the current row gets removed and
a new line is added in the array.
It seems that the formatting decorator wins over the splice action.

**Comment by fskreuz** [comment]
Notes:

- Removing the decorator fixes the issue. Bug is on the decorator, not data handling.

**Comment by evs-chris** [comment]
It looks like this is happening on any version of 0.8 and edge. It's an issue with the decorator not updating the observed keypath when the target list is shuffled. Basically, the second item starts out watching the `.1` keypath, and when the first item is spliced out, is _still_ watching the `.1` keypath. It _might_ work to use a relative observer rather than the absolute path including the index, but there are still scenarios where that would break down.

One option might be to notify decorators when they are shuffled, either with the `update` method or one specifically for when their host keypath changes.

One thing the decorator could do would be to check that the binding path is still the same in the observer callback, and if it's not, set up a new observer from there.

**Comment by evs-chris** [comment]
After fixing a bug with context relative observers and shuffling, the fiddle can be adjusted to work with edge: http://jsfiddle.net/ucLj8mtr/12/

Unfortunately, 0.8 doesn't have context relative observers, so that doesn't help a whole lot. If edge isn't an option, here's a workaround for 0.8: http://jsfiddle.net/ucLj8mtr/13/

**Comment by kouts** [comment]
I managed to solve this using another approach.
What I did was to disconnect the twoway binding from the input and used the decorator
to set the value instead. Here is the fiddle http://jsfiddle.net/zth3c4sy/1/

I don't know if it's a "valid" thing to do (i.e pass the keypath to the decorator) but that worked ok.

**Comment by evs-chris** [comment]
That's absolutely a valid approach. In fact, that's what I normally do with my formatting decorators.
