### ISSUE TITLE
merge no longer preserves existing DOM in v0.8.x and up

### ISSUE THREAD

**Issue by wearhere** [ractivejs/ractive#2917]
## Description:

Merging no longer preserves existing (unchanged) DOM in v0.8.x and up.

## Versions affected:

v0.8-dev, v0.8.12, and edge (which is 0.9 something right?)

## Reproduction:

http://jsfiddle.net/z3nd2qh0/, using v0.7.3, preserves the "c" paragraph through the merge.
http://jsfiddle.net/yd7sgcyh/ shows that v0.8-dev does not.
http://jsfiddle.net/z904k6td/ shows that edge (using `set` + `{ shuffle: true }`) doesn't preserve the "c" paragraph either. (It's a little harder to see since fading isn't working for some reason in that JSFiddle, but if you right-click inspect the "c" paragraph before the timeout fires, you can see that you'll lose your selection in the elements panel as the paragraph is removed from the DOM.)

**Comment by wearhere** [comment]
I feel like I must be missing something since this is the core feature of `merge` / `set + shuffle`… I tried to look into the code to see where it went wrong but I find the shuffling code kinda hard to trace and I know there are some big changes to it in 0.9.x (though, as the description states, it broke before that).

**Comment by evs-chris** [comment]
It preserves the virtual DOM and actual DOM nodes, it just detaches and reattaches them as part of the sorting process: http://jsfiddle.net/z3nd2qh0/1/. The `RepeatedFragment` uses a `DocumentFragment` to render its various iterations into the correct order, and in doing so, the existing iterations get detached from `document`. Then the DocumentFragment is inserted into the `document`, which replaces any nodes that already existed and adds any that were inserted by the merge/shuffle.

I believe the `splice` version of the post-shuffle update avoids unnecessary detachment, but the `merge` version can't really do that for all cases.

It looks like there might be a bug with the removal of fragments during the shuffle, because the `c` shouldn't jump up between the `a` and `b` while they're fading out.

**Comment by wearhere** [comment]
Hm, for our purposes, detaching the DOM nodes may be almost as bad as recreating them, since it will cause the focus and I think the scroll position to be lost. Here's a JSFiddle illustrating the former: http://jsfiddle.net/pfskyzg1/.

> I believe the `splice` version of the post-shuffle update avoids unnecessary detachment, but the merge version can't really do that for all cases.

I'm not sure exactly what you're referring to here—is there any way to force the use of the `splice` version?

Btw I know that we can also actually use `ractive#splice` vs. `merge` and that will make targeted modifications, it just would be super convenient for Ractive to figure out what modifications were necessary. It seems like it's so close.

**Comment by evs-chris** [comment]
I think if there's any sort of reordering that it will always have to do a detach/insert _somewhere_. We can probably use the ["standard"](https://medium.com/@localvoid/how-to-win-in-web-framework-benchmarks-8bc31af76ce7#.nx0c6mk44) algorithm to avoid the detach/insert in more cases where the changes mostly happen in contiguous blocks on either end of the array. I've tried to come up with something to do minimal DOM movement for merges, but I always get jammed up on corner cases. Even that would have the chance to cause a focus/scroll position issue though, depending on the changes.

I was referring to using `splice`-equivalent e.g. `splice`, `push`, `pop`, `shift`, etc, which have the benefit of _knowing_ that nothing needs to be re-ordered because each element will be added, removed, or stay the same.

Coming at it from a slightly different angle, perhaps we could add checks for focus/scroll position and restore them when everything is done shuffling? Scroll position would probably be the more difficult of the two, since it's more involved than getting the focused element and potential selection for cursor position.

**Comment by wearhere** [comment]
Good ideas @evs-chris. I have the intuition that we can make some assumptions around how the data is likely to change, to simplify when/how we need to preserve the focus/scroll position, but will need to think about my use case some more.

Here's an example of what I'm thinking about though: I think we can assume that _the focused element will not be changing_. This is of course up to the application to ensure, but makes sense, right? —If the user's e.g. editing an element, the application won't be trying to update it at the same time. For example, the user might be editing a new list item before saving it, at which point it _then_ becomes under automatic control.

So (for my purposes at least) the focus position is preserved "automatically" if we can only detach/insert modified elements.

--------------

I like the idea of restoring scroll position when the shuffle was done although I may agree with you that sounds more involved; if, for instance, the scroll height changes substantially, I could see us possibly having to implement scroll-to-visible behavior or something.

--------------

>  We can probably use the ["standard"](https://medium.com/@localvoid/how-to-win-in-web-framework-benchmarks-8bc31af76ce7#.nx0c6mk44) algorithm to avoid the detach/insert in more cases where the changes mostly happen in contiguous blocks on either end of the array.

Ooh, neat. Is this something that Ractive currently does in some scenarios, or something you'd like to implement? That could be a very valuable addition since I bet that inserts/deletes often happen in contiguous blocks at the ends of the array, like adding a new item to the top of a to-do list.

**Comment by tommarchi** [comment]
If it's a scroll reposition issue a simple fix is. Save current height of scroll div await on changes then remove hard coded height. Done. This is of course given the sort has the same and or more divs in place. The mentioned optimization is another part of that total solution.

**Comment by evs-chris** [comment]
A bit of benchmarking has shown our current method to be reasonably fast for more scenarios that other algorithms, which excel at some and are abysmal in others. It seems that since we're synchronous, detaching and reattaching in one go [doesn't affect the scroll position](https://jsfiddle.net/rfqmgkr2/) (at least on modern browsers). That leaves the focus problem, which can be solved pretty easily handled in the corner in which it occurs by recording and restoring the focus and selection of the active element, if there happens to be one, [around the shuffle](http://jsfiddle.net/pfskyzg1/1/).
