### ISSUE TITLE
Adding a handler after having removed the same handler does not work

### ISSUE THREAD

**Issue by ggiamarchi** [ractivejs/ractive#2922]
## Description:

First, i add a handler with `ractive.on()`, then i remove it either calling `ractive.off()` or `.cancel()`. Then, if i try to add the same handler again it doesn't work. No error occurs but the handler is not installed.

## Versions affected:

Tested on Ractive `v.0.8.12` and `v0.7.3`

## Platforms affected:

Tested on Google Chrome 56.0.2924.87 (64-bit) / Mac OS X 10.11.6 (15G31)

## Reproduction:

See snippets below.

## Code:

From my understanding, the exectution of the three snippets bellow should print `ok` in the console. `1/` and `2/` don't work. `3/` works (this third snippet is the workaround i use).

1/ 

```javascript
var printHandler = function() {
    console.log("ok");
}

ractive.on('print', printHandler);
ractive.off('print', printHandler);
ractive.on('print', printHandler);
ractive.fire('print');
```

2/

```javascript
var printHandler = function() {
    console.log("ok");
}

ractive.on('print', printHandler).cancel();
ractive.on('print', printHandler);
ractive.fire('print');
```

3/

```javascript
var printHandler = function() {
    console.log("ok");
}

ractive.on('print', function() {
    printHandler();
}).cancel();

ractive.on('print', function() {
    printHandler();
});

ractive.fire('print');
```

Do i miss something or is there a bug ?

**Comment by evs-chris** [comment]
There is a bug. Since event subscribers can get modified while events are firing, the event firing code makes a copy of the subscriber list before dispatching events. When `off` is called on a handler, it gets a flag `off` added to it to let the firing code know that it should skip that handler. In this case, the handler is being added back with the `off` flag still intact, meaning it gets skipped for firing.

I _think_ we can work around this by using a `setTimeout` to drop the `off` flag, but looking at it, there may be other implications for other scenarios still. For instance, attaching the same function to two different events with two calls to `on` and then `off`ing one looks like it would stop the other from firing too.
