### ISSUE TITLE
No error on wrong section closing tag

### ISSUE THREAD

**Issue by Minstel** [ractivejs/ractive#2925]
## Description:
If section closing tag does not correspond to opening, no error appears, section is rendered with value of opening tag.
## Versions affected:
Tested only on `0.8.8` and `0.9.0-build-117`
## Platforms affected:
Tested only on Chrome 57.0.2987.133
## Reproduction:
[https://jsfiddle.net/1zjyakL0/1/](https://jsfiddle.net/1zjyakL0/1/)
## Code:
```
new Ractive({
	el: 'body',
    template: 'Start {{ #foo }} Text {{/bar}}',
    data: {
    	'foo': true,
        'bar': false
    }
})
```

Output is:
```
Start Text
```

**Comment by evs-chris** [comment]
That's correct :smile:

Plain mustache sections don't care what goes between the `/` and the end of the tag, whereas `if`, `with`, `each`, and friends do. You can think of the closing tag more like a comment, and here's why: `{{#foo + 7 > bar / 2}}...{{/???}}`. The minimum is simply `{{/}}` for plain mustache sections.

**Comment by Minstel** [comment]
@evs-chris Wow... Of minimum I know, that looks like correct, but everything else... Does not look like correct way for it to work.

Issue arised in context of developing syntax errors checker, for UI where user create ractive templates himself, sometimes pretty complex.

Sometimes wrong closing tag is used by mistake, not as comment. So in result it gets confusing, and harder to understand the contents of template.

**Comment by Minstel** [comment]
I understand, that this behaviour would hardly be changed, just point out)

**Comment by evs-chris** [comment]
In general, we try to encourage specific sections (`{{#if ...}}{{/if}}`, `{{#each ...}}{{/each}}`, etc) for that and a few other reasons. Notably, plain mustaches react to different data types in different ways and always introduce context, both of which may be surprising.

**Comment by Minstel** [comment]
Maybe, if a comment is in closing tag, it should use some special syntax, so that it was clear, that it's comment. So when this syntax is not used, and closing tag differs from opened (not counting shorthand `{{/}}`), parse error appear.

**Comment by Minstel** [comment]
The following problem seems to be connected with this issue.
[https://jsfiddle.net/Minstel/8co3Lwpw/1/](https://jsfiddle.net/Minstel/8co3Lwpw/1/)

```
new Ractive({
    el: 'body',
    template: '{{ #foo }} Text {{ /foo } More text {{ bar }}'
})
```

Parse error is not thrown here, athough closing section is not closed correctly.
If we remove `{{ /foo }`, error is thrown.
If we remove `{{ bar }}`, error is thrown.

Seems like `foo } More text {{ bar ` acts like a closing tag text :\

**Comment by dagnelies** [comment]
+1 for ensuring strict tags checking (`{{#foo}}` matching `{{/foo}}`) ...or at least print warnings. 😉 

Btw, mustache.js & handlebars.js also enforce strict tags matching ( see http://www.tryhandlebarsjs.com/ )

**Comment by ghost** [comment]
> Btw, mustache.js & handlebars.js also enforce strict tags matching

Tag matching in Handlebars is possible only because those sections have defined helper names. The same is true with Ractive's borrowed `{{#if}}`, `{{#each}}` and `{{#with}}`. But for regular sections `{{# }}` that accept expressions, [there is no name](https://jsfiddle.net/zeuvxohe/), thus no closing name.

```js
Ractive({
  el: 'body',
  template: `
    <div>
      This: {{# [1, 2, 3]:index }} {{index}}: {{this}}, {{/how do you close this?}}
    </div>
    <div>
      Or this: {{# @this.double([1, 2, 3]):index }} {{index}}: {{this}}, {{/how do you close this?}}
    </div>
  `,
  double: n => n.map(o => o * 2)
})
```

You also do not want Ractive to  [force you to match the closing with the opening](https://jsfiddle.net/zeuvxohe/2/) particularly if it's an expression. That would be a horror show. This would be more inconvenient than than the problem it's trying to solve.

```js
Ractive({
  el: 'body',
  template: `
    <div>
                                                        <!-- omg, I have to rewrite the entire thing again?! -->
      This: {{# [1, 2, 3]:index }} {{index}}: {{this}}, {{/ [1, 2, 3]:index }}
    </div>
    <div>
                                                                         <!-- no! stahp! nooo!!! -->
      Or this: {{# @this.double([1, 2, 3]):index }} {{index}}: {{this}}, {{/ @this.double([1, 2, 3]):index }}
    </div>
  `,
  double: n => n.map(o => o * 2)
})
```

The best thing you could do is just add a "comment" that tells you "hey, this is the closing tag for that inline expression opened somewhere up there". The `{{/}}` with an optional comment of your liking is sufficient.

**Comment by Minstel** [comment]
@fskreuz Why is this a horror show? I do not see anything horrible in here. It's long, yes, but it does not lead to any unpredictable errors, and clearly shows, what section was closed.

**Comment by ghost** [comment]
Why would you require text in a closing tag when all the parser needs is to know is when to close the preceding section? Even a `{{/}}` alone does just that.

And saying that matching closing tags are needed is like saying the JS `for` should have an `endfor`, or the `if` should have an `endif`. Just because JS doesn't have an `endfor` or `endif` doesn't make it any less clearer that the loop or conditional ended where the `}` is.

**Comment by dagnelies** [comment]
Wow, I never stop learning something new about ractive. I wasn't even aware you could place expressions like `{{# [1,2,3]}}` ...fancy.

That being said, a nice, yet simple alternative would be either the same closing tag *or* the simple one `{{/}}`. Another alternative would be to introduce an `{{#expr ...}}` tag to be more explicit. But this would be a breaking change ...on the other hand, it'd be interesting to know who was even aware that it is possible.

Like @Minstel said, with big templates, it's easy to misplace a tag, at least a warning would be helpful.

**Comment by Minstel** [comment]
@fskreuz Well, I partialy agree with your words :) But comparison with JS seems not really valid, because no JS loop allows *arbitrary* closing text, or symbol.

Yes, for parser it's really enough to have any closing tag. But for human, who works with template, sometimes not.

Also I think that bugs like that described in my upper [comment](https://github.com/ractivejs/ractive/issues/2925#issuecomment-292838708) should not appear.

**Comment by ghost** [comment]
> yet simple alternative would be either the same closing tag or the simple one `{{/}}`. 

A warning on debug mode isn't a bad idea tho.

> Ractive.js: Hey developer! We expected `{{/}}` (simple closing) or `{{/ expression }}` (match opening) but found `{{/ funky text that is potentially a malformed closing }}` instead. Just making sure you meant to do it instead of by accident.

---

> I wasn't even aware you could place expressions like `{{# [1,2,3]}}` ...fancy.

Docs indicate that [it's been there since 0.5](http://docs.ractivejs.org/0.5/expressions). Not sure how extensive it is, but as far as I know, only simple expressions are allowed.

---

> But comparison with JS seems not really valid, because no JS loop allows arbitrary closing text, or symbol.

The idea is that languages aren't any less debuggable/understandable because it never had an explicit closing tag. That goes for JS, C, Java, PHP (although it has `endfor` and `endif`, not many use them). And the same goes for Ractive and the simple `{{/}}` to close `{{# optional_expr }}`.

**Comment by dagnelies** [comment]
Hello again everyone 😄 

@fskreuz You're a bit nitpicking here my dear 😉 

...I think we're slowly but surely missing the point here. The point would be: "what would be helpful for developers?". Although I understand both your standpoints, I tend to agree with @Minstel that tag matching definitely is helpful. Once your templates grow, it's so easy to have misplaced tags. Therefore my +1 vote.

I'm sure almost everyone would already be happy with just a warning, or a stricter version, either way.

**Comment by ghost** [comment]
Tracking the docs clarification separately. This thread will track the addition of the warning.

**Comment by evs-chris** [comment]
RE expressions in blocks, you get the full monty there. Any expression available anywhere else in the template is available as the target of a `{{#...}}`, `{{#if...}}`, `{{#with...}}`, or `{{#each...}}`. As for an `{{#expr...}}` block, we kinda already have that in the form of the if, with, and each blocks. The _only_ difference is that to be exactly equivalent, you'd need to do `{{#with ...}}{{#if .}} ... {{/if}}{{/with}}` because `with` is not conditional; it's only contextual.

For the warning, I'd say only issue it if the mustache is a reference e.g. `{{#foo}}` or `{{#bar.baz}}`. If the closing isn't empty and doesn't match the reference, issue a warning, otherwise, consider it a comment.

**Comment by dagnelies** [comment]
Perfect 👍  

PS: ...indeed the `{{#expr...}}` was a silly idea of mine.
