### ISSUE TITLE
Any plans to improve performance? 

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#2929]
Hi, 

As I love RactiveJS and the community, I want to see Ractive being compared with the others neck and neck in terms of performance. Right now, [it seems a bit far from this point](http://www.stefankrause.net/js-frameworks-benchmark5/webdriver-ts/table.html). As the benchmark author says, Ractive had a huge performance improvement lately (about %35) which is very promising. 

I don't know, maybe it is a design decision, as Ractive may be designed to use more resources in exchange for its features. 

Is there any road map to make the performance improvement plans clearer for us?

**Comment by ghost** [comment]
> Is there any road map to make the performance improvement plans clearer for us?

Ractive never really had a roadmap. Stuff just happens as needed. 😄 

> As the benchmark author says, Ractive had a huge performance improvement lately (about %35) which is very promising.

0.8 was a perf overhaul for the most part, so that was kinda expected.

With regards to performance, I'm working on [automating benchmarks](https://github.com/ractivejs/ractive/pull/2895) so that we have an internal tool to get insight on what's fast, what's slow, what became faster and what became slower. Instead of having to wait for others to publish benchmarks, why not do it ourselves per build? 😄 

Haven't gotten around to finishing it (got busy the past few weeks). It's almost done though. Just a few more things to do. When that's done, we can pin-point what needs boosting.

**Comment by evs-chris** [comment]
If you noticed the Ractive edge benchmark in the non-keyed table, that's a very early version of 0.9. I'm actually pretty happy about 1.5x hand-coded and optimized DOM manipulation. The only thing I think we could significantly improve upon would be render time for large chunks of DOM, especially the initial render, as we do pretty well in all of the other tests. I haven't found anything in profiling beyond what's already in 0.9 that helps significantly, though. These benchmarks also aren't necessarily a good real-world comparison, and many of the libraries have specifically tailored benchmark implementations that don't follow best practices for the library in order to squeeze out every last drop of performance.

Memory usage may also have dropped since that was published, as we've cleaned up quite a few memory leaks.

Also, I'd like to note that running those benchmarks locally often results in wildly varying numbers between runs. For instance, I've seen the 10,000 row render for Ractive get well below 2 seconds and also go above 5. I've also seen the memory usage after render come out under 6M. Browser performance is not terribly consistent.

**Comment by dagnelies** [comment]
*Btw, I think the benchmark code examples are suboptimal and can maybe be easely improved.* 

See:

https://github.com/krausest/js-framework-benchmark/blob/master/ractive-v0.8.9-keyed/src/main.es6.js

For example this ugly piece:

            this.splice('data', 0, this.get('data').length);
            this.merge('data', buildData(10000), 'id');

May be replaced by:

            this.set('data', buildData(10000));

...and may already lead to performance boosts ...or not, dunno. Of course it would be nice if someone had the time to actually look into it, test it out, and contribute the better performing benchmark code.

**Comment by dagnelies** [comment]
Based on a little experimentation, tweaking the benchmark example does not appear to have a big impact.

**Comment by evs-chris** [comment]
The first version of the benchmark with 0.7 was pretty bad, and I submitted a PR to clean it up a good bit. I _thought_ the goal was to be able to compare code too at the time, so I didn't make it fully idiomatic or try to get hacky with optimizations. I haven't done anything with it since early this year, but once 0.9 hits, I will revisit it.

**Comment by dagnelies** [comment]
Personally, I find it quite nice to browse through the various sources to get a feel how it looks like. These are indeed nice examples. ...but I think I'm part of a minority. I think that from a broader perspective, people are mostly looking at it to know if a framework is ok to use, and green looks better than red. Dunno if it's worth to spend time on it though.

**Comment by evs-chris** [comment]
0.9 is a _bit_ faster than 0.8, and I think the benchmark numbers could be improved by preparsing the template to drop the startup penalty.
