### ISSUE TITLE
isolated:false related bug

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#2930]
Hi,

as usual, here are the fiddles:

With broken "Title: {{foo}}" data-binding: https://jsfiddle.net/x5serz9o/1/

With working "Title: {{foo}}" data binding: https://jsfiddle.net/x5serz9o/2/

The only difference between the two is an additional input field. Breaks for both `latest` and `edge`.

**Comment by ghost** [comment]
> as usual, here are the fiddles:

As usual, thanks for the report. 😄 

~~I think the issue is that if the component data is uninitialized, the mapping leaks. Here's a few more cases:~~

- ~~(uninitialized component data, data on instance, broken) https://jsfiddle.net/vry3pquy/~~
- ~~(initialized component data, no data on instance works) https://jsfiddle.net/y4pjpp0w/~~
- ~~(initialized data on both, works) https://jsfiddle.net/j6cmxqkn/~~

~~Workaround is to provide defaults to the component data until fixed~~

Ignore comment. I thought it was `isolated:true`.

**Comment by evs-chris** [comment]
I think this is actually intended behavior as it stands. The issue is that if non-isolated components can't find data in the context hierarchy, they default to binding against their own root. The only way around that would be to default to the root context rather than the local context. If I recall correctly, this was changed around 0.7 and was fully intentional because defaulting component bindings to the root context can be quite surprising if you forget to init some component data.

Now, with isolated being the default in 0.9, one could certainly argue that reverting that change would be reasonable since it's now opt in. It might make more sense to introduce another flag to specify where ambiguous references should resolve if they aren't found anywhere. Like maybe `isolated: 'root'` is isolated false but defaulting to root context rather than local component context. Opinions?

**Comment by dagnelies** [comment]
I can live with the current state, fine with me. 😄 

That said, I'd add a warning for "non-isolated components can't find data in the context hierarchy". Something along the lines:

"The data binding {{some_mustache}} at line N was never initialized and is therefore ambiguous."

**Comment by dagnelies** [comment]
On a second thought, I think you're totally right with your comment:

> with isolated being the default in 0.9, one could certainly argue that reverting that change would be reasonable since it's now opt in.

It indeed just feels weird that non-isolated components binds data locally when unknown.

IMHO, I'd leave only:

- isolated:true - (default) binds uninitialized stuff to itself
- isolated:false - binds uninitialized to root
