### ISSUE TITLE
Component not updated when computed property changed

### ISSUE THREAD

**Issue by chenxsan** [ractivejs/ractive#2935]
## Description:

I'm building a pagination component with ractivejs, here's my code http://jsbin.com/ziketehero/edit?html,js,console,output, when I run `ractive.set`, I would expect the component to re-render because of the updated computed property, but it's not. What am i doing wrong here? Any suggest? Thanks.

**Comment by chenxsan** [comment]
When I changed the component into partial, it just worked, guess I might misunderstand something.

**Comment by ghost** [comment]
Seems to be working for me https://jsbin.com/zacimajoki/edit?html,js,console,output

Also suggesting you split your computed properties into separate properties instead of having them in one big object. That way, it's easier to track down which one is misbehaving. Ractive catches thrown errors inside computed properties (while still logging them), so it might not be evident until you look at the console.

**Comment by chenxsan** [comment]
@fskreuz The only difference between your code with mine seems to be the ractive.js script, I got this:

```
<script src="http://cdn.ractivejs.org/latest/ractive.min.js"></script>
```
while you got this:

```
<script src="https://unpkg.com/ractive"></script>
```
Is there something wrong with the file on cdn?

**Comment by ghost** [comment]
I just realized `http://cdn.ractivejs.org/latest/ractive.min.js` is the old CDN link. That link is not https 
so browsers will block it from loading.

[We're currently updating the docs](https://ractive.js.org/). `https://unpkg.com/ractive` is where we're serving it now.

**Comment by chenxsan** [comment]
Thanks, I updated now, and it works.
