### ISSUE TITLE
Why are proxy events called... proxy events?

### ISSUE THREAD

**Issue by ghost** [ractivejs/ractive#2937]
Title says it all. Is it because the event transforms into the name assigned to it? i.e "click" becomes "clicked" and handled as "clicked"?

```js
Ractive({
  template: `
    <button type="button" on-click="clicked">Push me!</button>
  `,
  oninit(){
    this.on('clicked', event => {
      console.log('clicked');
    });
  }
});
```

**Comment by evs-chris** [comment]
I _think_ it's because a DOM event gets wrapped up into a proxy object of sorts in order to be fired through Ractive's event system. When a component rewraps one of those, it was termed reproxying, which is where I thing the name came from originally - if refiring from a component using a different name and the same source event is reproxying, then the original fire must have been proxying. When method calls became available to event handlers and a name was needed to distinguish between the two flavors, the occasionally used proxy event name became the norm.
