### ISSUE TITLE
Unexpected behavior in helper

### ISSUE THREAD

**Issue by Inversion-des** [ractivejs/ractive#2938]
## Description:
Case when helper is not triggered when expected to.

## Versions affected:
0.8.13-edge
same in older versions

## Platforms:
Chrome on Win

## Reproduction:
see line 20 there with comments
first open console and click on the Do btn many times ('1' logged many times)
after '==' changed to '||', rerun and again click on Do many times —  '1' will not be logged
http://jsfiddle.net/Inversion/uknyn4eo/

**Comment by evs-chris** [comment]
This is actually expected behavior. The `||` operator short circuits, so the `get` is never called. Since ractive never sees the `clss` expression reference the `index` keypath, it doesn't set it up as a dependency to recompute the expression when it changes. You can _force_ `index` to be a dependency of `clss` by storing the value in a tmp var e.g. http://jsfiddle.net/uknyn4eo/2/ because the `get` will _always_ be called when written like that.

**Comment by Inversion-des** [comment]
Oh, now I understand, but still it is hard to have such things, remember about it…
Thanks

**Comment by Inversion-des** [comment]
Maybe it is possible to analyze function code (probably in debug mode only) and show some warning in console about possible issues with '||' before @get.

**Comment by evs-chris** [comment]
I don't think we could be accurate enough parsing the function to be useful enough to be worth the overhead. For instance, if the keypath is stored in a variable, there's no easy way to check the call. I think better documentation is the best answer :)
