### ISSUE TITLE
Array modification doesn't work

### ISSUE THREAD

**Issue by sinnus** [ractivejs/ractive#2942]
I taked code from the following example and it doesn't work

http://docs.ractivejs.org/latest/array-modification.

I use Ractive.js v0.8.12

**Comment by evs-chris** [comment]
`modifyArrays` is off by default because it can cause surprising behavior and performance issues. It's also been removed from core on 0.9 (we're working on the docs :)): https://ractive.js.org/playground/#N4IgFiBcoE5SAGAdADhAXwDQgC7wDwAmAlgG4AExhAvADq4CGMA5gKY70B8+A9CaZxDYAzvFJNyMctXIA7VgHdyAJQYBjHGVYAKYLVm0crADaRyAcgDEOJmxznM+w0YC2AB2MMjZ88GCXWdTByY2JhHHR0PyRIvx5AtTBIhyccQi8GMz0DDhxQ8LMAbQBGTHIAJjKAZgBdVKxUlwB7EgAzAE8AQRgYBnbhMxwYAFdWfXQASgBuJ1lxKSYpGRgkO21zfPtp2cWkN2HhMG0AFm3ZXcPiVpxtM93h2Uvr7QBacumMIA

**Comment by sinnus** [comment]
Thank you for answer!

What kind of surprising behavior?

**Comment by evs-chris** [comment]
Well, if you are used to using the `splice` methods of your ractive instance, having an external reference to an array update the instance is a bit surprising, especially if it happens in some other library code. The performance issues tend to be more surprising, though, as the array adaptor adds a fair amount of overhead.
