### ISSUE TITLE
oncomplete called after onteardown

### ISSUE THREAD

**Issue by sabob** [ractivejs/ractive#2945]
## Description:
In this fiddle, http://jsfiddle.net/sabob/mygdmrzv/, the oncomplete lifecycle is called after onteardown. 

In my app I have a menu to switch between pages with a fading transition.
I generally use oncomplete to setup external libraries such as validations which need access to the form on the page. 

When switching pages I teardown the current page, then render the new page.

If I quickly switch away from a page that is still fading in, I get an error because the current page dom has been removed by the time oncomplete is called.

I expected the teardown call to jump to the end of the transition, call oncomplete, unrender the dom and call the rest of the lifecycle callbacks.

Is this a bug?

## Versions affected:
0.9, 0.8.x

**Comment by sabob** [comment]
Perhaps a more accurate approach would be for a teardown() call to skip the remaining lifecycle calls?

**Comment by ghost** [comment]
I believe this is intended behavior, as weird as it is.

`oncomplete` is async because it has to wait for transitions and stuff. So what happens is that the setup, rendering, _and teardown_ happen in the same tick while `oncomplete` is still pending. Putting breakpoints on each, it appears that `oncomplete` executes from a resolved promise, which backs up the claim.

Setup and immediately tearing down is an odd use case tho. You could [do `view.teardown()` _inside_ `oncomplete`](https://jsfiddle.net/mygdmrzv/5/) so it also waits with it.

> Perhaps a more accurate approach would be for a teardown() call to skip the remaining lifecycle calls?

Yep, it's probably a good idea to cancel any pending stuff when the instance is being nuked. 😄

**Comment by sabob** [comment]
Setup and immediately tearing down is an odd use case tho. You could do view.teardown() inside oncomplete so it also waits with it.

I cannot

**Comment by sabob** [comment]
>Setup and immediately tearing down is an odd use case tho. You could do view.teardown() inside oncomplete so it also waits with it.

My real life use case is explained in the description. Menus drive the teardown/render process, as users navigate around the site. The issue I saw arise because there are transitions between rendering pages. If users navigate away from a page to another page, before the transition completes, the issue arise. Another way this was produced is by pressing the browser back button twice :)

>it's probably a good idea to cancel any pending stuff when the instance is being nuked. 😄

Unfortunately, Ractive doesn't expose a way to cancel the current transitions.

Still, technically it should be possible to reject the oncomplete promise and not take further part in the clifecycle?

**Comment by evs-chris** [comment]
We can probably add a check in the complete handler to make sure the component isn't torn down. Part of me says that `complete` is an async event, so it's up to the user to check the state of things. I'm not sure what the best thing to do is in this case.

Out of curiosity, would the `destruct` event, which is the `teardown` analog of `complete`, work in this case if you're using 0.9? Also, FWIW, there's an exposed property `instance.torndown` that will tell you if the component has been torn down. `torndown` is available from 0.8, so you could use it as a check in the `complete` handler.

I still haven't come up with a good way to have cancel-able transitions. The simple cases aren't too bad, but getting layered runloops caused by things like `set`ting in observer callbacks makes things get pretty hairy.

**Comment by evs-chris** [comment]
Sorry, I had a bit of a reading comprehension fail. `destruct` probably wouldn't do anything for you and the issue as described. Are you cross-fading the views, or fading one out and a new one in? If the latter, I'd think that reasonably fast transitions along with keeping a queue of actions to drain would be a reasonable solution? I've been working on something similar, and that's the approach I'm taking.

**Comment by sabob** [comment]
Yep, fading out/ then in. The transitions is 200ms, so fairly quick. Even so, the error can still occur when user hits back button twice. 

In terms of workarounds there are a couple. The simplest for me is to move the onComplete code to onRender. since that is a sync'd operation. However this approach is limited since the dom isn't visible at this stage.
Also onComplete feels like a natural place to me to perform further dom manipulations.

> We can probably add a check in the complete handler to make sure the component isn't torn down.

Seems reasonable to me. It is an edge case, but if we can avoid it, it removes some cognitive overhead. ;-)

>Part of me says that complete is an async event, so it's up to the user to check the state of things. 

Nods, but that would create a bit of work since the check has to be done on every page.

Regarding the torndown check, that could be useful if there is a way for me to hook into Ractive lifecycle somehow to globally add this check? My Javascript ain't the best, but I know "prototype"ing does allow a fair amount of monkey patching.

>I still haven't come up with a good way to have cancel-able transitions. 

Are Ractive transitions in a queue of some sort? I know jQuery has the stop() method which stops all queued transitions and jump to their end state. As you mentioned this approach might not work very well in all cases for Ractive.

**Comment by sabob** [comment]
Tried to fix this locally, by checking if "ractive.torndown" is true before firing "oncomplete. But lots of tests fail after this change. Is firing oncomplete (even after a teardown) by design or is the next test kicked off before the current test finishes, thus causing the ractive instance of the current test to teardown before the oncomplete fires?

**Comment by ghost** [comment]
> Is firing oncomplete (even after a teardown) by design

`oncomplete` should just be in the rendering side of things, not the teardown side (I believe it has a counterpart on the teardown side). Here's a demo showing that [`oncomplete` doesn't fire on teardown](https://ractive.js.org/playground/#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gMYD2AdrgC4AEMAhgeQJYBuClAvJQEp2MsAUwADolB5BABtIlAOQAjIkgCe0rMNFiAtgAdxNMVOkAzIkRVrypYtvEIxfAJRCR5UUgSyArijQwA3OexzUjEaGCQiAHcSBydRV3cvH39nDGEMe2ThXFsAFQYNBCIPcj5DDxJ6BlIY81pKlgA6ELDI6Iy0rEoAJgAGPvtMIA). 

If you can open a PR or push up a branch in your fork, we could check what's going on. Tests do get wonky where transitions are involved, so it might be a tests problem. A quick tip is to run the failing tests solo (click rerun in the QUnit interface) to see if it's affected by the code change or the other tests in the sequence.
