### ISSUE TITLE
Browser freezes on huge updates

### ISSUE THREAD

**Issue by seriouz** [ractivejs/ractive#2950]
## Description:
The browser freezes due to heavy javascript computing and/or dom manipulation.

## Versions affected:
All

## Platforms affected:
All

## Reproduction:
Generate a table with 100 columns and 20.000 rows. Or a huge list of elements with complex sub models.

## Question:
Would it be possible to implement a config variable or tag-variable to let ractive render/update the dom with a list of asynchronous calls (window.setTimeout i.e.) to give the browser some time to let other threads run and preventing hanging/freezing of the browsers?

### Pseudo Examples:

Render lists in chunks:
```javascript
 var myRactive = new Ractive {
   chunkSize: 100
}
```

Render templates async with a tag keyword
```html
<script type="text/ractive" id="list">
    <ul>{#childs}{>child}{/childs}</ul>
</script>

<script type="text/ractive" id="child">
<li render-async="true">...some use of heavy templating...</li>
</script>

**Comment by dagnelies** [comment]
You're rendering 2 million elements. The browser rendering will be the bottleneck and will freeze. Ractive has nothing to do with it nor can it affect the rendering "lag" AFAIK. ...that's why paging and virtual scrolling were made. By rendering them in "chunks", you might even make it worse since late elements might cause re-renderings of the whole table.

**Comment by dagnelies** [comment]
Btw, here is an example of virtual scrolling with as many millions items as you want:

http://dagnelies.github.io/ractive-dataset/big.html

**Comment by ghost** [comment]
Related reading: [What is the XY problem?](https://meta.stackexchange.com/a/66378/177538)

By design, Ractive operates synchronously. Everything is synchronous except for transitions and animations. This makes the DOM reflect the data immediately after the data change. For instance, after calling `ractive.set`, the DOM is already updated. In contrast (and if I remember correctly), after calling React's `setState`, the DOM is not yet updated  - a feature of React but a common gotcha for most beginners.

Rendering the table that big is also bad UX. No one would probably read 20k rows. Have you considered pagination or other forms of chunked rendering?

If possible, provide us with a reproduction we can aid you to make it performant. It may be a code issue on your end and/or bottle neck somewhere in Ractive that needs fixing. 😄

**Comment by seriouz** [comment]
Thanks for the replies!
The problem started, because users, for which we made the webapp, wanted to see all data on one site. Yes i know it does not make any sense. So we ran into the problem of long loading times and worse the browser freezes. @dagnelies gave me a link to a nice ractive dataset plugin which adds chunks of row during scrolling (like facebook is doing it).
I think we could restructure the list with virtual scrolling and paging. And set the `ctrl + f` key event to a search mask above that list. If we don't find a suitable solution or come to a bottleneck in RactiveJS, i will contact you again.
