### ISSUE TITLE
Precedence and preparsing of inline partials and option partials

### ISSUE THREAD

**Issue by ghost** [ractivejs/ractive#2953]
## Description:

Three issues:

- Inline partials, according to the tests, should take precedence over option partials. But it doesn't.
- Inline partials alone on instantiation are preparsed. Are option partials supposed to be unparsed?
- The [unit tests for this feature](https://github.com/ractivejs/ractive/blob/dev/tests/browser/init/template.js#L139) only checks the presence of the partial, but not what it contains.

Discovered while doing https://github.com/ractivejs/ractive/pull/2912

## Versions affected:

0.7 and up

## Reproduction:

https://ractive.js.org/playground/#N4IgFiBcoE5SAGAdAdhAXwDQgM7wDoB2AxgPaE4AuABAMKkC2ADuQKaGUCM1AvNQEoBDYpQCWAN1ZJWAD0rsAJgApg1ecwA2g+ZGoByPdXQBKANxEyFGqKuCSrbn3rM2HTirWtN21rr3BgADNSUnR0AIBiJkEYMUENagAjGLCA5JhU4AB6aNjReLDDE3NCC3IcUg0pDVIAcyU9Gyo7YlZqbnUmLXk9TGomyhaHJE7u1j6AbVUYP2DSXrVdACYjAF0zMopK6rqGgaH2pJjqXLiNBf37TiRT-I0cJHTJ6b90hcpltY3SknKaZxYhHYlBWfCEIgkUlk8kIylUox8fiK30sVH6tnsoLojEBwKWKiI+EoCJ0+gCc0yURiZyOGXCwHSmRy1LuhUwhMot3iOF0qnSfgCRwAXkZ0AsAI4AVxkAtUUpkoqKRGKhN+WyqSBq9UaGNa1BWJNYF11rCWIy8XR8z2oM30c3en3Q6xKqO2mt2Oua9n1tJOLPixq9rTNXPujxi1ttejefQ+PqdKPKbq1exNPvlfryAb6l2DN39Yflkb88od8edGCAA

## Code:

```js

const Component1 = Ractive.extend({ template: '' });
const instance1 = Component1({ template: '{{foo}}{{#partial bar}}{{bar}}{{/partial}}' });

console.log('instance 1 template', instance1.template, [{ r: 'foo', t: 2 }]);
console.log('instance 1 bar partial', instance1.partials.bar, [{ r: 'bar', t: 2 }]);

const Component2 = Ractive.extend({ template: '' });
const instance2 = Component2({
	template: '{{foo}}{{#partial bar}}{{bar}}{{/partial}}',
	partials: { bar: '{{ baz }}', qux: '{{ qux }}' }
});

console.log('instance 2 template', instance2.template, [{ r: 'foo', t: 2 }]);
console.log('instance 2 bar partial', instance2.partials.bar, [{ r: 'bar', t: 2 }]);
console.log('instance 2 qux partial', instance2.partials.qux, [{ r: 'qux', t: 2 }]);
```

**Comment by evs-chris** [comment]
I _think_ this is probably because inline partials nested directly within a component (or instance) template are effectively an option partial. The parser pulls top-level level partials out into a hash attached to the parsed template. That hash is merged with the partial option, which has precedence at that level.

Inline partials within an element are attached to the element and will resolve before option partials.

**Comment by ghost** [comment]
After a bit of tinkering, the behavior is strange but seems correct:

- If an inline partial is declared in the template and there's no option partial defined with the same name, regardless of the partial being used or not, it makes its way to `ractive.partials` parsed.

    ```
    const instance1 = Component1({
      template: '{{#partial bar}}{{bar}}{{/partial}}'
    });
    // instance.partials.bar === parsed inline bar
    ```

- If an inline partial is declared and an option partial of the same name is defined, the unparsed option partial is found on `ractive.partials`.

    ```
    const instance = Component1({
      template: '{{#partial bar}}{{bar}}{{/partial}}',
      partials: { bar: '{{bar}}' }
    });
    // instance.partials.bar === unparsed option bar
    ```

- Only when the inline partial is used on the template does the inline partial replace the option partial in `ractive.partials`.

    ```
    const instance = Component1({
      template: '{{#partial bar}}{{bar}}{{/partial}}{{> bar }}',
      partials: { bar: '{{bar}}' }
    });
    // instance.partials.bar === parsed inline bar
    ```

It does make sense not to parse the partial until used. But I haven't checked out other cases. :D

**Comment by evs-chris** [comment]
Addressing the original three points:

1. It looks like the correct thing is happening - inline partials on component calls win over the option hash. Things get fuzzier when you look at inline partials on the template option vs the hash, but that's not really something that should come up - use one or the other, but not both for the same name.
2. The inlines are pre-parsed because they're pulled off of the parsed template that's passed to the component. The options would only be pre-parsed if the user pre-parsed them.
3. I don't think I've ever actually looked at those tests. They're weird.
