### ISSUE TITLE
`data` property magicly added, containing all data

### ISSUE THREAD

**Issue by jasny** [ractivejs/ractive#2954]
## Description:
Ractive automatically adds a `data` property to the data with all the data. This is weird and causes a conflict if you have your own `data` property.

## Versions affected:
v0.9.0 all builds

## Platforms affected:
Chrome 57

## Reproduction:
* v0.8 -> https://jsfiddle.net/ffro38eL/
* v0.9 -> https://jsfiddle.net/g4qh5xbh/

## Code:

```js
var ractive = new Ractive({
  el: output,
  template: "{{ JSON.stringify(data) }}",
  data: {
  	foo: "bar"
  }
});
```
Expected blank, but got `{"foo":"bar"}`

**Comment by evs-chris** [comment]
There's not really a conflict if you have a `data` property, because the `data` property will win. This is a function of the `resolveInstanceMembers` init option, which puts all ractive instance properties at the end of the resolution process. If you set `resolveInstanceMembers: false`, then you don't get the instance `data` property: https://jsfiddle.net/g4qh5xbh/1/
