### ISSUE TITLE
0.8.12 - Calling unrender on a component does not remove the instance from DOM

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2959]
Here is the fiddle: http://jsfiddle.net/jL4601re/2/
While teardown works as expected, unrender does not remove the component's HTML from DOM.
Am I missing something obvious here?

**Comment by sabob** [comment]
I'm not an authority on components but I remember Ractive doesn't unrender components because their render cycle is dependent on the instance they belong to. So even if you unrender the component, Ractive will ignore the command. Only when you unrender the parent, will the component unrender. I don't know why teardown behaves differently though.

In 0.9 there is a new component API which allows you to fully control the component render cycle: parent.attachChild and parent.detachChild. When you call detachChild the component willl be unrendered.

**Comment by evs-chris** [comment]
There are scenarios in which a component will be asked to unrender when it shouldn't actually remove itself from the DOM (because something else will be removing it from the DOM). That's what you've bumped up against here. The component is managed by another instance, which is saying it shouldn't remove itself. I'm not entirely sure of the best solution to this particular problem, other than perhaps explosing the flag that say "yes, go ahead and unrender" to the instance `unrender` method. That would make the call `instance.unrender(true)`.

**Comment by kouts** [comment]
I found out about this by accident when doing some tests, I wasn't going to use unrender on a component
so I don't know if "fixing" this is the right thing to do. Maybe just explain this behavior in the docs?

**Comment by ghost** [comment]
Didn't know about this feature. In this case, a warning might suffice in debug mode and a note on docs for unrender. Also curious about the scenarios that led to the implementation of this feature.

**Comment by evs-chris** [comment]
It's partially an issue of conflating internal and external API at some point. The component VDOM item should _really_ use a strictly internal API, as it's what cares about leaving the component DOM intact for transitioning purposes. It uses `instance.unrender()` instead though, which means that `unrender` can't force an actual unrender by default when it is called.

**Comment by evs-chris** [comment]
I'll call it a docs bug for now, and if the issue arises again at some point or there just happens to be an appropriate refactor, we'll address it then.
