### ISSUE TITLE
splice causes error when removing items

### ISSUE THREAD

**Issue by sabob** [ractivejs/ractive#2961]
## Description:
This [play](https://ractive.js.org/playground/#N4IgFiBcoE5SBTAJgcwSAvgGhAF3gDxICWAbgATFIC8AOiALYCGxAdvQHy0y3u7e8CAehKkuPdhIIBnAMYxiAB1yUa9XAgaKANkw31yuAJ6KEdPAgAeuIWFwNtnAZMG4mAI20Jys3dOnUAORungiB4rzkUdExseTAwADEMAD2AO7SkMQYGM5x+dEEuDARrAXlhbhIHAmsTAwIOcJVpRUVRdUJTGhNQi15bQUdrYNtBO4Arri4KWW+TP7m7rhly6wAtEhMrGg8IOSz677EsgDW5gACuGDE0gB0MJoppAgAFMQAlJwASk8vwpNprMRqNYs1qgNQc0SpDRgkhKkMjlnLCYs0PF4QWChHIFMoOCAcNJ4F4VDAmLJyNRyKwEGlyN8KbgyG9gLxaBptJByPREsw2PQsOzppodHoENzeRotLp9IThVs3Ny2XwOYjMuQANrCjkc4A0+oSnkgABCKXcgvI3SNACYAAxYVTcgCMzvI2B1-Fw+rqDUlIAAyhoXpbrdyAMwOp3kZ0292egC6wo9qr4jwYzyNADMJqxZMzZu9WEgrB94p7rrc7tIdCc3sb1Za2CXLI63R8ANzJ3gYL7sViYIA) shows a loop with a button next to each row that deletes that row. It deletes the row but there is an error in the console:  
>Cannot read property '_ractive' of `null`

I could trace it to this [loop:](https://github.com/ractivejs/ractive/blob/f6a5b44a98e182edba47c515b73da9494f13f103/src/view/items/shared/EventDirective.js#L29)

Eventually node.parentNode becomes 'null', before matching the end node.

## Versions affected:
0.9

**Comment by evs-chris** [comment]
This is an interesting corner case where an element with a delegated event handler is removing itself and its parent(s) while bubbling the event. When the element is detached from the DOM, it no longer has a parent, so bubbling can't continue. That part is now fixed, but should the list of elements be defensively copied ahead of time so that bubbling can continue, or is it safe to say that that's a special case that you could just turn off delegation for?

**Comment by sabob** [comment]
Before your fix, would you have expected not to have this error if delegation was turned off?

Before opening this issue I did try the following:
> Ractive.defaults.delegation = false

Got same error

**Comment by evs-chris** [comment]
That's really weird because the bug is in the delegation code. I'll take a look at when I get back to a real machine.

**Comment by sabob** [comment]
Turns out to be a doco issue, changelog says:
>Ractive.defaults.delegation = false;

But should be:
>Ractive.defaults.delegate = false;
