### ISSUE TITLE
0.9 edge - setting a variable inside a component does not work

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2963]
I'm trying to port my existing app (running 0.8.12) to Ractive edge and I begun some tests.
First thing to encounter was this behavior displayed in the following fiddle.
http://jsfiddle.net/4qmbqxzr/1/

When pressing the "Show popup" button, Ractive fails to set the variable so the content never shows up.
I have all my components to isolated: false

This works fine in 0.8.12
http://jsfiddle.net/gz3tw2w0/9/

I know that @this.root.set would work and also defining the variable inside the template of TestComponent would work (i.e printing {{page_info.show_popup}} somewhere), but this is an option I don't currently have.

So is this a "bug" or is this the intended behavior?

**Comment by evs-chris** [comment]
There's a weird interaction happening between the middle component and the implicit mapping between the popup component and the root. If you throw a [`this.get(basedon)`](http://jsfiddle.net/4qmbqxzr/2/) in the `complete` handler, it will work as a workaround. The `observe` really should be enough though.

I'm looking into why the `observe` alone isn't enough.

**Comment by evs-chris** [comment]
I've tracked down the issue, and it seems that the `get` working is actually a bug at this point. What's happening is the popup component is observing a keypath that it doesn't have, and ractive is correctly creating an implicit mapping to the root where the data exists. The middle component does _not_ have a reference to `page_info`, so no mappings are set up. When the middle component calls `set('page_info.show_popup', true)`, it has no mapping, so it creates its own model to hold that data, which is obviously disconnected from the root data. If you call `get('page_info')` in the middle component init, that would correctly create an implicit mapping to the root data.

There may need to be a behavior change for this to work out in a sane way, and I see two options:

1. When setting up an implicit mapping, also create mappings in any components that happen to be in the middle as well.
2. When something is doing a `set` on a keypath that does not yet exist, allow it to look for an upstream keypath to map in. This could be defaulted to on, and it would be a breaking change. It could also just be introduced as an option.

At this point, I'm not really sure which approach is best. The first is considerably more automatic and would not affect isolated components. It also may be a bit surprising that mappings appear in intermediate components. The second gives you a bit more control over exactly what happens, but it's also something that would either be breaking or require the additional option. It also wouldn't affect isolated components.

Opinions?

**Comment by kouts** [comment]
I thought 2. is the behavior we have now (0.8.12) on non isolated components, no?

**Comment by evs-chris** [comment]
0.8 actually has a slightly different version of the `get` bug in 0.9, where it creates the mapping in the popup component _and_ the middle component from `observe` too. If you added another intermediary component between the middle and the popup, you would have the same problem in 0.8.

Fixing the `get` bug in edge actually exposed a few issues with the test suite. I also implemented the first option to see if it would break anything in the test suite, and it didn't.

I think option 2a might be default it to on for non-isolated components and have an option to turn it off for `set`-type calls. Option 1 seems to play out ok too, but it doesn't quite feel right - like it may have some unintended consequences for slightly more complex scenarios. Though, option 1 is basically what is happening in 0.9 with `get` and 0.8 with `get` and `observe` if you only have components two levels deep.

**Comment by kouts** [comment]
@evs-chris  do what you feel it's best!

**Comment by ghost** [comment]
So long story short, observer hooks up to the top to begin with but something of the same name appeared out of nowhere in the middle. And the ask is to tap on the middle if it exists? 🤔 

Not sure what's "good" in this case.

From a setup point of view, wiring the observer to where it found the data first sounds like a stable choice since it presents lesser surprises during runtime. A warning would probably be needed saying "Hey! We tried to get this value but didn't find it in [ancestor 1, ancestor 2, ...]. However we found it at [ancestor N] and we'll wire it directly." 

However, from a resolution point of view, the on-the-fly "let's ask our parents of they know" approach seems reasonable, as it is consistent with how one would think about resolution. Although I'm not sure what this entails in terms of setup and performance. I'd imagine all components will need wiring regardless of if they even map to it or not.

(now I'm starting to see why Angular uses prototypes for resolution)

Also, this is a strange way to implement this feature. Whenever I use observers, I always remember the advice they give out to Angular devs when using watch which goes like "If you're using watchers, you're doing it wrong." It's because Angular already has watchers for data for use in two-way binding. Adding a manual watcher was redundant.

How about doing it [this way](https://jsfiddle.net/bjprxoaa/)? Besides `basedon="page_info.show_popup"` maps a hardcoded key. Why not pass `page_info.show_popup`'s value instead?

```
Ractive.components.popup = Ractive.extend({
  isolated: false,
  template: `
  	<div style="display: {{ display ? 'block' : 'none' }}">{{yield}}</div>
  `
});

var TestComponent = Ractive.extend({
  isolated: false,
  template: `
	<p>
    This is a test component
    <button on-click="@this.set('page_info.show_popup', true)">Show the popup</button>
  </p>
  <popup display="{{ page_info.show_popup }}">
    This is a popup!!!
  </popup>
  `
});

var ractive = new Ractive({
  el: '#my_test',
  template: `
    <div class="row">
      <testcomponent />
    </div>
  `,
  data: {
    page_info: {
      show_popup: false
    }
  },
  components: {
    testcomponent: TestComponent
  }
});
```

**Comment by kouts** [comment]
@fskreuz you are right about observers, I too use them sparingly.
This is an oversimplified example of what this popup component does.
In reality the observer opens a jquery popup plugin when newValue == true and closes it
when newValue == false.
So this observer actually uses data to invoke an action, whether this is "right" or "wrong"
depends upon implementation I think.

**Comment by sabob** [comment]
My opinion shouldn't carry much weight since I don't use components very much. This will probably be a bit controversial as well ;-)

Looking at the example, I had a hard time figuring out why it would break. Only when @evs-chris pointed out that the observe resolve to the root context and @set resolves locally did I realize all the implicit logic occurring.

So I'd argue for another option:

3) remove "isolated" as an option, it should always true and cannot be changed. Isolated has too much effect. Reasoning about code with isolation true vs false is like looking at two different code bases.

Back to the above example, my understanding with isolated:true, is that the data will have to be explicitly passed in (or mapped as it is also called) from the parent to the children:

```
<testcomponent page_info={{page_info}}/>
```
and
```
<popup basedon="page_info.show_popup" page_info={{page_info}}>
```

Looking at the template with explicit mappings it is a more obvious if a mistake is made. If get/set doesn't work, it is because the data was not set on the child. There should be no workarounds and no implicitness.

The price is paid by the author, because she has more work to do (explicitly map the input). But the reader has an easier time to solve issues. 

Nothing is free though, explicitness (boilerplate) can be annoying to code.

**Comment by kouts** [comment]
There are scenarios that isolated: false comes very handy, it depends on how you structure your app and what "component" means to you, the developer. 
Sometimes "components" are just interchangeable parts of a bigger layout that composes a view and if you have a **standard data structure** coming from the backed, there in my opinion explicitly passing all the data object's nodes that the component must "use", does not make any real sense.
When this is the case, seeing all these mappings (I'm talking **alot of mappings**) inside the HTML template  just makes my eyes hurt. :smile:

I really like the freedom of Ractive gives you in that area!

**Comment by ghost** [comment]
I'm in favor of making components just isolated. I agree that there's just a lot going on with implicit resolution. If you think about it, regular HTML elements don't implicitly inherit attributes from its ancestors. You need to provide them every time. And that's not so bad at all. 😄 

But then, that's just opinion. :D

**Comment by sabob** [comment]
@kouts I hear you, but is components the best fit for that scenario? Do you need the parent/child relationship going or is partials enough to split the html into sections? 

Components are all about reusability and providing an explicit mapping of its input is good for the API. Relying on implicit data higher up the chain, especially if that chain is more than two levels deep (as with this issue) becomes unwieldy. Not for the author of the code , but for the reader.

The problem I see with isolated:false is that large codebases can be built with Ractive and leaving room for so much implicit magic can cause maintenance problems.

Documenting isolated:false is also a challenge: we have to explain implicit mappings of set vs get, components in the middle (which is what this bug is about).

Documenting isolated:true is simply: pass it in or else it fails.

As you said, it depends on how you view "components". But therein lies the rub, we are bound to view "components" differently, and that is perhaps not such a good thing. Ideally one should move between Ractive codebases (even different companies) and expect to be on familiar ground.

**Comment by evs-chris** [comment]
I completely agree that non-isolated components are not great for maintenance, but they're also super handy for fast prototyping and some app structures. I think defaulting to isolated components in 0.9 is a good thing and will encourage cleaner designs from startup.

The more I look at this issue, the more I think option 2 is best. If you have isolation off, then it shouldn't be surprising that `set('foo.bar', 42)` could be operating on parent data. We can still provide an escape using an option `set('foo.bar', 42, { isolated: true })`.

Side note regarding mappings: you can now actually compose partials containing mappings, but you have to do it by hand as there's not an explicit parser mode for parsing in an attribute context. That parser flag should probably get added.

**Comment by sabob** [comment]
Wrt prototyping is there any advantage to isolated: false vs simply passing in all the data needed by the children?
<child graph={{all-the-data-children-may-need}}/>

While this seems like a get-out-of-jail-free-card for explicit mappings, at least bugs such as this one won't occur?

**Comment by andreujuanc** [comment]
@sabob How would you implement that? Sounds nice.

I understand @kouts and maybe partials are the best solution here. @sabob idea is not bad, just maybe over complicated?, but I liked it xP

**Comment by sabob** [comment]
@andreujuanc you mean prototyping with explicit mappings? My thinking is this:

Given a main ractive instance with data fetched from server:
```
let page-data = fetchData();
ractive = new Ractive({
    data: page-data
}});
```
we can explicitly pass in all the data to the children:
```
<child graph={{page-data}}/>
```

vs implicit mapping

```
<child/>
```
If I'm understanding components with explicit mapping, making get/set calls in the child will resolve to the graph we passed in.

With implicit mapping (ie not passing in the graph to the child), get/set calls will try and resolve across component boundaries which can cause weird issues, like this one.

Not being a component champion I could be completely off base. Or miss some of the advantages of implicit goodness?

**Comment by evs-chris** [comment]
The benefit for prototyping is when you have a wide field of data that changes around a bit during prototyping and a semi-deep (two or three) logical view (non-widget, so not really reusable) component structure. Having more than five or six mappings on a component can get pretty cumbersome, especially when they change names and need to be propagated deeper.

I suppose you could think of explicit mappings as DI and implicit mappings as just using globals. The DI is better in the long run, but you can get by on globals and usually a good deal faster. Rich has said that his issue with explicit mappings during the prototyping stage, which to be fair, is usually the only stage of newsroom apps, is that you don't usually know what data you're going to need in the component until you need it. At that point, the path of least resistance is to just share the data throughout the hierarchy.

**Comment by sabob** [comment]
The global vs dependency analogy is pretty good. I'll take it.

**Comment by evs-chris** [comment]
I implemented option 2 on edge and all seems to be working with the example now: http://jsfiddle.net/4qmbqxzr/3/. If you want to _not_ implicitly map from a non-isolated component, you'll now need to pass `{ isolated: true }` to the mutator method (`set`, `add`, `toggle`, etc).

**Comment by sabob** [comment]
Here is a detailed discussion on components and explicit mapping (passing parameters to components).

#2166 - I'm not sure if a better way was found though ;-)
