### ISSUE TITLE
Inconsistent behavior for <select>s without twoway binding

### ISSUE THREAD

**Issue by paulie4** [ractivejs/ractive#2965]
## Description:
If a template has a `<select>` without twoway binding, then its value will get reset when any unrelated keypath used in the same Fragment is updated. This behavior is inconsistent with how other inputs behave, e.g. `<input>`s and `<textarea>`s do not get reset when the Fragment updates.

## Versions affected:
Ractive 0.9

## Platforms affected:
All

## Reproduction:
[ractive.js.org/playground/ example](https://ractive.js.org/playground/#N4IgFiBcoE5SBTAJgcwSANCAzlA2iCALoC+WukIAbgIYwAEDAvPQHYIDu9ASjQMYAXAJZUEACmAAdVpIEIANpHoByJCOUZpsuQFsADvJpylygMS6DRhBq0CkRmkqkyBsvTAQAzIQA8TNl1khViEBADUaRRUAJmVbMlsBDgB7DhoATyVPSOwEaRIASgBuTBABeAAeNSoAPgqAemqa6QrsPhghPQF6ISQmSTKEfUM5AebWenoAFTAhbHoEHxphhB75eQBXbAEYK3mBMCN6A9Xc+QRBZHpkrqFkibn6PkPWNCR6DjAECZoJjdYPCMrgBrBDpPRGMBPF5obAAOgqACMYONZBVDIiFDVgMB3F5fCQSPQAMoKC6uFyTVpkwT0WibBD9EA44KhCLyQljWyTKk3YT3OmRDaMgYARjGooafLurFR3R5FWlAvpwqZ0TG0Slt3ucp59EV2omKpFIAAzGNTVr+bLufr6mdyXKGhisbYkSitC50TRMfJsbiPN4fIT6ABJVh6DYU2RU4KR7rGpkskLhSKckBO+ouv1u5Gor3Z-14oMhqaLAQAQQ8NFtFTkPgEdAQNEFDKTwFZqY5JDGDXrjermcLuY9gS9iKjAgF9wAtHx5EI+MCmQABOG5ARiZTF3waFQABW4AFFlAUxs9fmh6DufGxkt1O+yGhOBFObawGm0Ol0aiASEA)

**Comment by evs-chris** [comment]
The select sync wasn't checking the dirty flag, which caused it to always update. It will now only update if something in it _actually_ changes. Note that you can also use a static interpolator (`<select value="[[initVal]]">`) for things like this to avoid the binding and unintentional updates in case `initVal` happens to change. This particular bug would still cause a problem even with a static interpolator, though.

This should be fixed in v0.8-dev and edge as soon as travis finishes his thing.
