### ISSUE TITLE
0.8.12 - stopPropagation produces a type error

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2968]
This happens in 0.8.12 (check fiddle here: http://jsfiddle.net/0w0dsjxn/5/)
but not in Edge (check fiddle here: http://jsfiddle.net/v5xLrbv6/6/)

To see the error: open the console, press "Show the popup" and then close the popup by pressing
either the top right "x" or the "Close popup" button.
It seems that something is going on with the transition because without the transition it works as expected.

**Comment by evs-chris** [comment]
This is an architectural issue with <= 0.8. The event arguments bind and unbind with their template, and the `set` `false` is causing the template, including event handlers, to unbind before the event bubbles. Since there's a transition in play, the elements are still sitting around waiting on the transition to finish and the event bubbles up triggering the other click handlers. Those handlers are unbound, so their expression functions get undefined arguments because they're no longer bound.

0.9 dropped the whole binding cycle for events and just resolves refs on demand. That's why it doesn't blow up.

**Comment by evs-chris** [comment]
I'mma close this, but if you need 0.8 to be a bit better behaved, feel free to reopen it and we'll see if we can prevent event directives from trying to fire if they're unbound.
