### ISSUE TITLE
Support Ractive Development / Maintainers

### ISSUE THREAD

**Issue by rockerest** [ractivejs/ractive#2975]
I like to show support for projects that I love, and it doesn't seem like Ractive is set up to accept donations.

Are there any plans to get Ractive on something like https://opencollective.com so those of us who want to see Ractive succeed but just can't find time to submit that PR they've been meaning to can show support?

For something like Open Collective, I *think* all it requires is a loose concept of "team" and then you can start accepting backers and using funds transparently. If a few backers could help core maintainers go to meetups, speak at conferences, etc., Ractive will surely gain popularity (how could it not?) and support / community.

*How can I give you my dollars?*

**Comment by ghost** [comment]
I'll leave this one to @Rich-Harris

**Comment by Rich-Harris** [comment]
@fskreuz thanks, but I think this is a question that belongs with you and @evs-chris as the lead maintainers! My involvement these days only really extends to cheering from the sidelines.

**Comment by rockerest** [comment]
Another perspective on the overall idea of "funding" open source: https://github.com/moment/moment/issues/3979#issuecomment-304533266

**Comment by ghost** [comment]
I was about to comment the same thing, but I think that comment summarizes everything for me.

For me, time is the hardest thing to find. Contributing is a fun hobby, a learning experience, and a good deed all rolled in one. But after 8 hours of sleep and 12 hours of the daily grind, there's not much left for everything else. Aside from daily responsibilities, I watch movies and I game... a lot. Work hard, play harder. 😁 

What this project needs is people, lots and lots of people. That's why in the past few months, we've been doing housekeeping - code, docs, everything. We're enabling everyone, regardless of background, to be able to contribute easily. Everything else like contributors, exposure, good ideas, etc. will come in organically as a side-effect of being very contributable. After all, it's a feature of the project: Optimized For Your Sanity. 😄 

Not sure where funding would fit in really. If funding gets us a time machine, that's a different story. 🙃 

I'll let the others chime in as well. After all, it's a community effort. 🎉

**Comment by evs-chris** [comment]
Here's where I'm coming from, which is pretty close to what's conveyed in the moment comment: I use ractive for my personal projects because I enjoy it and none of the other templating/view libraries I've evaluated over the years compare particularly favorably (svelte is a close second, but I'll leave the _why_ out here). I also use ractive in commercial projects for clients, which means that they usually donate my time to fixing bugs, improving performance, and adding features. It's also a bit of a hobby for me because it was my first use of JS beyond a bit of jquery and scriptaculous associated with rails.

I'm also not sure how funding would fit in here. I have no experience with bug bounties, but that seems like it might be a way to attract more contributors? Honestly, just getting more feedback on issues and PRs and hearing a few success stories would be pretty rewarding for me.

**Comment by MartinKolarik** [comment]
I think funding *can* help open source projects, but it definitely isn't an instant solution for all problems. For me, being paid for working on OSS works, because I work as a freelancer and can relatively easily allocate the necessary amount of time. I love Ractive and would like to contribute more, but with all other responsibilities I have, I'm unable to do so outside my "paid working hours" right now. However, I fully agree that most OSS maintainers probably have full-time jobs and this model doesn't really work for them, for the reasons explained in the moment.js comment.

**Comment by mattapperson** [comment]
To me though, the argument is that there is a need for MUCH more money. Enough to not have to have a full time job right? 
Because there is not a need for extra side cash because someone feels the need to make money for their time... the issue is that between work, life, and sleep there is not enough hours in the day... remove or severely decrease the need for work and now you have time.

**Comment by MartinKolarik** [comment]
@mattapperson yes, that's pretty much it. Also, many people are happy in their full-time jobs and wouldn't want to quit even if they could.

**Comment by mattapperson** [comment]
@martinkolarik yea for the maintainers perhaps. But with more money on the table it would be easier for freelancers to become more active contributors no?

**Comment by mattapperson** [comment]
Money on the table or not, OSS needs to be a collaborative effort

**Comment by dagnelies** [comment]
Let me start with an anecdote. Once (like 2 years ago or so), I suggested my boss we could use Ractive in one of our product. Basically, he considered it, but in the end decided against it. His main thought was "if the couple of maintainers drop it, it's a dead fish in the waters" ...and, guess what, they went for the angular route (luckily I'm not really involved in that project).

I think financial backing would be great. It's not just a "salary" but could lead to other things: covering expenses for events, conferences ...showing that this project *lives* and is important enough that people companies freely pay for it. On the other hand, I doubt donations would bring in more than ridiculous amounts.

...and hey, I'd be glad to spend @evs-chris and @fskreuz a *"Ractive.js T-shirt"*! 😉 
Perhaps that's a way to do it too: "merchandize". Buying coffee mugs or T-shirts as a way to support the project, and promote it a bit on the same way. It's still ridiculous amounts, but I'm sure some would love their mugs. 😝

**Comment by mattapperson** [comment]
@dagnelies thats why me and my team built [GitFundMe](https://gitfundme.com). We are trying to help the OSS community move beyond donations for the exact reason you just mentioned. 

Our concept is that companies such as yours could opt to pay for monthly or ad-hoc support agreements to ensure the stable project they so desire.
`</ShamelessPlug>`

**Comment by MartinKolarik** [comment]
@mattapperson yeah as I said in my previous comment, I think it would mostly help freelancers.

**Comment by boussou** [comment]
@mattapperson I like this project: we are developers, not beggars. 
I hate the idea of donationware.
EDIT: btw, your app uses React. ;-)

**Comment by mattapperson** [comment]
@boussou shhhh lol. Hey everyone has to use something right? :)

**Comment by tomekmarchi** [comment]
@evs-chris love you bb

**Comment by rockerest** [comment]
I'm closing this, since I feel that the issue has been addressed. I think the maintainers are largely in general agreement with the perspective from the above linked Moment post.

Feel free to reopen if this needs more discussion.

**Comment by kouts** [comment]
We're now on Ractive v1 🎆 and I would like to bring this back up.
I suppose I agree with @dagnelies that maybe donations won't bring any serious amounts,
but unless we do it we don't really know, do we?

I for one support any form of financial backing @evs-chris and @fskreuz  as the lead maintainers propose.
Open collective seems like a nice idea, we could do this without any specific financial goal set.
It doesn't only have to do with money as value but as a way expressing our gratitude to the effort.
