### ISSUE TITLE
Style-attributed set to outdated value after transition

### ISSUE THREAD

**Issue by LeJared** [ractivejs/ractive#2986]
## Description:
When an element is transitioned-in (e.g. fade-in) any style-*-directive or style-attribute which was updated after the transition had started, will be reset to its initial value it had right before the transition began.

## Versions affected:
0.8.14

## Reproduction:
https://jsfiddle.net/lejared/v7m4jxwb/
Click on "Toggle Visible" to start fade-in animation
Click on "Change Color" before animation ends

The Color will change instantly but will be reset to its initial value after the transition has completed.

Note that the colors text-value in the box is not affected.

**Comment by evs-chris** [comment]
The issue is that transitions take a snapshot of the `style` property when they start and then restore it when they finish. Anything that happens in the middle is not accounted for. We can address this by tracking individual property values on transitions and only restoring those that have a value that we expect, but there's a considerable amount of cruft in the transition code that makes it a bit painful.

**Comment by LeJared** [comment]
Naive approach without knowing anything about the internals: Wouldn't it be possible to just reapply the current model on the style-attribute or re-evaluate any style-* expression after the transition has completed?
