### ISSUE TITLE
Every docs.ractivejs.org link is redirecting to home page

### ISSUE THREAD

**Issue by hadijaveed** [ractivejs/ractive#2987]
It's been like 5 days since every search engine page is redirecting to home page. Which is kind of annoying for me.

**Comment by ghost** [comment]
Previously, Ractive is comprised of 5 different repos backing 5 different domains (homepage, learn, examples, docs, cdn). Currently, we're consolidating everything to one repo, one site, and a new js.org domain so that everything is in one place. The new site is https://ractive.js.org/ and all the old urls redirect to it.

Should you have any bookmarks saved, now's the time to update them. Docs are also in flux while we simplify some of the pages, so pages may shift around in the next few months. 😄

**Comment by hadijaveed** [comment]
Makes sense. I hope one day search engines will pick up all the new pages
