### ISSUE TITLE
0.9 - copy data object, wrong values 

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2988]
Here is the link in the playground: https://goo.gl/zLGf4F
When I'm copying the data object with ```JSON.parse(JSON.stringify(this.get()));```
I get the previous selected values instead of the current values.

Change a dropdown select and then check the console.
This does not happen with 0.8.
Any ideas?

**Comment by ghost** [comment]
I vaguely remember having a discussion about this before, whether or not to update something before or after the change event. Lemme see if I can find it.

**Comment by ghost** [comment]
Aha! Found it! https://github.com/ractivejs/ractive/issues/1371 Not sure if this was reintroduced recently. Worth debugging tho! 😄

**Comment by kouts** [comment]
If data isn't copied it works as expected though, check it here: https://goo.gl/TiBCHE
Not sure if this is exactly like #1371

**Comment by evs-chris** [comment]
This is caused by twoway bindings not being delegation-aware. I'll see if I can extract an internal listening interface so that they are, which will have the bonus of allowing custom events and decorators to use delegation as well. In the meantime, you can throw a `no-delegation` directive on the `div.row` element to prevent it from being a delegation target or just turn off delegation entirely with `Ractive.defaults.delegate = false` if you don't have any iterations with more than several events.

**Comment by kouts** [comment]
But why does it work with 0.8 https://goo.gl/BXOYPa ?
I'm not sure what delegation-aware is :blush: would putting ```Ractive.defaults.delegate = false```
revert to the 0.8 behavior?

**Comment by ghost** [comment]
It's an optimization feature that was added just recently. It's similar to `jQuery.on`, where the handler is placed on an ancestor instead of the element itself. Helps with dynamic elements, and avoids adding repeated handlers when you can let bubbling do its thing.

- https://github.com/ractivejs/ractive/pull/2841
- https://github.com/ractivejs/ractive/pull/2846

By default, [it's enabled](https://ractive.js.org/api/initialization-options/#delegate). As with any initialization option, modifying `Ractive.defaults` will globally change the setting. `Ractive.defaults.delegate = false` globally disables it.

**Comment by kouts** [comment]
Ahh I see! Ok so Ractive tries to delegate the events "automagically", nice!
Hope this gets fixed so we can retain the performance benefits added by this feature.
Thank you @fskreuz  and @evs-chris

**Comment by evs-chris** [comment]
@kouts I've pushed the fix for delegation and twoway bindings out to edge. If you have some time, could you try edge with you app a bit to make sure everything is good to pull it to the 0.9 branch?

**Comment by kouts** [comment]
@evs-chris it works but the event is fired twice, I shall post a fiddle soon.
Edit, here it is: https://goo.gl/ueMDQL

**Comment by evs-chris** [comment]
@kouts whoops, logic derp. Should be good now.

**Comment by kouts** [comment]
It's ok now, thank you @evs-chris 
You can push this fix to 0.9.

**Comment by kouts** [comment]
@evs-chris can you push this fix to 0.9 also?

**Comment by evs-chris** [comment]
@kouts I have a planned cherrypicking later this week.
