### ISSUE TITLE
Disabling two-way binding for certain decorators

### ISSUE THREAD

**Issue by monoblaine** [ractivejs/ractive#2989]
AFAIK there are 2 ways to disable two-way binding:

# First way

```js
new Ractive({ twoway: false })
```

# The other way (per element)

```html
<input type="text" value="{{someValue}}" twoway="false">
```

The thing is, I'm planning to write a decorator to use some jQuery plugin and I want to have two-way binding disabled wherever I use that decorator, so I won't have to do this:

```html
<input type="text" value="{{foo}}" twoway="false" as-myDecorator>
<input type="text" value="{{bar}}" twoway="false" as-myDecorator>
<input type="text" value="{{baz}}" twoway="false" as-myDecorator>
```

Is there any way to do this?

**Comment by kouts** [comment]
Yes, you can have your decorator handle the two-way binding instead of passing it to ```value```
You can do this by passing the keypath as a string argument to the decorator and using ```getContext()```
on your element inside the decorator.

**Comment by kouts** [comment]
Here, check this: http://jsfiddle.net/2cgkzs8h/1/

**Comment by monoblaine** [comment]
Thanks! Funny thing is, the jQuery plugin that I'm planning to use is also `autoNumeric` 😄

**Comment by monoblaine** [comment]
Hey @kouts I've created a fancy little demo based on your work:

http://jsfiddle.net/monoblaine/6kb433Lt/18/

Instead of creating a custom observer within the decorator I chose to send keypath and value expression to the decorator function:

```html
<input type="text" as-autoNumeric="@keypath + '.value', value">
```

When either the keypath or the value change the method `update` of the decorator is executed, which seems to be fair enough. To make sure there's no two-way binding involved, I made sure these two parameters are provided and that `Ractive.getContext(node).isBound()` is falsey.

BTW, decorators are awesome! 😄

**Comment by evs-chris** [comment]
@monoblaine you can acually skip passing the `@keypath` part with 0.9 because the context will let you use relative keypaths (`.value`) for observers and `get`/`set`. [Here's](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAF3gDxICWAbgATFIC8AOngIYxq70B8BA9CaW7QHYEAzgGMYxAA65yuAJ4SEdPAgAeuTmFwBbADb1KNergRaJOhsfYDauAsX4SArtIZCAtFtcBrZNWDkAI3skSHIAcgA6ADMAexiwrEDggBFiITMGWVDI2JiAWW9kBKT+JAKhHxDw6LiABSZcYgYdYs8K7IAKAGIegEpyHq63Qa7i8wAvLPIo5qEEcgxyTj5+GzsHZ3JXD0KafyDS7IiAplbvbJ7OS5GxhknQmZ05haWVtfsnF3c2yuoAAwAAgCegB+EF-V7WWwSNjAYAAKQAygB5AByESEuHE-BQxCisg6NRivQwizhSLRGKx9lx+MJuXKlRJZIRKPRmOxtIJRPqMEazWZXBhUPWn3IpGajkU9AAjAAmADM+mWcK6AHdiLgwOQIgoYEIYvxSaLNtsfr4-oNhkMRn8sH8MUJ+Hb-BMpo9nosVcBHUaMHDOBqtaSRTxYazKRyaXiCQA-TiC7hkFZcUTiKQptOSaRyBRKYxqDTaPQgAz5kwZYwAfSsq1sH1N312fnIPwuXSuHZuL2WAlTYmzbBAOCE8BEhsx5EZyHI1HIHSijn4Ikaho6-WAUPH-EnMQCcxgEoCOgQQln5AA2mEJTopcUwuakPeSOlzLIwgBdADcUKQCACjgoGgMBQlCi7Lqu-BTrsHT8DEf6JDEUgyohUhyqhuAKhuoG4Nuk72LE55amkEQsKi8EIAAkvwsSwRRvQ-nWNg4Se0hIbgQiMcxjRRPOuYIDEvHsTKs7UHOYR7gAVggK5hP07FnnOwlcawxhPPMeJ8fIAlCWhoniVJMm4HJ5AKee7FyipNgIOplC8R0-GCaZUgKvp4SGbJ8lSIpzmYVZanPGZc7ABg-k4ZpDnaU5wluWEUY4iZCkRD85nIf5EWObpuByrF8UoIl3nHMEqXZWFTG4ElKVKYVKUAD61eEYT+ZV3g+S1FRnvV0EVMgER-jMjg6BxyWtc1NXeAAwmATA+WETU4UlBxIFWN5SiVQhFaUABqkrzF1i3BGNw1LVWj7rZtZS7EdG0nS+GSyOdS2pK+mRldxsQwPOeHSF4lBQe1XhCNh5U2BFXgRCeOJauQbDkDKwPce9MSfR0rGUOeAAMX7owQ5Dg5DKBatjxAANQk15w0-EIF5eBexAfh+51UzT344TYGA4RzIPlWjq3zMFoUsQg0gBDES5IOeIX+Wje4HqQCDS8L5BCLIy5vap32meIKCS2zuA3qEcF-hEfOc+rNjgSuxCGuQjgSEgFgIB09iaok-AMKQCOqTYnCcHZMhgGklBOmELjTDEIiOGeCDy-wLilAHCAwAgcWtsj8xagw-38PMIjTTADArknys2UZyCJM0OiBMLZ5MPMglRIkaNavMUfF0gMTkGq03GPLIEgzx84AIQu9IABkY-QVqEQMPudHG3MJ5W4aACiCduOQRsIBipfL-wiK4A0-Sw-D5DJ7gjgwPwYWsAPaOR-qyPnlvO9L5BB8NDfeuazez8USbu0b6ayqr5DaPwgETmkJDc8PwIYIChmAG+aNk6zXmnfJWS4zriTQYjXAaMsGNSQUrcwk45xYz1sgrOaBMZfwHh9ecaNiCY0SJJGhONyCQ2JmTL2uDgFM1aheH4dMGZfzwUrTwuFtRzlYbjG8cCEHkAnq2RRk8tARGMJiDoN4LySQ-L0PWzEB6g3shIvOPDvaqUwbscgJM5zaN0aImwZ1bHimaDo1mRjVIoJsXYtxkkyYeNwdxEh0g5xMJJnDURiwbLPE3J4n2ftNI6DiF4Gk4dPoMFbN4LJkjEgVEkOktUTAJb2FcVXJcjQq6Gg0meWI4sDGqQilocxQTcDd2ICeYepjtRKP8RE2RzR5GEzAC0ix3FukwPUaeXAWi-F6McapLmrTuJNIsHnFRHDXChLEpQfoBccQIDcG4BZ0TbIRRCW5YgozcEXLCTYyJDTuL7LQGTBZTjrEuKEfTE5jzb7LMHh0Ie3S9mnh8VkiowiFkxI0kcqJeslljIHnzABt5+a234I+G+yKCGYr1siu6b5zwoNobgl+fMiWnhJRY32tt7aO0TuQB+BpPoSBiEITU1soJZwlovIynL-Y5xEKeIQTBZB6wiqPfoTKn5zhCdjGlNtR5NCrrESOQg8m7xzGAeYFyUp5yYHraF-tAXu09uQfwNKO78FDlsJAkko7SExI4KIQkoKmrxggWQQgGkRWlZ9WGFyInPL2g1VGWz7nBvIAQOcsCCbQyUX6iNVD+Y7JCb0KVl9mXnjlQ0+hqMlZMLnH64mUbZXwK4eTc1vyIoA2pl8hm-QAjJwYF4BZfrXkNIRdxLt3sB40s0nBMO7qfCyA1W-Bl+rPpP1NgPCKQ9TXXIBaPDZiaxIxu8EMrU-QX5zFwIiTVnKABKyaOgY0SImiJ8NRFGp3cLfdb8j0nr9eezNT9L0MXheQG9-9d33r5YaY9ByOjPsZa+mADElh+xiC3GAGpnhaBiPLCdYHAiF1+hVLu2rk6UEdWAMWOgJYBAQAY2d9kVbLg2UlN0bkPQIEXeRkQ64b49p7QtfcScjwng2h9FehcwAdF+tQWGcTcE1u8heP4J0AAkwAvAYD+Hoqtni52yw43R0y7HDxoqlg01TWmWbngIjECIen5YdAUhJ6Tsn5MfkSBQITSn-lkt2ueUgCy7YO2MAuWYCBEi0Y-Z47A5q-qageD5hYAXWmi3FgZsJNFjMsHM+JyTwQqwybkwpyLFiWNZcRuVGtmn5ajIY+eS2kEOjqZE2MiqhXZ5cZqDAXjecBOzmE9W+ypmEAGaUXzAzQ8dnRdKCzRd3FOsswxB0+BQqmO-NBvFneMyLMpdKGl6zCm7O7WG283Ag2kCxbKVKFm22xteA-BEFBjgtBO1y9V1jiybvsypdxF+DAkBIBXrHXAAAZNIxgc4wA6GEY8l9igMZu6x8qmsdC-fgcXOcZXOUVdGR5x2FX1HaViqqqOxRt4jo2R0WMuPPURGCKoZEURAcAEEYAwBiGqEyXVCcRBHST0oZOKdhAAEJofSIXFO-RGdE9kKzv8KhyeA+SDZOS6b-KC25s9-+r33ufZ+5iWHAOwgjrtmMGH-2bsvbex9+B33ddJ0B1joQOu1d6-NuoRJ-AOXNGIOMDO2q-pih+DhZzqLzy7ZRWtLqfuzqB7FqUPqaR7rkH2uNCo6UOuFcq3rFHXnaN+Z8+Dtm5Vz6XyglV7ixhil0-4OuRz1WX7JwQ-LI3cdVd-bN5rz12um6m-A6I8vJhEMIGryb639eLdW7r63n18e5aJ-ibgdvleu8q5b4D4HMBQeqxEA9ixpm6unga01-jgnYYncZkovfEQRBZyFTodcK-2bwrNlCLtdZpxID6ggAaQ0fJ5+0K1UIb+bBhFGKETgtBaAkBOAsA9YwgQQwg-8AC1RgDQCAQIClgLwGA3BxhKc3AAAtD8f-cqBFOXQxGwbPK+bqSoRiDAXoGbVYfgDUUoOnc7Z+BANUcgY9K2MzKrGyC4Q+ZgYWBIKEYwUwcwYwdgisfglOEAusP8ccAuCqfUT-HCR8UIe-G-UQmwTzBgGQ8qXIbIOURUAADhlG0LlAAE55RuDyo9QDR+BP8cCBBSCvxhwQARB4AGxpAqtWJjAYA3BecRAaRQgMYIgMYAB2EwFSCQJXbw8gXwgAViCKhE8GYHsB8IiCiK0BUliDjg8OdwQFCBlAiDlGiLrFFhgD-BgCyIkBUGVhiGhwlhQALlkBUgKKKLcALhICjlCDlFKJIMwCAA) a slightly more 0.9-ish example of a formatting decorator.

**Comment by monoblaine** [comment]
Thanks @evs-chris ! You're right, passing a keypath to the decorator for every usage seems a little cumbersome. But my primary goal is to create a global decorator and be able to use it anywhere (regardless of the keypath), any project.  So if I don't pass any `@keypath` to the decorator, will I have to hard-code some relative keypath (eg. `.value`) within the decorator function?

**Comment by evs-chris** [comment]
Well, you still probably want to pass a keypath, but you can just use a relative one e.g. instead of `@keypath + ' .value'`, you can use just `'.value'`. The object returned by `this.getContext(node)` in the decorator body has methods mirroring the Ractive API that work with keypaths relative to the context in which the element exists in the template.

**Comment by monoblaine** [comment]
You're totally right. `context.set(relativeKeypath, value)` is the way to go:

http://jsfiddle.net/monoblaine/6kb433Lt/19/

**Comment by kouts** [comment]
Nice one @monoblaine! I'll try to make it work without an observer (I'm using an older patched version of autonumeric which is 1/3 in size of the current version)
@evs-chris nice idea, will this work in 0.8 too?
