### ISSUE TITLE
Decorators to use an expression as arguments

### ISSUE THREAD

**Issue by ghost** [ractivejs/ractive#2991]
## Description:

It's the only one out of place considering everything else is either an expression value or a string value. The comma-separated string resembles comma-separated expressions in JS which decorator args isn't really. Array (due to `function.prototype.apply`) or object (because of transitions) comes into mind.

Thoughts? Or am I painting the bikeshed neon green? 😄

**Comment by evs-chris** [comment]
Thats [already the case](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SAbAhgFwKYGcUgDQg1ANoC6AvngMby77wB2aA7gAQBKSFKAlgG5oAUwADp0hKFEhgBzNCkjMA5ACMA9gBMAngpwix6ALYAHZOnkKAPIeZIMAWnRYAvAAMAZipXOcSyTgCMAAzMAFTMACzMANQATAB8GGho8uYA9Iax2rooaqhI8sKiKGI+MGYO3HRSClnkWWpoFCowqE0Y+Vl6mCj8dDjMAHSDklIYAJTMBWJTKHT9XHQMMAASACoAsgAyUY7W0hj9AFYq8-zaiqMA3B1FKDCyAK4wdBPM6JJqKox0-OPApMykK6FMSkGoiUijGjYSAgECkIA) isn't it? Decorator args parse in expression context already, or have I misunderstood the issue?

I read `as-test="foo, bar"` as `test(foo, bar)` when translated to js, and the only difference for the decorator is the injected node as the first arg.

**Comment by ghost** [comment]
Something like events
```
as-decorator="[arg1, arg2, ...]"
```
or transitions

```
as-decorator="{ foo: 'Hello', bar:'World' }"
```

**Comment by evs-chris** [comment]
Ah, gotcha. That is usually what ends up happening with most decorators and transitions anyways. They only take one user-supplied argument, and it's usually an object. I typically have my decorators use an options object but also allow for the most common non-object option to be passed as the only arg e.g. `as-spytarget={ name: 'somepoint' }` === ```as-spytarget=`somepoint` ```. Backticks in unquoted attrs and unquoted attrs in general don't bother me because my go to editor syntax highlighting doesn't care 😄.

Technically, you can take additional params on a transition directive too - `fade-in="{ duration: 200 }, 'something else too'"`. All of the the argumented directives (event, decorator, transition) are implemented with an implicit array wrapping the args so `as-foo="bar, 'baz', bat * 10"` is actually `[bar, 'baz', bat * 10]` in the actual expression that gets run. With the proxy event sugar, you get `on-click="['foo', arg, 'bar']"` -> `[['foo', arg, 'bar']]` where when `result.length === 1 && Array.isArray(result[0]) && typeof result[0][0] === 'string'` proxy the event.

I'd say leave directive args parsing as an implicit list for the flexibility in taking args and so that there's no special casing on the parsing side.
