### ISSUE TITLE
Default CSP doesn't like Ractive's CSS

### ISSUE THREAD

**Issue by ghost** [ractivejs/ractive#3001]
## Description:

While avoiding/pre-compiling expressions avoids the eval-related CSP warnings, CSP does not like inline CSS as well. While you'd think not providing `css` would avoid this, the initial setup does some inline CSS stuff, tripping warnings.

Proposed fix:
- Docs to inform developer that `style-src 'unsafe-inline'` can be used to bypass the whole thing.
- Not providing `css` shouldn't trip any warnings (fix that CSS setup code).
- Maybe an `allowCSS` that if set to `false`, totally ignores any CSS provided and doesn't print it too.
- To have component-scoped CSS, either
    - Write the CSS externally to boot. Use BEM or some other naming convention to scope.
    - For SSR, `css` can be extracted to a file using `Ractive.getCSS()` or `ractive.toCSS()`. Few problems:
        - `ractive.toHTML()` doesn't emit scoping ids nor emit the CSS if rendering a document. Related issue: https://github.com/ractivejs/ractive/issues/2706

Thoughts?

## Versions affected:

All?

## Platforms affected:

All?

## Reproduction:

http://plnkr.co/edit/uci3CFljlSJVVoPOIic5?p=info

## Code:

```html
<!DOCTYPE html>
<html>

  <head>
    <meta http-equiv="Content-Security-Policy" content="default-src 'self'">
  </head>
  <body>
    <script src="ractive.js"></script>
    <script src="script.js"></script>
  </body>

</html>
```

```js
Ractive({
  el: 'body',
  append: true,
  data: {
    msg: "Hello, World!"
  },
  template: '{{ msg }}'
})
```

**Comment by evs-chris** [comment]
`toHTML` will emit scoping ids if there's css that needs to render. If you're gonna use it though, you probably need to set `cssId` so that it's something stable.

I think just doing a deferred init on the style element will suffice for getting rid of the csp error. It looks like setting up a nonce would be the best way to skirt the unsafe-inline requirement for ractive's css.

I'm not exactly how to approach the injected styles for progressive enhancement. Maybe throw an attribute on the style tag that tells ractive to take it over and then do `indexOf` checks for each chunk of css that would be added to it to see if it's already there?

**Comment by evs-chris** [comment]
As of edge now, the style injection tag will be lazy loaded rather than created immediately during ractive lib init.
