### ISSUE TITLE
Two-way binding doesn't work on a computed value's keys

### ISSUE THREAD

**Issue by briancray** [ractivejs/ractive#3006]
This works prior to 0.9.

We use this process to merge URL params and some defaults into a settings object that is mutable (which then updates the URL). It's critical to our development and has blocked us from upgrading any of our apps to 0.9

https://jsfiddle.net/4sm4y69z/1/

**Comment by evs-chris** [comment]
You can work around this by setting [`syncComputedChildren`](https://ractive.js.org/api/initialization-options/#synccomputedchildren) to `true`. It looks like it's also buggy in 0.8, as the setter doesn't get called, though I must admit I'm not sure exactly how to handle that in this scenario. I think the `set` on computeds is more intended to do things like take a `name` and split it into `firstName` and `lastName` properties. I haven't encountered a setter where it should just use the value passed through in the model.

**Comment by evs-chris** [comment]
Are you extracting the params back out to their source objects to keep them updated, or are you just doing an initial `Object.assign`-type thing and just using the result going forward? If the latter, then enabling `syncComputedChildren` without the setter is probably what you're after. Using the setter in that fiddle would actually result in the same behavior as disallowing the binding on the computed because the computation gets invalidated and recomputed after the call to the setter, which causes the `{ foo: false }` to be returned again.

**Comment by briancray** [comment]
Thanks! Looks like that worked.

I was basically taking the objectified query string (`query`) and defaults object (`defaults`) and doing `Object.assign({}, defaults, query)`. Then whenever a setting changed the page URL would get updated using another computed `pageUrl` that diffed defaults and settings, resulting in a URL that only had params changed from the `defaults`

**Comment by briancray** [comment]
Actually syncComputedChildren isn't working in my case. Perhaps there's a good explanation or it's a bug, but you can look over a closer example of what I'm doing here:

https://jsfiddle.net/4sm4y69z/3/

**Comment by evs-chris** [comment]
Yeah, `syncComputedChildren` won't help you in that case, because it invalidates the dependencies of the computed, which in this case causes a full recompute. I see three potential solutions here:

* Fix the calling of computed setters when children are updated and use that.
* Avoid using `get` in the computed by pulling references to those objects out ahead of time.
* Create the merged data ahead of time and inject it as a non-computed reference. Then use an observer to update external deps.

Either way, I think I have a fix for the setter not being used on downstream updates.

**Comment by evs-chris** [comment]
I _think_ this should be good on edge now: https://jsfiddle.net/4sm4y69z/4/

I'm not positive that that's exactly what you were trying to do, but I think it's reasonably close. This will go out with 0.9.2 when it is cut. Feel free to reopen this if it's not fixed. Thanks!
