### ISSUE TITLE
Invalid example in docs for namespaced events

### ISSUE THREAD

**Issue by alexlibby** [ractivejs/ractive#3007]
## Description:
In the docs for Propagation at https://ractive.js.org/concepts/event-management/#propagation, it shows 
this example:
```
Ractive({
  template: `
    <div on-click="buttonclicked">
      <button type="button">Click Me!</button>
    </div>
  `,
  oninit(){
    this.on('buttonclicked', event => {
      console.log('button clicked')
    })
  }
})
```
This technically won't run - it's missing the ```el:``` config option.

## Versions affected:
N/A - this is not specific to any version of Ractive.

## Reproduction:
I've set this up as a Codepen at https://codepen.io/alexlibby/pen/GErmwO - if you run it, you will see nothing show in the console. Add ```el: 'body', immediately before ```template:...``` and it will run fine.

**Comment by ghost** [comment]
This is intentional to remove visual clutter and to highlight only the important parts of the concept being explained. Most examples are written this way. If there is a need to explain further, examples will be supplied an interactive example with full, working code.

**Comment by alexlibby** [comment]
Thanks for this - I get the intention, but I'm not sure this is coming through? If you're intending to only show the crucial parts, then maybe put a ```...``` inbetween ```Ractive({``` and ```template```? This would make it clearer that we're only showing the valid parts, and that the example won't necessarily be a complete one. I would say though, that as it is only one line that is being replaced, then perhaps it might be as well to add in that missing line, so the demo would then work as expected...?

**Comment by ghost** [comment]
> then maybe put a ... inbetween Ractive({ and template?

This would only throw off the syntax highlighter since it's invalid JS. It also doesn't really help informing what's currently missing.

> I would say though, that as it is only one line that is being replaced, then perhaps it might be as well to add in that missing line, so the demo would then work as expected...?

Having full code would only make the docs unnecessarily long and redundant. There was already [an issue opened](https://github.com/ractivejs/ractivejs.github.io/issues/43) about the docs being too long. For instance, the [Adaptors](https://ractive.js.org/extend/adaptors/) example is so long, nobody would probably read the rest of it unless you're building adaptors and picking it apart. It will only get in the way.

If having working code is really needed, a full interactive demo would be better. [References](https://ractive.js.org/api/references/) already does this with the "Run It" buttons. We just haven't gotten to the other parts of the docs. A pull request adding interactive examples would be nice though. 😉

**Comment by ghost** [comment]
I think I'll close this one. I've been adding `el`/`target` lately because I just copy-paste whatever I put on the playground when adding interactive examples. There's still a lot of ground to cover though for examples. Adding this to the laundry list https://github.com/ractivejs/ractivejs.github.io/issues/64
