### ISSUE TITLE
Please put back or provide option to get the complete API

### ISSUE THREAD

**Issue by lnryan** [ractivejs/ractive#3014]
## Description:
Previously, the api could be viewed in its entirety (at least all the Static and Instance Methods and Properties). This was very helpful in terms of scanning and familiarization. Now the API is broken into sections that require you to have a guess about what _kind of thing_ you're looking for before you can begin to find it. I guess that's helpful for someone who's just poking around but it's extra time when you're just trying to use it as a reference. 

It would be really helpful to be able to click on the "API" top-level and just get the same content as standard document sections in a single page. 

Please consider it.
## Versions affected:
0.9

**Comment by ghost** [comment]
[Tried this once before](https://github.com/ractivejs/ractivejs.github.io/commit/45a552e023c7a386352575c5c9a61ba99199d42d). It will just hide everything in one really long sidebar. Documenting stuff is also a challenge since you have to deal with one huge file. Also, Ractive's old docs prior to 0.9 didn't document everything which is why it looked and felt short. This time around, everything is being documented thoroughly.

Segregating the API into what they are now seems to be a cleaner and more maintainable structure.

**Comment by sabob** [comment]
For me the most cumbersome part with the current layout is that all the methods/properties aren't available in a sidebar so I can do: 'ctrl+f'. The pages themselves can still be separate files g. Javadocs is a good example of a massive api, but fairly accessible because of the iframe sidebar where you can search for methods/properties etc.

Isn't there a way to replicate this somehow? In other words, have a sidebar/iframe with all the methods/properties which links to the individual pages.

The hard part, which is writing the docs, seems to be in place, we just need to find a practical solution to the structure, so users have an easier time learning and understanding Ractive.

**Comment by ghost** [comment]
> For me the most cumbersome part with the current layout is that all the methods/properties aren't available in a sidebar so I can do: 'ctrl+f'.

Hmm... But isn't that the purpose of the Search (last item in the menu)?

**Comment by ghost** [comment]
> Isn't there a way to replicate this somehow? In other words, have a sidebar/iframe with all the methods/properties which links to the individual pages.

The docs pretty much handed all the aspects of the build to mkdocs so we don't have to deal with that and focus on writing docs and keeping it complete instead.

If anyone can suggest a site generator where this is possible but where we don't have to play with fickle build configs, that would be great. 👍

**Comment by sabob** [comment]
The site search doesn't work well for me eg. findParent bring back nothing. I guess it's not only about ctrl+f, it's also about scanning down the alphabet. 

Imagine a new user who has no notion whether something is static or instance. She goes through the list, finds nothing, now has three more pages to trawl through.

**Comment by sabob** [comment]
> The docs pretty much handed all the aspects of the build to mkdocs so we don't have to deal with that  and focus on writing docs and keeping it complete instead.

As I mentioned it's great to have easily editable docs and lots of info, but if it is cumbersome to find that info that defeats the purpose. Writing docs takes serious effort, imagine it not being read ;-)

If mkdocs cannot help here, can't we hand-code the sidebar, and manually link to the generated pages? Then we can still easily edit the pages and have the entire api available in one place for easy reference. The compromise would be to maintain the sidebar.

**Comment by ghost** [comment]
🤔  How about a single-page version of the docs, with a full ToC at the side?

Was thinking about how to keep the 0.9 docs when it transitions to 1.0. A script that concats all the pages to one file based on the `pages` property of `mkdocs.yml` was one idea. The resulting file would be checked in, and rendered like any other page - a snapshot of the entire docs in one file. We could also do one for the current version.

This way, a Ctrl+F would work out of the box for the entire thing. Also good for "Print to PDF".

**Comment by sabob** [comment]
That would work for me. 

Although I like the "edit the page" link at the bottom of each page. As you mentioned, that makes contributing easier. Editing a generated doc won't work. So we'd just go with the normal 'fork repo' way of contributing docs?

**Comment by ghost** [comment]
If the generated file is from an older version, one can just edit the generated file directly (since it no longer has its loose files/loose files already versions ahead). If it's from the current version, just edit the loose files, run the script, and check in both loose and generated files.

I haven't thought this through yet, will have to try it out. 😄

**Comment by sabob** [comment]
Just to clarify, ideally we can have the API as a single page with TOC. If that works out it could be worthwhile doing the same for the "concepts" section since that seems to be the actual "documentation". It contains the "templates" section which is really what Ractive is all about.

**Comment by evs-chris** [comment]
I don't think combining static and instance methods and properties would be _too_ cumbersome for one page. Looking at it, on my monitor at least, that would add about four screens of additional content to the instance methods page, which isn't awful for reference material. The TOC really helps with navigating around the docs too, and in a much less aggravating way than the old docs site where the page load moved the menu back to the top of the page.

The search is a bit... interesting. It's pretty ok considering the amount of stuff that it covers, but it's a little finicky too. It doesn't order results quite as I'd like, but it's a bit better than no search at all. Just searching "find" has `findParent` about 10 items in. "findParent" not showing `findParent` is... special.

I'd like to get a short overview of all of the template constructs into the API section too. Eventually, I'd like to get the Concepts down to in-depth descriptions of the different constructs and how they are handled internally, with everything you'd need to be able to maintain an existing ractive app available from the API section with links to in-depth Concepts docs where applicable.

**Comment by ghost** [comment]
The sections on the docs are now combined to one file each, except for the tutorials. Removed internal cross-linking for now since every time I move around content, I have to fix a hundred links linking back to it. I think I can close this one now.

(You may have to clear cache for CSS changes to kick in)

**Comment by sabob** [comment]
Thanks! I find the new structure much easier to navigate.

In terms of structure we could also consider hoisting the Mustache section (and other templaty things such as special refs) into a top level menu item. Technically Templates are API though but it feels as if they deserve more ;-)

**Comment by ghost** [comment]
API section updated (or a few moments ago). 🎉
