### ISSUE TITLE
findAllComponents is not working

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3020]
## Description:

We shouldn't see the error on the console: http://jsfiddle.net/waqzjjj2/5/ , should we? 

## Versions affected:

0.9.1

**Comment by ghost** [comment]
It's a strange case if you consider the case between `{{> content }}` where the context belongs to the child component vs `{{ yield }}` where the context belongs to the parent component. I'm not sure what's the correct behavior on this one.

Anyone have ideas on how other frameworks handle this?

**Comment by evs-chris** [comment]
The fiddle, as it is written right now, would never find a mycomponent2 because it will never be rendered. If you throw in a `{{>content}}` or `{{yield}}` on mycomponent, I think you _should_ find a mycomponent2 from the render hook, but I'll have to poke at it a bit to be sure.

I _don't_ think context matters (`{{yield}}` vs `{{>content}}`) for `findComponent`, as mycomponent still technically _owns_ mycomponent2 as far as rendering and lifecycle. mycomponent2 is just getting context from elsewhere.

**Comment by evs-chris** [comment]
Ah! `'*'` is not a component query - it's only applicable for elements. If you want all components of any name, just don't pass a name: http://jsfiddle.net/waqzjjj2/6/

**Comment by ceremcem** [comment]
A-ha! Thank you.
