### ISSUE TITLE
Is there any easy way to use dashed component attributes in template? 

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3021]
## Description:

As of now, we may use a dashed attribute in the component like so: 

```
<my-component data-id="hello" hi="there" /> 
```
In the template: 

```
<p>this is hi {{hi}}</p>
<p>this is data-id: {{@.get('data-id')}}</p>
```

Is there any way to accomplish the same goal by simplifying the `@.get('data-id')` part?

## Versions affected:

0.9.1

**Comment by evs-chris** [comment]
While not a _whole lot_ prettier, you can use a [root](https://ractive.js.org/playground/#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoRtIQAeAEwEsA3AAgrIF4AdQpGAczRRYD4SB6SlR4gCGeAGMA9gDssNJAAdFNBjRloA7jQBKSCSmpoAFMCYymKFG04pINAOQBiaxy4O85y+gC2i5Oj2AAbAwAB+-ADaDmSoSAC09A4Aujg4QZ4WKLHW9sCOOQlJ9g5IDjQ45jgAlADcuEA) or context property reference to do this e.g. `~/['data-id']`. It still doesn't result in a plain reference, but it will at least be a reference expression rather than a full expression, meaning it will still be bindable. Converting reference expressions with only string property accesses to direct references has been on my list to address for a while, but I haven't quite got round to it yet.

Unfortunately, `a-b` is a legit expression in js, so it's not likely to get much better than that. The only other possibility may be too expand escaping allowed in references e.g. in addition to `foo\.bar`, allow other arbitrary chars to be escaped with `\` like `data\-id`. I'm not sure that's a _whole lot_ better either, though.

**Comment by ceremcem** [comment]
I remember this is discussed before and someone (maybe @dagnelies ) mentioned that other libraries are just converting dashed `variable-names` to  camel cased `variableNames`. 

Would you consider the same approach?

**Comment by evs-chris** [comment]
It has been considered before (LS, coffeescript), but ultimately decided against. That _does_ remind me that we support relaxed references for partials, so perhaps we could add a parser flag for extending relaxed references support to the entire template. Relaxed references allow `-` and `/` to appear in references as long as there are no spaces around them, meaning that the only weird side effect would be _requiring_ whitespace for subtraction and division.

**Comment by dagnelies** [comment]
Nope, wasn't me 😛 

...as for my usual grain of salt, inline conversions (dash to camelcase) seem a bit unintuitive to me. I'd favor escaping.

Btw, be careful @evs-chris , if I'm not mistaken `/` can be used like `.` as keypath separators.

**Comment by ceremcem** [comment]
Hmm. Getting older is like this =P 

@evs-chris I would vote for requiring white spaces around math operations and use `dashed-variable` as is in the templates for three reasons: 

1. It makes the code (the math operation parts) more readable, IMHO
2. I'm already required to do so by Livescript 
3. It will look Ractive templates **a lot** more readable

**Comment by dagnelies** [comment]
Well, one other consideration is:

"how many people build components using dashed parameters"

vs 

"how many people would have their app break because they use {{a-b}} or {{a+b}} as computations, or be frustrated that they can't write 'valid' js expressions like this"

---

Not to be nitpicking here, but I've feeling the second group is fairly bigger. As such, it would do more harm than good. Escaping them therefore still looks fine to me 😉 ...or avoid dashes in your component parameters. 😛

**Comment by ghost** [comment]
I'm in favor of staying as is.

- Auto-conversion of dashed to camelCase and vice-versa is also one source of frustration in Angular 1, something that isn't obvious and had to be communicated across every time. When you have to explain something across multiple places, it's a sign of bad design.

- It keeps mustaches simple. It's either a keypath or an expression, and that's it. No extra rules to think about, no hidden features, corner-cases and the like. Also, Ractive pretty much follows the JS dot and bracket notation for expressions anyways, nothing the bracket notation can't do.

- It's nothing a camelCase prop couldn't handle. I used to treat templates as HTML, and just lower-case and dash everything. I broke the habit not too long ago and did TitleCase component names and camelCase props because they roll better (Component constructors are imported with TitleCase because they're constructors, props in camelCase because they become data props)

**Comment by ceremcem** [comment]
As a result (for me), `~/['my-dashed-variable']` will work well enough. It's also not that hard to remember the `~/['...']` notation. (Also, [here](https://ractive.js.org/playground/#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoRtIQAeAEwEsA3AAgrIF4AdQpGAczRRYD4SB6SlR4gCGeACUkAYxTU0AOmkB7ALYAHZQDs0WlBgVIaDGlNnyFaAB7otZABTAmWpinQbk6SDQAG5ajzOrq4k6jwqeroo3sDAAJ4UaAhkODgCYUHcKKE8AGYUMFgxwPmFKKnpgS5ZOapxALSlRTSxAH78ANoA5HWNBVhdALoV-BnVIWG9TSgATMUAAgqcKPY9DdNdAJQjY8HZYVgwFFrsFPloZMUAUgDKAPIAcgqHx6e5cfbt3VP9KEPbaVGVT2tXWvw6vQwaAiZEGNHs1nU0PQlxoAEZNsUvms+mUhh1sZDodoyENhoDdllMiFBAEfM4cJsANxBLQRLA0JDqdTGGg6ADuphkcioaEcmRQbGW3i6AGJJRwuF08BK0B5UGhvH4jNNmCBgFZvGi8DQ4t4ZjgWNSqTa9j8ynqDUaTWaaBareNbV6iTC9VYPXtAzaeEhQ0gBEgePStIzcEA) is an example to myself)

But, still, if it is not that hard for you all, a flag or something might come into play. I would love to write: 

    <p>my-first[my-second] (expected: 1): {{my-first[my-second]}}</p>

instead of 

    <p>my-first[my-second] (expected: 1): {{~/['my-first'][~/['my-second']]}}</p>
