### ISSUE TITLE
How to get rid of double quoting in v0.8?

### ISSUE THREAD

**Issue by Inversion-des** [ractivejs/ractive#3028]
In this case:
`fade-in="'slow'"`
it looks very weird but works.

In some sample I found that this works:
```
fade-in=`slow`
```
but it needs v0.9
Is there some trick for v0.8?

**Comment by ghost** [comment]
I thiiink... this isn't a bug. Arguments for transitions (and decorators) as of 0.8 are comma-separated expressions. This means the string has to have quotes around it, otherwise it's treated as a variable.

iirc, the backticks syntax was a 0.9 addition by @evs-chris to get around this quoting frenzy while keeping the old (and more familiar) syntax there.

**Comment by ghost** [comment]
Found the PR https://github.com/ractivejs/ractive/pull/2868

**Comment by Inversion-des** [comment]
Yes, I'm not saying it's a bug, I understand the behavior, and thank you for all additional related information.
I'm just looking if there is some trick in v0.8…
Here is some option http://jsfiddle.net/Inversion/cvq1ku8f/ (I know, it is not good…)

**Comment by Inversion-des** [comment]
This can be closed. I personally do not need it anymore, maybe no one else needed it )
