### ISSUE TITLE
resolveInstanceMembers footgun: Data resolves to instance members, but doesn't animate

### ISSUE THREAD

**Issue by ghost** [ractivejs/ractive#3040]
## Description:

Taken from the broken code of [this Stack Overflow question](https://stackoverflow.com/q/45022326/575527), I found it strange the way it was written until I realized it has to do with `resolveInstanceMembers`. The data resolves to the instance member, but cannot be animated.

[In this demo](https://ractive.js.org/playground/#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoRtIQACEgHjAEYA+AQQDc0YkBzNEgCQEtWwSAKmgC2AB2aoArjEzkA9NRoAdGEoB2K9WXIATbgxLcdAXgDkAYwD2alEm5rmpmvL0NlqtWU2eKGczG5RFEMTJUIRUWR0MJIUAE9xYzD0AA8UORZzFH00MPctEgAZS3NUbmtIEmBgc25szAA6NSRhNBwcb06PJRQe3X0Sc2QMDDN0MQkUaUwnTt75uZ7tAEIAWlXYsA5zMCQYYPX8jXntV0Hh0dMAIz3Vnb2UWe7gslfyNY2qACYSDDQs8pqDB4EjWDgAM0sMBIaCQOxIwmsKH4hzmr1e1QAxLD4bV6hgGoibGAMJVuO00ei3mchkgRmYbjBVqwYJZJKInupKVSSH0PiQkEwWOwSGBePxxuIWFMZCRUc8eej+gZafTrrc2ehoWK+CRRJYMHUcqZfvEEGgzFtxShKtVfqVzQAKHVgACUJHaohSAG5OcdFVTlec6ZdGat7A4YCasHFzQy4QBrFlstQ6O6WBBQyoyHS+5xyVxHJYBt4YURITyq0bJCJ5O147iNInIjAAbW4AF0Gi6PTgAA0AMXkZYrRZeAZc+iLCpL73WCKR-GQVzQCBIjoAUgOALJ0bcbjd0ADKAHkAHIAEXd8q548V5BHlYuZmbYFWy9XTjtr7PLUw7Y7Xth3LNQxwnAsp25DFgDkHEwApbpnmLSc3EWFAUJoKlvG0OQ-ACIIaBAAgMHgBg9hIdkdFQNAdAAYSNTASGMKpsN5EBmlaMJKjCWjLHENRdnYNQQQvNA1GEPYEzCPBWLCV8MC4khW1YshgDYl1FIAZgAdg9GSPHRNSwg0qASE0gA2PSVKqdTxUUgAWKgrIMjFbL4ByAE5nIKVS3LARTzIABm8nxfOMuzTPMyz8GsozwAiypzK8mKXLC+L3Mi5L9J8mzwoyxKnJSnK4pMyoAFZNJCwy-Ic+yqtcvL-NMzTktYjtvA6RD1DI6FMmyJgmJIBwAHcSAAJThfq0EdYBWMlKI0EqUxMXm6jTGynxVyWzErBsOxI3W1ifz-UklJIUwN3W86Byu0xt1uuhbvukELtuy6Xsel6j1uk9brPW6LxNDsNrIBtMFtaywg43JTJ4vixMEsSRLEiSYCkojIZAeTFOU1KGvSprKh0+rqsarTdKK0L8dKsyKZBqkSoS2mSeppnicpnlGfy5mOYZmrmrp6y0pp9n6dJgnyZZ4W2cFvHpe50WhdyiWBY9az2pc-BeRcqjbAhlyej8JBzUqcFJDUAFrHXEgyLXd1ZrlkgZBlTxKoAKhIbdUDABokCuDBHRt42SFdb1rM6goI7UHBQ68Lq1D6nJfbUbgJPQQOLAYjArso6i6KzkE1J0aQygqEgysCyuQVhQ01FYJaa7QABJNQT0kR4PRD70iJAcx4AAAUhGxVnBOEOAd28h5QEeWm4BA4iW1krksFAoTQVhJGQKMw+eDAYHMSppAQR1TAaBo5CnuQxssZfV9WMb18325hrQK4p4aYbLHBcFTHdSEYDTifT+39f470nkiVYL9rSVDUFCCSCAwHHCnqsGMJshpwONogqO3gwAoGEGuCexwrR8BtCQKglcGBgCwV0dQy8dBxBYi5ZBo9hBzwXk7G+K814by3iCDAFYMAoOYNwcEiCyDIMNAAL0WiQQKDQAAc2kyoyGEGIvUSAdB6DrpUL4KjEE9GIbgyo5DAoAFJ9EoHLJo+w9cyEiAsajVg9hKiBQscvFIKDuCSJsZUZeMAdDMFWO46h8cVp7HYMEQhBi0DQLIZXcxHUaFqAaCwPQlhmSsnZIw28+pDTZDLn7DAGZ25oAsQEEhxj7FzFXqIFxDQypVI8Ngjw3ZYQBOhFEyxBojQFP9sU9AFiakuIscNIwyJjHxJCVyFpYZ7j7GyccXJPS1DZlXGUJgIyxlgAmWYixhjSEmISc8KxWjbHBWCppEQsi3GWA8VInxJA-HtKCbcqZGgWmvnfH7VcCyei31XsISoqwqCNPAcPKRMi5HmT0Yk+ODQwzJiyZ0pZ+SVlOzWVNPZMSKlxN2XMcEmZUCVHNOCFAgy0BpFWMbXgaLzBiS1BYk5Dy5HKNBZ4HooydDjJIF8Boml+UCqOeoZp6h4UahKR0uYKLASVEKf00pcxOXcsOYyjRpyXFkK9Dcu5XiHlPMCcE2F0zRXSoGp0-5lhAU8rxU0pJDRTUcDFUyCMzBfkoH1UyVJ3BJCnS+F6Hl-rzk3P8YEklBz-VFIQEYEgmIBXBueeUoxmqUi-AzNG2N-L42BKGcm1NUadAxrjXMC1VrXFGveSa7pU1fggTdTmuR8i2U9GQVAnFy8EC5nLd4bs4oa0VjrXxIFDaYW2rhWGF1kqXLSrLjIKIOQ1FKu2SQeyZUtWsX2TsoV0c7WSkmNMDACyyDTrRbO9ZCqXKLs3WojduKt1HrVQ8qgrLhCyNfWW0dxrkmzN2PMx8h69RVplQKPpCASkLq2Ve1iYbhmsQkV4mRVAGi6LZWQKNDhVg3vfQUSR4ZUwUsSm87tko3VwekXUjyI7hW4CAA), `cities` resolves to the `cities` instance property. However, `ractive.animate()` doesn't work. Move `cities` into `data`, [and `ractive.animate()` works](https://ractive.js.org/playground/#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoRtIQACEgHjAEYA+AQQDc0YkBzNEgCQEtWwSAKmgC2AB2aoArjEzkA9NRoAdGEoB2K9WXIATbgxLcdAXgDkAYwD2alEm5rmpmvL0NlqtWU2eKGczG5RFEMTJUIRUWR0MJIUAE9xYzD0AA8UORZzFH00MPctEgAZS3NUbmtIEmBgc25szAA6NSRhNBwcb06PJRQe3X0Sc2QMDDN0MQkUaUwnTt75uZ7tAEIAWlXYsA5zMCQYYPX8jXntV0Hh0dMAIz3Vnb2UWe7gslfyNY2qACYSDDQs8pqDB4EjWDgAM0sMBIaCQOxIwmsKH4hzmr1e1QAxLD4bV6hgGoibGAMJVuO00ei3mchkgRmYbjBVqwYJZJKInupKVSSH0PiQkEwWOwSGBePxxuIWFMZCRUc8eej+gZafTrrc2ehoWK+CRRJYMHUcqZfvEEGgzFtxShKtVfqVzQAKHVgACUJHaohSAG5OcdFVTlec6ZdGat7A4YCasHFzQy4QBrFlstQ6O6WBBQyoyHS+5xyVxHJYBt4YURITyq0bJCJ5O147iNInIjAAbW4AF0Gi6PTgAA0AMXkZYrRZeAZc+iLCpL73WCKR-GQVzQCBIjoAUgOALJ0bcbjd0ADKAHkAHIAEXd8q548V5BHlYuZmbYFWy9XTjtr7PLUw7Y7Xth3LNQxwnAsp25DFgDkHEwApbpnmLSc3EWFAUJoKlvG0OQ-ACIIaBAAgMHgBg9hIdkdFQNAdAAYSNTASGMKpsN5EBmlaMJKjCWjLHENRdnYNQQQvNA1GEPYEzCPBWLCV8MC4khW1YshgDYl1FIAZgAdg9GSPHRNSwg0qASE0gA2PSVKqdTxUUgAWKgrIMjFbL4ByAE5nIKVS3LARTzIABm8nxfOMuzTPMyz8GsozwAiypzK8mKXLC+L3Mi5L9J8mzwoyxKnJSnK4pMyoAFZNJCwy-Ic+yqtcvL-NMzTktYjtvA6RD1DI6FMmyJgmJIBwAHcSAAJThfq0EdYBWMlKI0EqUxMXm6jTGynxVyWzErBsOxI3W1ifz-UklJIUwN3W86Byu0xt1uuhbvukELtuy6Xsel6j1uk9brPW6LxNDsNtYqjbFtWSXgbTAIdStiONyUyeL4sTBLEkSxIkmApKI6y5MXBTTOUuG0tKszdKK0KGvSprKh0+rqsarSKY2nkSoS8mGepsn6cptmaualnrNJjnedZql2fyzm+YlgW6aFkncpp5muZFqWxeFpWeYp6z2pc-BeRcno-CQc1KnBSQ1ABax1xIMi13dWbFZkGVPEqgAqEht1QMAGiQK4MEdO3TZIV1vWszqCkjtQcDDrwurUPqcj9tRuAk9Ag4sBiMCuyjqLo7OQTUnRpDKCoSDKwKq5BWFDTUVgltrtAAEk1BPSRHg9UPvSIkBzHgAABSEbFWcE4Q4J3b2HlBR5abgEDiJbWSuSwUChNBWEkZAo3D54MBgcxKmkBBHVMBoGjkae5DGywV7X1Yxo3rfbmGtArmnhphsscFwVMd1IRgOnU+X8f5-13lPJEqxX7WkqGoKEEkEDgOONPVYMYzZDXgabJB0dvBgBQMINck9jhWj4DaEgVAq4MDANgro6gV46DiCxFyKCx7CHnovEgy9V7r03tvEEGAKwYFQcwbg4IkFkBQYaAAXotEggUGgAA5tJlRkMIcReokA6D0PXSoXxVFIJ6CQvBlQKGBQAKQGJQOWLR9gG7kJEJYrGrB7CVECpYleKRUHcCkbYyoK8YA6GYKsDxNCE4rT2OwYIRDDFoBgeQquFiOq0LUA0FgehLDMlZOyJht59SGmyOXf2GAMwdzQJYgIpCTEOLmGvUQriGhlWqR4HBHhuywkCdCaJViDRGkKQHEp6BLG1NcZY4aRhkQmISaErkrSwz3H2Dk44eTelqGzKuMoTBRnjLAJM8xlijFkNMYk541jtF2OCsFTSIg5HuMsJ46RviSD+I6cEu50yNCtNfO+f2q5Fk9DvmvYQlRVhUCaRAke0jZHyPMvopJCcGhhmTNkrpyyCmrM4esqa+zYmVPiXsuY4JMyoEqOacEKAhloDSKsU2vB0XmDElqSxpzHnyJUWCzwPQxk6AmSQL4DRNICsFcc9QLT1AIo1KUzpcxUWAkqEUgZZS5hcp5UcplmizmuPIV6W59zvGPOeUEkJcKZliplQNLpALLBAt5fi5pySGhmo4OKpkEZmB-JQAapkaTuCSFOl8L0vKA0XNuQEoJpLDkBuKQgIwJBMSCpDS8ipxitUpF+BmGNcaBUJqCcMlNabo06FjfGuYlrrVuONR801PSpq-BAu63N8iFHsp6Cg6BuKV4IFzBW7w3ZxS1orPWviwLG2wrtfCsMrqpUuRleXGQUQcjqOVTskg9kyratYgc3ZwqY72slJMaYGBFlkBneiudGzFUuSXVu9Rm68XbuPeqx5VA2XCDkW+8tY6TUpLmbsBZj4j16mrbKgU-SEClMXds69rFw0jNYpI7xsiqAND0eysg0aHCrFvR+goUjwypkpYld5PbJTuvgzI+pHlR0itwEAA).

## Versions affected:

The version that introduced `resolveInstanceMembers`?

## Platforms affected:

All?

## Reproduction:

See example

## Potential resolution

Disable by default/remove feature?

**Comment by evs-chris** [comment]
It is a bit of a footgun, especially if you happen to be trying to access `data` in the root of your viewmodel without a prefix (`~/data`) or initializing first. `resolveInstanceMembers` will definitely be off by default for 1.0, ~~and I'm about to adjust the resolution path to make sure `data` is not considered unless there's actually a `data` member added to the instance~~ (as it turns out, prototype data is still used to inherit data, which I completely forgot about. That will be moved to the constructor for 1.0).

Instance members _can_ be animated, you just have to be sure that you [specify them using `@this`](https://ractive.js.org/playground/#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoRtIQACEgHjAEYA+AQQDc0YkBzNEgCQEtWwSAKmgC2AB2aoArjEzkA9NRoAdGEoB2K9WXIATbgxLcdAXgDkAYwD2alEm5rmpmvL0NlqtWU2eKGczG5RFEMTJUIRUWR0MJIUAE9xYzD0AA8UORZzFH00MPctEgAZS3NUbmtIEmBgc25szAA6NSRhNBwcb06PJRQe3X0Sc2QMDDN0MQkUaUwnTt75uZ7tAEIAWlXYsA5zMCQYYPX8jXntV0Hh0dMAIz3Vnb2UWe7gslfyNY2qACYSDDQs8pqDB4EjWDgAM0sMBIaCQOxIwmsKH4hzmr1e1QAxLD4bV6hgGoibGAMJVuO00ei3mchkgRmYbjBVqwYJZJKInupKVSSH0PiQkEwWOwSGBePxxuIWFMZCRUc8eej+gZafTrrc2ehoWK+CRRJYMHUcqZfvEEGgzFtxShKtVfqVzQAKHVgACUJHaohSAG5OcdFVTlec6ZdGat7A4YCasHFzQy4QBrFlstQ6O6WBBQyoyHS+5xyVxHJYBt4YURITyq0bJCJ5O0AWVQYAarMkqcdeO4jSJyIwAG1uABdBou93tAANADF5GWK0WXgGXPoiwqS+91gikfxkFc0AgSI6AFKT+t0euHw90ADKAHkAHIAEXd8q5C8V5FnlYuZh7YFWO73Jw7V-O8WkwAdBw9HAZ3LNR50XAtl25DFgDkHEwApbpnmLJc3EWFBcJoKlvG0OQ-ACIIaBAAgMHgBg9hIdkdFQNAdAAYSNTASGMKoSN5EBmlaMJKjCNjLHENRdnYNQQQfNA1GEPYEzCPA+LCX8MGEkg+z4shgH4l0tIAZgAdg9VSPHRfSwkMqASCMgA2czdKqAzxS0gAWKhnMsjE3L4TyAE4fIKPT-LALSHIABhCnwwps9y7Icpz8Bc6zwESyoHOC1LfPijKAqSnKLNC1yEsKrLvNy0r0tsyoAFYjNiqzws8jzmr88qIrsoycr4wdvA6LD1Ho6FMmyJhuJIBwAHcSAAJThCa0EdYA+MlKI0EqUxMQ2ljTBKnw922zErBsOxIwOviQLA0ltJIUxDwOh7J2e0x6zeug3o+kFHrep7fq+36rzem83rvN6HxNQdDrITtMFtFywkE3I7NE8T5Kk+TZPkxSYGU6ikZADStJ0vLOoK7rKlMjqWq64yzOquKKbq+zGdhqlasytnaZZ7maaZnkuYqnnBc51qevZlz8tZgWObpymGd5mX+al8mVZFuXpbKxXJY9FyBt8-BeV85jbER3yej8JBzUqcE2wBawDxIej93dNb1ZIGQZU8JqACoSEbZEGiQK4MEdF2bZIV1vRcoaCnjtQcBjrp1HGnIQ7UbhFPQR0AAMAAFkW4Al4YwPOQSYlj2M44FXJ0aQygqEgqCituQVhQ01FYbbO7QABJNQb0kR4PRj6iQHMeAC8hGxVnBOEOA919Z5QeeWm4BA4m21krksFAoTQVhJGQKNY+eDAYHMSppAQR1TAaBo5FXuR5ssPeD9Weaj5P24ZrQK4q8GgzUsOCcEph3SQhgDne+ICwEQPPivJEqx-7WkqGoKEikECIOOKvVYMZbbTUwTbHBidvBgBQMIfcy9jhWj4DaFubcGBgFIanNQe8dBxF4r5PBC9hCb23l7d++9D7H1PiCDAFYMD4OYNwcEOCyB4MNAALy2iQKKDQAAcJl6oyGEAovUSAdB6G7pUL4eicE9DoRQyorcooAFJLEoHLMY+wPcW4iCcXjVg9hKhRScXvFI+DuDKLcZUPeMAdDMFWIE1hw01C7T2OwYINCrFoDQYwhxcSuQeBbEY8ozJWyiG4a+fUhpsjN1DhgDMI80BOICPQ2xni5gH1EH4ho9VmkeDIbkrYRjmAlOOGUo0lSw41PQE41pfinEzSMMiWxbdHGDTYQ0MM9x9iDJ6MMipahsx7jKEwGZcywALKyXMaxDC7FLOeC4kx7iYoxSMiIdRATLBBJUWEkgESolMlics+JhItz-lDnuTZKAP4H2EJUVYVAulILniotRGiHIWP+Tk9QqzbjJnZGC7ZgI9lRByE4i5pzrkr0zKgSo5pwQoEmWgNIqwba8F2YMeSWonG3M+Ro3RcLPA9FmToeZgwbbmEdFckgcgW5fBTpZHogTgmhNMV8qEPyYlvOyRoXJYZNQDNSc4g0IyWVVPGXUuYAqhVXI5UYu5fj1EdNRc8eVHylXfOiX87pKy8WTT1RCywUKSBfDOR6gFXqOCYqZBGXVcxXVMhYHoSQd0vhegDcmh5rzInROpZc5N1SEBGBIJiIyRb02qoaTYluOaMz5sLcW6NKrolTIrSkX4VadAFqLUZV5KBIXTLRZqjFobfiwTBY2jRmjeU9DwagxpyqEC5j7d4Ec4oh0VhHeJaFY6HXqB6RisMkboQ0LIHi5uMhCWHL4uak5mSyU+BJdejVi7JSTGmBgQZR6DU7IJQc01vlL2koMXey1fFOVKqoDy4Q6jIP+IXVq246zgifjfXqD9+KBRjIQLUgxf7718Szb2nhyDEW2IaOY3lZA80OFWHe6DvllHhlTPSrKD7cmSjBUokJSKGiBS3UnXAQA).

TIL `ractive.animate` on an non-numeric keypath. I've never animated a sub-path like that before 😄.

**Comment by evs-chris** [comment]
The footgun is now unloaded by default :smile:
