### ISSUE TITLE
What does your CSS workflow look like?

### ISSUE THREAD

**Issue by ghost** [ractivejs/ractive#3044]
## Description:

A few questions:

- What does your CSS workflow look like? 
- How do you use CSS pre-processors together with Ractive?
- What pre-/post-processing tools do you use?
- Do you use the `css` initialization option?
- Do you use `<style>` in your component files?
- Do you let Ractive manage your CSS for you or extract it during build?
- Do you use a naming convention for your CSS?

Just want to get insight on how people are actually using CSS on Ractive.

Personally, I use `css` and vanilla CSS for smaller apps, and let Ractive do the rest. But for larger apps where third-party CSS libs and a lot of code sharing is involved, I do SCSS on separate files. I also use BEM in any case, even if Ractive does scoping for me, because it makes the HTML and CSS easy to read and debug.

What's yours?

**Comment by dagnelies** [comment]
Personally, I use a vanilla CSS stylesheet most of the time, and `<style>` for a few component files but not many. Nothing very fancy here.

In the future, perhaps LESS or SASS will be used but since it's fairly minimalistic, it's at the bottom of my priority list.

**Comment by evs-chris** [comment]
I've not really used any managed css up until recently, and before, I used mostly stylus when not just using plain css. Stylesheets housed in external files kept alongside the component were compiled if necessary and concatenated into a library bundle. I actually have no problems with plain css in general, except that it should support nesting selectors. Prefixing has gotten to the point that I don't find it particularly necessary except in a few rare cases.

I have no naming convention :smile:, though I'm coming around to using a base component class as a prefix and hanging part names off that namespace e.g. `<div class="my-component"><span class-my-component-part1 /><span class-my-component-part2 /></div>`. That seems to work out reasonably well up to the point that you expect a part to be a container, where you need to apply child selectors `>` to keep from accidentally cascading if you are targeting, say, `button`s in the `.my-component-title`. Those should probably get a class for direct rules too, but for some reason having a class on _every_ element bugs me.

When dealing with components, I've found that chunky selectors tend not to matter, as most components don't deal with more than a couple of screens worth of css. Tying the css to the component and using scoping seems to make it much less append-only.

For libraries, where I have used ractive's css handling, I typically turn off scoping so that it's easier to override styles with an app-specific stylesheet. Landing support for style computations should remove the need for that.

**Comment by giovannipiller** [comment]
Our Single Page App deals with CSS in two ways.

The main CSS file (Bootstrap based) is completely out of Ractive’s control. We write SCSS, then bundle it up and load it as a single file through a plain `<link>`.

Animations (keyframes) are in their own css file, it too untouched by Ractive to avoid any scoping issue.

The rest of the application though, is split across multiple components. We use Webpack and a collection of loaders/tools to convert SASS-like syntax to CSS, and then feed it to Ractive.
We do keep scoping enabled, but having been burned a couple of times in the past (all closed bugs, don’t worry 😊), we started using BEM just like @fskreuz. As a side effect, code is much more readable now, and like it has been already pointed out, way easier to debug.

Our components range from fairly simple ones, to those including tens (or perhaps hundreds) of sub-components.

Just to give you a general idea, each of our components is usually made of:
- **component.js**, its logic
- **component.rhtml**, its template (we use a modified reactive-loader to pre-parse it)
- **component.pcss**, the css of the component, usually in one file, which will go through things like postCSS and Autoprefixer
- **_partial.rhtml**, one or more partial files, if necessary

The [new CSS functions](https://github.com/ractivejs/ractive/pull/3041) are very interesting, though we still have to figure out how, and if, we’ll be able to use them extensively in our project.

**Comment by PaulMaly** [comment]
My way to use component's separated styles:
`
Ractive.extend({
  css: '@import "/css/component.css";'
})
`

**Comment by sarendipitee** [comment]
I use stylus (and force everyone on my team to as well 😈 ). Just kidding they love it. 

I use webpack to bundle/build individual stylesheets for specific components/pages along with a base stylesheet with global styles that is used across an app. With Webpack's code splitting/async loading they get loaded and added to the page when the component is required/imported.

This is how I've done all the provided-for-you styles in my ractive components:
https://github.com/JonDum/ractive-datatable
https://github.com/JonDum/ractive-tooltip
https://github.com/JonDum/ractive-multiselect
https://github.com/JonDum/ractive-datepicker
https://github.com/JonDum/ractive-colorpicker
https://github.com/JonDum/ractive-paginator
https://github.com/JonDum/ractive-stepper
https://github.com/JonDum/ractive-select
https://github.com/JonDum/ractive-dropdown
https://github.com/JonDum/ractive-multi-decorator
https://github.com/JonDum/ractive-autosize-input

I don't think I've ever used the css option in Ractive and don't really see the need for it. Nor do I *directly* use `<style>` tags, because, again, Stylus is such a requirement.
 
As for naming conventions, BEM makes so little sense to me because it's very unreadable and machine looking. I definitely fall into the Semantics camp in the CSS-Naming-Conventions Holy War  https://maintainablecss.com/chapters/semantics/
