### ISSUE TITLE
[Suggestion] Use alias for module imports

### ISSUE THREAD

**Issue by marcalexiei** [ractivejs/ractive#3055]
[Rollup-plugin-alias](https://github.com/rollup/rollup-plugin-alias) could be useful while importing from "far away" folders and during recode / restructuring operations.

If you are interested I can create a PR 🙂.

**Comment by evs-chris** [comment]
I find your ideas intriguing and wish to subscribe to your newsletter 😁

There are probably a several spots that would benefit tremendously from that. Most of the really chewy ones are just off root, so is it possible to create an alias to the root of the src?

**Comment by marcalexiei** [comment]
Yes, sure!

My initial idea was to create an alias for each src folder.

I've created a little [POC](https://github.com/marcalexiei/ractive/commit/41dac715475e4da06174616229970a1ad19a254c)

**Comment by ghost** [comment]
I'm curious of the need for that Rollup plugin since Rollup accepts a [`paths`](https://github.com/rollup/rollup/wiki/JavaScript-API#paths) config (similar to RequireJS) where you just use a global-ish name, and Rollup does resolution for you (unless I'm missing something obvious).

Also not sure if Ractive should have this. I think it's best to leave it to the loader since it has knowledge about what environment it's in, what bundler it's using, and what's best for the situation.

**Comment by evs-chris** [comment]
The biggest benefit for me would be during refactoring, when splitting a file up the relative paths are inevitably off and I have to actually think about how many `../`s there should be. And then fix it when the build blows up 😁... Twice. I'm not good at picking the correct relative path.

**Comment by marcalexiei** [comment]
> I'm curious of the need for that Rollup plugin since Rollup accepts a paths

I've tried to use `path` but I've found this [issue](https://github.com/rollup/rollup/issues/1285#issuecomment-275462442): it seems that `path` should be used to include  external dependencies.
