### ISSUE TITLE
Anchor #each iteration is broken

### ISSUE THREAD

**Issue by BartVanBeurden** [ractivejs/ractive#3060]
## Description:

When using anchors (mounting points), mustaches inside `{{#each}}` statements don't work.

## Versions affected:

0.9.3; 1.0.0-edge (tested on ractivejs.org playground)

## Platforms affected:

Firefox, Chrome (others untested)

## Reproduction:

Code taken from the ractivejs.org example on the Anchors API documentation page, with modifications

```
const MyComponent = Ractive.extend({
    template: `
        <div>
            <div>Model Name: {{ model.name }}</div>
            <div>Model Items: 
                {{#each model.items }}<span>N: {{ name }}</span>{{/each}}
            </div>
        </div>`,
    data() {
        return {
            model: { 
                name: "model", 
                items: [ {name:"item1"}, {name:"item2"} ]  
            }
        }
    }
});

Ractive({
  target: 'body',
  template: `
    <# mountpoint7 />
  `,
  oninit(){
    const myComponent = MyComponent();
    this.attachChild(myComponent, { target: 'mountpoint7'})
  }
})
```

Output:

```
Model Name: model
Model Items: N: N:
```

Note that the model.items collection is iterated, but the name is not displayed!

**Comment by evs-chris** [comment]
Attaching a child rebinds the child's fragment, but repeated sections are a little weird and were missing checks to make sure they were bound before trying to update. Unbound (missing data) interpolators have nothing to render, so it was showing up as blank. This is now fixed in edge and will go out with 0.9.4 when it's cut. Thanks for the report!
