### ISSUE TITLE
class attribute clobbered by splice

### ISSUE THREAD

**Issue by lazylester** [ractivejs/ractive#3061]
## Description:
ref [this jsfiddle](https://jsfiddle.net/hku8vmaq/2/)

1. An array of data items is rendered to the view.
2. After initialization, the class of an html element in the array is modified (in example, I add class "hilite").
3. If a new data element is spliced into an array, replacing the already-rendered element, the class of the rendered element is reverted to its original value. The added 'hilite' class is not preserved.

## Versions affected:
edge

## Platforms affected:
OSX/Chrome

## Reproduction:
see [this jsfiddle](https://jsfiddle.net/hku8vmaq/1/)

(thanks for all your work on ractivejs)

**Comment by evs-chris** [comment]
This is actually a feature of ractive's array support. When you splice out an item, the DOM associated with that item is destroyed in a transition-friendly way rather than being reused. If you want the DOM to be reused, you can just set the item directly e.g. [`flintstones.set('people.0', {name: 'Barney'})`](https://jsfiddle.net/hku8vmaq/3/) or modify the underlying array directly and tell ractive when you're done e.g. `r.get('array').splice(0, 1, 'a', 'b', 'c'); r.update('array');`

**Comment by lazylester** [comment]
thank you @evs-chris. Always so helpful and much appreciated.
