### ISSUE TITLE
ractive.set {deep: true} causes wrong values to be returned by ractive.get

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3078]
## Reproduction:

[**BUGGY** Example in 0.9.3, with `{deep: true}`](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoQN4YACAXhIDs0B3EgJSQGMUBLANzQApgAdS3igAmqJJBJ8BKQWDQIEAe3GTBqlGJIBGPCX5rBAI3EAmPdJQ4zlyjgCUeykwWUMChGgB0igOZcA5KyUrGxICCRYqGjifjowHt5oKFy29pRxGIk8svJKEhoArDj4EkJoaAAO4igwAK5odvxOLm6ePv5IJKwYJPlUCjTRsfGZKfy4QA):

![image](https://user-images.githubusercontent.com/6639874/30140369-ac7f7f88-937c-11e7-85ca-3e8552df7641.png)

Buggy: Initial state is wrong.

[**OK** Example in 0.9.3](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoQN4YACAXhIDs0B3EgJSQGMUBLANzQApgAdS3igAmqJJBJ8BKQWDQIEAe3GTBqlGJIBGPCX5rBAI3EAmPdJQ4zlyjgCUeykwWUMChGgB0igOZcA5KyUrGxICCRYqGjifjowHt5oKFy29pRxGIk8svJKEhoArDh2-E4ubp4+-kgkrBgk+VQKNNGx8Zkp-LhAA):

![image](https://user-images.githubusercontent.com/6639874/30140426-12880cfa-937d-11e7-9acf-a0d834d3f3fe.png)

**Comment by evs-chris** [comment]
What you're experiencing is a by reference vs by value thing. Deep set updates parts of the tree inline (reference) rather than replacing parts of the tree (value), so if you don't inspect the object _before_ the references are updated, you'll see the new data. Try [this](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoQN4YACAXhIDs0B3EgJSQGMUBLANzQApgAdS3igAmqJJBJ8BKQWDQIEAe3GTBqlGJIBGPCX5rBAI3EAmPdJQ4zlyjgCUeykwWUMChGgB0igOZcA5KyUrGxICCRYqGjifjowHt5oKFy29pRCaAYArt4JMPxxGIk8svJKEhoArDj4EuloAA7iKDCZaHb8Ti5unj7+SCSsGCQVVAo00bHxRSn8uEA) with devtools open and see the difference when the debugger pauses before the deep set.

**Comment by ceremcem** [comment]
A-ha... I [got it](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoQN4YACAXhIDs0B3EgJSQGMUBLANzQApgAdS3igAmqJJBJ8BKQWDQIEAe3GTBqlGJIBGPCX5rBAI3EAmPdJQ4zlyjgCUeykwWUMChGgB0igOZcA5KyUrGxICCRYqGjifjoAUgDKAPIAch5YMIHerABmAJ5cMB7eaChctuX8hRglPLLyShIaAKw4+BJCaGgADuIoMACuaHb8Ti5unj7+SCSsGCRNVAo00XFJqemZOfmFxaXl9pS4QA)...
