### ISSUE TITLE
Any easier way to use @.get('foo') inside {{each}} loop?

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3087]
## Description:

I don't know when (or if) it is changed, but

```
<input value="{{foo}}" /> displays something 
{{#each bar}}
    <input value="{{foo}}" /> is not displaying anything
{{/each}}
``` 

Is there any easier way to get data without using `@.get('foo')`, as [in the example](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gEoCGAxgC4CWAbggHQkD2AtgA4MB2C7ZutR-AAgC8A4uWp0EADzJckACmAAddkrKzWAGyKzIAgAYq1agDxgALAD4kOonuDAAUgGUA8gDlauMjArsUFABmAJ7yNmREAJQYGAImAPQWlkZkhuwYkSqcAO6ipJQ0iikImnoA5ADEDACuZCy1ZVgpGizaugYppvxEAuFEQkogDlIxgwLxyapkag4VCKRgAoEMDAKjU8ZkJt29tgNDwAACtGhk8mVSZdEYYxOdZA7x8yRg62r6TVMc0PeMWgjtQLVdjiDjySLKDbTdRgCi8XAA86XLACADaAEYUQAmFEAZgAupEANz3G5TbApPr2e7LBh6DHYvH4lJkjIgHBkeAmJDUAQUJD7Gp1WqDSwJHlUSyYIA)?

## Versions affected:

1.0

**Comment by ghost** [comment]
[Parent prefix](https://ractive.js.org/api/#parent-keypath)? Seems to work.

```
<aaa data="{{ ../../x }}" />
```

**Comment by ceremcem** [comment]
Hmm... And if we need absolute path, we can use `~/` right?

```
<aaa data="{{ ~/x }}" />
```

**Comment by ghost** [comment]
Yup, you can use the other prefixes.

**Comment by ceremcem** [comment]
But still, it doesn't make sense when `{{ x }}` differs from `{{ ~/x }}`.

**Comment by ceremcem** [comment]
[In this example](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gHYIDuABAEoCGAxgC4CWAbggBTAA6B7tCANpKQDkAYgD2AV1oAHSYKyduPALZTelHgIAGC2twA8UgHykAHgODATGDKT0B6Izv1gAzIdEBre68NPaF4QQaMFIAM1FRUms-fVwpSgJDCwA6KxsAH1s7OITfLl1-YDsg6jBornzuPz0fcSITKQQ6ZG83PwCSkPDI8qqCvRzEizTSTPtBvL6LYuDegoVK2hq3BAamniRWyYKO4LCIqIwYpYmLAD87EbHs+MT2os7e-M15fNECaD9qURVeBA0wnU6PR3iwAJQcRaKMD0XDJXD-FiCExyUgAbQAjFhSAAmbEuAC6YIA3H4jvlsDokOpKOY-N0BGjjpYBIJKIJKVD-GYhAAjDmvPrcFlCagcvwEnTkjBgkA4WjwPRIJikehIAC87BAEmkki1hnsysYhkwQA), `{{x}}` behaves just like `{{.x}}` inside `{{#each}} ... {{/each}}`:
![image](https://user-images.githubusercontent.com/6639874/30274133-c2c1fd58-9704-11e7-9cc3-43b7964222af.png)

Is it a bug or a feature?

**Comment by ghost** [comment]
Without a prefix, Ractive uses the [resolution algo](https://ractive.js.org/concepts/#reference-resolution). It's like JS variable resolution - it goes through the contexts bottom-up and resolves to whatever gets snagged first. `~/` explicitly starts resolution from the instance data's top level instead of the current context.

Prefixed keypaths don't follow the resolution algo (or at least gets stuck at step 2, explicit reference) and specifically locks the reference to that path.

```
<h3>ok</h3>
{{#each foo }}
  <span>{{.x}} | </span>
{{/each}}
```

Tells Ractive to specifically lock to `foo.*.x`

```
<h3>expected</h3>
{{#each foo }}
  <span>{{~/x}} | </span>
{{/each}}
```

Tells Ractive to specifically look at `x` (instance top level).

```
<h3>unexpected</h3>
{{#each foo }}
  <span>{{x}} | </span>
{{/each}}
```

Goes through the resolution algo. Goes to check for `foo.*.x` first, then `foo.x`, and lastly `x`. Since the `foo` items have `x` (`foo.*.x`), it resolves to that.

**Comment by ceremcem** [comment]
Such a great explanation...
