### ISSUE TITLE
Async components - feature request

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#3089]
It would be nice if we could have async loaded components and use webpack for code splitting.
This basically is a continuation from here: #2830 
I thought I'd open this to see if anyone else think this should come handy.

**Comment by evs-chris** [comment]
I'm using webpack with the bin loader to do async loading of different chunks of an app via dynamic import and splitting. The async chunks tend to be more view-style things that are loaded in anchors, but widget-style components work as well. Are you looking for something beyond that?

**Comment by ceremcem** [comment]
Note: I think this is highly related with #3086 

WIP: [Here is the example](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gIZEAEAvMQEoEDGALgJYBuCAdAgB60IB2SAFMAA63YsS4BbAA4AbAl0jEABsNGiAPACMArrVoB7EQYC01afWoBrUoJAB9U+Ys2AfLgIBPYmATTpegITEfDA8SAgwxNR6Wty0CsDAUTG0GBgAlGoA9Nq6Bs4qqmoAxMR6tN4RmfkiSlgFBiG84QoAZjF09AZ8aUI1grpg9LgAJGRig7gF-eVDLARI-ADkSbGLaQDcU7S4CLQAKvTiCNG0fG3cHV09wv23tBoPY1QdzGycoXz6tAS+7gAi9BaLXCPFOaQ2N1oon6GgAjGMHhpuptuP1VOMhsM5roaGAAMKDaT8OFYYjAb4wNBxYiLMoVRbpFHQlKk2EABg5aQK2AKSDkBFa7QYV16zJCtC0MBEouIdxW1LZWww3OE6Ru3GeDGYAgKFKpCkWRROkh0izqNT533iBVE4lwKANAAkfH5SQB1PQwIn+Rbc82iCQyOQIBSKYjFYjiTxVRT+0rcRphGCCi7C7jdGWidhjIgEZE24jsFhdTOy2j2MyWFOXdPXVG0O79Wy2FgteghPiLby+PRrdboxs1ZnKofENX16YTbHfaj4wn8dik4BiAiU3YGqMMrk1Hn1gzWiflF16atpjOQu4-cKnRYzXDEIbEFowPTiYhIdzcAjicyRV+SAxQTWC8UhVbhx2Ec4azEMofmkf5AWBRowV6fpxUlaUQMDWR5CUTQdH0QxuBMSsrBsCtHBcREH24XBvguBAyWAdx6B8JBUiyHJCOcWMQP3MkQKbBxLHPQ9+ivGAbwAdxdd9AJ9bdG1A+tRBHfoRxHEAcFoeA1DAAAmZwjSPCICAuMBPWIKT6F8YgNEYjRol4YgCBaLgInhHYomcrIDOqNQkCYB8kGsEBjR0FwskCxhnEwIA)

### TODO: 

* ~Convert the `totallyDifferent()` function output to a pure string and convert it back.~ Done [here](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gPQEAEAUgMoDyAcgGYB2kxAKgIYDWC9xtMA9gFtiYAC4iADrkhFcI1gGN2fAG4IYtADZ8A7gDp5ggqwIBGAOwAOAMwBOCwFYLpm-YBMNmyYA69ZaxhkVHT0ANw+AJa0xAAUAIQUNAwAlMTAPsQZgYncALypGGH0GD4+0bQArvTyIuF83NEpadxZwbqyMOH0KJEAnsR5FVU1ddF8AEYAVo3pmTAIIuUw3AnUbSIdXb2jk1iD1bX00Zw9WMR+GuUISU2Zt3dzC0sxIj3iCHxR55f9OXkA5HthvQ-sQUgB+M6sC4IXQiPjkdadFANYhML4IQp3TIYJKY4jFegzFYMXTify4BD9HiVfYjdrTZoZB6LZZBUnkhDRdq7GlAo4IE6Q6HXGZYyLRF5vD5C76xf7tJF-FLMp7ovFYlX1GUw3DlMYKrrRAAMWAsKV+xABvIOSuIEIQ52ifydAGp0S6lba0VDLur8biZgSMA0A4T6ERiABaaPR4gAUXoSGI0sBB2ISAQtE64SBuGIJXoAh6AGFBOI6lwRAARVhyKlNLxiBACcQaWsIJgAAwAPGNymI6sn6JH5Bpwoocl4QAB9Ufj9hTgB8YxXxE6slYVUp8iYwGA8gwGD3PXCCA0SEP3YIfYH9EXnawJThjFST8bs7HiiYqZGIsJIkbRsoTUEQnW0M8NHTCtYiVQpAIAsQwHCXBdFYJAkCdeRYLfEQCQyIMCx8CMDRQYg5nEOYKXoOQgWTKIRDAbcywraj01rVgfAADypYl6DWDZuloHpoiLUsWxY6t2KSHwDHoXA+A0GEtGRMY4VYaJOKSUMIwMcQ+k3JMyVkSkc2IMYzx0Qj6FYGyqQAJQUGpVF0BBOJELgMJuYh3JbNt3K7UViF7ftnyHEdP3YScZznRQl1wVg+kYjQtFiGI5kTNRiAMSoRF3fc+Byw8kivG9n0XQLuwAYmTBjMvkHI92y6jD2IAhyuaB8ZjqdKMxgb9rV-LzGwY5CABIqRG3AZmGpCULQjC-iakRsOaRsKREZhwgEd5+zKAbDj-DJ4NqsTy3oSsEQCPJa3GaIpwFUgjQALQAdRMbQxgAcQAMWe8gAEkADZ-omTjwiQAANOyjTGVwABYUFhuGRAATVcTjxDR3AbAh4tSFoNGMbRkR5BB+xwhRgR-pQVgXvsAAvJAfvKNGAFUUBR+m+DQKwRAmWgIfMBArA0cRXs49gBaNCwABlXFIEwkAACTs5RJjh8IZbxtXwiBh6CfRzHXFwcJKHCUgBCQOmJiZjQdYAQT4ABpCGSbGDROKNCGVfkJnvtwJ6Icep3iyQKxxdwf7PtVsYBFZsBSB6dgzAhz77F977Pe96HWE+jR6ZlgRvvYJ7ixQegUZ6eRxEoExOPKbPfaVo1Igho0p1DeDG3kHighJMkYApCVGNOiTLuk-94JXMZ7Mc8JnNc9zE2ieRO5EI6RDGEwqWnho4PXzJJtG1CxAUMBiyQ89oi305gDkGA0Fyy0+FqmA-hxPFG2wYgTCNP+J-wo+ZoSB2L9SGAcBoQ11jzBZK+VaCElpMHbvAvC+IfA4gLA5fYqhoheXvo-JgfxKoFQkP2P4QCMggLkLuQKAhcAoEIUrCCfBTgvT4DAc8MFAwUO8s2Vs7Yuz5ngd2JA89iCyB6IpKKYx2G9SYCYcQ3F5JjiTHMJAIRiBknQkieRRpFFLmmiIKqxAixZQKtRKKe4bKsEPFOVq7UN5XlEcoBx+YjGdHEP2bUljgDWNsSAbyrwEBRXoOUAQ5kYB2LaoYzqzRuoeTUGA2kB0vIZG4tdGye9AqcV0CMVJbiPzziSXyP8XcELTmnLoLMcwnRJS0LBW4XdGRuNQfhCex1ZonzkPIc+l8MKcVvt5fwBDLRFnfgA-EQDGx1BoZPWqyU+DFIgaUhCQFFIwFAn8Saa48y8EEOmHo1kBDjjMeJc61ElQ4VQUGdp9AQA4BEPAbsYBXCLmIa-Ygm4ensOINocIyUzKUhkZUJMrBaDuQCNvCkskkxXhee1ERYjwZRRIZ4gCIBFxOPnouTAQA)

**Comment by fskreuz** [comment]
Throwing random ideas to the wall and see what sticks, who gets hit, or who corrects me for my misconceptions. 😁 

- Ractive would need to move from its ahead-of-time setup (loading deps, defining configs, assigning references to implementation) into a more on-the-fly load-it-when-you-need-it describe-it-to-me setup. For instance, you can't define registry things as references anymore since you can't make hard dependencies.
- Ractive to have its own dependency injection system. Since it cannot use hard references to dependencies, you'll be describing to Ractive what's there and where stuff is. It will then handles loading, resolving, construction, wiring, and all that.

    ```js
    // You can't do this since this will initiate module loading/tells the bundler to inline
    // You'll need to inform Ractive about this dependency without hard-wiring this.
    import MyOtherComponent from './foo'

    export default Ractive.extend({
      // you can't do this anymore since MyOtherComponent may or may not be present.
      // You'll have to tell Ractive about this without having the actual reference at hand.
      components: { MyOtherComponent }, 
    })
    ```

- Because of the DI, Ractive would need a runtime dependency resolver. `ractive-load`, as mentioned in the issue, would be a good jumping point. Determine dependencies, maintain an internal cache, we all know how that works.
- Ractive would need a way to define boundaries to know what to lazy-load. It needs to know what to load when. I would imagine this system would be very close to routing.
- Seamless API integration. Although we have success at anchors, yields and similar mechanisms, it would be nice if we never thought about it during authoring, that It Just Works™.

Been using Angular at work the past few weeks (and the whole reason why you're not seeing much of me lately). Angular's module system does a good job at defining entire chunks of the app and it's closely tied to routing as well. Although pretty, I'm not a fan of annotations, TypeScript nor compilation.

**Comment by ceremcem** [comment]
[This is the fully working draft](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gPQEAEAUgMoDyAcgGYB2kxAKgIYDWC9xtMA9gFtiYAC4iADrkhFcI1gGN2fAG4IYtADZ8A7gDp5ggqwIBGAOwAOAMwBOCwFYLpm-YBMNmyYA69ZaxhkVHT0ANw+AJa0xAAUAIQUNAwAlMTAPsQZgYncALypGGH0GD4+0bQArvTyIuF83NEpadxZwbqyMOH0KJEAnsR5FVU1ddF8AEYAVo3pmTAIIuUw3AnUbSIdXb2jk1iD1bX00Zw9WMR+GuUISU2Zt3dzC0sxIj3iCHxR55f9OXkA5HthvQ-sQUgB+M6sC4IXQiPjkdadFANYhML4IQp3TIYJKY4jFegzFYMXTify4BD9HiVfYjdrTZoZB6LZZBUnkhDRdq7GlAo4IE6Q6HXGZYyLRF5vD5C76xf7tJF-FLMp7ovFYlX1GUw3DlMYKrrRAAMWAsKV+xABvIOSuIEIQ52ifydAGp0S6lba0VDLur8biZgSMA0A4T6ERiABaaPR4gAUXoSGI0sBB2ISAQtE64SBuGIJXoAh6AGFBOI6lwRAARVhyKlNLxiBACcQaWsIJgAAwAPGNymI6sn6JH5Bpwoocl4QAB9Ufj9hTgB8YxXxE6slYVUp8iYwGA8gwGD3PXCCA0SEP3YIfYH9EXnawJThjFST8bs7HiiYqZGIsJIkbRsoTUEQnW0M8NHTCtYiVQpAIAsQwHCXBdFYJAkCdeRYLfEQCQyIMCx8CMDRQYg5nEOYKXoOQgWTKIRDAbcywraj01rVgfAADypYl6DWDZuloHpoiLUsWxY6t2KSHwDHoXA+A0GEtGRMY4VYaJOKSUMIwMcQ+k3JMyVkSkc2IMYzx0Qj6FYGyqQAJQUGpVF0BBOJELgMJuYh3JbNt3K7UViF7ftnyHEdP3YScZznRQl1wVg+kYjQtFiGI5kTNRiAMSoRF3fc+Byw8kivG9n0XQLuwAYmTBjMvkHI92y6jD2IAhyuaB8ZjqdKMxgb9rV-LzGwY5CABIqRG3AZmGpCULQjC-iakRsOaRsKREZhwgEd5+zKAbDj-DJ4NqsTy3oSsEQCPJa3GaIpwFUgjQALQAdRMbQxgAcQAMWe8gAEkADZ-omTjwiQAANOyjTGVwABYUFhuGRAATVcTjxDR3AbAh4tSFoNGMbRkR5BB+xwhRgR-pQVgXvsAAvJAfvKNGAFUUBR+m+DQKwRAmWgIfMBArA0cRXs49gBaNCwABlXFIEwkAACTs5RJjh8IZbxtXwiBh6CfRzHXFwcJKHCUgBCQOmJiZjQdYAQT4ABpCGSbGDROKNCGVfkJnvtwJ6Icep3iyQKxxdwf7PtVsYBFZsBSB6dgzAhz77F977Pe96HWE+jR6ZlgRvvYJ7ixQegUZ6eRxEoExOPKbPfaVo1Igho0p1DeDG3kHighJMkYApCVGNOiTLuk-94JXMZ7Mc8JnNc9zE2ieRO5EI6RDGEwqWnho4PXzJJtG1CxAUMBiyQ89oi305gDkGA0Fyy0+FqmA-hxPFG2wYgTCNP+J-wo+ZoSB2L9SGAcBoQ11jzBZK+VaCElpMHbvAvC+IfA4gLA5fYqhoheXvo-JgfxKoFQkP2P4QCMggLkLuQKAhcAoEIUrCCfBTgvT4DAc8MFAwUO8s2Vs7Yuz5ngd2JA89iCyB6IpKKYx2G9SYCYcQ3F5JjiTHMJAIRiBknQkieRRpFFLmmiIKqxAixZQKtRKKe4bKsEPFOVq7UN5XlEcoBx+YjGdHEP2bUljgDWNsSAbyrwEBRXoOUAQ5kYB2LaoYzqzRuoeTUGA2kB0vIZG4tdGye9AqcV0CMVJbiPzziSXyP8XcELTmnLoLMcwnRJS0LBW4XdGRuNQfhCex1ZonzkPIc+l8MKcVvt5fwBDLRFnfgA-EQDGx1BoZPWqyU+DFIgaUhCQFFIwFAn8Saa48y8EEOmHo1kBDjjMeJc61ElQ4VQUGdp9AQA4BEPAbsYBXCLmIa-Ygm4ensOINocIyUzKUhkZUJMrBaDuQCNvCkskkxXhee1ERYjwZRRIZ4gCIBFxOPnouTAQA) for my use case. Let me put the strategy into production and see what happens.

**Comment by ceremcem** [comment]
Main problem with my above approach is that if that async component requires `foo` library,  we should send `foo` library before sending the actual component data. 

Moreover, If we have 4 async components and 2 of them needs `foo` library, we should ensure that we will send the `foo` library for only the first time, not twice.

> This problem is a bit like what we talked about the dependency management problem at [gitter](https://gitter.im/ractivejs/ractive?at=59c78fd3cfeed2eb6544adb7).

**Comment by sarendipitee** [comment]
@ceremcem that's not a Ractive issue, but a bundler issue. Check out Webpack's code splitting and CommonChunksPlugin that does exactly that. 

https://webpack.js.org/guides/code-splitting/

**Comment by ceremcem** [comment]
@JonDum I've looked at Webpack's code-splitting, and I didn't understand how things work in the Webpack universe (again :) )

What I mentioned above is to state *what to do*, rather than *how to do*. Switching to (yet) another bundling system (immediately, to be able to use dynamic components) might not be an option (it's a matter of time and human resource). Moreover, things may become complicated if you want to provide a different transport and authentication/authorization layers for sending the dependencies. 

So providing a recipe might be useful, IMHO.

**Comment by ghost** [comment]
I don't want Ractive to end up like other mainstream frameworks that designed themselves around a specific tool and have become handicapped without them. If Ractive were to require build tools, I'm not sure what other frameworks out there fit the bill of "It Just Works™". 😁 We can have tools, but at least it should be optional.

**Comment by sarendipitee** [comment]
@ceremcem Webpack isn't doing anything mystical to your code. It's essentially just JSONP; loading extra script files that are eval'd and the return value passed to the `require()`/`import` call. You could do that with zero build system, but it'd be a pain in the ass and you'd be re-inventing the wheel.

@fskreuz I don't see how that conflates Ractive into "requiring" a specific bundler. Ractive is just a library you use in whichever bundler/build system you so choose. The build system (or lack thereof) is a choice for you and your team and is, of course, completely optional.

With that said, I would only consider Webpack, and JSPM as having first-class support for asynchronously loaded modules. Rollup still has no-support and has actually started a bit of [a holy war on the subject](https://github.com/rollup/rollup/issues/372). Browserify has support through plugins, but  those plugins are old, hardly used, hardly worked on (like Browserify itself). 

So that leaves Webpack and JSPM. Both have great code-splitting/async support. I think the only real action item on Ractive's part is the ability to re-render at some point in the future when a Component resolves. You can technically already do this, albeit in a very convoluted way abusing Partial Expressions and toggles to trigger re-renders: https://jsbin.com/giyewox/edit?js,output

That would be much more clean if you could use Promises like Components in a template that would then re-render with the fulfilled value (a Ractive component class/function) when it resolves. I wonder how hard @evs-chris thinks that is.

**Comment by ghost** [comment]
> I don't see how that conflates Ractive into "requiring" a specific bundler.

When we start saying "this feature only works when you use this lib/tool/workflow".

I once removed polyfills so that the core is polyfill-free and a dev can just bring their own polyfills (via [a service](https://polyfill.io/v2/docs/) or [a third-party lib](https://github.com/es-shims)). Personally, that was a pretty minor change but they came back because we needed Ractive to run out of the box.

Following this trend, if this feature were to be implemented, it should also work out of the box. Meaning async components (syntax, render, loader and all) should all be in Ractive. Otherwise, the arguments made to adding back the polyfills becomes questionable.

I'm not against the feature. I'm just saying that if we're to implement this feature, and we're set to have Ractive work out of the box, then _there should be no mention of third-party library/tooling at all_. They could integrate but they should all be optional (i.e. how Ractive has runtime parsing, but you can _opt-in_ to do it at build time).

**Comment by kouts** [comment]
@fskreuz that was probably my mistake mentioning "webpack" in the beginning.
I didn't mean to target a specific tool (not that webpack code splitting support is not welcome though e.g via a plugin).
```ractive-load``` for example offered a similar functionality to what I'm describing, albeit not with "compiled" components.

I can already use e.g webpack codesplitting, the thing is I must define all component dependencies down the tree upfront in order for a View  component to render.

**Comment by ghost** [comment]
No problem. It's always nice to gather input from people from all sides, and have everyone covered. I often pop up in the issue tracker, say something random, and you'll be like... 

![image](https://user-images.githubusercontent.com/1582932/31277434-f334bec6-aa6e-11e7-8bed-5c78c78b7021.png)

...and poof! Valuable input! 😄

**Comment by evs-chris** [comment]
So... async is now available for components, but it just works with promises. You still have to bring your own loader, and I think loaders are well beyond scope for Ractive. Are we close enough to call this feature implemented?

**Comment by kouts** [comment]
Haven't had the time to play with it yet, looks good.
I think we can close this.
Thank you @evs-chris for your efforts.
