### ISSUE TITLE
ractive.spliceAt method

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3090]
## Description:

Would a `ractive.spliceAt` method be considered in place of `ractive.splice(ractive.resolve('..'), ractive.resolve('@index'), 1)`, particularly useful for [`removeMe` buttons](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gHYIDuABAEoCGAxgC4CWAbggBTAA6B7ttlMatSKQDkAIwD2SAJ7CsnbrQQBbAA4AbSoqEADebW7BgAYgQ0wpAGbjxGDHu7cAPEialctKWoQBediAkwSAgwQgCMKgAebuJq9EikpIYAdNQx4jC2ANykKpRILgQoYQAMkX4AfPb61WAIamriicAAAvQEQRG2VQ60jqIArjziBKTDALTUsdQA1r4gMMrizACyCBULSksIpKuOAPQDQwSVXNVOey6MJz2Ge6bUYF2n2nKnw0Icp9wbW6tCFv0CHR6MMWHQIgBKT49bjgpK4dT0aisOELXAxZgsYRJJLCCFYUiohDotSY4StdoICJ4gmhCGZKp2U7YPRITSUD5VKziIQAbW6tGAqQaIRECyQwhZX2qQrSouEKAWCAIkteMMFwvSQmE6UohQQqoFspF2tEan6BqZPQAunomRgIZggA)?

**Comment by evs-chris** [comment]
In that example, you've got a context object, which will actually handle the resolution for you. You still have to pass it an index, but that's not too terrible an imposition: [`ctx.splice('..', ctx.get('@index'), 1)`](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gHYIDuABAEoCGAxgC4CWAbggBTAA6B7ttlMatSKQDkAIwD2SAJ7CsnbrQQBbAA4AbSoqEADebW7BgAYgQ0wpAGbjxGDHu7cAPEialctKWoQBediAkwSAgwQgCMKgAebuJq9EikpIYAdNQx4jC2ANykKpRILgQoYQAMkX4AfPb61WAIamriicAAAvQEQRG2VQ60jqIArjziBKTDALTUsdQA1r4gMMrizACyCBULSksIpKuOAPQDQwSVXNVOey6MJz2Ge6bUYF2n2nKnw0Icp9wbW6tCFv0CHR6MMWHQIgBKT49bjgpK4dT0aisYRJJKyUhwgQsYStdoICLCCFYUihCGZKp2U7YPRITSUD5VKziIQAbW6tGAqQaIRECyQwhpX2qXLSvOEKAWCAIgteMM53PSQmE6UohQQso5op5ytEan6GqpPQAunoqRgIZggA). Is that close enough?

Note that _all_ of the keypath-taking methods on a context implicitly resolve relative to the context.

**Comment by ceremcem** [comment]
Simpler, but is open for improvement :) I might add [this method](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3kjAPYAOAggC4AEAvFQGYCuAdgMYUCWRzAFCQIYUwWKqyIsKNAIwBKYAB1m8ikI64AdLhIAbDqwQ8A5OvWGRqjTAS4i2gG4GBQmSLESZAbkUZFi5ggB3KgAlfnYOBx4FJRV+GDQKSCpDACMiJABPM18VBABbHUEEJIADHOVgYABiBDCwBiIiDB8Y5WUAHiQIqlwKDO0EGnkQNJgkBBgkqRIADx7bDiQqKkr1MW0iGGaPKgEkLuYUKYAGWeGAPnKKNqEEbQ2V4AABDmZxmearm-aUxhVuKjcAC0rF0rAA1kMQFY8kQHABZBAXGFwhBURHtAD0v3+zEurWuFCxXTs+JulUxtVYYE+MRKWBy3FeHESDBY4W4PDkOWwjOYSWiNxRCOKbLYnE57Bm3IJyil6kIpEotCoivIFHUKVeSB4UpkviUsoo8rVlCMLzeCBmhn1BJayl5MSQgn4Aqu9EaSQA2l8KMB1pskoYrEhDI6bhUA5NkigrAhmGGGUb-bZA8lNvxDghE76Uxto6ltIxs-bCQBdHneGSYIA) to my [globals](https://github.com/aktos-io/scada.js/blob/0fbcac1804317d1ad049dcebd11a971c4ef35b3e/vendor/000.ractive-npm/ractive-npm.ls). Is that possible?

**Comment by kouts** [comment]
You can surely add a method by adding it to the prototype but I don't know a way to add it to the ```on: {}``` events object globally

**Comment by evs-chris** [comment]
As of edge, you can add methods to the `Context` prototype using `Ractive.Context` in the same way you can add to the `Ractive` prototype with `Ractive.defaults`. That should let you get `@context.dropAt(@index)` with `Ractive.Context.dropAt = function(idx) { this.splice('..', idx, 1); };`. You can take it a [step further](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gEoCGAxgC4CWAbggHQDCA9gHZkIAeZtMCAtozQCyCAAQBeEQDMArs3IUWACgCUwADrM1ZMmAq5auAA4AbCiQSKA5LVqWsInXtpoyVgAIVmSDpeX2AjMoA3BoYIZrMzAgA7iLE8jSK6praRDAukCKWAEaMSACedhpabLwmRGyZAAbFZFrAwADECKRgUoyMGBi1WloAPEjUIrhk+cYIYmoguTDeMJn+huzDjKZIIiINtCSrjDBdQSKGREiDzCgLAAxLUwB8PXWPYAjGxoybwB5eHF0PvWR9bLSbQsEQsAC0JFMJAA1pMQG4dqwOFwePwhBZlHc0QJRMI+gB6IEg5j3FL-QmDKhk-4NAktEhgX4pKpYWosTwUMiZGRyShKVS1bC1JAVIiZZL-SQdTIAbT+ZGAOze8yyPCQlmF5MeSt2qssKB4CGYmrZ2vqyr2mUseyI5wQpoVupV1uyxmkDu62oAukLQsFMEA) if you like, since this is not general API, with `Ractive.Context.dropMe = function() { this.splice('..', this.get('@index'), 1); }`. Of course, you may also want to make those methods check up the context until they find an array to get an appropriate keypath in case there happens to be additional context between the iteration and the button. :)

**Comment by ceremcem** [comment]
@evs-chris I don't know what to say! Thanks!
