### ISSUE TITLE
question about empty <style> Ractive places in <head>

### ISSUE THREAD

**Issue by Jeff17Robbins** [ractivejs/ractive#3091]
Ractive adds an empty `<style>` element to the browser's `document.head`, apparently to test for something, and doesn't remove it.  If it isn't necessary past the point of testing it at startup time, perhaps it could be removed?

```
// If we're on the browser, additional setup needed.
if ( doc && ( !styleElement || !styleElement.parentNode ) ) {

	styleElement = doc.createElement( 'style' );
	styleElement.type = 'text/css';

	doc.getElementsByTagName( 'head' )[ 0 ].appendChild( styleElement );

	useCssText = !!styleElement.styleSheet;
}
```

**Comment by evs-chris** [comment]
That's actually something that has been addressed in edge and should make it to 0.9.4. That style tag is for components that have a [css](https://ractive.js.org/api/#css) option, as it's where ractive aggregates the various component styles.

In edge right now, that style element is created on-demand rather than when ractive spins up, so if you have no components with css, you shouldn't ever see it appear.

**Comment by ghost** [comment]
Having it there should be harmless, unless you have a CSP in place that dislikes inlined styles. I'm curious about the issue you're having with its existence so that we can document it somewhere or at least have a historical reference.

**Comment by Jeff17Robbins** [comment]
I was tracking down some of my own `<head>` `<style>` issues, and needed to account for every `<style>` element.  I first assumed a bug of mine was putting that empty `<style>` element in `<head>`.  

Finally, using Chrome devtools setting a mutation breakpoint on `<head>`, I saw Ractive put it there.  

Perhaps Ractive could put an `id` attribute on it so that its provenance would be more obvious?
