### ISSUE TITLE
Suggestion: detect if a different version of ractive is already loaded

### ISSUE THREAD

**Issue by mikemaccana** [ractivejs/ractive#3101]
## Description:

I've just been tracking a hard to reproduce bug where ractive would fail on a component with:

    Object prototype may only be an Object or null 

After a bunch of debugging - more than I'd like to admit - the cause was ractive 0.8.19 and 0.9.4 being loaded simultaneously. I only noticed it when enabling `debug mode` and two separate messages popped up. 

Totally my bad.

BUT: it would be cool for ractive to flag if another version of ractive is already loaded. 

Might save other folk some time when upgrading in future.

**Comment by evs-chris** [comment]
Just wanted to note that I've looked into doing this, and it's not simple to accomplish with the way our UMD bundle is produced right now because of the way rollup handles `noConflict`. I'mma flag it as future, because I agree that it would be useful - I just haven't come up with a way to do so yet.
