### ISSUE TITLE
Outlook conditional comment

### ISSUE THREAD

**Issue by miladah** [ractivejs/ractive#3103]
## Description:
Conditional comments do not work in Ractive

Template: 
```
<li class="header-link">
  <!--[if !IE]><a href="{{url}}">BROWSE</a><![endif]-->
  <!--[if IE]><a href="{{url}}">BROWSE</a><![endif]-->
</li>  
```

Output: 
`<li class="header-link"> </li>`

-------------------------------------------------------
Template: 
```
<li class="header-link">
  {{{ifnotie}}}<a href="{{url}}">BROWSE</a>{{{ifend}}}
  {{{ifie}}}<a href="{{url}}">BROWSE</a>{{{ifend}}}
</li>  
```
```
data: { 
      ifie: '<!--[if IE]>',
    ifnotie: '<!--[if !IE]>', 
    ifend: '<![endif]-->',
    url: 'www.google.com'
    }
```

Output:
```
<li class="header-link">
<!--[if !IE]>--><a href="www.google.com">BROWSE</a><!--[endif]----> 
<!--[if IE]>--><a href="www.google.com">BROWSE</a><!--[endif]---->
</li>
```
When I put the comments in the data, Ractive modifies the comments so they don't work anymore.
`<!--[if IE]>  ====>  <!--[if !IE]>-->`

any solution?

**Comment by ghost** [comment]
It's not that it doesn't work, [it was never supported at all](https://ractive.js.org/playground/#N4IgFiBcoE5SAGAdANhAXwDQgM7wMYD2AdjoQDYCmS5hA5gBQBSAygPIBySOALjAJbE6-AGYBPBgCUAhvh78AbtQAO0mDkoMABgB1iOngB4cq4gD5eaowHoT083oAEjwwEIAtO8eTKdAK7kao4AEgAqALIAMo5EALaxlMQ8jp5mTi4e7gDaoo6uAJIAogC6ZvkA5LGO9o5FMSQAJvzyJNLk9fGJRq5ZiU0ixanpbp45IrUlZZXVxIQ8YJQwE-XETS3EbR0JSW69q6KD7mnEzsDAro6xfpb4C1tdjujoegbGpmZ9hrbveloAlACMEA). Both HTML comments, including IE's special conditional comments,  as well as template comments are ignored by Ractive's parser and never make it to the AST, which is the basis for rendering instances.

<sub>(It's a common misconception that Ractive does string interpolation because it uses Handlebars syntax.)</sub>

What I recommend is sticking in a boolean on a global data property using `Ractive.defaults.data` at the beginning of your app. This property is present across all instances unless shadowed by an identically-named one. Then use conditional mustaches on your template with that property.

```js
Ractive.defaults.data.isIE = /* IE checking logic, true if yes */;

Ractive({
  template: `
    {{# isIE }}I'm IE{{/}}
    {{^ isIE }}Not IE{{/}}
  `
})
```

**Comment by evs-chris** [comment]
See also https://ractive.js.org/api/#stripcomments

**Comment by evs-chris** [comment]
It looks like there's a bug with rendering comments since somewhere before 0.7.3.
