### ISSUE TITLE
Question: passing partials to subcomponents

### ISSUE THREAD

**Issue by BartVanBeurden** [ractivejs/ractive#3109]
How do I pass a partial defined in the content of a component to a subcomponent of that component?

Example: 

EventList:
```html
<div class="events">
{{#each events }}
    <div>{{ > content }}</div>
{{/each}}
</div>
```

GroupList:
```html
<div class="groups">
{{#each groups as group }}
    <div>{{ > groupPartial }}</div>
    <EventList events="{{ group.events }}">
        {{ > eventPartial }} <-- this line doesn't work
    </EventList>
{{/each}}
</div>
```

Usage:
```html
<GroupList groups="{{ groups }}">
    {{#partial groupPartial }} {{ name }} {{/partial}}
    {{#partial eventPartial }} {{ title }} <br> {{ description }} {{/partial}}
</GroupList>
```

In the content of the &lt;GroupList&gt; I define two partials:
- groupPartial > used to render a group
- eventPartial > used to render a group's events

How would I pass the eventPartial as defined in the usage to the content of the EventList

**Comment by ghost** [comment]
First of all, defining a partial inside the inner HTML of a component makes that partial available to that component. That's how `groupPartial` and `eventPartial` are available within `GroupList`. But that's where the similarities end.

The problem why you're getting `Could not find template for partial 'eventPartial'` is because of how `{{> content }}` works. Rendering the inner HTML of `<EventList>` into a component with `{{> content }}`, the context of the inner HTML is the `EventList` component. That is, references, data, partials, methods, etc. will resolve to the `EventList` component, and you've guessed it, the partial named `eventPartial` does not exist there.

In contrast, `{{ yield }}` does the opposite. Rendering the inner HTML of `<EventList>` into a component with `{{ yield }}`, the context of the inner HTML is the `GroupList` component (the enclosing component), where the `eventPartial` is available, [like this example](https://ractive.js.org/playground/#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoQN4BjAewDssACAcxlIFcAHDKgXioG1gAdcnlOSQBbNJCoByOoyZUAjBLx8BaAG5pyKDOO7KUAlAEsUCMZOnN5VNRpRWjJtIr0Hjp8VPqW519ZqsAJpjEMIZMRhQSevi8-PooDu7mXrI+Nv4ATFSJTkpxro4eFqm+tlRZQRghYRHkUXE4ALp8MXpCokUp5c5x6Vo6sQIFSZ4y5aX+Pjk9QwluZqOWWX2BwaHhhpHReIPxOZ1jy352WdN5s-vJhxMnVJXVG1sNzeRNyuRklHYAoscAMoZqBwAEpIYhGdQAOjQAA90OQAgAKXboYRMZDocQAAxcKAAPAFDKoqMRkBgMGweCA+hgqQA+PhUJnM4DAADEaDBYBurBwOFxzKoBKJdNZVAAnoY0AgAlQAO7GbkoMCAyE5KhIVg5PDZFUYSH3da1DWsQ01TbkKh8vEAekJqgZ+XirJtnOIYD5uNt9sdAhxrwAlO9PtQAOIpAFAqig8FEtDQuEaJG7Mhoii2bRUYBUX62SN2fB6VHo1Bmf2zYXE0mailU4q0kC++ICVkcrm0FK8-lOwWV0XAOkdmQABSQMCMSAQVpw3pFAuZeNzmnzPMpIDFNOn9L0gsFrMHfVH48Mk63PYXNqXKHzTdmLrdHu7Fbtc7i-pwQf4Hwo1AAgkxZBBMEIXjWF4WTPRUyYdNNEzbNwxkFdCziYsMTLL0EOYFd6zXMV6y3RsdxZdkmDHCcp2KI9yOnLNs3aNAaJdUjj0nT04j3EiyJPKdDy408+Vo7J5hovEACMYEHMUzUeS0BKYviEDY59MKYG89HfT8+H-JhkWyMcaDQFAPFE0gAnFRQ7lQJBxGzfCcCtANcCAA).  [Here's another example](https://ractive.js.org/playground/#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoQN4BjAewDssACAcxlIFcAHDKgXioG1gAdcnlOSQBbNJCoByOoyZUAjBLx8BaAG5pyKDOO7KUAlAEsUCMZOnN5VNRpRWjJtIr0Hjp8VPqW519ZqsAJpjEMIZMRhQSevi8-PooDu7mXrI+Nv4ATFSJTkpxro4eFqm+tlRZQRghYRHkUXE4ALp8MXpCokUp5c5x6Vo6sQIFSZ4y5aX+Pjk9QwluZqOWWX2BwaHhhpHReIPxOZ1jy352WdN5s-vJhxMnVJXVG1sNzeRNyuRklHYAoscAMoZqBwAEpIYhGdQAOjQAA90OQAgAKXboYRMZDocQAAxcKAAPAFDKoqMRkBgMGweCA+hgqQA+PhUJnM4DAADEaDBYBurBwOFxzKoBKJdNZVAAnoY0AgAlQAO7GbkoMCAyE5KhIVg5PDZFUYSH3da1DWsQ01TbkKh8vEAekJqgZ+XirJtnOIYD5uNt9sdAhxrwAlO9PtQAOIpAFAqig8FEtDQuEaJG7Mhoii2bRUYBUX62SN2fB6VHo1Bmf2zYXE0mailU4q0kC++ICVkcrm0FK8-lOwWV0XAOkdmQABSQMCMSAQVpw3pFAuZeNzmnzPMpIDFNOn9L0gsFrMHfVH48Mk63PYXNqXKHzTdmLrdHu7Fbtc7i-pwQf4Hwo1AAgkxZBBMEIXjWF4WTPRUyYdNNEzbNwxkFdCziYsMTLL0EOYFd6zXMV6y3RsdxZdkmDHCcp2KI9yOnLNs3aNAaJdUjj0nT04j3EiyJPKdDy408+Vo7J5hovEACMYEHMUzUeS0BKYviEDY59MKYG89HfT8+H-JhkWyMcaDQFAPFE0gAnFRQ7lQJBxGzfCcCtANcCAA) that preserves the loop inside `EventList` by exposing values from within the component into the yielded content (whose context is normally the outer component) by using yield aliases.

**Comment by evs-chris** [comment]
`{{yield}}` is typically the best solution for cases such as these, as @fskreuz pointed out, but you can also turn off isolation for the inner component if you're ok with it always being tightly coupled with its host component. When you set `isolated: false` when extending the subcomponent, it allows ascending through the sub-component boundary when looking for plugins and resolving data. You have to be careful with your data references without isolation though, because using non-scoped references without isolation can lead to very strange behavior when your data structures change or aren't exactly what you expected.

**Comment by BartVanBeurden** [comment]
The problem with this solution is that EventList is a generic standalone component. So I feel the `> content` partial is a much better fit than yielding because yield uses the "wrong" context. Also, I didn't know `{{ yield with this as event }}` is a thing, seems like something useful to add to the docs somewhere. It makes sense, but it's not something I would have thought of :)

So in other words the "proper" solution would be to pass the eventPartial in the GroupList as the > content partial of the inner EventList. I can make this work with the tips you gave but it still feels like a workaround.

**Comment by evs-chris** [comment]
I've found that with nesting components, you typically want to `yield` vs just using a plain partial. While the context feels wrong from the component side, it tends to be more what the user of the component generally expects. For instance with a `List` component: `<List>{{#partial item-extra}}<button on-click="@.doThing()">Do a thing</button>{{/partial}}</List>`, the user probably expects `doThing()` to be called on the instance hosting the `List` component, and it will if the `List` component uses `yield`. Not so with regular partials.

Passing aliases back into partials was actually added specifically for this type of scenario. If `doThing` needs to take the current item as a parameter, there's no way to access it from a `yield` unless it's passed in as an alias. It's a bit of compromise to strike a balance between the context you expect from either side without introducing a terribly confusing system wherein `yield` can switch contexts in certain circumstances. See [the yield docs](https://ractive.js.org/api/#yield) toward the bottom of the section 😁

**Comment by BartVanBeurden** [comment]
Closing this issue because it's been resolved.

Thanks!
