### ISSUE TITLE
Question regarding use of virtual with get

### ISSUE THREAD

**Issue by Noah-Vivial** [ractivejs/ractive#3114]
## Description:
My coworker and I have been banging my head against the wall trying to solve this problem all day. 
We have a issue setting a value for a fairly complex object. After the value is set, we attempt to get the value, and the old value is returned, unless we use the virtual option.
Here's an example of the calls I was making, this was in chrome console. 
```
> views.designerLeftMenu.set('themeData.designer.selection.page.head.styleVars.bg', 'test')
 >views.designerLeftMenu.get('themeData').designer.selection.page.head.styleVars.bg
>"rgba(31, 2, 2, 1)"
 >views.designerLeftMenu.get('themeData',{virtual:true}).designer.selection.page.head.styleVars.headerbannerbg
>"test"
```
In the snippet above, I would expect that the first get call to return 'test', however it returns 'rgba(31,2,2,1)'. 
In this this scenario we have three different views sharing the same object.

We're using version 0.9.2.

I'm trying to better understand the virtual option in order to troubleshoot the issue. As far as I know there are no linked objects, or computed values involved.

**Comment by kouts** [comment]
Does ```views.designerLeftMenu.get('themeData.designer.selection.page.head.styleVars.bg')``` work ok?

**Comment by evs-chris** [comment]
How do you have the views set up to share data? That would typically be handled by links/mappings.

**Comment by Noah-Vivial** [comment]
@kouts oddly enough, it does return the correct result, I wasn't expecting that. 

@evs-chris  we recently updated from an earlier version, .7.3.0. All the data is stored in a 'globalData' object that is passed into each ractive. There is no mapping, or linking, that I know of. 

I should add that when update is run `views.designerLeftMenu.update()`, that new value is gone. I can't access it any more via the vitrual option.

**Comment by evs-chris** [comment]
I'd say your best bet is probably to create a shared instance for the data e.g. `const shared = new Ractive({ data: { globalObject } })` and then `link` that to each instance rather than putting it in the data dictionary for each instance e.g. `new MyView({ on: { init() { this.link('globalObject', 'globalObject', { ractive: shared }); } } })`. With that, the object can't get out of sync on one of the instances because they all would be tracking the same model. I'm not sure if that would fit with your code.

Do you have an example fiddle or something similar that we could take a look at?

**Comment by giovannipiller** [comment]
@Noah-Vivial @evs-chris this might be related to #3116 (just opened)

**Comment by evs-chris** [comment]
Cleaning up old issues. If this is still an issue, please don't hesitate to reopen.
