### ISSUE TITLE
Template variables inside loops must be initialized

### ISSUE THREAD

**Issue by JoeImpact** [ractivejs/ractive#3173]
## Description:
This happens when using rvc, not sure if the same thing happens normally. Basically if you have a template with something like `{{#if foo}}asdf{{/if}}` in the template and don't have a `foo` param in the initial data object (`data: fn(){ return {foo: false} }`), "asdf" will only show (`this.set('foo', true)`) if that if statement isn't inside a loop. This may make sense if it said `{{.foo}}`, but there is some conflicting logic going on somewhere.

If this is intended, and there's a better way to do things that's fine, but a warning message would definitely help with debugging.

## Versions affected:
Noticed in all recent versions.

## Platforms affected:
Firefox, Chrome

## Reproduction:
Using rvc, load a component that looks like:
```
{{#if foo}}asdf{{/#if}}
{{#bars}}
{{#if foo}}fdsa{{/#if}}
{{/bars}}
<div on-click="@this.toggle('foo')"></div>
<script>
component.exports = {data: function(){ return {bars: [0, 1, 2]} }}
</script>
```
Only asdf will appear, fdfsa won't.

**Comment by ghost** [comment]
[Here's a reproduction](https://ractive.js.org/playground/#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoQN4BjAewDssACAYVIFsAHCtclKgXioCUliUAlgDc0AOjQAPdOQAmACmAAdcopTomydJCoADZatXBgAYgEAzKmdKkcOJBhlmjAenO39KQyYBGSGBncVT2CjUwsrGxwzGQwkFzccDy9nX39AgxQAHhlhKgoAWmIEAWIAaw5FEAABFDABDFEUUgBzZoQ0OQByCM6ASkqAPgAVFra0TOccoQGPHTwPGVQkbTMAV3J+AQo5XqUg1Rg0FFWYcipgVIxtAG0ABjwqAEYHgCYAXUSgz5x+lXI6JgsNgKKhoBDaGSkYireisFCibykGQATyoP1wQA). 

So what happened is that Ractive tries to resolve `foo` when rendering each item of `bars`. 

1. Ractive looks for the item's `foo` (`bar[n].foo`). Doesn't exist.
2. Ractive looks for `foo`. Doesn't exist.
3. Ractive did not find `foo`, it will resolve `foo` as `foo` (relative to root).

There's actually a setting for it, turned off by default, called [`warnAboutAmbiguity`](https://ractive.js.org/api/#warnaboutambiguity). Set it to `true`, and you get the log warning.

**Comment by JoeImpact** [comment]
in that case, is there a point for the {{.foo}} syntax?

**Comment by ghost** [comment]
Hmm... it _should_ lock down to the item's `foo` with the `.`. Looks like a bug to me.

**Comment by evs-chris** [comment]
I _think_ [I've got the example right](https://ractive.js.org/playground/#N4IgFiBcoE5SBTAJgcwSAvgGhAF3gDxICWAbgATFIC8AOngIYxq70B8BA9CaW7QHYEAzgGMYxAA65KNergQBbCQBsG8+uVwBPCQjp4EAD1ycwuBcvYCA9gFd5McgDNr16MADExJ89cYMDEJITsDAnN7+BABGMJx8-KEeUUxC-gK0uNHK1iIA1gCOttby8eS+buSJ3uX+TkhCDKHhTpExcQJlAHQuFVU+3X4YdQ1NERjRsaXknZ2cM5w9kJWe1fPzPbX1jWFjE+38ZQB+C65LfeTHG0NB281pB+RcUdl5hcUI8U3JMKkYAkRkcjWfgAWhEymIeX0AAFcGBiEJOrhrCgUMoEAAKADkPSxAEp2ODIbkuDx4lxROIpGwQDghPARMChNJHNRyPwEAB3cgAJQYIlwZExwHSuFwTBYSyxHnFzAQuCxWFF8iUqnkUplihUagQitFSDUDAxeMq5Bg8tsMAOwHI3yESwA2sBFpoYLYENhKp7gBgALrkDAAbgDAgweMDmCAA).

@fskreuz step 3 is actually, "oh, I couldn't find a `foo` anywhere, so I'ma assume you mean `foo` in the current context".

It _does_ lock the `{{.foo}}` refs down, as intended. What it _dosen't_ do is make a supposition about where you mean for `{{foo}}` to appear in your data some point in the future. That's where the `.foo` comes into play. For instance, if you take my example above and add a `foo: false` to the initial data, the ambiguous `{{foo}}` refs inside the loop will resolve to `~/foo`, which is also probably not what you want if there's ever a `bar.x.foo`.

So, any ref with a prefix is explicit, and any ref without a prefix that doesn't also immediately resolve in the current context is ambiguous. Ambiguous refs that don't find a place to bind bind in the immediate context, and since refs don't rebind on their own without the template re-rendering or being shuffled, there they sit.

**Comment by JoeImpact** [comment]
So the fix to this is actually to not ever use {{foo}} inside a loop to refer to something outside of the loop. But instead always use {{~/foo}}?

**Comment by JoeImpact** [comment]
I believe the ambiguity may be in Ractive itself, and might need making more strict.
For example if you have in the root of a template a variable called "color", and then you have a loop of items, of which one of the properties is "color", and for some reason an item doesn't have it set or it evaluates to false, it is going to inherit the color of the root, which may be entirely unrelated.

That would be if they wrote the template like:
```
{{#each items}}
Color: {{color}}
{{/each}}
```

Sadly enforcing the use of {{.color}} would be a pretty big breaking change. Maybe {{color}} should never evaluate to ~/color and a warning should be shown only if there is data in ~/color. That would however make {{.color}} deprecated.

**Comment by evs-chris** [comment]
Cleaning up old issues, but please don't hesitate to reopen if needed.
