### ISSUE TITLE
Root key path not available in non-isolated component without outer reference to context key path

### ISSUE THREAD

**Issue by p3k** [ractivejs/ractive#3177]
## Description:

If an object in a block of a non-isolated component has a property with the same name as a property in `data` (root) the template reference to this root property (using ~) will only be rendered when the context property is referenced before the block.

This might be related to (or the same issue as in) #3173 but as I only have a much simpler test case I think it is worth the extra record.

## Versions affected:

Ractive.js 1.0.0-edge

## Platforms affected:

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/63.0.3239.84 Chrome/63.0.3239.84 Safari/537.36

## Reproduction:

Run the following code in the script section of the Ractive playground:

```js
const Foo = Ractive.extend({
  isolated: false,
  warnAboutAmbiguity: true,
  template: `
    {{ #foo }}
      <div>bar in #foo block: {{ bar }}</div>
      <div>~/bar in #foo block: {{ ~/bar }}</div>
    {{ /foo }}
  `
});

Ractive({
  el: 'body',
  data: {
    bar: 'root',
    foo: [{bar: 'foo'}],
  },
  components: { Foo },
  template: '<Foo/>'
});
```
The expected output:

```
bar in #foo block: foo
~/bar in #foo block: root
```

The actual output (note the missing output of `root` in the second line):

```
bar in #foo block: foo
~/bar in #foo block:
```

(I don’t get any ambiguity warning in the console.)

However, if I reference the context key path before the block the code works as expected:

```js
  template: `
    <div>bar before #foo block: {{ bar }}</div>
    {{ #foo }}
      <div>bar in #foo block: {{ bar }}</div>
      <div>~/bar in #foo block: {{ ~/bar }}</div>
    {{ /foo }}
  `
```

Output:

```
bar before #foo block: root
bar in #foo block: foo
~/bar in #foo block: root
```

Same goes (though with expectably different output) if I only change the name of the `foo.bar` property:

```js
  template: `
    {{ #foo }}
      <div>bar in #foo block: {{ bar }}</div>
      <div>~/bar in #foo block: {{ ~/bar }}</div>
    {{ /foo }}
  `

  data: {
    bar: 'root',
    foo: [{nobar: 'foo'}],
  }
```

Output:

```
bar in #foo block: root
~/bar in #foo block: root
```

**Comment by evs-chris** [comment]
All of those results are actually correct and also why we strongly recommend component isolation and unambiguous references 😄

For the first block, `~/` always refers to the data root of the current instance, which is the `Foo` component where `~/bar` is referenced. Since there is no `bar` in the `Foo` component data, you get no output there. Any prefixed keypath is never ambiguous because they all can only point to exactly one place in the data.

If you reference it before that point as `{{bar}}` what actually happens is:
1. the current context (root of the data in this case) gets checked for a `bar` property and none is found
2. the resolution process sees that the current instance isn't isolated, so it jumps to the context in the template containing the component (it also makes a note that an implicit binding needs to be made)
3. the current context _does_ have a `bar` property, so the reference is resolved
4. since an implicit mapping needs to be made, `bar` in the parent instance will be linked to `bar` in the `Foo` instance, which also means that `~/bar` will now exist in the `Foo` instance (as if you used `<Foo bind-bar />` in the template).

There is not currently a way to explicitly reference root data with a prefix. If you need to do that, you can do so with `@.root.data.bar`, which will also circumvent isolation in an isolated component. Again, that definitely not a recommended practice.

The recommended practice for this sort of thing would be to have an explicit mapping for the root data if that's what you need to access e.g. `<Foo root="{{~/}}" />` and then use `~/root.bar` in the `Foo` template.

[Here's a playground](https://ractive.js.org/playground/#N4IgFiBcoE5SBTAJgcwSAvgGhAF3gDxICWAbgATFIC8AOngIYxq70B8BA9CaWyDgGd4AYwD2AOwG5yAMVGjy1cgCUGw3GQQA6BAA9cCcUgAUwWjFrjylAaIA2DA0kjkAZgzsCEWc5esB3JnEAQQAjUQBXXGCAW1DiFAjiXABPF1wYCO9fK3IDGIAHBwMXAAMc62tgYHIAYld5cgwMCsrrIjI2UKZKK3rG0LtRYQBrF2rybpgmjC4eNla2jt4AP04p3rqGhUHhsfIJtY3muc7FyuW2AAEtGHlcLSRHBi0N4j7tyaHR8eAbu9EDyeuBeUxO3DOFlyS3mawBDzeHwG3321Th91eTHB83OE04n2arXKUIwAEoANw5HKqdSaUytBB2FwAcnCSBSzJ8UOswIY43OUxZ8M5522LgA2sBBeRmdtmRgALpcvxNZW5MSFCSGXACcayRrYVr5IqOBAsghyBTwuggNGcQkgcicNgi7l5JgsFm1EHMBC4Zk5MnkzBAA) with the explicit path circumventing isolation and also using an explicitly mapped root.

**Comment by p3k** [comment]
Thanks for the reply, @evs-chris – though I am still confused.

Are you basically saying that one and the same reference `{{ ~/bar }}` in one and the same block is going to render a value of one and the same data object, only depending whether there is another reference called `{{ bar }}` present outside the block? And this is by design?

> All of those results are actually correct and also why we strongly recommend component isolation and unambiguous references :smile:

Sure, and I assume this is good advice. However, if the feature is available, I think it should work in a manner that one could consider predictable – which I find it is not regarding this issue, to be honest.

**Comment by evs-chris** [comment]
It is indeed by design, though it's also strongly discouraged - and confusion and unpredictability are exactly why it's discouraged. Isolation blocks convenient access to parent data, but it also prevents weird stuff like this and discourages depending on having the component be rendered in a very specific context.

When you reference `bar` in a non-isolated component that doesn't have a `bar` anywhere in the component's data, it creates an implicit mapping, as if you did this: `<component bar="{{bar}}" />`. At that point, `bar` is available in both the component template and the component data, so if you `this.get('bar')` from an event handler or computation in the component, you won't get different results than if you explicitly passed `bar` as an arg to an event or used `bar` in an expression in the template.

Also, calling `component.set('bar', 42)` will set `bar` at the component root. Without the mapping, that will lead to a new `bar` value that future resolution will use rather than finding the parent `bar`.

So the short answer is: isolation + ambiguous references are complicated and their interactions rarely match everyone's assumptions about how they work.

**Comment by p3k** [comment]
> isolation + ambiguous references are complicated and their interactions rarely match everyone's assumptions about how they work.

OK that makes it pretty clear. Overall, it sounds like this “feature” should rather not be used at all (anymore): 

What do you think about the following suggestions then?

1. Mark the `isolated` property in the code as deprecated (maybe even remove it in version 1.0?)
1. Remove any reference to the `isolated` property from the docs ([1][1], [2][2]) immediately

[1]: https://ractive.js.org/api/#isolated
[2]: https://ractive.js.org/concepts/#isolation

**Comment by kouts** [comment]
```isolated: false``` comes in very handy for prototypes and mockups, but even in real implementation situations when you know that your component will only be used in a specific context.
That said, by default is set to true, so I think this is fine.
This also is a feature that comes a long way back from previous versions of Ractive so that would be a big breaking change.
For me it (and probably others I assume?) would probably make it a "show stopper", because I have a huge codebase that then needs to be refactored and retested.

**Comment by dagnelies** [comment]
Same opinion from me, `isolated:true` is a good default and should rarely be changed. However, they should not be deprecated IMHO, there are some rare special cases where it can turn out to be very useful. To be used with caution though.

**Comment by kouts** [comment]
@dagnelies you mean "```isolated:true``` is a good default" right?

**Comment by dagnelies** [comment]
Here is an example:

https://dagnelies.github.io/ractive-split/

Basically, this is a component which inserts splitting bars between it's contained divs. However, if it was `isolated:true`, it would block all data to be forwarded inside, which is obviously undesired.

@kouts : yes, indeed, I meant `isolated:true`. Thanks for noticing 😛

**Comment by evs-chris** [comment]
Cleaning up old issues, but please don't hesitate to reopen if needed.
