### ISSUE TITLE
Mustache comments evaluate to boolean value

### ISSUE THREAD

**Issue by p3k** [ractivejs/ractive#3179]
## Description:

From the [documentation](https://ractive.js.org/api/#comments):

> {{! }} defines a template comment. Comments are ignored by the parser and never make it to the AST.

In fact, a mustache like e.g. {{! bar }} is evaluated to a boolean value and turned into output like `true` or `false`

## Versions affected:

Ractive.js 1.0.0-edge

## Platforms affected:

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/63.0.3239.84 Chrome/63.0.3239.84 Safari/537.36

## Reproduction:

```
Ractive({
  el: 'body',
  template: 'foo {{! bar }}'
});
```

Expected output:

```
foo
```

Actual output:

```
foo true
```

**Comment by MartinKolarik** [comment]
This isn't really a bug. Ractive supports JS expressions and `{{! bar }}` is a valid JS expression (`!bar`, don't let the spacing confuse you) - it can't do anything better than try to guess what you meant, and in this case the guess is you wanted it to evaluate as an expression.

The only thing we can do is clarify this in the docs. It *would* be interpreted as a comment, if it *weren't* a valid JS expression, e.g. `{{! bar baz }}`

**Comment by p3k** [comment]
Then may I question the choice of `!` for the comment symbol?

It makes me uneasy when I have to be aware of such minimal distinction, `{{! FIXME }}` evaluating to true and `{{! FIXME: }}` not…

**Comment by MartinKolarik** [comment]
>Then may I question the choice of ! for the comment symbol?

Absolutely. The problem here is that Ractive started as a mostly mustache compatible implementation, and mustache uses `{{! ... }}` for comments. Then support for JS expressions was added, which created this problem.

Personally, I always use regular HTML comments, and don't see much value in supporting the `{{! }}` version, other than that we *somewhat* support the mustache standard.

**Comment by evs-chris** [comment]
You can make sure that a `{{!` is a comment by throwing a `#` in there too e.g. `{{!# FIXME }}`, which is probably something we should suggest in the docs. An additional problem with mustache comments is that people often want to use them as a block comment to temporarily remove part of a template, which can't work because comments are not block-level nodes.

The other thing I never remember is supported is `{{& basically.a.triple }}`.

**Comment by ghost** [comment]
Maybe we should be strict in the spacing of the doodads and section syntax, in that there should be no space between `{{` and the glyph (i.e. `{{&`, `{{>`, `{{!` and require at least one space around the expression/reference.

A Django dev once warned me about spacing inconsistencies when he thought the component file was a Django template, not a Ractive component. "It should have spaces around the reference for readability" or somewhere along those lines. Maybe we can enforce something like this.

**Comment by p3k** [comment]
Thanks for the clarification. I understand the compatibility issue with Mustache.

A heads-up and suggestion in the docs to use something like `{{#! FIXME }}`, as mentioned by @evs-chris,  would be a good thing, though.
