### ISSUE TITLE
Bump dependencies

### ISSUE THREAD

**Issue by ghost** [ractivejs/ractive#3187]
https://david-dm.org/RactiveJS/Ractive?type=dev

Would like to keep this badge green and secure. Just a heads up, Rollup 0.55 has some significant changes that might need tinkering of the build script.

**Comment by evs-chris** [comment]
Since there's no stable electron, the devDeps don't really do anything to the code to speak of, and I think knowing that there are _no_ deps rather than secure devDeps is probably more important, I moved the daviddm badge to deps instead :)

I think we should probably wait a bit before pulling in rollup 0.55+.
