### ISSUE TITLE
partials doesn't show up in {{>context}}

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#3192]
Here the small snippet:

		var ractive = new Ractive({
			el: '#target',
			template: 'Outside: {{>foo}} - <mycomp>Inside: {{>foo}}</mycomp>',
			partials: {
			    foo: 'fooooooo'
			},
			components: {
			    mycomp: Ractive.extend({template: '<i>{{>content}}</i>'})
			}
		});

Actual output:

     Outside: fooooooo - Inside: 

Expected output:

     Outside: fooooooo - Inside: fooooooo

**Comment by ghost** [comment]
This sounds familiar. Off the top of my head, since it uses `{{> content }}`, `{{> foo }}` is being resolved on the inside the child component, not the parent. https://ractive.js.org/api/#content

@evs-chris might know more

**Comment by PaulMaly** [comment]
Seems you should use ``{{yield}}`` instead of ``{{>content}}``.

**Comment by evs-chris** [comment]
I can confirm that `{{>content}}` is not supposed to find partials on the parent unless the component is `isolated: false`. If you need stuff from the parent, `{{yield}}` is indeed the way if you don't want to break isolation.

It _may_ make sense to have a way to pass a partial into a component from the parent via template without using `{{#partial}}`. I haven't run across a scenario where `{{yield}}` doesn't work yet, though.

**Comment by dagnelies** [comment]
I'm aware of the difference between `{{>content}}` and `{{yield}}`. Both have their use cases. To illustrate my point better, I provided a small example:

https://ractive.js.org/playground/#N4IgFiBcoE5SBTAJgcwSAvgGhAF3gDxICWAbgATFIC8AOngIYxq70B8BA9CaW7QHYCCAZwDGMYgAdclGvVwIAtpIA2DBfXK4AnpIR08CAB65OMBqNxkE7AbVwEwAZjYBCd+QAqYYsMp+GcmFiZRViADNiZHJjBlCELHJ+AHsZQIB3ZJgAa2J+FHIkJWTyZPDyBn4KgFdcMuIVFXJ3Vy5nPkFBB0k2AHUwBCrcAcKYZMkkZPSq4gVFPzKtEYZa+sagsCm-aslE9LB1LRKSYVUGbXJwrJiLMEo5jeTqlSRyACMEclFq4TrFYgAXgw3ioEAA6Lg9OwOFZ1SLrWZKYQGYDAH4IGDCDAYWxdewEN5sVFUbFcQnkAC05FR-DiCGxlPIBGIbAAFKilAwGtiAJRcFnQriwtYqDr2QU9ADKeVEn2E1VEd2F8JUARgn3Rrzy5EUlQuZ1lwkSoNwAHI-JIxqQqJ9Zn5RMl+AonRULUwrAwVGDyAAhaqKRQYxLq+UqGS+GLKHQQzhQroEZUNJqI+YotHCDFYnEgMWsXCotjomAAfTeDGCoizgs4icauehqIAxJJ3cRPeQi6Xy8RK9jofjCcSkKTOOSqTS6Qyqcy2RzddyMHzOAKuqjY63PX3+FwxBJpGwQDhhPAAEoWKykcEO5SOwa4YQAbVNtZUpoAuuRqOQz5ZrGDjM6SDstCcxnAokDkAABv2Dh5JItTkJw9YOM8yH2E2CC3PcSJbuKeb4mEQQ6KCBhlqI2QoGM1T8EgFIOioWSQI2RThAA3LqzB5JAACskhGKxuJ4UJ+bAGwDpOneuH4XmXBhGhImcJhipSfinCodC5BQQIi52J0pBMOQ5i-pen5JAg6Tfue1jAV0uBMCwEGmnZzAIGaWACJpoFqOB5Cmo2XnqAgpruVUhTqAwEHAB55D2EWwgQQ+UWhXhVAQQAjBlIWaXhtKBo5ACCYSysF0V4ZyDSOZ6PYIAAApkNEYmCag0aapW4Ng1JtZpqXkAATP1WUxXmuUII5PrJG8JXJXm5UqI5bwTTVsTxGC16tdNHVJdlMiyBBTj7YNOV0o5ADCBwwGEQWHTN85zb5ipMJdNWVGgqpgjK63bRgb7RTi-CLqxmBAA

IMHO isolated should solely apply to the data, not the other stuff. Or at least not the partials. From a ractive user perspective, I find it rather counter-intuitive that the second example doesn't work.

**Comment by ghost** [comment]
I think isolated actually affects more than just data. I think it also does the other registries (i.e. components, adaptors, etc.). It's the general plug for everything trying to creep out of the current component.

For the second example, `{{#partial }}` is defined on the outer template, equivalent to putting `partials` on the init options for that instance. The boundary starts at `<autofill>`. Again, this is a `{{yield}}` use case since you want outer-context stuff.

The context difference between `{{> content }}` and `{{ yield }}` should explicitly be different. Blurring the lines would only cause confusion. `{{ yield }}` is already starting to blur the lines with [aliasing](https://ractive.js.org/api/#yield) allowing it to access data passed _into_ the component, while still have everything from the outer context. [Here's an example](https://ractive.js.org/playground/#N4IgFiBcoE5SBTAJgcwSAvgGhAF3gDxICWAbgATFIC8AOngIYxq70B8BA9CaW7QHYCCAZwDGMYgAdclGvVwIAtpIA2DBfXK4AnpIR08CAB65OMBqNxkE7AbVwEwAZjYBCd+QAqYYsMp+GcmFiZRViADNiZHJjBlCELHJ+AHsZQIB3ZJgAa2J+FHIkJWTyZPDyBn4KgFdcMuIVFXJ3Vy5nPkFBB0k2AHUwBCrcAcKYZMkkZPSq4gVFPzKtEYZa+sagsCm-aslE9LB1LRKSYVUGbXJwrJiLMEo5jeTqlSRyACMEclFq4TrFYgAXgw3ioEAA6Lg9OwOFZ1SLrWZKYQGYDAH4IGDCDAYWxdewEN5sVGIxRgqjYriE8gAWnIxLmYP4cQQ2Jp5AIxDYAAp6UowUoGA1sQBKLic6FcWFrFQdewSnoAZTyok+wmqojuUvhKgCME+6NeeXIikqFzOKuEiVBuAA5H5JGNSFRPrM-KJkvwFJ6KvamFYGCoweQAELVRSKDGJPVqlQyXwxZQ6CGcKFdAhahpNEnI+io9GY7G4uUOVzU2nDePu5QewYydF+bRRF6JSqvYYYhBXPVBBAIbbCDEAfTeDGCoj8ACsfjJIvxPmXZaxcKi2Pnh6PiOPC2nOBnGovoaiAMSSP3EAPkNcjsdYnFdcjs0u0o0DPV7T4HUifCwWvx1JbfmEo73EoNLUgeDiErypLkhglJsGy0GMsyrK0hy3JIQKQoYKKnDil0qIpmeAbblwYgSNIbAgDgwjwAAShYVhfmCVaSDWnrCAA2jae4qDaAC65DUOQDGWNY-ImIMSA8tCcxnAokDkAABtC+J5JItTkJwEEEM8EH2MeCC3CB8zbsWxYEGEQQ6KCBgjqI2QoGM1T8Eg1LuioWSQEeRThAA3CazB5JAACskhGH5RZLuZy7AI2CAvOQ6SzHcQbASS5BmdFS5cGE+mxZwRkall+KcHp0IPip-A4XYnSkEw5DmGJX5CUkCDpCJjHWDJXS4EwLCKTafXMAgtpYAID5yWoCnkDaR5TeoCA2uNVSFOoDCKcAE3kPY+bCIpnFbatxZUIpACMF0rQ+xZMhGg0AIJhCqy3bcWWEqINAabggAACmSuRiYJqK5Nqvbg2B0mDD6neQABM8NXTtS63Qgg3BskbwvcdS7vYNbwYz9sTxCxySKKD2MQ0d10yLIilOPTiM3cyg0AMIHDAYRLYzOMmg0g0akwnM-ZUaA6mS-CiOT1MYPx213jhfmYEAA), and I _think_ this is what you want.

**Comment by dagnelies** [comment]
Thanks for pointing that out. You are right. I was stuck in old versions of ractive's `{{yield}}` in my mind and wasn't aware of this "aliasing". It's a quite an advanced but nifty feature
