### ISSUE TITLE
class-* does not work as class="{{#if ... }}" does

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3195]
[Playground](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAF3iDgM7wBKAhgMa4CWAbggHSUD2AtgA4sB2C3uRRgHcaqBLgAEAXgkVq9JggAeuPkgAUwADrctuVZwA25VZAkADHXr0AeIh3LcJlY0SJStIYMBfk3GDE8APhsAIyDvINZ+PlwAmwB6cMT7RyCrXD1LbgwASituXiFZKloGTQyEQzMAclCWJABPGqwMgw5jUwsM2xZDdN1MoZtDGgHrIb0AFUaOBAkidnEwGm4UCTAEGAQzG1WOAFdJOnJDA4QPL2AAMxYWAM8JBPHJ3ETRl4mRsZ7XgFElHNqGZyBJtkgJPUYEgthJyDAWAduBCEFQwBJboZDCwRGsJEIWNCiL9bAkPiS3uTBhM9AAFBGhQwINhmTwAOQA8hIAEIc0gAET+pAkAAkhX8APyPERYiTcFiSNCSUFQmEwCnvH7Ut4JPqfN6pJy+NwAWiUl1uLGCmyxLBSDm4+psIjEkmNRDNFruwU5PL5guFYtIksSLqVTrD4mcrncnm8AGJLQElN4Eg8QEFcJttgAmUOicMZcytHK5QggSjwRhKCTaQaqrZmACMHBri1GEPBAG4dBhMEA)

**Comment by evs-chris** [comment]
It can't really, because `class-*` gets special handling (directive) and can only appear on elements. If you need to pass through class and style directives, you have to [yield the `extra-attributes`](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAF3iDgM7wBKAhgMa4CWAbggHSUD2AtgA4sB2C3uRRgHcaqBLgAEAXgkVq9JggAeuPkgAUwADrctuVZwA25VZAkADHXr0AeIh3LcJlY0SJStIYMBfk3GDE8JbwBPGgRDJAllXBhyAFoTWJoAIwBXVSIAgD4bFOzvbNZ+PlwAmwB6fMr7R2yrXD1zLAakmFSMhCIzAG0AXR0MAEorbl4hWSpaBk0GiLMAchSWJBCFlt19BCMTBDNLTdsWQ3rDxtwbQxpT63O9ABUQjgQJInZxMBpuFAkwBBg9hIbF8OBkJHRyIY0ggPF5gAAzFgsAJBCo3O4XCpXdG3S7XBq3PQAUSUz2oZnIEgBUWWMCQ-wk5BgLDS3CiCCoYAkiMMhhYIm+EiELDpRAJ50q2PFtilZ1uAAVmSlDNszJ4AHIAeQkACFNaQACJE0gSAASxqJAH4giJeRJuCxJGhJJTafSYNLMbLcRVjjiLrUnL43PElLDESxPNk-ryWDUHNx-TYRGJJMGiKHw0io1rdfqjSbzaQrZUU86k2XxM5XO5PN4AMQRgJKbwVFEgbK4P4AgBMpdE5YazUGQ0IIEo8EYSmCDTd-zMAEYONO3lcotSANyDTBAA) partial on the element in the component template on which you want them to appear.

When you pass a `class-x="foo"` into a component, what you end up with is a property named `class-x` in the root data of the component.

**Comment by ceremcem** [comment]
I had tried the `extra-attributes` approach but apparently the problem was a missing `attributes: []` item. Two birds with one stone :) Thank you
