### ISSUE TITLE
Is onrender fired before rendered to the DOM?

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3198]
## Description:

After upgrading from 1.0.0-build-130 (from?) to 0.9.13 I noticed the following error:

```
Uncaught Error: Cannot call ractive.find('.ui.dropdown') unless instance is rendered to the DOM
    at Child.Ractive$find [as find] (vendor.js:13696)
    at Child.onrender (<anonymous>:1909:17)
    at Hook.fire (vendor.js:13508)
    at Array.<anonymous> (vendor.js:27253)
    at flushChanges (vendor.js:12464)
    at Object.end (vendor.js:12361)
    at set (vendor.js:13203)
    at Child.Ractive$set [as set] (vendor.js:27485)
    at Child.toggleEditing (<anonymous>:1029:21)
    at Child.caller (vendor.js:15251)
```

...where the `ractive.find('.ui.dropdown')` is called inside `onrender:`: 

![image](https://user-images.githubusercontent.com/6639874/36627553-7f8ee14e-1955-11e8-860d-24f33c183dc1.png)

## Versions affected:

0.9.13

**Comment by ghost** [comment]
IIRC, `onrender` happens after the component's template has been rendered on DOM but before animations start. So if `.ui.dropdown` is on that component's template, it should be there.

Hard to tell with the stack trace and screenshot alone tho 🤔 I'll ask a few questions 😁 

- Where is `.ui.dropdown` rendered?
- Does it belong to this component or another component?
- Is it bound by some conditional/async section?
- Can I haz playground? 😁

**Comment by ceremcem** [comment]
1. `.ui.dropdown` is in the component's template 
2. Not sure if I could understand this question correctly. [This dropdown component](https://github.com/aktos-io/scada.js/tree/ff7bd6f6c95646e53c050b82ba916da092d342c5/components/dropdown) is used in another component (and they are used just another component)
3. Yes, it is bound by a conditional
4. Nope :D At least not so quickly. Really, I wanted to prepare some (as usual), but it's a huge application and I need to spare some amount of time to strip down the problem. 

If this issue doesn't flash some lights instantly, let's wait a little bit to see if it occurs again, so that I can create a reproduction example.

**Comment by evs-chris** [comment]
edge has wandered a pretty good ways away from 0.9.13, though at least [onrender shouldn't have changed](https://ractive.js.org/playground/#N4IgFiBcoE5SAGAdAThAXwDQgC7wDwAmAlgG4AExhAvADq4CGMA5gKY70B8+A9CaZ1oA7YfgDOAYxjEADjnI4AnjNZ1crAB44eMBhJxlW9SjXo5WAWxkAbBua7DaOYMADExAGbkPAex-p0fAkrch5OFx5PANEeSWk5QREhcSlZeSUVNXMtHT0DUiMQEzVgmQcRHCIyTjBWa2sfXn5E3ji0zhBsMXgJHyExeVLyanIAJTzDJE1zIUIACmBHHHMrW3NIcgByV1LNzCW+mFZZ1hg5gEpyRYqnXv6fa1YkBuY5nDBiMSQPYlm5zf4m3OSF+QlOAAkACoAWQAMucluhhOgEUk7gNyDBhuQwQB3MYTAoLJY4JhsHAbbakljsPYkyw2OysSmuFaM8x0iq9Kx9Y44MQbYDkIZIoQoxxCGBIHA+ZjMR7-Xw+IEYIA). My first guess is that something is causing the component to render and immediately unrender so that the hook is scheduled to fire at the end of the runloop, but the component is no longer rendered at that point due to some observer or computation being overwritten during the runloop. Does it work with 0.9.12 or 0.9.11?

**Comment by ceremcem** [comment]
I don't encounter the problem for a while, it might be owing the fact that I'm following the `edge` build. Better to close the issue. 

@evs-chris Do you want me to investigate if it works with 0.9.12 or 0.9.11? (or it can be reproduced when I switch back to 0.9.13 while my app has evolved?)

**Comment by evs-chris** [comment]
Looking at the render detection for the `find` method, it's checking for the presence of `el`, which may not be the best way to handle that as evidenced by #3146. This may be a case where the formalized 'is this instance rendered' property would help, and I thought we already had one in place. It seems we don't though.

At any rate, a repro I could poke at to distill a test case would be very nice :smile:. Any version that it fails on would work.

**Comment by evs-chris** [comment]
As of 0.10.1, there's a `ractive.rendered` that lets you know explicitly whether the instance is rendered, and the `find`-type methods use it in their logic, so you should be good checking there. I'm going to close this, but if it needs to be reopened, please don't hesitate to do so.
