### ISSUE TITLE
{{#with}} alias edge case – create an alias of a function output with the same name of the function

### ISSUE THREAD

**Issue by marcalexiei** [ractivejs/ractive#3209]
## Description:
In changing `{{#with}}` syntax from:
```{{#with { prop: calculateProp() } }}```
to
```{{#with calculateProp() as prop}}```

However I've encountered a inconsistency between Ractive versions; consider this code:
```javascript
{{#with foo() as foo}}
  {{foo}}
{{/with}}
```

- On `0.9.x` the value of `{{foo}}` is the `toString` of the function.
- On `edge` the value is the output of the function.

Which one is the correct behaviour (if there is one :D)?
Maybe a warning should inform that you are creating an alias that is "clashing" with another property?

## Versions affected:
- 0.9.x
- edge

## Platforms affected:
All

## Reproduction:
https://jsfiddle.net/qnjtgtsj/

```javascript
const r = window.r = new Ractive({
  el: '#main',
  template: `
  <h1>Width alias edge case</h1>
  
  {{#with foo() as foo}}
  	<h2>Inside with</h2>
  	{{foo}}
  {{/with}}
  <hr>
	<h2>Out</h2>
  {{foo}}
  `,
  data() {
    return {
      foo() {
        return 'bar'
      },
    };
  },
});
```

**Comment by evs-chris** [comment]
This is an intentional breaking change for 0.10 because - you can still access the `foo` in the data with `.foo`, but there's no way to say "use the alias". If there's an alias available _before_ a context, it will use the alias.

In the example, starting from the `{{foo}}` interpolator, there is no immediate context, so stepping to the owner (the alias block), there _is_ a `foo` alias available, so that's what resolves.

In 0.9, what happens is it starts with the `{{foo}}` block and tries to resolve through all of the contexts first, where it finds `foo` in the root of the data from the root fragment. If it didn't find a `foo` in a context, it would then start with the `{{foo}}` again, look through the template, and find the `foo` alias.

That's arguably more reasonable behavior, right? - resolving to the nearest name from data _or_ template, rather than going to root on data first and template second.

**Comment by marcalexiei** [comment]
Yes, I think that it is the most reasonable approach.

Thanks for the clarification!
