### ISSUE TITLE
Proposal: @tmp special reference

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3211]
## Description:

Useful when we need to use some temporary values in the loops and we don't want to contaminate the original JSON. 

Here is contaminated version (which we don't want): [Playground](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoQN4AlJAYxQEsA3NAOjIHsBbAB0YDs0OUM6kMGSgHMOAAgC8Y0hRr00AD3QcAJgApgAHQ6aUnGNxVoYkMQDMArh1mc1ASi06UulGEp8MaFGoDkCNGYoPnhiru50wl6+MCJgQXZ22rr4YkkoKqhIppbWVLYOaboGKBYw4o66lSj+gaYcFggIIYXOKDHCcXUNCC04aX0cOIkcXADu0uRUtBppaAimPgBGjCoAnsFp6GzI6KYABi3AwADErEgwVEgIYssKAAowjKzGVJg4A1UAPA0AfC26R2OaHIYBujAUbw+rV0nwQlD+TiqMIEQlEYhqKAkmhARwYYDQZAA1mgVO9sWJ2nEsTjgG0LGgySAxAB6H6pRHQlCfSgcVgWFChVbPalkfFE27k0UE4kqam4qVEkmM0KUapoakYMCMUbMtxGcms-6tQGUMxiPHSpVQpGtUaUFSuUy4u0OsDvEL42IoJ3AOiejooMkcm0ms10W5Bm0h4A-W4PJ4vSiYc23MQCMEQjCRzlVI7M03Z6NzTyFnMoABUlbETEaSFYnhUYkr5aNAOA+bMpZhzLhCOjzOBotLn2Zv0O7bOF0oVy7HKOsfB8eeU8hLU+YAATD8ACIWNhiNSaxgNRscRgCxZoaucFBIZg81Akuwjzd91qfVgGH5HABSAGUAHkADk6CwGIOGEU1VjUW5MBCepGhCDc7HeEdPzQN89jwNIMlvJ0WlgjBTAAbSNYAXUdMQAEYPTQL1TA3EJbkgUjg05cj7UoqiaLEf1OjEDcN3wVtjQosBTAAZgk2j6LEAAWOSmPBEiRJDMTTG4ni+O9QShNU1oAF1rU5IzsLYjjXUkmSA1MOTjN0Az+m0IZcCAA) 

Here is current solution/workaround: [Playground](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoQN4AlJAYxQEsA3NAOjIHsBbAB0YDs0OUM6kMGSgHMOAAgC8Y0hRr00AD3QcAJgApgAHQ6aUnGNxVoYkMQDMArh1mc1ASi06UulGEp8MaFGoDkCNGYoPnhiru50wl6+MCJgQXZ22rr4YkkoKqhIppbWVLYOaboGKBYw4o66lSj+gaYcFggIIYXOKDHCcXUNCC04aX0cOIkcXADu0uRUtBppaAimPgBGjCoAnsFp6GzI6KYABi3AwADErEgwVEgIYssKAAowjKzGVJg4A1UAPA0AfC26R2OaHIYBujAUbw+rV0nwQlD+TiqMIEQlEYhqKAkmhARwAfgB6ADaPhQbB8YgA1GIAAIAazQqzOrkpYh8DDAaDI9JUPgAuu9sWJ2nEsTjgG0LGgBSAxPifqlEdCUJ9KBxWBYUKFGWhRWQOVzboK9ZzuaK8USSWSWXSGUzQVS2cauWgefy+jKqNUddiMGBGKN8W4jIK5f9WoDKGYxATiaTWOSqTbGah7az2SaXXyBYqkShRpQVK5TEc6PnC2B3iEObEUMXgHRqx0UNnc1UI1G6LcW0rc0cfrcHk8XpRMGJO+CxAIwRCMN3WygjvjI3OlUc5p4V7mAFQ7sRMRpIVieFRiHdbsMA4BLsyb5X4uEI3tX4F6leffG-Q5Xs4XShXTeKn2A6PM8v6Qi0nxgAATD8AAiFhsGIai+owDQnhwjCaosaB7pwKBIMwqqoC6djvtBj6tJ8rAGD8RwAFIAMoAPIAHJ0FgMQcMIkarGotyYCE9SNCEUF2O877UWgFF7HgaQZPhxYtPxGCmISYbAGWRZiAAjFWaA1qYUEhLckBqTmq6aWApjabpYiNp0YhQVB+AXuGlmmAAzB5ekGWIAAsfnGeCqmub27k6TZPlNpATnOaFrT8q5-KyeZGkFlp3l2fp0X+VCVS8v02hDLgQA)

Desired usage would be: 

```html 
<input type="checkbox" checked="{{@tmp.show}}" title="show/hide" />
{{#if @tmp.show}}
  ...
{{else}}
  *** collapsed ***
{{/if}}
```

**Comment by evs-chris** [comment]
How's about a [`@local` alias](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoQN4AlJAYxQEsA3NAOjIHsBbAB0YDs0OUM6kMGSgHMOAAgC8Y0hRr00AD3QcAJgApgAHQ6aUnGNxVoYkMQDMArh1mc1ASi06UulGEp8MaFGoDkCNGYoPnhiru50wl6+MCJgQXZ22rr4YkkoKqhIppbWVLYOaboGKBYw4o66lSj+gaYcFggIIYXOKDHCcXUNCC04aX0cOIkcXADu0uRUtBppaAimPgBGjCoAnsFp6GzI6KYABi3AwADErEgwVEgIYssKAAowjKzGVJg4A1UAPA0AfC26R2OaHIYBujAUbxwgNGlFcYgAAghGGQrmIBKE2O9-ihPghKH8nFVdJ8BEJRGIaigJJoQEcUGwGGA0GQANZoFRYkBidpxam04BtCxoTliAD0P1ShNaxMoHFYFhQoVWzz5ZCZrNuNLEauZbJUfLpDJ1rPZIqo1TQfIwYEYo1FbiMWvF2IBJ0oZgxrEZutNH2l-phKlcpiOdEDrneISZsRQIeAdGjHRQWKlRJQgPdYjotxTabTRx+tweTxelEwWduaIwYIhGFz-qqR1F7vr+eAc08rYbKAAVH3tYxGkhWJ4VGI+z2XengM2zF3iaK8QS26KYRGoTPgWqu59Rb9DjOzhdKFd51KC0XHs9j5CWp8wAAmH4AEQsbDEamtjAaY44jEVixoAOPBIMwsqoOydi7o+y6tJ8rAGD8RwAFIAMoAPIAHJ0FgMQcMI7qrGotyYCE9SNCED52O8u4IWgsF7HgaQZCgWRiBUrQkRgpgANrYsA4ZgKYACMUZoDGpgPiEtyQHxqb+gJlBBkJYjCaJYiJp0YgPg++BTgCgmmAAzEZYkSWIAAsFnSeCvH6QphmqWpZlJpAOm6fZugALp+mmPlMfJinKcZLlaRZvmtF5-TaEMuBAA)? There may be room to squish that into `{{#each boxes, @local as tmp}}` for 0.10, because there's some alias-y work in iterative sections there.

**Comment by ceremcem** [comment]
Even better! :tada:
