### ISSUE TITLE
veryyyy borderline bug

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#3217]
Hi,

I encountered a small bug in a very borderline use case:

https://ractive.js.org/playground/#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gG4CGMABDEQMYAuAlgQqQLykB2CA7qQEpV0MAKYAB1Ww6uPHUSaapFIByAEYB7JAE8FWUZInVqCALYAHADZED8gAY69ugMJgirNKVpzSAHlqtjAV2pSanVjBCZhEFY-QyUEGAjSYlM-MIjgYAAzFRUMDASAegA+UnSsnIxSeXTg0JUMgTKASlyvJRgi211xR2dXd3lvXwCS4ABiBCowUgtqGFolAIRcFvSAAQBrBHVc8JB0gDpchPT8icowFqSU3fSlEiOQUiKRu5gWquAahDqBV+a8sR2ahWbSA3RICxEKqdIFleQAVlBXT0rwRSKB4hmcwWBlw0LBGP0IQQ8gUURicQUMN0AORAIwjQA3CAcNR4JggA

It's rather contrived though. If it's an easy fix, great, if it requires too much investigation, I suggest just dropping it under the rug. :wink:  Funnily enough, using `<input {{attr}}="{{val}}"` produces a template error, but not if it's within a loop :stuck_out_tongue:

**Comment by evs-chris** [comment]
This is an interesting case indeed. It took me a bit to pin down exactly what's happening, but I think I've got it now.

This isn't a bug so much as a limitation in how input bindings work. Ractive only knows what kind of binding to select when there's a knowable `type` attribute available, which it _looks_ like there is, but anything that's not a literal attribute `name="value"`, like an each block with a couple of interpolators with a string in the middle, is evaluated as a string, stuffed into a div tag, and is read back out by the attribute list during the render process (after binding is done). In fact, there's special handling on the `type` and `value` attributes that makes sure they get added in the correct order.

There is a facility in place to handle recreating a binding when some of its parameters change but it isn't exercised when conditional attributes are evaluated. It would add a pretty fair amount of bookkeeping to be able update bindings on the fly in that way though, as the element would have to start tracking those additional values. Unfortunately, there isn't always a node available to check with `getAttribute`.

All that said, since it doesn't seem to be a big deal, I'm going to close this for now. If you feel like it's something that needs to be addressed, please feel free to reopen and I'll take a stab at it 😄
