### ISSUE TITLE
Lifecycle events extends – this._super call missing warning is not logged

### ISSUE THREAD

**Issue by marcalexiei** [ractivejs/ractive#3218]
## Description:
While extend a component with a `lifecycle` event callback without calling `this._super()` no warning message is logged in console.

Only "last" `lifecycle` callback is called.

This warning has been introduced with `0.9.0`:
> Overriding a Ractive prototype method during Ractive.extend without calling _super() will now issue a warning, as it's probably being done in error (#2358)

## Versions affected:
0.9.x

## Platforms affected:
All

## Reproduction:
https://jsfiddle.net/entzhx1q/

```javascript
const extendConfiguration = {
  oninit() {
    console.info("extendConfiguration oninit");
    
    this.add('oninitCalls');
  },
};

const MyComponent = Ractive.extend({
  template: `<p>oninit methods has been called:{{oninitCalls}} </p>`,

  data() {
    return {
      oninitCalls: 0,
    };
  },

  oninit() {
    console.info("MyComponent oninit");
    
    this.add('oninitCalls');
  },
})

const CustomComponent = MyComponent.extend(extendConfiguration);

const r = window.r = new Ractive({
  el: '#main',
  
  components: {
    CustomComponent,
  },
  
  template: `
    <h1>this._super missing warning</h1>
    <CustomComponent/>
  `,
  data: {
    hasSomething: true,
  },
});
```

**Comment by evs-chris** [comment]
This one is a little bit tricky. Technically, only methods on the prototype check for `_super` calls, and the lifecycle methods don't exist on the Ractive prototype. I can definitely see where it would cause problems if you overrode a lifecycle hook without properly deferring to any super hooks. It also causes some test failures when warning about failure to call _super in `onlifecycleevent` methods.

So, would it make the most sense to:

1. Make a minor (I think) breaking change and warn about failure to call _super hooks.
2. Automatically call _super hooks when processing a method hook. This will add a bit of overhead, because each lifecycle event will have to traverse the constructor hierarchy in addition to the component hierarchy.
3. Make a more major breaking change by removing `onlifecycleevent` init and extend options in favor of `on: { lifecycleevent() {} }`.

**Comment by marcalexiei** [comment]
1. IMHO This is the most reasonable option.
2. I think user should explicit the call to `_super()` method for better readability (and performance): When I see `_super()` invocation I know that parent component has a `onlifecycleevent`.
3. This option might be too "destructive". Not sure if it's worth it..
