### ISSUE TITLE
0.10.1 - error when find is called inside onunrender

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#3227]
## Description:
When ```find``` is called inside the ```onunrender``` lifecycle event, produces an error when the instance is not rendered.
This used to work [fine in 0.9.13](https://ractive.js.org/playground/#N4IgFiBcoE5SAGAdAThAGhAZygbXAC4EAOWkA9OQMYD2AJgKZIBWAjgK4MwCeStAtuTaceAWgCMScQCYkAFiT8AlgDsWOTGCKkK5LAQCGVANbEDBMEgBGNGgX0wDxKnTUDyNuw6fkAzEn8AdiEsD1t7AkdiRVV1EABdAF9MAngAHjolADcAAiU6AF4AHRBDGABzBgISgD408kysmqKVFrSsKhglYgI8wpKCBn5iABtzBhKcgm5iBmLShgAPAnJHKgJsiZBmlQzsnP1uEbmSgHd8i0g5AFYEYkWAblqWooI93KoxrCx5sxUGEY5P4A0SMABmBnYI16-Cs12erWqb0aOU+Bm+vwM-xGojADAMmRU5VRNGGRmq2xeSNeaTAclRXx+JWBOI2BGOqPYMCwNBgomINFUgxgtQAKgx9DkAApYgH1Ok7V40hrZRVI94M9FMkAs0S0EZjUhbNVK5H7NEY5mynE2OjcHKwhBAgjwymI000lEW7X60RYfgSaQIj3Ut7EGqisBKLB5GMGKYS3os+rhqkhmnhyPR2M5eODSXJ8ip92hjMRqMx7N5xNA60pk2lsPl7NVhMFutFhshtKZis56vt7H1tONnvNytxttJjvF9Pq3styf56dDzsj7sLie5qe11ezxsZzWWhbLPUMFTC4MH9VWdhEGgqKYzE4gW-31ogI-aqwER8-lR+vwOT-vyXT8AYPCTIcxzzFQXI8jAkA5HiIzEE8n7ovyNAClkXB6iMSgmPMwDlDADBVKo5RIaR5EbESyQ5AA5OKBbYTQuEwIx6BMfw3BYThXBcUxAoCXytAXueBCMbUUpsRx9RvgQD5dqGw4lhu479juhb7t2KpNOubz6Q29SNGqpmqm0xkvLsInsXh4mDBe5nhsAJFkRR9GJGpNLxmAZFgvMzAGFk6KdN0BCQOhX7zEp5TlMcIrbAAwgRJgOgwUw0AcBj2lGACE9QGDsKZyQ5D5OQQiq7Ho4U9DUGDYPAAAUYLsCo6xKA+zUAJTADZpoAErkpsSDEDAdh2M+SAqHYZEqIwZF0DkBQ5G1HUbN1fUjjku1kQQXKPvlFjRkgYKOOU-CSUg82LQwdBPCWiQ2btu3rZ1D45GR5TRsKAD6WBgDQpwqH9VhYH9dkcX9DC4RezUACQAtxdDmAY3ECAK-wXttj6vfjSMjEg3WMYDwNqODY1lZx3HvZtKi9f1eP4yzOShTAQLYStOQI81J1YD1SCo4YzWMZTUOCT1j2s6z7Oc8Qf2OZJMOAqtIlIAjGzRGCqh0KLVOiXqFWSYxUstDLLNKGCzWYw+12zZE553XrPUratEIjFgDC4xbFu29jBBIO1t1cL10u+7tz3M77wsGEgZOnNzkScOHEf+9dXsEM1sdm9Hfuklj10hzAzUiYrxsXirucW4k1evVH5uvcNnW4ULDC0I4SncrgjES2JaXGIx8Tc3TXUMwCQySSjaPcWyxwY98iuMhjBd2xe3HYfTAtMxbcvgpC0IxqtO8R1MSjsgwSFzww6CN2nFeRUxGrevM-AEOICC1AAMjQBKUUgACLJNC4nfX2kQlDxS4EhRinxCKD1vnnGWWh+AjCvjATgCDT5AjGFQSeF5oGQiUiAxBrNGBjG4EhYACckLiFuNxKMjAaEIAQMkUBFtBjDDGIMJCCMzpqD7kgZKD4HDsHWLyJAAARAAogAMQAIIAFUv6igAMpIA4aMcYN0GCaNwaLF+zJqYlCEjAxkvxqZMQANRUEXt6Sx0kQCm20bohg+izGGMNtfYx3FTFanMZ48+xxJjX3mIxSx197HGJ6mw+uMTdpy03mPI+PMkBLCcnrYADF95QnsBvHoSS66ywgjzAE3NeYTyujjVOltrb5XTjjE+EcLATUTv8ROUiYATRLoxAAmjQdgDp2CSnBKoTK8Z6m9BUAYK6eRHwWEyok4Rptqn4wbiQtmxSlbLG5s3DYrdKgECERJZYzUKmSUKSzOWEzuZbMDmsPZTAdYLSEcMNeWcJkXPxlciqBhRkc1Wrcm6I1W5PL1oxAAVMsl6MtCZIHMJEUWsdQTRmUN8UQD5YEmBMcnBgUL1mwr7s1RZKgBaPTiV9BgP19BcABkDEGYMIZ9xhnDLOhNp6GBXq8gOnzXqwpJgwxgFMsAG3sjTNa7UPoMx9qfCZ8cqiiwTkJD2XseWs1laoL2MB3k-L+aqnItcyXrP2odHIjTfbsGIMLS+4qNpj2zmjaVWDdp8rBNbUmdKhUio4nip1r1vq-RpQnUG4NIbU2ZZJRGyMcix05YXKp5LVmYNPoMCCdByZIVHltM1WCraRqJrHUW4tqam0db63lAJiaurDgm0+BLqaIsTBNbgPqy1RywW2mWiRqlrPxrs0aEysA9z7kbCSF4h47OBUwNJTtmrZtetGGgXD7poIweSjRS7oFuQAMRWwOHSxI3kzJuRqErC8B6gE1DcuQK2B7iEW1jhmiV9NGY1r2lUE1c6I7ULWgYT2Ex1mrPJaw9ZD5i6PttVm19PM+YVjOrrORBp9ZxQSpLQWJNMXwJtZK05paLavF-VwLOjECotojgaoDSbWYPmDk7KBWHn24ZhTB06oKEMjCQzQeKiUS2Vutnqjtkdc4tESL1ITKg5b3M2NzNpOQ+24VnY3MoBzoFbqU1UO9CZOHjBU+u8YGmH2msbq8GinkqJMVSnAnIn15nATvEpR8Bhyi-LmdlT4NAvYZXytJPGUcDWNSoPAAAAkoV5WqchcnYyULQJAyCUH0EYUw5hLCeAiFEFwbhSRhC8JEHw-ggjUG+Fl1LTgYhuG+CUXOig+J92AHiCBWgaG+DuI8KOIBEhAA).

To resolve this I have added a guard inside the ```onunrender``` lifecycle event to check if the instance is rendered.

I think that this is either a) a breaking change b) a bug in 0.10.1 or c) a bug in 0.9.

## Versions affected:
0.10.1
## Platforms affected:
All Browsers
## Reproduction:
[Playground](https://ractive.js.org/playground/#N4IgFiBcoE5SAbAhgFwKYGcUgDQg1ANrgooAOGkA9FQMYD2AJmgHQBWAjgK5owCeLBgFsqnHvwC0ARhZSATCwAsLIQEsAduwJ4wpCtSpYktANZlUYFgCN69FFhhIytRpuFUbdh06oBmFv4A7KIYHrb2KI5kKhpaIAC6AL542JAgADyMqgBuAASqjAC8ADogKEgwAOZoKKUAfOlUWdl1xept6Ri0MKpkKPlFpehCZMjopbkofGRoJWVoAB4oVI60KDlo9R3NuVh8CLOlAO4FKGCQigCsAAxkCwDcW+0omTm5tMgYGHPm6mgIuV+-wkzAAZkguAh+kIrJcnsVai8dh8kF8fkg-ggJGA0EgsupKu96CNjLUQK1ngiEekwIp3p9vqUgVj1igDu8uDAMPQYBIyPQNOgYPUACqYfoABQx-0atIpVJeTRy8sRrzyKLRTOlWIYCGQFE25LaCupyIZ6MxEhsjD4uRh10BKDhRspiNNbw1jJAuokGCE0jk8LdwfSZDqIrAqgw+WjSEm4sB2saYeNwYVofDkejUdycfQWETmOTKpNqrDEZzObzCeZxdTpep5azMdz8YLtaoKddpYzFezsbb-Q7XYbZczlYH+aHSc7JbTLybE9bU8LMtn9fnvebVcHq4Qde7IbI9NRXvQSwktDQ6iFQdH1KsXFI9HUk2mhxAj+f7RAJ81n5QV8rEA30hFyYD1D5HohAqPgJj2A45loTluRgSBchxBAyEeX9UT5eh+WyXhLwQVRTDmYBKhgNAag0Sp0Komj1gJZJcgAcjFdsCPoIiYDYnB2KEPh8MI3h+PY-lRN5Bgb2vFA2PqCVuN4xovxQF85x7ddD3TRd+2XGsZxHTclRaDdqVMudGmaFVrOVDpLONdRQ2U4iZPQG9bLDYBKOo2iWMSA9qTjMBqNBOY2CQbJUW6XoUEgHC-zPehKkqA5hXJABhUjTDtNBJnoXYkFtSMAEJGiQClk1c6SXw8lB5WcwxYr6OpcHweAAApQS4dQ1lUF9OoASmAJzcnG3Ier69YX1yajKijIUAH0MDAegjnUJarAwJbJJ43glrQIib06gASf4BMYVAkAE4R+T+G8RraCaXtyc6EBYQa2NW9bNG2lg9t48Spv6wantfV7IeimBAQI3JCjezqzijIaWCu8pOrY-7AbEobHghyGXuh2GyCW9y5MOgEEcklhTvWaJQQ0RhMYBmrLzquS2Lx57CZe1RQU6u6XzklhqPUZhqMYeGEciHhwd53mhYelAWF6sWJeG-GFYmxIee19GkBYH6jnhyYYB4LXtaJEZhZvI2ak6g3uYJhWlZF9XeE6ySyY5m9Ked3nEgDnWxomgAlUkNjRtAGEcdSuUINiceknKTDY+JTZBmb1E6-40CEOTLuugTWQOW6vjJhlbuJe7C9yAjs4weXCeJsEIShaMEdGl3edLtB0L7nA9dd334vYtUkrmIQUCka56gAGXoPE6JYVe7Jafjh97npUt4dC2I+Mi06HnvCd0IQEAH820BPq3AWQK8C5vfeIXUzfT8h5hkD4dDgGN9CpA3AEpGZgADrjXGSFvQmwxRioH7m9FgoJNDJxYJlF8DguBrB5CwAAIgAUQAGIAEEACq88RQAGUWAwLGKwaisCryY09D8GqpRxIH3NEyGq7EADUtAK6eh4QpEAXNRZoAYWgJhnCQDJwkH3NhAkOGnhYVJORqg2SGkmOoxCbCeF9yEWwoaUDxq6w-rkYmDcBrqE7ggxYHlmbAFYm3SE9gBKWPQcHKGFQ3r-FNqdXOBwn4oE8a9fmnVSpu0et3O+ZwYDrVyH8E2eCYBxJgJjAAmvQLgdouAFjBBofKcZIn9HUEgAu+RXxnHyu46xXNLaQ1McY8x3jyZLFNhHfqREWDVBQGg2SSwAn5zkiEomLSa6236AjVpKtVjrC6YzcWaCbbK0FuM5WIyJrE3ckgApMMpkcyWKLSO8ymaYwAFR1NDpDd6LBUCRExgbEEUY1BfAkC+Q+ph2GyzQJcsxNzk6dRqU3fGTT5qLQOsbTa21do1UOsdFAZ0Lq5ANtXZZwz6mvRuV9EBzA-oYFZlJYGvVQY52btrYp9sEXfTWkcYGSAEAYDQBsyGFKNCMpgAi7ZuzmW5CDiCsx1EUCclfNEq2XAyDo3gVnKxjtrpkrvj4j69BQQC2pb9aw+Lk6-IVRNMFWAIU0qhTtZOcK5KIoQEXcoqLa6PQxYHW+Vt0AVEYL9dC0qwaip1WEm5BtMbYxqlzeVOrxpYpVZrJpd9-k1QeeKOJfBtXBtMXfJNhNEgYsaS7DpczWDFIwInWR5Mbzp3acc1gdjrwOKaVGegtDGBXx4A6yGNC4H7x8gAYn5rsGliRAo2R8nUQtKAe3rzqD5Kg-Me3v15gbN1xLs7DU9QrQVwrciLrvv-Sa9LGURpDmYyBZiXwezQpNOdMqg2E38cjfFCzGBEL1CzdSqV0qBs+jnDhR8iXTRlUytdhMET0t4FSsqCbtZ8qafu3mL41YVr3ier9HqmkIhoPkAWV6xHi14GgRg57rlIyzIgpmd6EAPpSmlXGqNlUCx5UhqgvLwPDzA+0dQiRhrOzaMTWZGxTaJNyFmjYnVRXlCqDUfebahM9KnfGEYtDRPNvQJJmdq6eYIkYv5ei7FspH3rpUnE4EnzqVfEgSoOzKmFQ+PQRleVSoKQhqYvl7VaDwAAAKqBthy3InJiOlF0OQSgNAjCmHMGcaw4RvDOFcIIYkYQvCRB8P4IIdAvjRYiFEGIbgvilGdioYSydgA4lUJUXQADfC3AeKYkAiQgA)

**Comment by evs-chris** [comment]
I think this may be more an issue with lifecycle events and find. Technically, that `findAll` in 0.9.13 will never find anything because the instance is never rendered in `unrender`, and it should probably also throw there as it would in any other instance where you try to find DOM nodes in an un-rendered instance. 0.10.1 just added better `rendered` tracking.

This has actually cropped up for the other lifecycle events as well over the years - when x event fires is it before, during, or after x, and if during, what does that mean? Unrender is probably the most sensitive for this case exactly - the instance is about to be removed from the DOM and you need to do some cleanup before that happens. There should probably be an unmount or unrendering or something along those lines to handle that.

From the `find` and `findAll` side, I don't know that throwing is necessarily the best approach there, but them I'm not as big a fan of "fail early, fail hard" on things like that. I think a warning and just returning `undefined` and `[]`, respectively, would suffice. If the instance is torn down, _that_ would be a reason to throw.

**Comment by kouts** [comment]
Ok @evs-chris so this is basically more of an issue of the 0.9.x version if I understand correctly.
I don't think another lifecycle event is needed, as long as ```unrender``` fires before DOM destruction I think it's ok to put any cleanup logic (unregistering custom events etc) in there.
I always put cleanup logic in ```onunrender``` instead of ```onteardown```, I hope that is the correct way to handle it.

**Comment by evs-chris** [comment]
According to #1256, which is the origin of lifecycle events, `unrender` is a bottom-up event, meaning that the instance will always already be unrendered before the event fires because the child components need to have their events fire first. There's not a _good_ way to have `unrender` remain a bottom-up event _and_ fire before the instance is no longer in the DOM, because the process of removing the instance from the DOM also triggers the child component events that make the process bottom-up.

I see three possible solutions to this:

1) Break `unrender` by making it top-down. This might make for some weirdness for components that listen to `*.unrender` for whatever reason.
2) Add another event that is top down and corresponds to just before unrender. Not sure that there's a good name for that - `unrendering`, `beforeunrender`, `unmount` are unpleasant in different ways. Another lifecycle event will add a bit more overhead to component-heavy templates.
3) Traverse the rendered template and fire `unrender` events before actually unrendering. This would leave `unrender` as bottom-up, but it also adds a good bit of code to the codebase and an extra full traversal of the VDOM during unrender, which is already not a light process.

Of those, I think 3 would be ideal behavior, but I don't think that 1 would really cause any issues in the wild and is the least complicated option.

**Comment by evs-chris** [comment]
After thinking on it a bit, adding an `unrendering` event as a top-down is non-breaking and doesn't add _too_ much overhead. There are legit usecases for both sides of the unrender event, so I think this is the best solution. If you need to clean up externally managed DOM stuff from a component, `unrendering` is the event you'll want from 0.10.2. Thanks for the report!

**Comment by kouts** [comment]
Thank you @evs-chris , so ```unrender``` event must not be used for cleanup?

**Comment by evs-chris** [comment]
`unrender` can be used for component cleanup, like dropping listeners and cancelling observers, but if you need to do DOM stuff, like tear down integrations with third party libs that were set up in `render`, then `unrendering` is the place for that. Of course, you can also do event/observer cleanup there too.

**Comment by kouts** [comment]
Ok @evs-chris I think I got it, thank you once again.
