### ISSUE TITLE
How to provide default component content?

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#3236]
Hi,

given a greeting component that you could use like this: `<greeting />` or like this: `<greeting>Some <i>customized</i> message</greeting>`.
Is there a way inside the component's definition to provide a default content? Or something you could use inside its template like `{{#if there-is-content-flag}}`?

**Comment by evs-chris** [comment]
You can set up a check in the config event to check for actual content, or you can do the same thing inline in the template [pretty easily](https://ractive.js.org/playground/#N4IgFiBcoE5SBTAJgcwSAvgGhAF3gDxICWAbgATFIC8AtgIbEB2AfAQPQmksA6TBAZwDGMYgAdc5XAE8xCargQAPXOzC5aAG0o1cYzbyY9cBIbTHl2h46fMsAkuRQwECSdID2AV3IB3YrhglEyazAjkQh5MitEAhBxmYtYmHoEIMJbJBKlg6SwAyl5i+sTI8ew5eXwcwqIShoIi4pIycgrKqupaOtSJycDAAMTEAGbkAAIAdGL0MLjE9JoCk5HRCNEYGAMsqzG4mwMISwibACIII-RempLOrvNMKBFRe5SSxAKxA+yjm3w2ACMYFZquxas0GuCJFJZPJFCo1BptFRqJUYP1gDsXut9hgCECQUZcANBjM5gttEgLlcbmdqddFEgvsB2GT5os-vwwU16iAcAJ4EwEL5yAAlehCeakBAACmA-1wuFmaFwkHIAHJBgxmOqsArFOZNPRFGrNXpNLqFZFzFEcQI1fKicZEmrxZKyAhJh11kg5VIEIbjQhTYNEuryBgAJR6p24NGuiVSz3epi+x3GDOKgP6IMhtGW2PGKIOhWZ51REbEFAyyPkdO4MsN+ZjGWxQIfaazdlLFbY6LkAA+A-IbbAHbZFOWuxxk006xQgVr7eWE8WU77kmoUjHK67k8mVMuDIA3KWm8YMGeL2eowrL0wo5ggA) due to ractive's ideas about truthiness.

```html
<div id=main></div>
<script type=text/html id=tpl>
  <cmp />
  <cmp>I greet you with inline content!</cmp>
  <other />
  <other>Supplied!</other>
</script>
<script type=text/html id=cmp>
  {{#if @.partials.content}}{{>content}}{{else}}Default greeting content it is!{{/if}}
  <br/>
</script>
<script type=text/html id=other>
  {{>content}}<br/>
  {{#partial default}}Defaulted!{{/partial}}
</script>
```

```js
new Ractive({
  target: '#main',
  template: '#tpl',
  components: {
    cmp: Ractive.extend({ template: '#cmp' }),
    other: Ractive.extend({
      template: '#other',
      on: {
        config() {
          if (!this.partials.content || !this.partials.content.length)
            this.partials.content = this.partials.default;
        }
      }
    })
  }
});
```

Template-controlled components always get a content partial, even if in a self-closing tag, so it's not quite as simple as providing a content partial in the component template. Whether a component should have its content partial overridden regardless of whether content is supplied could probably be argued either way pretty soundly, so I'm not gonna say this is necessarily a bug.

**Comment by dagnelies** [comment]
That's fine with me! :)
