### ISSUE TITLE
Chrome extensions

### ISSUE THREAD

**Issue by Inversion-des** [ractivejs/ractive#3244]
These tools:
https://chrome.google.com/webstore/detail/ractive-dev-tool/mobaekclikghnakiffjacknpimanblii
https://chrome.google.com/webstore/detail/more-ractive-data/ifbnmdpghgpcceednkpklhfkmjgipaih
Why they aren't mentioned on the site? Are they recommended for use or not?

**Comment by ghost** [comment]
I was not aware these tools exist, nor did the developers of these tools reach out (i.e. post on Gitter, send a PR on the docs site, etc.).

If someone can reach out to the developers of these extensions, ask a few details (i.e. version compatibility, is it maintained regularly, is it open-source), as well as verify that they do work, we can probably reference them on the docs. Of course, there's also the option of sending the PR themselves if they really wanted to. 😁

**Comment by Inversion-des** [comment]
@petermekhaeil could you provide some info about your extension?

**Comment by Inversion-des** [comment]
Sent email to the developer of other extension.

**Comment by petermekhaeil** [comment]
The source code to [Ractive Dev Tool](https://chrome.google.com/webstore/detail/ractive-dev-tool/mobaekclikghnakiffjacknpimanblii) is over at [petermekhaeil/ractive-chrome-extension](https://github.com/petermekhaeil/ractive-chrome-extension).

It's listed on the [v0.8 Docs](https://ractive.js.org/v0.x/0.8/plugins), looks like it was missed out when the website had a redesign.

The last supported version is v0.8. If anyone is happy to update it to the latest version that would be awesome! I am more than happy to continue to maintain it. :smile:

**Comment by ghost** [comment]
😱 omg, I missed it. I'm even the one who merged it on the original docs. 🤦‍♂️ Adding it back.

**Comment by ghost** [comment]
@petermekhaeil re-added the missed links. Should be on docs site shortly.

**Comment by kouts** [comment]
Didn't know this even existed, does it work with Ractive 0.10.x ?

**Comment by petermekhaeil** [comment]
I released a new version to today that works with 0.10.3.
Try it out and if you find an issue, raise it over at [petermekhaeil/ractive-chrome-extension](https://github.com/petermekhaeil/ractive-chrome-extension).

**Comment by krityan** [comment]
The More Ractive Data extension is hosted here: https://github.com/squaredup/RactiveDataChromeExtension

It was written primarily for internal use at Squared Up so only currently has known support for the versions we have used (0.7/0.9), We haven't yet had a chance to look at upgrading to 0.10 so the extension hasn't been updated either yet.

As for what it does, it adds a sidebar panel that displays data/computed properties from the component related to the selected node in the elements window. And for Squared Up specifically, separates out the inherited properties from the base component.

I'll ask about getting some time to upgrade it, since there's a few other things I want to improve anyway, we're quite busy currently so it might take a little while for me to pick it up.

**Comment by ghost** [comment]
Added both More Ractive Data and Ractive Data to docs.
