### ISSUE TITLE
Ractive inserts double semicolon in the last inline style

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#3257]
## Description:
Ractive inserts double semicolon in the last inline style rule.

## Versions affected:
0.10.5

## Platforms affected:
All browsers

## Reproduction:
[Playground link](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAF3gDxICWAbgATFIC8AOngIYxq70B8BA9CaW7QHYCCAZwDGMYgAdclGvVwIAtpIA2DBfXK4AnpIR08CAB65OMBqNxkE7AbVwFJ5YTpX76Adyq4wkcgCYABkDJIwBucgAjAHsYJAQYPwBGUOdolSpyAGIEXIiAM2j+XABaYWIALwRkgA5QsPYACQQVFWiscg9YlSQAQi5JPkEHQYBJfmE9Sy0wBHIYBH54haRySSYGFHNJMHIGGNI5rx9ybWiAVxgomGiPYQSAcmFKCamZFqVFmVxo9IA6AiRK6cIb2exnc7OMAXHrOXJ+LxIHx+IIhcJRWLLZKpYTpTI5PLkQrFMqVarkJJ1cIRAAU-GiVlEcx8cyQF0ibjhimIonSRT231m5EWSAAlHYHJxBkJOGIJNI2CAcMJ4JxOMKjAhROcFDNiM9efFOsQTiy1mptFEdT9+C8ZszopIShIUGAZLyYPwEuRovk9c91l6BKQmPMLFZDuRqOQvR5yAAlcPWGnAATkLRMFh+B5ZXCZhC4B5YNNaJSqdTknMKZRqBQPAQYUUNQT8NUzG7nV0XQUIe5aHWxYgMFTCDoshaUZ4MW3dyQ68g8Y0naeyH1+h555gF+ut9XT1YMUs1ivOcRSGTHXYrzK+8gbsu1hA7tsQ8iiFf5YhLe0+nVzmSLvuR7lrqcrnj6tpmo0AAqACyAAyGaRJgQA)

**Comment by evs-chris** [comment]
So, not exactly a bug, but a slightly weird behavior that was added with merging multiple style attributes together to allow them to be static. As of 0.10, you can have `<div style="color: green; background: red;" style-font-size="1em" style="border: 1px solid;"></div>` and the parser will merge all of those into a single node that ractive knows won't change, so it can short circuit any tracking logic and save a bit of time on renders and updates. When I added that, I didn't add a check to see if the style ended in a semicolon and just added one every time, since it didn't affect the outcome.

It does look a bit weird though, so I've added the check to only add one when necessary to edge. Thanks!
