### ISSUE TITLE
Question:  oncomplete event vs. document ready

### ISSUE THREAD

**Issue by tobiah** [ractivejs/ractive#3261]
Is there a way for and Ractive instance to let me know that
the whole document is ready, a la jquery's .ready()?  I'm going
to ajax some data from the back end, but maybe it's ok to just
do that when the instance is complete.

**Comment by evs-chris** [comment]
That's a bit out of scope for ractive. If you're rendering at document ready, you typically put your ractive init/render script at the end of the body, so that the dom is already ready when it runs e.g.

```html
<html>
  <head> ... </head>
  <body>
    <div>placeholder loading thingy or wrapper chrome or server-side rendered stuff or maybe some combo of those</div>
    <script src="index.js"></script>
  </body>
</html>
```

If you're using ES modules in the document, they already load async, so the dom should be ready when they load.

At any rate, you can safely do something like this:

```js
var app = new Ractive({
  // init options
  target: 'body' // or wherever
});

fetch('/some/data').then(async res => {
  app.set('the.data', await res.json());
});

// or if you use an `{{#await}}`
app.set('the.data', fetch('/some/data').then(res => res.json()));
```

Ractive doesn't care when your data appears, so it's only an issue if you're concerned with a flash or you're trying to rehydrate with data that hasn't arrived yet.

**Comment by tobiah** [comment]
Thanks, that's helpful.  Since I do have jquery available, I'll probably just put the initial stuff in its .ready() thing.
