### ISSUE TITLE
When using {{#each:key}}, references to {{key}} resolve incorrectly

### ISSUE THREAD

**Issue by clarkd** [ractivejs/ractive#3264]
## Description:
When using {{#each:key}}, references to {{key}} resolve incorrectly. If the data being iterated over has a property called `key` then the references resolve to that rather than the index of the iteration as you'd expect (or at least, I think you'd expect!).

See here for an example: http://jsfiddle.net/k64psftq/

Removing the key property from the data or changing the name of the index fixes the issue however this becomes difficult when the data is dynamic and you don't know the possible properties ahead of time.

As a workaround you can use the special reference {{@index}} but it does seem like the behaviour described above is a bug. _Especially when this same code works fine on 0.7~._

## Versions affected:
We're using 0.9.13/14

## Reproduction:
http://jsfiddle.net/k64psftq/

**Comment by evs-chris** [comment]
This is one of those things that got adjusted to fit more with general expectations. With the block structures in ractive that provide scope (with, each, and components) the content of the structure resolves references starting from the immediate scope. In this case, the scope inside an each block, is an object that has a `key` property, so when resolving `key` within the block, it finds the data first. The `key` alias exists on the actual `each` block, which puts it at a slightly higher scope than body of the block. The js correlation would be something like:

```js
items.map((item, key) => {
  let key = item.key;
  // ...
});
```

The reason it works in 0.7 and 0.8 is that they didn't have a unified resolution structure, so it was kinda hit and miss trying to figure out how a reference would resolve in a given situation. Ambiguous references still introduce that possibility, but it is significantly less that it used to be, particularly with aliases (like the index and key names on each blocks).

Personally, I would prefer that a plain (non prefixed e.g. `key` vs `.key`) reference _never_ resolve to data, because that would allow removal of all ambiguity in the template. FWIW, I always use the `@index` and `@key` names over aliases where possible, because they're faster and you know that they will resolve to the index on the nearest parent each block.

**Comment by ceremcem** [comment]
We still need `{{#each foo:i}}` syntax when we need nested loops, right?

**Comment by evs-chris** [comment]
Yes, at least in one form or another. 0.10 introduced additional aliases on each, so you can have `{{#each filtered(foos) item, @index i, foos source}}`, among other things, which will net you a computed list with each fragment in the context of its source list item (rather than a computed context) and the item and current index available in the context just outside of the data as `item` and `i`, respectively. Makes doing twoway binding on a filtered list relatively painless.

**Comment by dagnelies** [comment]
indeed, the `{{#each data:key}}` is ambiguous with the `key` that's inside the items. So which one should `{{key}}` be? ...that was a rethorical question. Simply use a non ambiguous name and it's fixed:
http://jsfiddle.net/k64psftq/9/

**Comment by clarkd** [comment]
@dagnelies If you don't know the properties of the data ahead of time, choosing a non ambiguous key can be difficult though.

> Removing the key property from the data or changing the name of the index fixes the issue however this becomes difficult when the data is dynamic and you don't know the possible properties ahead of time.

**Comment by dagnelies** [comment]
That's what the the special references `{{@key}}` and `{{@index}}` are for.

If you really need to reference grandparent keys in nested loops, just use special key names that are "reserved" or unlikely to be used.

Ambiguity is always an issue. When `{{name}}` refers to both a property of the object and an iterator variable, it's ambiguous/problematic per-se. Which one should it be? Ractive 0.7 apparently favored the iterator var in this case while more recent versions favor the object property. So be it. If we turn it around, the next person would likely complain that his local variable is not accessible because he obtains the iterator variable. IMHO, just use `{{@key}}` or reserved/unlikely names.

**Comment by clarkd** [comment]
👍 

> Ambiguity is always an issue. When {{name}} refers to both a property of the object and an iterator variable, it's ambiguous/problematic per-se. Which one should it be? Ractive 0.7 apparently favored the iterator var in this case while more recent versions favor the object property. So be it. If we turn it around, the next person would likely complain that his local variable is not accessible because he obtains the iterator variable. IMHO, just use {{@key}} or reserved/unlikely names.
