### ISSUE TITLE
Alternative yield if partial doesn't exists

### ISSUE THREAD

**Issue by enneid** [ractivejs/ractive#3268]
Lets say we have component, which can be  customized by {{yield partialContent}}.
My question is  there is a way to define "default" partialContent somewhere in component, which will be use if partial is not passed, or we have to always initialize our component with definition of this partial?

**Comment by evs-chris** [comment]
You can supply a default in the component partials, though with a yield,
you won't really be able to access any data because you'll be in a weird
(callers) context. If it's just plain text/dom it should work out fine. If
you supply a context to the yield ({{yield somePartial with .}}), you'll be
able to access that context.

**Comment by enneid** [comment]
thanks for fast answer

**Comment by JohnnyFun** [comment]
If it's any help, I needed a way to check if a partial was passed and wrote this helper function:

```
Ractive.defaults.data.containsPartial = function (partialName) {
	const containspartial = Object.keys(this.partials).some(k => k === partialName)
	return containspartial
}
```
Then you can use it like:

```
{{#if containsPartial('buttonLabel')}}
{{yield buttonLabel with selected as selected}}
{{/if}}	
```	
Works for my needs, but not sure if this violates any best practices.

Cheers,

-John
