### ISSUE TITLE
Equality inside components is wrong

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#3269]
Instructions:

Select an address, it will fill the content and get highlighted.
When changing some content in the address manually, the highlight should disappear since the button's content (original value) and the modified value obviously differ. The `{{#if ~/target == .}}` should become false. The printed JSON values and equality value is particularly disturbing.

https://ractive.js.org/playground/index.html?env=docs&hidemenu#N4IgLiBcIDwBZgLYBsB8AdAdvApgQwBMNN0wZkBLTAawAIAnHZAXnRAGcwBPZHduHDjBtacRgDNWIBGAAO7SAHpFnPAGNqsvGDgA6AEYB7Q2E708stQUy61hxIqMmzFxQBZdARl0BmRWvZ2R2NTMHNZXUQqW0CRKjAcAHN6Cm4pfjwfAA43AFoAWQBhAHcATizFAGUAMUwAcQBRLPEAKQAVHzqADWKGgHlMRPYANQB2AC0wACZRgDku6sM8QwBBWUQATUQszwoAVy7DAAVqar6W4pashoAlAmpMABkj-L6RNXpDQMMUxKopPCYQyYLiIQx7dhsYikGDsD4UWRgWjsehqKQyeRKfzWXQAK3YBCYFAAbvRdJghIpMOtFOY1GASTgoTAVPDEdCyJweDgOaQDGBMLRgFhSKKkHh6H9MJBaABWWQADwA3CLhGAAL6qllc3jEFkCQh6owELgcmAEEm0CgEKR2TBgPBUHD0d7IPCBW3Ah1Ol0gVAsi3E3kkTlspHWqQJRCyN0JETcWQ4SM4aOxpl+1WikMwwO0NRuj1scQ-RC5ZLg2RQzNq8h4fRMVAAaT29AAXvXWzgKGo4Jg9oMWW762hqzDiXhkHscLlZN3qM683BDN2+FJgMAe8u1HxdIU+vkjitZht1ZqQLQHZKhGvgJfEkJdABJLoAfUqAAk+jc2rMVvkGqeIiKLyNZULIexIvm7rsFIxb0KWdphIYyAiOOk5Jmw653g+z5vp+36-v+gHnsB1YBiS0LZmQcA+HmBYwWwCQKmAM4pIgEpcFCKz6OwOCYIS9D6j4IGjmQ5Z7LIM5zgum4rgxIDrrJ27sLoKwACJqTcDSVJUxEXhK95gDe2FgE+r51DcRwvtUNz7nppEkFRWZijmlpQYWIBwaW4mVhmTk1kODazHgiA4IOdYNqJMJgRBdHQbBJa5IhnwoeeaFTsZBk4eZlnWbZ+S6IRAFnrQDkuWQiiBiJwj+eabn0Ql8Flp8ElVv5MKBWgKwEAQjCBGFiiddV0XUrF7nyV5SVeilqEThlmG3llpm4RZVk2fuuiVG0WkNG09nVeRQZRbVubjY13ktb5w1kENRyPOM4XDtdMAxZBDVFolyXIbN6GZVey05Wt+W6Hd4z7aJh0iSd9XxR9TU+W15UdRFaCVA6BAVUNUVkK9cUeZNX2pbQ6UYQpi3-WZL6rXlG2FI+bQniVZVqjClUUVqrIpOymYhrCYZWjabAk1JGjOvGXCJsmqbaOmIHrgAxPgPaLlufCAbV+gQWAwJ4-J+gCkKwDyxQ4i0AAfooJm0MwzC0Lop765grEUOx9BcOuTC8Q7Aq5LxdoEBx66KCbenAkllAaFIAACui8WAAAUADkJmJwANHbACUiMs2q6725qtWOFrwJy8AihK3A6us3CXNgMGMI1wi4aCyAPki-OvoXhLpNRjGMvZ6QCsVyrclVznMCa2A2uCmdbCO4bxumxbVs23b3tO7IbGB8Ans4Ovvs4P72-B+IodO-mc7R7HQhJyn6e6FnflI2AQ-qHAF5wBQ7Bj8-eenhP9BmblSDhXH+NYi5TxLtWEBb8q5URgJvHkWAlI7gAAwynXC0SofRZixzCFQP44guDxxQSpVBGd1YmQwcALBOC8EpEGCbYhJkKEFwaAARz2BOAA-IbUhuhUHW1tiZdWtAxG0BZIgs0nMm711DLXKGYplASNnKLegI9lI3mKHAGWxJnR6RMjeEm4MqI3HUAyPRth7CyGBHxUwABtROwtVEd0TgAXWtrQMx9JGS6BwMxPiBB47Cn8r3NMMpE7y2cdJegidqzqizk5Ux5jfF2GjLY+07BHFtxcc6dxnjvEWJwH4gJ-FgmiTCTLCJ8sckxLiVRBJo4klinHOo9RtsKTFC8SkvR5TQkpj7gkaplSEhpwqUtapiFHQUlianUSAcHQYOxqQpZ7UWYgD3AeI8Gw2AynsWwBojw+i0DUhQP4DpkC0D6OIcQK5aB1EQPod8bB05sEqK7JEjYcBcGKD8C0gx7mPOeSANxcy1mihAGpFYbQGi7NoPskAUxUGeCyLkTwqDcjIpebQNgSKUVooxZ4TwbBQXYwhepTS2lKhwvsSE5+LkQBFV2Qco5JyzmpAnFcm5dyHlPJeWS9ZW0dptDhWwNoAAf-QBCFxozJLQNwPh+XgvWaDUVIBRjItGFkJV9L1l0wZmqtGWtEgSmECAAV6p050pzkjRlf5YVQDYO+Z06iVj0EwHgPYBAdU2ptSAIVDRdqGoks6MwuhaCeCmIqkAYLdUQtVVAHF6qfCjCmNqmNAqIX6p2Ymg5gRKCDD4mwC1bjsYF3KuWtUjTeYyO5tgYIJo9SKAQCgYgMaOBQBAO2tQnb21wCgKAegna0ycBAKeIAA

**Comment by dagnelies** [comment]
And when you click back and forth, the modified values are kept, but not shown in the buttons. It smells strongly of some shadow fancy broken magic.

**Comment by evs-chris** [comment]
Took me a minute to noodle this one through, but it seems to be behaving correctly. What's happening is you have a list of objects for the group select and the values for the inputs are bound to child properties of the objects. When you change a value, it changes the child property, but that doesn't affect the object equality of the parent objects in the list. If you want to detect a change, you'd have to clone the initial list and do a deep comparison, which fortunately for something relatively simple like this, can be done with [`JSON.stringify`](https://ractive.js.org/playground/index.html?env=docs&hidemenu#N4IgLiBcIDwBZgLYBsB8AdAdvApgQwBMNN0wZkBLTAawAIAnHZAXnRAGcwBPZHduHDjBtacRgDNWIBGAAO7SAHpFnPAGNqsvGDgA6AEYB7Q2E708stQUy61hxIqMmzFxQBZdARl0BmRWvZ2R2NTMHNZXUQqW0CRKjAcAHN6Cm4pfjwfAA43AFoAWQBhAHcATizFAGUAMUwAcQBRLPEAKQAVHzqADWKGgHlMRPYANQB2AC0wACZRgDku6sM8QwBBWUQATUQszwoAVy7DAAVqar6W4pashoAlAmpMABkj-L6RNXpDQMMUxKopPCYQyYLiIQx7dhsYikGDsD4UWRgWjsehqKQyeRKfzWXQAK3YBCYFAAbvRdJghIpMOtFOY1GASTgoTAVPDEdCyJweDgOaQDGBMLRgFhSKKkHh6H9MJBaABWWQADwA3CLhGAAL6qllc3jEFkCQh6owELgcmAEEm0CgEKR2TBgPBUHD0d7IPCBW3Ah1Ol0gVAsi3E3kkTlspHWqQJRCyN0JETcWQ4SM4aOxpl+1WikMwwO0NRuj1scQ-RC5ZLg2RQzNq8h4fRMVAAaT29AAXvXWzgKGo4Jg9oMWW762hqzDiXhkHscLlZN3qM683BDN2+FJgMAe8u1HxdIU+vkjitZht1ZqQLQHZKhGvgAA-RSXxJCXQASS6AH1KgAJPo3NqzFZ8gaU8REUXkayoWQ9iRfN3XYKRi3oUs7TCQxkBEcdJyTNh13vR9nzfT8fz-ACgJA88wOrAMSWhbMyDgHw8wLeC2ASBUwBnFJEAlLgoRWfR2BwTBCXofUfHA0cyHLPZZBnOcF03FcWJAddFO3dhdBWAARLSbgaSpKnIi8JSfMAbzwkyCI-OobiOd9qhufcjMokg6KzMUc0tWDCxARDS2kysMzcmshwbWY8EQHBBzrBtJJhSDoKYuCEJLXIUM+dDz0wqcb3wsBX2s2z7Mc-JdFI4Cz1oFyPLIRRAwk4RgvNLzmJSpCy0+GSq2CmFQrQFYCAIRhAiixQ+oa+LqUS7zlL8tKvQyjCJxynDgDygr3xsuyHP3XRKjaPSGjaZyGuooM4qa3MZra-zOsCiayHGo5HnGaLhwemAEpg1qi1S9K0KWrDcss-LCK24rdue8YTsks6JMulrkt+9qAu6mrepitBKgdAhavGuKyC+pKfLm-7MtobLsJUtaQY28GdtKwoXzaE9KuqtUYTqmisFoXm+Z5vneZgWRUHXFpKj6WZdDMKg-nELgAAo8oASlPFkRa1VkUnZTMQ1hMMrRtNhKbkjRnXjLhE2TVNtHTcD1wAYnwHtFy3PgQKa-RoLAYFieU-QBSFYAHYocRaAsq8kWYZhaF0U8A8wTiKG4+guHXJhBPjgVckEu0CB49dFFDozgTSygNCkAABaWhAVgByPK64AGlj5W0Y5tV1zjzUmscb3gXt4BFGduAPc5uFtbAYMYQnhFwyNkAAtN+dfQvS2qajGNbfb0hHZH12lLHjuYC9sAfcFa62AToOQ7D8XJelsJZdDxWI9M5XaGj2h76lmXBhfhWuhVbqgTknFOadgAZxwFnROudgT51ToXYulVS75jnFXGuYB66Nxbn0fQuIcD0l0HBCgiRMAK2AOqFuQC25BXRmAPe6g4AXjgBQdgR96FdzVvoeg7MaqFxHhwmsfcz4D2rAIphY86LC1FsAH+j8Uj-3lkrEGwD1Zmi1nPaeoZJ7wzFMoWgwt5L0APupG8xQ4C22JM6IyeUbyUxhnRG46gGTWNsPYWQwIhKmAANp1xNrOM29A64AF1P60GcfSRkugcDsSEgQChklN5phlHXB2ATjF12rOqNubknEuOiXYaMXj7TsD8UvQJK9QnhMia4nAMS4nCUScFZJttUkOwqZk7JuSPJ5LFOOExJiY4UmKBEgp1jmk1VaQkdp0ycDNySSDdpKFHQUmCU3SS+cHQymFD1MAak+A7IJqKEAe4DxHg2GwGUPi2ANEeH0WgWlSGpAnLQPo4hxArloHURA+gvxsBbmwSoKckSNhwFwYoPwLSDG+b8-5IAQkbL2ScrSKw2gNCubQG5IApgAAZPBZFyJ4XFuR8UAtoGwPFBKiUks8J4NgiLjnCBANpXS+lKiYp8bs+hHkQDlSubc+5jznkOmQG8j5Xyfl-IBUyk5+1DptExWwNoAAf-QssFzYzJLQNwPgZXIo5iAKGSqQCjHxaMLI+qeWGqZizE12NvaJAlMyplVChSyuZfyqAbAvzOhMSsegmA8B7AIFaju6MQDyoaEde1MlnRmF0LQTwUw9UgCRdak5xqoAUtNT4UYUxLVpo9WwW1lzs23MCJQQYQk2CusZYKQWja8o7J7vQ1tHd22kByZrWeOtsDBBNHqRQCAUDEDTRwKAIBx1qEneOuAUBQD0EnWmTgIBTxAA).

The reason the buttons don't also update even though the object is updating is that ractive doesn't track the same object across multiple keypaths unless you specifically tell it to with `ractive.link`. If you wanted to update the source choice, you would just need to use `@.link(@keypath, 'target')` instead of `@.set`.

**Comment by dagnelies** [comment]
Well, it might have a "logical" explanation from a technical point of view, I don't argue ...but from a user's perspective how it behaves is just plain crazy nonsensical.

The following excerpt:
```
JSON.stringify(choices.0): {"NAME":"A"}
JSON.stringify(target): {"NAME":"B"}
choices.0 == target ?   true    <===
```
...is from a user's perspective just completely nuts, if I may say so. It's not meant to be rude, just to illustrate the fact ;)

**Comment by evs-chris** [comment]
I don't disagree :smile:. Unfortunately there's not a really good way (that I've found) for ractive to figure out that a particular object also lives at another keypath unless you explicitly tell it so. I've looked into it before and the tracking overhead gets pretty serious if you have more than just a handful of keypaths in your data. The next best thing is to wrap data in a proxy that keeps track of where all it exists, but that's something I haven't had time to fully explore and it limits you a good bit on browser support.

**Comment by evs-chris** [comment]
To clarify a bit on the `choices.0 == target` with them showing different values on the template, when you change `target` or one of its child keypaths, ractive knows to update `choices.0 == target` too, because `target` is clearly referenced. It _doesn't_ know that `choices.0` should be updated though, so it doesn't try to sync the underlying value, which has clearly changed, back into the ui.

Again, I agree that it's surprising, but I haven't found a good way around it, and it's why `link` exists, since being able to handle it manually is better than nothing.

**Comment by dagnelies** [comment]
Actually, what I would intuitively expect is following:

`@.link('a', 'b')` => `a` and `b` refer to the same object. Equality prevails and changing `a.child` or `b.child` is the same.

`@.set('a', b)` => `a`'s value is set to the value of `b`, they are "copies". Changing `a.child` or `b.child` does not affect the other which is separate.

*PS: I did indeed solve it through JSON.parse/stringify, but I would have expected to behave like this in the first place.*

**Comment by dagnelies** [comment]
Or at least putting a warning that something like `@.set('foo', @.get('bar'))` leads to unexpected/undesired results. That saids, directly making a copy in such cases would be easier. ;)

**Comment by evs-chris** [comment]
How would you go about making copies? Would you always do a deep clone on an object that gets set, or would you try to detect that the object is also installed elsewhere and automatically do a copy or link? If the former, I'd think that would cause issues with non-POJO objects and the latter, tracking gets pretty expensive, right?

I can't really think of a good way to have ractive warn you in that scenario, as that would involve all of the tracking that would allow automatic linking. So that leaves me with the docs, which are ok-ish but not in super great shape right now.

**Comment by dagnelies** [comment]
I wrongly assumed there was a way to differenciate a normal POJO from a Ractive.get one... But if that's not the case, there is indeed not much you can do. :/... What a pity.

**Comment by evs-chris** [comment]
I have a roadmap plan that involves setting up Proxies for ractive data, so that you don't _have_ to use get/set that would also cover tracking where in the ractive hierarchy the data is available. That will limit you on browser support though, and is more of a `2.0` sort of thing.
