### ISSUE TITLE
[not-issue] CSS properties naming not consistent

### ISSUE THREAD

**Issue by marcalexiei** [ractivejs/ractive#3273]
I noticed that some CSS related function have CSS written in uppercase:
- [ractive.toCSS()](https://ractive.js.org/api/#ractivetocss)
- [ractive.addCSS()](https://ractive.js.org/api/#ractiveaddcss)
- ...

However component `noCssTranform` setting has CSS written in lowercase. 
Should be "uppercased" for consistency?

I think `css` property is fine as it is. 

Just nitpicking. Fell free to ignore it and close the issue :)

**Comment by ghost** [comment]
_(Let's just pretend `XMLHttpRequest` doesn't exist for now 😂 )_

It's a good question and I agree that there should be consistency. The reason I named the CSS functions that way (I think I implemented some of those 🤔 ) was because the basis of the functionality was `ractive.toHTML()`. Also, it's an acronym so it makes sense having them uppercase. However, `noCssTransform` is an old API.

This would make a good addition for 2.0 stuff, making names consistent across.

**Comment by evs-chris** [comment]
FWIW, I've actually tripped over `noCssTransform` before, expecting it to be `noCSSTransform`.
