### ISSUE TITLE
{{#if {} }}....{{/if}} doesn't work as JS would

### ISSUE THREAD

**Issue by giovannipiller** [ractivejs/ractive#3290]
## Description:

A template like: `{{#if {} }}....{{/if}}` doesn't get executed as it would in JS `if ({}) {....}`.

`{{#if {} }}....{{/if}}` won't print its content, even though `!!{}` is `true`.

Note: this is especially problematic because it can happen even when properties from data are involved.

Example, where `emptyObject = {}`:
```{{#if emptyObject}}Won't be printed{{/if}}```

## Versions affected:
1.1.0, 1.0.0

## Platforms affected:
Any

## Reproduction:
[JSFiddle](https://jsfiddle.net/rczkxyg5/)

```javascript
const r = new Ractive({
  el: '#main',
  template: `
    <h1>Bug</h1>
  	{{#if {} }}<div>Plain empty object is NOT printed</div>{{/if}}
  	{{#if emptyObject}}<div>Empty object from data is NOT printed</div>{{/if}}
    
    <hr>
    
    <h1>Workaround</h1>
  	{{#if !!{} }}<div>Plain empty object is printed</div>{{/if}}
  	{{#if !!emptyObject}}<div>Empty object from data is printed</div>{{/if}}
  `,

  data: {
    emptyObject: {},
  },
})
```

**Comment by dagnelies** [comment]
I think that's in order to be compatible with handlebarsjs, see https://handlebarsjs.com/builtin_helpers.html

Since ractive has opted for a similar syntax, one goal was to be compatible to some extend.

It's also like this for as long as I remember, so changing this would be a major breaking change.

**Comment by ceremcem** [comment]
I just noticed that an empty array is also considered a falsy value although it's a truthy value in JS.

Actually, I would expect the same behavior from JS. IMO, an empty object shouldn't be considered as a truthy value in the first place. Anyway, I never noticed that before, it's good to point that out.

> It's also like this for as long as I remember,

Yes, it seems the behavior is the same since 0.7.3.

> so changing this would be a major breaking change.

Besides, change will involve creepy empty object/array checking actions. 

However, it's desirable to have JS and template interpretations to be compatible, which will reduce number of things to remember.

Current behavior seems OK and has specific advantages, IMHO. However, it might be better to underline this behavior (with a few examples, like @giovannipiller did) [in the documentation](https://ractive.js.org/api/#if-sections): 
> `{{#if }}` renders a block of markup if the reference is truthy **or a non-empty iterable**.

**Comment by evs-chris** [comment]
It is a little odd, but I can confirm that it is by design and has been so pretty much from inception. It's in the [conepts](https://ractive.js.org/concepts/#section) section of the docs, so a little off the beaten path.

**Comment by giovannipiller** [comment]
Thank you everyone! I have **no** idea of how I missed it until now 😬
