### ISSUE TITLE
Propagation not working when model changes from a component

### ISSUE THREAD

**Issue by jaloplo** [ractivejs/ractive#3296]
Hi guys,

I'm facing a very simple use I think. My model has only one property and I have two Ractive components that show the message in different ways, the first one using a ```h1``` tag and the second using a ```p```. That's all, nothing else is added just to make this PoC. 

Both of them show the message in the right way as I expected. Now, I added a button to the second component that changes the message property when clicking it. I used ```this.set('message', 'Changed from P component');``` and works fine but only for the second component. The first one still has the same old text.

``` javascript
model = { message: 'Hello Ractive World!!!' };

var h1 = Ractive({
	append: true,
  data: model,
	target: document.body,
  template: '<h1>{{ message }}</h1>',
  observe: {
  	'message': function() {
    	alert(this.get('message'));
    }
  }
});

var p = Ractive({
	append: true,
  data: model,
	target: document.body,
  template: '<p>{{ message }}</p><button on-click="[\'change\']">Change message property</button>',
  on: {
  	change: function() {
    	this.set('message', 'Changed from P component')
    }
  }
});
```

I thought that using ```observer``` methods in the first component would be a workaround to be notified when the model property changes but nothing happens.

So, here my question, is there a way to let components be notified when model changes?

Ractive versions I'm using are 1.2.0 and 1.3.0
I'm using __Express__ over __Nodejs__ and __express-handlebars__ as the view engine.

Here you can find the jsFiddle with the [example](https://jsfiddle.net/jaloplo/28n04wqd/).

Thanks in advance.

**Comment by evs-chris** [comment]
Ractive doesn't automatically track changes outside of its own scope because js doesn't really offer a good way to do so. When you have two instances pointing at the same data like that, changing the data from one is not visible from the other even though the same data changed. You can either tell the other instance that the data has changed with `h1.update()` or you can tell ractive that the data should be kept in sync by doing `p.link('message', 'message', { instance: h1 })`, which says "p should use the internal 'message' model from `h1` at its own keypath 'message'". It's kinda like a symlink in fs terms: https://jsfiddle.net/sqyxLn8k/

**Comment by jaloplo** [comment]
Thanks for your help. It does really work with the ```update``` method but seems to be pretty manual to have a semi-real propagation. ```link``` method allows creating a better component architecture and creating some kind of useful patterns.

@evs-chris, thanks for your answer and your code.
