### ISSUE TITLE
Triple mustache detaches early during transition out

### ISSUE THREAD

**Issue by ilessiivi** [ractivejs/ractive#3324]
## Description:
Using triple mustaches (`{{{something}}}`) to display HTML inside a component, inside a yielding component and then transitioning out both of theirs container causes the triple mustached fragment to detach immediately instead of waiting for the transition to finish.

## Versions affected:
This happens on version 1.0 onwards, including 1.4.0-edge. Works as expected in 0.9.14.

## Platforms affected:
Tested on Firefox and Safari (both on macOS)

## Reproduction:
https://jsfiddle.net/hx637kr1/4/

---

I managed to track things down to the `detachWhenReady` call in [Triple.js](https://github.com/ractivejs/ractive/blob/159a583f80f60308766b5cee964aa84c8d97e6ea/src/view/items/Triple.js#L133) which seems to call its `detach` function immediately, but the logic in [TransitionManager.js](https://github.com/ractivejs/ractive/blob/159a583f80f60308766b5cee964aa84c8d97e6ea/src/global/TransitionManager.js#L92) where the detaching is started is pretty complex. The yielder must not be passing the outro onto its children?

**Comment by evs-chris** [comment]
Looks like this particular issue is caused by more than one level of nested transition manager (because each unrendering component gets its own runloop and associated transition manager), where the innermost manager only checks its immediate parent to make sure it's done outro-ing before it detaches when it really needs to check all the way to the root. This should be fixed on edge once Travis gets done Travising, and I'll cherry-pick it over to 1.2 and 1.3 branches to propagate it out to current releases at some point in the not-too-distant future. Thanks for the report!

**Comment by ilessiivi** [comment]
Thanks, it works now properly on edge. 🎉
