### ISSUE TITLE
Computed Property with wildcard not updated under certain conditions

### ISSUE THREAD

**Issue by LeJared** [ractivejs/ractive#3331]
## Description:
Computed property with wildcard keypath does not update, if the _only_ usage of this property is in the expression for a class-* directive and this expression is negated (starts with a exclamation mark).

See reproduction example for clarification.

## Versions affected:
1.3.11

## Reproduction:
https://jsfiddle.net/lejared/edc6gwn8/33/
There are two computed properties, which are perfectly the same and use the same internal value.
Both properties are only used in a class-* directive in the template. 

The difference is, that the expression in the second class-* directive starts with a negation (exclamation mark). This prevents the computed property from being updated when the internal value changes. Remove the exclamation mark or output the computed property additionally in a mustache, then everything works fine.

Also it would be nice, if i did not have to put the dummy call `this.get('boxes');` in the computed property getter. It should update automatically if the object in the watched wilcard keypath changes.

**Comment by evs-chris** [comment]
The issue here was the computation was getting stuck behind the expression `!disabled`. I believe I've got that issue resolved in edge now. This also pointed out another issue - nested computations should implicitly depend on their parent model so that they get recomputed when the parent changes. [Here's](https://jsfiddle.net/ybvmh9nc/) the fiddle with the changes applied. Lemme know if that will resolve this issue.

**Comment by LeJared** [comment]
The fiddle works well with ractive@1.4.0-build-31 
I will test with our real world app in the next week.

**Comment by LeJared** [comment]
Tested with our real world app and everything works just fine. Looking forward to the next release!
Thanks.
