### ISSUE TITLE
Feature Request: Handling white-spaces as first class citizen in textOnlyMode

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3338]
## Description:

I recently started to use Ractive as a template engine in a project to generate the necessary C header and source files regarding to user supplied data. 

Ractive might not be the intended tool for that purpose, that's okay. However, I would love to use Ractive for this type of tasks in the future as it's both familiar to me and already the part of the rest of the system. I guess there is no harm to open a feature request for this one. 

## Versions affected:

All?

## Platforms affected:

All?

## Reproduction:

Here is the [reproduction](https://ractive.js.org/playground/index.html?env=docs&hidemenu#N4IgLiBcIDwA4CcCmACAlgEwLwB0QHsBXMOYvAPhwDsYB6RJckAGhAGcoQ0q2wUsUVJAHcUAJQCGAYzBoAbkgAUwaihRgJCAOZIwkFAHIAxERLEDzVeqQBbOABsJYJPskz5SAHRxNbJQANqIwwkADNuVAALJHt7fHVo5BRqYGAjNFCUaIBPAF9cqzVgsIistBQAVhTgWgz86mqjJGlIlBtsgHkAIwAreqo1NVSjYTQwVvbunoBtAAEAayRsgF0UCTYUOQl7fsG9lGLwoRRUrftPAA98k+AzzzyCgcHU2lHx-pfmqUj+6n9mE7OC5gDpUezZACy+BC+jACEISABDD8CAUAHVImMkGwfFIXOp4UhcgBKSxPDBOCT6FRPNQ5WGEsl7Sa9SA0-bJEASACMeGpF30eFC+HweAB2UFIC6mjwuQBhWSYDwEgATHyTgLOdKAF5ilASzkAR0IF1lCseakeJJYICknBtkSgoAQnEczl4IHyQA) for my intention.

### Template 

```ractive
#define hello there 
{{#if hey}}
    #define hi 5
{{/if}}

{{#each myObj}}
    {{#with myObj[@key] as val}}
        #define {{val.x}} {{val.y}}
    {{/with}}
{{/each}}
```

### Expected 
```c
#define hello there 
#define hi 5

#define foo bar
#define baz qux
```

### Observed

```c
#define hello there 
    #define hi 5

    
        #define foo bar
    

    
        #define baz qux
```

**Comment by MartinKolarik** [comment]
~Except for the whitespace on empty lines, about which I'm not sure,~ The indentation matches exactly what's in the template (think `white-space: pre`). If you wanted to only preserve line breaks but no indentation (like `white-space: pre-line`), it would only make sense with a separate config option.

**Comment by ceremcem** [comment]
Applying a `white-space: pre-line` style resolves the prefixed whitespaces, but absolutely interferes with indentation-sensitive parts. Here is what I mean: [playground](https://ractive.js.org/playground/index.html?env=docs&hidemenu#N4IgLiBcIDwM5gJ4BsCmA+AOgOwAS4AcAnVXYHffAdwAsBLMVAWjgIEMBjVSQkp5OtlQBuCrgC+OGAHoEKDFOKk6AEwC8mEAHsArmAJ7NWbDKXoQAGhBwoIQQlxrcQqrgBKnMHQBuqABTkeLhgbEQA5qhgPADkAMS6+nrRFmKMALYEyGyMPB4cXr4AdOxEcP4ABjixKqgAZoKkNKjIyFrBTSS4OMDAsXS1uE2I4pJB+NV1DYN0uACs3cDS-SM4C7GonDS4aYgA8gBGAFYrY2S9VAxbOweHANoAAgDWqIgAurhscLjebMgnlADcBN6kIzj9kIUAB4jMG-QrDUYAnrSC5gGgnZEbDjo0ZVXAAFXoXzK+ToWjwdC+AAVEGjyUwOFoajh+rhalotJAxPh9qFHLheQAvblndabbZ7I7-QH4HqxVFXSV3J4vd6fb6-aUygFDHoqhH8nrgqEjaRGuEIkVIxYKrVnaRYnGrbDlCxkRiQsC7bDIRAAWSZ3GCRB0qDdSjKRF8AHV6IxWJwg2AQ6hxABKFJBFTZNg8QI6l48ZOhzMA65HSD5wGaNgARk0echPE07K0mjdiGbIF5RE04jdIswYBrACYG2Qm11u2xhZZcJ2pwBHHSQvsixESHDpywgDi2Hc0KCgIi2LLxiAjIA)

### Template 

```
#define hello there 
{{#if hey}}
    #define hi 5
{{/if}}

{{#each myObj}}
    {{#with myObj[@key] as val}}
        #define {{val.x}} {{val.y}}
    {{/with}}
{{/each}}

# This section is Python-code
if foo:
    bar = baz
    {{#each myObj}}
        {{#with myObj[@key] as val}}
            hey{{@key}} = {{val.x}}/{{val.y}}
        {{/with}}
    {{/each}}
```

### Expected 
```
#define hello there
#define hi 5

#define foo bar
#define baz qux

# This section is Python-code
if foo:
    bar = baz
    heya1 = foo/bar
    heya2 = baz/qux
```
### Observed 
```
#define hello there
#define hi 5


#define foo bar



#define baz qux

# This section is Python-code
if foo:
bar = baz

heya1 = foo/bar


heya2 = baz/qux
```
### Proposal

What I propose is: 
* Ractive will have an `indent: REGEX` option (eg. `\s{4}` or `\t` or `\s\s` or `  `) for user defined indentation. 
* Any block (`{{#if}}`, `{{#each}}`, `{{#with}}`, ...) will subtract that configured number of whitespaces for its child nodes. 
* Blocks (`{{#if}}`, ...) will not introduce a newline.

**Comment by ceremcem** [comment]
@evs-chris is it a `wontfix`? 

# Edit 

It turns out this feature is documented in FreeMarker library: https://freemarker.apache.org/docs/dgui_misc_whitespace.html

**Comment by evs-chris** [comment]
I don't think it's a wontfix, as I think it definitely makes sense to allow more control over whitespace. I won't be able to implement it for a while though, unfortunately.

**Comment by ceremcem** [comment]
@evs-chris Ping?

**Comment by evs-chris** [comment]
I was kinda thinking something more along the lines of https://shopify.github.io/liquid/basics/whitespace/, but it would probably make sense to have a mode that just strips out the lines with only block tags. I'll poke at the parser a bit and see what that would take.

**Comment by ceremcem** [comment]
That'd be very nice. By the way, I saw another project, modm.io, that uses Jinja as the initial templating stage, which IMHO proves that this "using a full-blown template engine in front of a regular compiler" approach has a valid rationale.

**Comment by evs-chris** [comment]
I've added some experimental support for something along these lines on edge. It's a sort of extension of preserveWhitespace, which is required because otherwise consecutive whitespace is collapsed in the template (where allowed i.e. almost everywhere), since HTML doesn't really care in most cases. It gives you manual control of collapsing the line contains section tags by adding a `-` before the end of the tag e.g. `{{#if foo -}}`. Alternate blocks (`else`, `elseif`, etc) are also handled based on the flag on the opening tag.

It's not particularly easy to describe, but [this example in playground](https://ractive.js.org/playground/#N4IgLiBcIgNCBnKN4GNlxACyqATlAHYCuANqfEpANogD0dqAJoQHQBWCTApqQJYA3PK0LcwdQgAcAtnTwBDVGEHcAAgEZWAFlYAGALQAjYn1JN9AVgCccxcoHcOSALoBfeNKjr4AMyrVQQnlpbmQ+Qh4AD1YFJRVWLDBpUkxUAHtCMG5M5AAeLHUAPgAJXlI02AACYGAgkMqAHwbKgHIAJTsVFtdXAEJcugLCgB1CUdyEVDw+STARwkrK9MIEMEreSoBeSqY01GIQzNYp7nksgFFSbkOwAAoWyTxuFoBKAG5Rxd39m9ZDNKYAE9WPJJJJskwAMJYUxMW68d6fdakVjhUR4YoAFQAsgAZLaVAAGpSeLQQlQA7lgzpTuJUAOZpMCQYajQkfBaVJHLVaVLLSSSkM507YdOIOViSeR4BDcW6EgDEPB84TpWDKaT56qeXLGYGG+sNBpqCr4Pkq6sBlX0PVGSu4KtEFr4lQsowNxuAvFlZsqAHZKoVKlZbaJAeHAe7DTVvdxQ4sE9VgKbzQBmQOVLTW+OVBiVcqkJGJ4sx0g+80BoMh1xIvNPeTkK1gLBpIvF9ul2Wh+2OtUuwhMhBpaTEVBYKPtycd4B0M05xM1Wc+UOjE2nMeVaSAgDyhnY2ZrnJNFL4zc3O731FUAGtuIDnJV5OSBA2D3blaqkze7z0ky-SDmi4ns2oaLuuWA9ISVTAJUjzcLKeAOAA6jCWQIFKqDcJAfJ4MQ3BVHBCEOAAymA8gRA2GTcMR3BxBkCDYWAuF0q4iKcjyawAIJggSYr2I43CRFkES3MAbb8oKwqMdcklZLAbaoAgDGVAAJJCxHEfJnKLIpCAAJJMNhLSgpILRaYmTBnPItwvNUbaLE8YDEHgCwwVuu7sNhME+GkaRGYY0pmZUAUAF7+WcLSVK4UVtoeiysRynxIrwqKEOiWJ4pUADU2yiBSlTcZINmsGAaQZbiNnjHQkzTLM8zjKsgJXPMiwFNUSxpOUeDYQqui6AAHOo-XyG8MWEAMjXNaMICuM48AOmEESCTEnQSokyQzUAA) will hopefully make it clear. There's also a [test case](https://github.com/ractivejs/ractive/blob/dev/tests/browser/misc.js#L1966).

This doesn't cover automatic handling of indentation, and I don't think it reasonably could. That leaves you nesting the sections with whatever indentation but leaving the content where it should appear on its own line. Let me know what you think.

**Comment by ceremcem** [comment]
Well, this example outputs what's expected. Awesome!

> This doesn't cover automatic handling of indentation,

Thinking again, not handling indentation (leaving it as is) is kind of a "feature". I like it more, because we can easily determine the resulting indentation of a `code` without tracing its surrounding blocks. Now I vote for "leave indentation handling as is". 

However, the `-` character... Is it too hard to remove that dependency? It seems annoying. We could perfectly use it, okay, but removing the need for `-` sign would be awesome.
