### ISSUE TITLE
Working with components in Typescript

### ISSUE THREAD

**Issue by marcalexiei** [ractivejs/ractive#3348]
Hi Chris,
In our webapp we are trying to use Ractive with typescript.
In these years we have have created Components with custom methods for example:

```javascript
const MyComponent = Ractive.extend({
  customFunction() { … },
  customFunction2() { … },
})
```

At the moment these approach do not work with typescript because:
1. properties not declared in ExtendOpts are not allowed
2. `customFunction` do not know that his `this` may include `customFunction2`
3. Ractive.extend() definition accepts only one parameter

In order to fix the issue I edited the declaration file `Ractive#extend` function in the following way:
```typescript
static extend<U>(...opts: (ExtendOpts<Ractive & U> & U)[]): Static<Ractive & U>;
```
which can be improved with something like
```typescript
static extend<U>(...opts: (ExtendOpts<Ractive & Omit<U, keyof ExtendOpts>> & U)[]): Static<Ractive & Omit<U, keyof ExtendOpts>>;
```

so the typescript code to generate the component will be something like:

```typescript
type RactiveWithMethods<T> = Ractive & T;

interface FirstExtensionDef {
  firstExtensionFeat?(this: RactiveWithMethods<FirstExtensionDef>): void
}

const FirstExtension: FirstExtensionDef = {
  firstExtensionFeat() {
    this.set('foo', 'bar');
  },
};

interface SecondExtensionDef {
  secondExtensionFeat?(this: RactiveWithMethods<SecondExtensionDef>): void
}

const SecondExtension: SecondExtensionDef = {
  secondExtensionFeat() {
    this.set('foo', 'bar');

    this.secondExtensionFeat();
  },
};

const RactiveSuperExtended = Ractive.extend<FirstExtensionDef & SecondExtensionDef>(FirstExtension, SecondExtension, {
  onrender() {
    this.firstExtensionFeat();
    this.secondExtensionFeat();
  },
});
```

By doing this we have come to a proposal: what if ractive `ExtendOpts` had an additional property called `methods`,
similar to Vue, which is a map of string -> function where the functions are added to the ractive instance during construction phase?

In that case the `U` generic in extend declaration will become the type which defines additional functions of the ractive component.
So the definition will become something like:

```typescript
// Allow definition of this inside helpers
export type Helper<T = Ractive> = (this: T, ...args: any[]) => any;
// ...
// Add methods in ExtendOpts
  methods?: Registry<Helper<T>>;
// ...
static extend<U>(...opts: (ExtendOpts<Ractive & U>)[]): Static<Ractive & U>;
```

and the code that generate components:
```typescript
type FirstExtensionDef = {
  firstExtensionFeat?(this: RactiveWithMethods<FirstExtensionDef>): void
}

const FirstExtension: ExtendOpts<RactiveWithMethods<FirstExtensionDef>> = {
  methods: {
    firstExtensionFeat() {
      this.set('foo', 'bar');
    },
  },
};

type SecondExtensionDef = {
  secondExtensionFeat?(this: RactiveWithMethods<SecondExtensionDef>): void
}

const SecondExtension: ExtendOpts<RactiveWithMethods<FirstExtensionDef>> = {
  methods: {
    secondExtensionFeat() {
      this.set('foo', 'bar');

      this.secondExtensionFeat();
    },
  },
};

const RactiveMultipleExtend = Ractive.extend<FirstExtensionDef & SecondExtensionDef>(FirstExtension, SecondExtension, {
  onrender() {
    this.firstExtensionFeat();
    this.secondExtensionFeat();
  },
});

const ractiveMultipleExtend = new RactiveMultipleExtend();
ractiveMultipleExtend.firstExtensionFeat();
ractiveMultipleExtend.secondExtensionFeat();
```

What solution do you prefer?

**Additional issue**: lifecycle callbacks are not defined inside definition file.

**Comment by evs-chris** [comment]
I ran across this a few days ago while I was testing something. I haven't really noticed it before because with ts I use classes for my components e.g.

```ts
class MyWhatever extends Ractive {
  constructor(opts?: InitOpts) { super(opts); } // only requirement

  firstExtensionFeat() { /* ... */ }
}

Ractive.extendWith(MyWhatever, { /* extend opts */ });

class MySpecialWhatever extends MyWhatever {
  constructor(opts?: InitOpts) { super(opts); }

  secondExtensionFeat() {
    this.set('foo', 'bar');
    this.firstExtensionFeat();
  }
}

MyWhatever.extendWith(MySpecialWhatever, { /* layered extend opts */ });
```

With classes you get the added benefit of allowing properties to wrap `get` and `set` with type safe accessors.

I think it would make sense to stop copying anything that isn't an init option out of the init options for the prototype. My typescript voodoo is a bit limited, but I think it would be nice to take it a step further and allow a prototype object to be supplied that sits on top of the ractive base. If that's not possible, I think I'd prefer to keep it simpler with a hybrid approach wherein the methods are still set up as a property of the extend opts, and that type gets merged with the type returned by `extend`. For the 1.x line, I think the first solution will work nicely and avoid breaking.

Looks like I also missed the on* methods in the typings, because I tend to prefer the event listener form with `on: { render() {} }`, but that's a much less involved and/or breaking fix.
