### ISSUE TITLE
Can anyone explain the Ractive Version Numbers to me?

### ISSUE THREAD

**Issue by wgrhstf** [ractivejs/ractive#3357]
I have an Electron project with Ractive 1.3.13 in my package.json. Now running npm update I get the message I could "update" to 1.2.10 - which is the latest Version according to npm. In the Changelog it seems as 1.2.x and 1.3.x are the same... 

I'm confused.

**Comment by marcalexiei** [comment]
> Now running npm update I get the message I could "update" to 1.2.10 - which is the latest Version according to npm

It was my mistake: I publish 1.2.10 after 1.3.13, so NPM detects 1.2.10 as the latest version. 
I'll fix that by publishing 1.3.14.

>  In the Changelog it seems as 1.2.x and 1.3.x are the same...

TL;DR No, they aren't. They include the same fix for two different minor version. 

If you noticed there are branches for each 1.x version.
Usually if there is a bug that affects the last 2 minor releases (At the moment 1.2 and 1.3) the fix is "cherry-picked" in the related branch and then published creating a new path version.

---

Thanks for the report.

**Comment by evs-chris** [comment]
Yeah, this is really bizarre behavior on the part of npm. Confused the heck out of me the first time I had a bug fix in an older branch that didn't affect a newer branch.
