### ISSUE TITLE
Question on TypeScript types: data property in ExtendOpts vs. InitOpts 

### ISSUE THREAD

**Issue by LeJared** [ractivejs/ractive#3366]
## Description:
We try to use ractive with TypeScript instead JS in our new project.

We do this like so:

```
class App extends Ractive {
   method() { }
}
Ractive.extendWith(App, {
    target: '#app',
    template: template,
    data: {   // <- type error here
        value: ''
    }
});
```

Now TypeScript says I can not pass an object to the data property.
In the ractive type definition only `data?: DataFn<T>;` is specified for the data property in ExtendOpts whereas `data?: Data | DataFn<T>;` is specified for InitOpts.

Is this intentional and if so, why?

## Versions affected:
1.3.14

**Comment by evs-chris** [comment]
Yes, this is intentional, as creating a component with a data object is probably not what you think - and even warns at runtime.

```js
const Component = Ractive.extend({ data: { foo: 'bar' } });
const c1 = new Component();
const c2 = new Component();

c1.get('foo'); // 'bar'
c2.get('foo'); // 'bar'
c1.set('foo', 'nope');
c2.get('foo'); // 'nope'
```

Additionally, since ractive watches data based on keypaths and not observing the objects directly (since that's not possible in a really consistent way), any template tied to `c2` will not update its references to `foo` when the `c1` instance changes it.

From a class-based perspective, passing in a data object effectively makes the data static, which ractive doesn't support. With a data function, ractive will call the function each time a component instance is instantiated and is much more likely to get an independent object e.g. `data: () => ({ foo: 'bar' })`.

**Comment by LeJared** [comment]
Thanks for explanation!
