### ISSUE TITLE
Date values being converted to empty objects when using get()

### ISSUE THREAD

**Issue by barron-j** [ractivejs/ractive#3388]
## Description:
`Ractive.get()` returns date values as empty objects.

- **EDIT**: Only seems to affect top-level Date values. If the Date is a sub-property in the data, it returns ok.
- It works if you specify `get({ virtual: false })`. 
- Appears to be an issue in `isObjectLike()` method. Doesn't check for Date values.

## Versions affected:
```html
Ractive.js v1.3.14
Build: 76470bafd78eddd27baa1425ed3f9475242d1c34
Date: Sat Dec 12 2020 08:01:19 GMT+0000 (UTC)
```

## Reproduction:
https://jsfiddle.net/wg80a173/2/

**Comment by evs-chris** [comment]
I believe I have a reasonable-ish resolution for this on edge once Travis finishes Travis-ing. I know there's some weird magic thing that happens when dates come in from another realm (iframes maybe) such that you shouldn't use instanceof, but in this case I think it's probably unlikely enough that we can address it if it ever arises. As it would happen, I ran into a similar issue with a deep set and a date today too.

**Comment by evs-chris** [comment]
Good and bad are now the same in the example, so I'm going to call this one good.
