### ISSUE TITLE
How to make Ractive.fire return a Promise?

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3410]
## Description:

I very often need to use my components in "headless" mode within from the other components (or when I use the whole application via a headless browser) and I want to re-use the component handlers in my scripts. However, `Ractive.fire()` returns boolean, so I can't make my scripts wait for previous handlers to finish. How can I create a different `fire()` method that returns a Promise so that I could `await` for it?

## Versions affected:

1.4

**Comment by ceremcem** [comment]
My current workaround is defining a `window.fire2` method that creates a Promise object and passes its `resolve` and `reject` methods to the `context`. I manually call `ctx.resolve!` or `ctx.reject!` in my handlers. 

```js
window.fire2 = function(instance, event_name, ...args){
  var ctx = instance.getContext();
  var promise = new Promise(function(resolve, reject){
    ctx.reject = reject;
    ctx.resolve = resolve;
  });
  args.unshift(event_name, ctx);
  instance.fire.apply(instance, args);
  return promise;
};
```

Then I edit my handlers like this: 

```js
on: {
  foo: (ctx) => {
     // do something
     if (typeof ctx.resolve == 'function') {
       ctx.resolve();
     }
  }
```

Then I call my handler from elsewhere like this: 

```js
await fire2(this.findWidget("reports-data-table"), 'openRow', 'report-11')
```

I just would like to use it like: 

```js
await this.findWidget('reports-data-table').fire2('openRow', 'report-11')
```

Without being had to edit my `openRow` handler if possible.

**Comment by evs-chris** [comment]
I've thought about this a bit, and the nearest pattern that I use in a similar scenario is to move the event handling code into its own async method, which is then called from the event listener. When I need to be able to await the handler, I call the method `this.findComponent('reports-data-table').openRow('report-11')`. I also typically register my "has-one" components as properties of the parent e.g. `<reports-data-table on-init="@.set('@.reports', $1)" />` so that I can `this.reports.openRow('report-11')` from the parent. This also plays nicely with TS, if that's your jam.

I couldn't really come up with a way to handle awaiting an event to come to some sort of completion much beyond what you've already shown. Events are a little tricky here in that there may be multiple handlers for any given event, so awaiting handler completion could mean different things in different scenarios. The next nearest thing would be to automatically extend the event context to basically be a promise itself, with resolve, reject, and then methods that wrap an internal promise.

**Comment by ceremcem** [comment]
I didn't think about "multiple handlers for any given event" cases (I'm even not sure what it really means) so I'll stick to your "move the event handling code into its own async method, which is then called from the event listener" technique. 

Thank you. 

> Thanks also for the `on-init="@.set('@.reports', $1)"` trick.
