### ISSUE TITLE
Is there a way to bind events to non-Elements?

### ISSUE THREAD

**Issue by amadanmath** [ractivejs/ractive#3436]
`HTMLMediaElement` does not expose an event for when a track is changed, `HTMLMediaElement.textTracks` does. This event does not bubble. Assuming I have something like this:

```
{{if video}}
  <video controls autoplay>
    <source src="videos/{{video.src}}" type="video/mp4">
    {{#each video.subs as sub}}
      <track kind="subtitles" src="subtitles/{{sub.src}}">
    {{/each}}
  </video>
{{/if}}
```

and

```
ractive.set('video', {
  src: "example.mp4",
  subs: [
    { src: "example1.vtt" },
    { src: "example2.vtt" },
  ],
})
```

What would be the most natural way to bind `change` on the `.textTracks` property of the video element? Currently, my workaround is to place logic where the `video` variable changes, but this is not at all elegant:

```
const oldVideo = ractive.get('video')
ractive.set('video', video)
.then(() => {
  if (video && !oldVideo) {
    document.queryElement('video').textTracks.addEventListener('change', textTrackChangeHandler)
  }
})
```

**Comment by evs-chris** [comment]
I think there are a few ways to handle this:

1. make a component that wraps the video element and installs a listener in the render event that fires a component event so that you can install a trackchange (or whatever name suits) listener on the component
2. a little lighter weight - add a decorator to the video element that installs the listener and raises a trackchange event on the element
3. slightly prettier, still light weight, but considerably more complicated - add a macro that does a sort of combo of 1 and 2

If you have a working example on the playground or a jsfiddle-ish place somewhere that I can play with, I'd be happy to take a stab at helping you with a solution.

**Comment by amadanmath** [comment]
Thank you, your hints helped; though I must say I only understood enough for no. 1: https://codepen.io/amadanmath/pen/bGPaagB

For no. 2, I am not sure how often `update` would be run. For no. 3, I haven't dealt with macros at all yet.

**Comment by evs-chris** [comment]
The docs on decorators and macros really aren't great, which is unfortunate because they can do some super cool and useful things. Nothing is jumping out as a way to update that pen without me having an account, so here's a decorator version:

```js
function cctracked(node) {
  if (node.nodeName === 'VIDEO') {
    const ctx = this.getContext(node);
    const listener = ev => ctx.raise('trackchange', {}, ev.target, Array.prototype.find.call(ev.target, t => t.mode === 'showing'));
    node.textTracks.addEventListener('change', listener);
    return {
      update() {},
      teardown() {
        node.textTracks.removeEventListener('change', listener);
      },
    };
  } else {
    console.warn('cctracked decorator called on non-video element');
    return { teardown() {} };
  }
}

// I'll just register it globally, but this could be an init option
Ractive.decorators.cctracked = cctracked;
```

The update function doesn't really matter because no params are being passed to the decorator, so it basically lives and dies with the video element. You could change the raise to have the values in the `@event` data or swap the order on the positional args or whatever fits your case best. Here's the usage, where I set samplevid in the root data to the video const in the setup:

```handlebars
<button on-click="@.set('video2', video2 ? undefined : samplevid)">Toggle Video2</button>
{{#if video2}}
  <p>Selected subs: {{subtitle2 || 'None'}}</p>
  <video controls as-cctracked on-trackchange="@.set('subtitle2', $2.label || 'None')">
    <source src="{{video2.mp4}}" type="video/mp4">
    {{#each video2.subs as sub}}
      <track kind="subtitles" label="{{sub.label}}" src="{{sub.vtt}}" default>
    {{/each}}
  </video>
{{/if}}
```

The benefit to the decorator is that it doesn't have to spin up a whole new ractive instance to do its thing, so it's much less resource intensive. A macro lets you dynamically generate and interact with whatever template you want based on the context it is called in, but I think the decorator probably fits this scenario a little better and less magically than a macro.
