### ISSUE TITLE
Conditional attributes

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#9]
See #6. We want to be able to add or remove element attributes (rather than merely changing their value) when parts of the viewmodel change, the obvious example being

``` html
<input type='checkbox' {{#complete}}checked{{/complete}}>
```

or even 

``` html
<input type='checkbox' {{checked}}>
```

**Comment by slarti-b** [comment]
Are you saying this won't be fixed?  We're looking at ractive for a re-write of our web app and really like it.  But we want to do isomorphic code, so we need the templates to render correctly from the PHP side too.  Mustache generally handles this, but a checkbox for example, I would like to do: 
`<input type="checkbox" value="true" {{#foo}} checked="{{foo}}"{{/foo}} />`
Thus, a non-js rendering renders the checked attribute only if `foo` is true, while the ractive model binds `foo` to the checked attribute.  Except the binding doesn't work then.  I'm fine with setting the value fo the `checked` attribute as the bound variable, but would like to be able to also make it conditional so that the server-rendered version is also valid.  Any ideas?

**Comment by MartinKolarik** [comment]
@slarti-b you can now do `<input type="checkbox" {{#foo}}checked{{/}}>` and it works like you'd expect.
